### ISSUE TITLE
Audio output doesn't always follow system setting

### ISSUE THREAD

**Issue by Jaiganeshkumaran** [utmapp/UTM#3879] opened 2022-04-08 11:49 UTC
Currently, UTM uses the output device that's system (macOS) default to play sound from the guest OS. However, when you change the default output device from macOS after launching the VM, it doesn't apply to the VM and continues to use the old output device. You've to restart the VM to use the new output device.

**Comment by Terabyte1385** [comment] 2022-04-10 14:29
Same issue here with Windows 11 guest OS. When Windows plays a sound (for example, from an alert or a new notification), the host Mac plays it at the volume set in Windows, even though I muted the Mac.

**Comment by fra-yer** [comment] 2022-04-11 15:06
interesting - for me Windows 11 completely ignores changes in its own audio settings. It always plays back sound with the volume set on the Mac side (that's with Win 11 on a 2021 M1 Macbook pro with the latest UTM/QEMU). There is no way I can make Win11 understand that I changed the volume. Most probably it's a sound card emulation issue, and not a very big deal for me, but weird nonetheless.

**Comment by osy** [comment] 2022-08-01 22:44
Duplicate of #3488

**Closed by osy** 2022-08-01 22:44 UTC
Labels: bug, duplicate, qemu, macOS

**Comment by yim0000** [comment] 2022-11-16 05:19
Same issue
