### ISSUE TITLE
Ability to list host usb devices, attach and detach them on a running VM

### ISSUE THREAD

**Issue by phraemer** [utmapp/UTM#5393] opened 2023-06-16 10:00 UTC
This is already working via the USB icon in the UI so in theory it should be relatively straight forward to add to `utmctl`.
It would make scripting VMs that need USB devices connected and disconnect for automated testing possible.

Some notes:

I tried achieving this functionality via qemu monitor and qemu qmp, and even though I can bring up those interfaces on the VM and attach to them for whatever reasons USB commands don't seem to work correctly. E.g. via qemu monitor the command `info usbhost` doesn't list the host usb devices and `device_add ...` doesn't work even if you happen to know the device ids etc.

I described my findings in the discord macos-support channel but nobody there seems to be able to assist on this issue. I'll copy them here:

I spent some time trying to understand the source code for UTM but I could use some extra guidance.

It doesn't appear to use either QEMU Monitor protocol or QMP because when I expose either of those via a telnet port and connect to it and for example try to list the host usb devices (using monitor, `info usbhost`)  I do not get the list of devices. I've also tried adding a device even though it's not listed with `device_add usb-host,vendorid=0x1234,productid=0x1234`  where I determine the ids myself but with no success either. Tried this with QMP and same results. But somehow the UI is managing to do it! The host usb devices are correctly listed when I click on the usb icon and the correctly attach and detach. If I could understand how this is working, what protocol or mechanism it's talking to QEMU, I might even be able to contribute a patch at some point. Or extend `utmctl` maybe. Thanks.

**Comment by osy** [comment] 2023-06-16 10:07
Duplicate of #5157

**Closed by osy** 2023-06-16 10:07 UTC
Labels: enhancement
