### ISSUE TITLE
[FEATURE REQUEST] Enable easy Raspberry emulation

### ISSUE THREAD

**Issue by Rastafabisch** [utmapp/UTM#4828] opened 2022-12-20 15:06 UTC
I would very much like to see an easy way to boot raspberry based images. This should be as easy as the onboarding wether you like to virtualise macOS, Windows or Linux, with just having to select an raspberry image that otherwise would be flashed to an SD-card.

**Comment by osy** [comment] 2022-12-27 07:17
Duplicate of #4827

**Closed by osy** 2022-12-27 07:17 UTC
Labels: enhancement
