### ISSUE TITLE
iOS UTM Remote won't show any VM's

### ISSUE THREAD

**Issue by bufferoverflowww** [utmapp/UTM#6413] opened 2024-06-08 17:07 UTC
**Describe the issue**
When connecting iPhone or iPad to Mac UTM using UTM Remote, on the iOS UTM Remote app, there is no VM's, but on the macOS UTM app, it shows all my VM's 
![IMG_0002](https://github.com/utmapp/UTM/assets/144923991/3724bd86-5ff9-4310-ab2a-2307b2c78e22)
<img width="1920" alt="Captura de pantalla 2024-06-08 a las 19 03 54" src="https://github.com/utmapp/UTM/assets/144923991/51013d11-3654-4fe6-9fd2-4d87733c98a4">

**Configuration (required)**
* UTM Version: 4.5.3
* OS Version: iOS 17.4
* Device Model: iPad 9
* Is it jailbroken (name jailbreak used)? No
* How did you install UTM? Installed UTM Remote with App Store

**Crash log**
no crash logs

**Debug log**
no debug logs

**Upload VM**
issue related to UTM Remote, not full UTM

**Comment by osy** [comment] 2024-08-20 00:11
Duplicate of #6380

**Closed by osy** 2024-08-20 00:11 UTC
