### ISSUE TITLE
UTM keeps crashing when quitting SuperTuxtKart on Debian

### ISSUE THREAD

**Issue by ViRo3** [utmapp/UTM#3448] opened 2022-01-05 15:40 UTC
**Describe the issue**
Start SuperTuxtKart and it freezes and on quitting it crashes UTM

**Configuration**
* UTM Version: 2.4.1
* OS Version: 12.1
* Apple Silicon

**Crash log**
[QEMULauncher-2022-01-05-205349.ips.txt](https://github.com/utmapp/UTM/files/7815915/QEMULauncher-2022-01-05-205349.ips.txt)
[QEMULauncher-2022-01-05-191629.ips.txt](https://github.com/utmapp/UTM/files/7815919/QEMULauncher-2022-01-05-191629.ips.txt)
[crash.txt](https://github.com/utmapp/UTM/files/7815932/crash.txt)

** log**
[debug.log.txt](https://github.com/utmapp/UTM/files/7815975/debug.log.txt)

**Upload VM**
[config.plist.txt](https://github.com/utmapp/UTM/files/7815992/config.plist.txt)

**Comment by conath** [comment] 2022-01-07 10:28
Duplicate of #3053

**Closed by conath** 2022-01-07 10:28 UTC
