### ISSUE TITLE
3.0.3: Cannot cancel or save Preferences

### ISSUE THREAD

**Issue by ylluminate** [utmapp/UTM#3503] opened 2022-01-20 03:59 UTC
**Describe the issue**
Having a strange issue with the 3.0.3 update when I attempt to make preference changes. Here's a quick screenshot to illustrate:
![screenshot](https://p153.p0.n0.cdn.getcloudapp.com/items/JruG4qZP/0e2af6d3-6f69-4e38-b441-5d2bf84b2481.gif?v=281ce3a87e13d135f9fc7585c06ff0aa)

**Configuration**
* UTM Version: 3.0.3
* OS Version: macOS 12.1
* Intel or Apple Silicon? Apple Silicon (M1 Max)

**Crash log**
If the app crashed, you need a crash log. To get your crash log, open Console.app, go to `Crash Reports`, and find the latest entry for either QEMU, QEMUHelper, or qemu-\*. Right click and choose `Reveal in Finder`. Attach the report here.

**Debug log**
[debug.log](https://p153.p0.n0.cdn.getcloudapp.com/items/YEuBRQnd/2f81727f-6b31-40c6-9ab8-d6f4e8110283.log?v=247aada29437e87131ba80b4e68dd0f9)

**Upload VM**
[config.plist](https://p153.p0.n0.cdn.getcloudapp.com/items/o0uZ6qnW/47a14b8d-3614-4bf7-bc6d-e70242728bf3.plist?v=2a5efcb99649758334e0f739a6c907c9)

**Comment by osy** [comment] 2022-01-20 04:45
Duplicate of #3494

**Closed by osy** 2022-01-20 04:45 UTC
Labels: duplicate
