### ISSUE TITLE
Network is not working when using 'Console Only' Display

### ISSUE THREAD

**Issue by n-stone** [utmapp/UTM#4191] opened 2022-07-06 14:01 UTC
**Describe the issue**
The network stops working when using **_Console Only_** as display, after switching back to **_Full Graphics_** the network will start working again. Also the interface name changes from `enp0s6` to `enp0s5`, the guest is debian 11 arm64. I tried **_Bridged_** and **_Shared_** network mode.

**Configuration**
* UTM Version: 3.2.4
* OS Version: 12.4
* Apple Silicon

**Debug log**
[debug.log](https://github.com/utmapp/UTM/files/9055365/debug.log)

**Upload VM**
[config.plist.zip](https://github.com/utmapp/UTM/files/9055375/config.plist.zip)

**Comment by conath** [comment] 2022-07-08 22:39
Duplicate of #3860

**Closed** 2022-07-08 22:39 UTC
