### ISSUE TITLE
Support unofficial Hypervisor framwork on jailbroken ios?

### ISSUE THREAD

**Issue by mio-19** [utmapp/UTM#4986] opened 2023-02-02 18:47 UTC
I found a post about installing Hypervisor.framwork on a jailbroken iphone and a modified UTM with Hypervisor support.

https://worthdoingbadly.com/hv/

Is it possible to add support of this on mainline UTM?

**Comment by mio-19** [comment] 2023-02-02 18:58
For A14/A15, this enables virtualization.
For M1, this enables a possibility to boot arm mac vm

**Comment by osy** [comment] 2023-02-02 21:04
Duplicate of #4934

**Closed by osy** 2023-02-02 21:04 UTC
Labels: enhancement
