### ISSUE TITLE
[Feature request] Ability to reclaim unused space

### ISSUE THREAD

**Issue by mavethee** [utmapp/UTM#3521] opened 2022-01-22 15:58 UTC
I've noticed that after Windows Updates, bunch of files deleted, I can't really do much with my VMs hard drive to make it smaller. For example Parallels can reclaim unused space on every power off and I'm wondering if it's possible to implement that here.

**Comment by adespoton** [comment] 2022-01-22 18:14
This appears to be a duplicate of #3460 ?

**Comment by osy** [comment] 2022-01-22 18:15
Duplicate of #3460

**Closed by osy** 2022-01-22 18:15 UTC
Labels: duplicate
