### ISSUE TITLE
When I shutdown A VM, make it return to the app instead of exiting the app

### ISSUE THREAD

**Issue by IIWare** [utmapp/UTM#412] opened 2020-07-10 11:42 UTC
So this may sound good (or not) but When I exit a VM, Make it return to the app, not making it exiting the app once I shutdown the VM because When the VM shutdown exits the UTM app, it will just redirect you to the home page which is just a waste of time (no offense here), but instead when I shutdown the VM can it just returns to the app instantly once I shutdown the VM? thanks.

**Comment by osy86** [comment] 2020-07-10 15:15
Duplicate of #6

**Closed by osy86** 2020-07-10 15:15 UTC
Labels: duplicate
