### ISSUE TITLE
Add 3D hardware acceleration or virtual graphics card

### ISSUE THREAD

**Issue by slavicweebofficial** [utmapp/UTM#413] opened 2020-07-10 17:40 UTC
Adding 3D hardware acceleration support would be good for gaming on a vm or adding some virtual graphics cards that won't do issues or overheat to iDevices if you can also would be good

**Comment by osy86** [comment] 2020-07-10 20:28
Duplicate of #161

**Closed by osy86** 2020-07-10 20:28 UTC
Labels: duplicate
