### ISSUE TITLE
Start VM from console

### ISSUE THREAD

**Issue by lonacluka** [utmapp/UTM#2550] opened 2021-05-20 10:31 UTC
Please add an option to start a VM using console command on macOS.

Thanks for the software! It is awesome.

**Comment by conath** [comment] 2021-05-21 08:17
Duplicate of #2280 

UTM does not have a CLI currently. However, you can export the QEMU command it runs: open VM Configuration,  click QEMU tab and then Export QEMU arguments…

**Closed by conath** 2021-05-21 08:17 UTC
Labels: enhancement

**Comment by lonacluka** [comment] 2021-05-23 11:04
Thank you for your answer!

@conath Could you please help me with starting VM, I'm trying for days to find a way to start a VM in a headless way using CLI.

This is the error I get, if I remove chardev arguments the VM doesn't start..

qemu-system-aarch64: -chardev pipe,id=term0,path=/var/folders/k4/c74r_h6j2_92p99yqv78yx7m0000gq/T/com.utmapp.UTM2/Ubuntu.terminal: Could not open '/var/folders/k4/c74r_h6j2_92p99yqv78yx7m0000gq/T/com.utmapp.UTM2/Ubuntu.terminal': No such file or directory

**Comment by conath** [comment] 2021-05-23 11:09
> Thank you for your answer!
> 
> @conath Could you please help me with starting VM, I'm trying for days to find a way to start a VM in a headless way using CLI.
> 
> This is the error I get, and if I remove chardev arguments the VM doesn't start..
> 
> qemu-system-aarch64: -chardev pipe,id=term0,path=/var/folders/k4/c74r_h6j2_92p99yqv78yx7m0000gq/T/com.utmapp.UTM2/Ubuntu.terminal: Could not open '/var/folders/k4/c74r_h6j2_92p99yqv78yx7m0000gq/T/com.utmapp.UTM2/Ubuntu.terminal': No such file or directory

Try this:

`-chardev console,id=term0`

For more information, see the [QEMU Emulator User Documentation](https://qemu.weilnetz.de/w32/2011/2011-02-10/qemu-doc.html), specifically the section *Character device options*.

**Comment by torarnv** [comment] 2022-04-11 16:47
> Duplicate of #2280
> 
> UTM does not have a CLI currently. However, you can export the QEMU command it runs: open VM Configuration, click QEMU tab and then Export QEMU arguments…

Does this work for macOS 12 virtualized on Apple Silicon?

**Comment by conath** [comment] 2022-04-11 22:45
> Does this work for macOS 12 virtualized on Apple Silicon?

@torarnv No, it does not work. Apple Silicon VMs use the Apple Virtualization backend, so you can't export the QEMU arguments. I don't know if there is any 1st or 3rd party CLI for the Apple Virtualization backend.

You can use the [utm:// URL scheme](https://github.com/utmapp/UTM/wiki/URL-Scheme-–-Automation-for-UTM-app-&-VMs) to start, stop or restart your macOS VM from Terminal (`open "utm://start?name=macOS"`). (the other commands are not supported for/by Apple VMs)

**Comment by AJAYK-01** [comment] 2022-08-13 14:55
> > Does this work for macOS 12 virtualized on Apple Silicon?
> 
> @torarnv No, it does not work. Apple Silicon VMs use the Apple Virtualization backend, so you can't export the QEMU arguments. I don't know if there is any 1st or 3rd party CLI for the Apple Virtualization backend.
> 
> You can use the [utm:// URL scheme](https://github.com/utmapp/UTM/wiki/URL-Scheme-%E2%80%93-Automation-for-UTM-app-&-VMs) to start, stop or restart your macOS VM from Terminal (`open "utm://start?name=macOS"`). (the other commands are not supported for/by Apple VMs)

Is there a headless argument?

**Comment by conath** [comment] 2022-08-18 19:07
@AJAYK-01 There is not. Opening the URL scheme will launch the app first and then execute whatever you told it to do, this is handled in the UI code (currently). @osy correct me if I am wrong.
