### ISSUE TITLE
IOS 14 BETA CRASH ON STARTING VIRTUAL MACHINE

### ISSUE THREAD

**Issue by SealOfficialYT** [utmapp/UTM#402] opened 2020-06-26 13:17 UTC
Hello so I am trying to run a virtual machine on iOS 14. When I do the app crashes. The log is:

-[CSConnection init]:250
2020-06-26 14:17:18.479 UTM[407:10815] -[CSConnection init]:250
Loading libqemu-system-x86_64.dylib
2020-06-26 14:17:18.480 UTM[407:10815] Loading libqemu-system-x86_64.dylib
Running:  qemu -L /private/var/containers/Bundle/Application/DB1A7EFA-91B8-41A6-B659-33B469AAF8CE/App.app/qemu -qmp tcp:localhost:4444,server,nowait -smp cpus=1,sockets=1 -machine pc,vmport=off -vga qxl -global PIIX4_PM.disable_s3=1 -global ICH9-LPC.disable_s3=1 -boot order=d -m 512 -soundhw ac97 -name "Virtual Machine 1" -drive "file=/private/var/mobile/Containers/Data/Application/39CB2CF8-E0D4-445F-9DF2-FEE5E53F77D7/Documents/Virtual Machine 1.utm/Images/android-x86-4.3-20130725.iso,if=ide,media=disk,id=drive0" -spice port=5930,addr=127.0.0.1,disable-ticketing,image-compression=off,playback-compression=off,streaming-video=off -device rtl8139,netdev=net0 -netdev user,id=net0 -device usb-ehci -device usb-tablet -device usb-mouse -device usb-kbd -device virtio-serial -device virtserialport,chardev=vdagent,name=com.redhat.spice.0 -chardev spicevmc,id=vdagent,debug=0,name=vdagent -uuid 0C54CD13-B2B7-4157-91B9-188824A91064 -rtc base=localtime
2020-06-26 14:17:18.566 UTM[407:10815] Running:  qemu -L /private/var/containers/Bundle/Application/DB1A7EFA-91B8-41A6-B659-33B469AAF8CE/App.app/qemu -qmp tcp:localhost:4444,server,nowait -smp cpus=1,sockets=1 -machine pc,vmport=off -vga qxl -global PIIX4_PM.disable_s3=1 -global ICH9-LPC.disable_s3=1 -boot order=d -m 512 -soundhw ac97 -name "Virtual Machine 1" -drive "file=/private/var/mobile/Containers/Data/Application/39CB2CF8-E0D4-445F-9DF2-FEE5E53F77D7/Documents/Virtual Machine 1.utm/Images/android-x86-4.3-20130725.iso,if=ide,media=disk,id=drive0" -spice port=5930,addr=127.0.0.1,disable-ticketing,image-compression=off,playback-compression=off,streaming-video=off -device rtl8139,netdev=net0 -netdev user,id=net0 -device usb-ehci -device usb-tablet -device usb-mouse -device usb-kbd -device virtio-serial -device virtserialport,chardev=vdagent,name=com.redhat.spice.0 -chardev spicevmc,id=vdagent,debug=0,name=vdagent -uuid 0C54CD13-B2B7-4157-91B9-188824A91064 -rtc base=localtime
WARNING: Image format was not specified for '/private/var/mobile/Containers/Data/Application/39CB2CF8-E0D4-445F-9DF2-FEE5E53F77D7/Documents/Virtual Machine 1.utm/Images/android-x86-4.3-20130725.iso' and probing guessed raw.
         Automatically detecting the format is dangerous for raw images, write operations on block 0 will be restricted.
         Specify the 'raw' format explicitly to remove the restrictions.

**Comment by obbcth** [comment] 2020-06-26 13:50
Duplicate of #397

**Closed** 2020-06-26 14:05 UTC
Labels: duplicate
