### ISSUE TITLE
Windows 10 Insider ARM64 does not boot on UTM v2.1.0 (Beta) on M1

### ISSUE THREAD

**Issue by HenkPoley** [utmapp/UTM#2558] opened 2021-05-23 08:48 UTC
**Describe the issue**
UTM 2.0.25-.28 does boot Windows 10 ARM64 Build 21354. Booting Windows 10 from a QCOW2-converted image.

But with the UTM v2.1.0 (Beta) it hangs just after the rebadged TianoCore(?) 'BIOS'. The circular Windows 10 loader is not displayed. 
<img width="912" alt="Schermafbeelding 2021-05-23 om 10 36 16" src="https://user-images.githubusercontent.com/2931213/119253910-9ea3b100-bbb3-11eb-9e14-83f0dfcabf2b.png">

But after a few aborted boots (closing the window), the "Preparing Automatic Repair" prompt does appear. Meaning the Windows bootloader could access the disk and set the failure counter. Nothing much visually happens.
<img width="912" alt="Schermafbeelding 2021-05-23 om 10 41 59" src="https://user-images.githubusercontent.com/2931213/119253922-afecbd80-bbb3-11eb-819a-0e035866f765.png">

QEMULauncher is using 100-102% CPU; doesn't appear to access disk, but that might be outside the view of Activity Monitor (e.g. hypervisor accesses the disk image)

I first mentioned it here: https://github.com/utmapp/UTM/discussions/2545#discussioncomment-770702

**Configuration**
* UTM Version: UTM v2.1.0 (Beta)
* OS Version: macOS Big Sur 11.3.1 (20E241)
* Intel or Apple Silicon? Apple Silicon M1

**Crash log**

No crash

**Debug log**

[debug.log](https://github.com/utmapp/UTM/files/6527780/debug.log)

**Upload VM**

[config.plist.zip](https://github.com/utmapp/UTM/files/6527781/config.plist.zip)

**Comment by conath** [comment] 2021-05-23 09:01
You need to add `,virtualization=on` in the machine properties.

**Comment by HenkPoley** [comment] 2021-05-23 09:06
```
		<key>MachineProperties</key>
		<string>highmem=off,virtualization=on</string>
```

That didn't quite resolve it. Still the Windows 10 bootloader doesn't progress to the circling boot throbber.

If it is a (partial) 2.0->2.1 upgrade requirement, consider adding it automatically.

**Comment by conath** [comment] 2021-05-23 09:15
> ```
> 		<key>MachineProperties</key>
> 		<string>highmem=off,virtualization=on</string>
> ```
> 
> 
>      
>   
> 
> That didn't quite resolve it. Still the Windows 10 bootloader doesn't progress to the circling boot throbber.
> 
> 
> If it is a (partial) 2.0->2.1 upgrade requirement, consider adding it automatically.

This was always required for booting the Windows on ARM system, AFAIK.

It seems like there is a new problem that prevents Windows from booting in version 2.1 so I am reopening this.

**Comment by HenkPoley** [comment] 2021-05-23 09:17
If I check the UI, under VM Settings > QEMU, it says (greyed out:

```
-machine
virt,highmem=off,virtualization=on
```

If I booted with 2.0.28, and then 2.1.0 again, it has chopped off the `,virtualization=on` again.

**Comment by conath** [comment] 2021-05-23 09:25
The `virt` is not part of the additional machine properties, it’s the System you choose at the top.

@osy was the `virtualization` parameter removed on purpose?

**Comment by HenkPoley** [comment] 2021-05-23 09:27
Ah, I did try switching back to a "virt-5.2" machine on UTM 2.1.0. Maybe that caused the string changes.

**Comment by osy** [comment] 2021-05-23 19:17
> The `virt` is not part of the additional machine properties, it’s the System you choose at the top.
> 
> @osy was the `virtualization` parameter removed on purpose?

I don't remember ever adding it.

**Comment by osy** [comment] 2021-05-24 02:20
I believe this is the same issue as #2546 so let's keep the conversation there.

Duplicate of #2546

**Closed by osy** 2021-05-24 02:20 UTC

**Comment by konatatenshi** [comment] 2021-10-30 08:07
I have met the same problem and i added the `virtualization=on` to the param but it made too slow to start the system opreation
