### ISSUE TITLE
UTM SE: Crash when booting VM as i386 BIOS

### ISSUE THREAD

**Issue by kirb** [utmapp/UTM#6479] opened 2024-07-14 10:43 UTC
**Describe the issue**

Booting a VM with the following characteristics crashes the UTM SE app:

* Architecture: i386 (x86)
* UEFI Boot: Off

Changing Architecture to x86_64 fixes this.

Same issue as #5925.

First caught this after sharing an existing VM from UTM on macOS to UTM SE on my iPhone, so this exact config works there.

**Configuration (required)**
* UTM Version: 4.5.3 (99)
* OS Version: iOS 18.0 beta 3
* Device Model: iPhone 15 Pro Max
* Is it jailbroken (name jailbreak used)? No
* How did you install UTM? App Store

**Crash log**
[crash.txt](https://github.com/user-attachments/files/16216504/crash.txt)

**Debug log**
[debug.log](https://github.com/user-attachments/files/16216506/debug.log)

**Upload VM**

No need, to repro:

1. Tap +
2. Select New Machine
3. Select no boot device
4. Turn on Legacy Hardware
5. Change architecture to i386
6. Accept remainder of defaults
7. Start the VM

**Comment by MisutaaAsriel** [comment] 2024-07-17 12:57
I get the same issue. Straight up crashes trying to boot, no matter what I change.

**Comment by Banjo-Oz** [comment] 2024-07-18 18:23
Same here. Anything I chance means a crash as long as i386 is the machine type.

**Comment by AlfCraft07** [comment] 2024-07-20 22:13
Same issue here on my XR

**Comment by StellaLovesTech** [comment] 2024-07-25 01:09
Same on my iPhone 13, has anyone found a fix? I need to use i386 for a OS im trying to run.

**Comment by StellaLovesTech** [comment] 2024-07-28 00:06
alr, i also found this issue on literally anything that isnt x86-64(like ppc, which i needed to run macOS 10.2)

**Comment by osy** [comment] 2024-08-21 23:33
Duplicate of #5925

**Closed by osy** 2024-08-21 23:33 UTC
Labels: qemu, iOS
