### ISSUE TITLE
USB devices attachment

### ISSUE THREAD

**Issue by rimvydukas** [utmapp/UTM#2549] opened 2021-05-19 08:05 UTC
Please browse the existing issues and filter by 'enhancement' to make sure this has not already been suggested!
Hi,

Are there any plans to introduce USB devices attachment ability in UTM? Such a feature is a must for virtualisation.

**Comment by osy** [comment] 2021-05-19 09:16
Duplicate of #46 

check out 2.1.0 beta.

**Closed by osy** 2021-05-19 09:16 UTC
Labels: duplicate

**Comment by rimvydukas** [comment] 2021-05-19 10:01
You duplicate issue talks about iOS version of UTM and I'm talking about Mac version of UTM.

**Comment by osy** [comment] 2021-05-19 14:04
Did you open 2.1.0 beta?

**Comment by rimvydukas** [comment] 2021-05-20 08:12
I'm considering it. Is it possible to install beta over normal version and then normal version over beta?
