### ISSUE TITLE
UTM Freezes Out of Nowhere

### ISSUE THREAD

**Issue by iinickb** [utmapp/UTM#2304] opened 2021-02-05 23:58 UTC
Clicking on certain things keeps causing UTM to freeze up. It happens:

On Windows 7:
Whenever I click the videos folder
Clicking on the C drive in file explorer
Clicking on the disc in file explorer

On Windows XP:
Sometimes out of nowhere
When clicking the C drive in file explorer
Installing some software
Sometimes when trying to close a window
When the "XX Days left to activate windows" reminder pops up

[debug.log](https://github.com/utmapp/UTM/files/5935871/debug.log)

Configuration:
* UTM Version: 2.0.20
* OS Version: Windows XP Professional (32-bit)/Windows 7 Professional (64-bit)
* Device Model: iPhone 12
* Is it jailbroken? No
* How did you install UTM? AltStore sideloaded
* iOS 14.3

**Comment by osy** [comment] 2021-09-04 03:31
Duplicate of #2221

**Closed by osy** 2021-09-04 03:31 UTC
Labels: duplicate
