### ISSUE TITLE
Property 'virtio-vga-gl.vgamem_mb' not found

### ISSUE THREAD

**Issue by LostInCompilation** [utmapp/UTM#4902] opened 2023-01-05 19:10 UTC
**Describe the issue**  
When using the virtio-vga-gl device and setting any value for VGA RAM, I receive the error in the screenshot down below. Leaving the VGA RAM field empty works.

**Configuration**  
* UTM Version: 4.1.5
* macOS Version: macOS 13.1
* Mac Chip: M1 Pro

<img width="327" alt="Screenshot 2023-01-05 at 20 07 31" src="https://user-images.githubusercontent.com/12819635/210861140-3f80d4ef-59ff-489c-a21e-0b209252ee77.png">

**Comment by osy** [comment] 2023-01-05 19:18
Duplicate of #94

**Comment by osy** [comment] 2023-01-05 19:18
We do our best to prevent setting incompatible settings but it’s always possible to find such combinations.

**Closed by osy** 2023-01-05 19:18 UTC

**Comment by Worko98** [comment] 2024-02-04 09:42
I have the same error and a lots of data in this virtual windows and I do not have any access. I'm using M1 max UTM 4.2.5 on Mac os 14.1
