### ISSUE TITLE
UTM Crashes when loading UTM bundle from external hard drive

### ISSUE THREAD

**Issue by tifasoftware** [utmapp/UTM#5430] opened 2023-07-07 02:00 UTC
**Describe the issue**  
UTM Crashes when I open a file from a directory that is not the default machine path.

**Configuration**  
* UTM Version: 4.3.1
* macOS Version: 13.4.1
* Mac Chip (Intel, M1, ...): M1 Max

[UTM-2023-07-06-204347.ips.zip](https://github.com/utmapp/UTM/files/11973841/UTM-2023-07-06-204347.ips.zip)
[Windows NT 3.1.utm.zip](https://github.com/utmapp/UTM/files/11973844/Windows.NT.3.1.utm.zip)

**Comment by runwaygoats** [comment] 2023-07-09 17:52
Exactly the same configuration and tha same problem.

**Comment by runwaygoats** [comment] 2023-07-09 18:14
UTM crashes even if you move the virtualMachine.utm first to another folder and back to its original location (~/Library/Containers/UTM/Data/Documents/).

**Comment by osy** [comment] 2023-07-10 01:53
Duplicate of  #5424

**Closed by osy** 2023-07-10 01:53 UTC
