### ISSUE TITLE
.qcow2 drive imports as a removable drive

### ISSUE THREAD

**Issue by Mokaman51** [utmapp/UTM#6541] opened 2024-08-04 13:30 UTC
Importing a .qcow2 drive imports as a removable drive without being able to uncheck it.
Because of this issue, a drive cannot be imported to run a system on iOS.

My workaround involved importing the drive in macOS UTM then exporting the UTM package to my iPad.

This issue iccurs on UTM SE.

**Comment by jorgebugon** [comment] 2024-08-07 01:56
I have the same problem currently, I tried creating the virtual machine in osx and importing it but it didn't work. I want to get Home Assistant working on an iPhone. Has it worked for you to import and get the machine working in UTM Se?

**Comment by osy** [comment] 2024-08-22 15:18
Duplicate of #6485

**Closed by osy** 2024-08-22 15:18 UTC
