### ISSUE TITLE
List of virtual machines with cut layout

### ISSUE THREAD

**Issue by Skramewell** [utmapp/UTM#2570] opened 2021-05-25 09:57 UTC
**Describe the issue**
The list of virtual machines appears with the layout cut, see the print.

<img width="1191" alt="Captura de ecrã 2021-05-25, às 10 56 17" src="https://user-images.githubusercontent.com/12413684/119478732-f5da8a80-bd47-11eb-9347-5c4b5ba02435.png">
<img width="1191" alt="Captura de ecrã 2021-05-25, às 11 38 25" src="https://user-images.githubusercontent.com/12413684/119484323-cd558f00-bd4d-11eb-9349-c7dce0efb611.png">

**Configuration**
* UTM Version: 2.1.1
* OS Version: 11.3.1
* Apple Silicon

**Comment by osy** [comment] 2021-05-29 17:36
Duplicate of #2335

**Closed by osy** 2021-05-29 17:36 UTC
