### ISSUE TITLE
USB drive support for iPad Pro and add jailbreak exclusive features

### ISSUE THREAD

**Issue by skulldealer** [utmapp/UTM#367] opened 2020-06-03 14:22 UTC
Hi developers, I appreciate the job u are doing to make the one of its kind app better. But still I want to see jailbreak exclusive features and help option integration with the app to help out the rookies.
I use this app on my iPad Pro and it has type c port
I have bought a type c 256 gig usb for it
It is full of Linux distress and other os iso files
I would like to see usb support
It means a way to use the stored iso file directly from usb and save the Vm on it so whenever I plug it in I could directly RESUME my work on it.
This would allow me to manage much more space as no iso file data will be there on my device and you guys will have a free hand to add more features and increase the app size

Also try to add some bios support

Please  do go through the features of other PC based Vm apps n try to add their features to utm it won’t be copying as u will be doing it on another platform. As users we won’t mind the size of the app scaling till even a gigabyte. Plz feel free to test out more and more stuff as we need it. Later if issues arise we will inform you to check app stability.
Plz make the options to resume work directly without needing to setup iso file again.
N also add recommended size for hda.img for respective iso file
Plz also consider adding inapp safari integration like YouTube which would indeed come very handy.
Other than that you may create an Cydia repo for app tweaks and inform us through in app pop up.

Thanking you,
Big fan of your app
Plz consider the suggestions and feel free to implement more as per your wish.
That’s it!

**Comment by osy86** [comment] 2020-06-03 16:34
Duplicate of #46

**Closed by osy86** 2020-06-03 16:34 UTC
Labels: duplicate
