### ISSUE TITLE
How long does it take to move a virtual machine?

### ISSUE THREAD

**Issue by chengluyu** [utmapp/UTM#6187] opened 2024-03-11 11:56 UTC
**Describe the issue** 

Moving a virtual machine to an external SSD takes forever. I have a virtual machine which takes ~100 GiB of my disk space.
Therefore, I want to move it to an external SSD. I selected the "Move" option from the context menu in the list of virtual machines. Then I selected a folder in the volume of my external SSD.

The loading indicator has been spinning for over 7 hours now. The activity monitor shows that the UTM process has written only 1.35 GB but read 190.31 GB. Note that the number of read bytes is growing but the number of written bytes didn't change much.
<img width="435" alt="image" src="https://github.com/utmapp/UTM/assets/2239547/60e13183-d38e-4c62-9f28-3f3929f48054">

In the target location, it shows that the file is actively being updated because its last modified timestamp is current.
![CleanShot 2024-03-11 at 19 50 18](https://github.com/utmapp/UTM/assets/2239547/4848542c-3ab5-47eb-b7e3-5f8e1d6130d7)

I have a few questions.

1. Is this a bug? Or is moving a virtual machine expected to be slow?
2. Is there any way to determine the progress? 
3. Will UTM show a progress when moving virtual machines in the future?

What I can do at the moment is wait, but carrying an external SSD around isn't very convenient since I'm using a laptop.

P.S. I've cooled my SSD and confirmed that it is capable of writing files.

**Configuration**  
* UTM Version: 4.4.3 (91)
* macOS Version: 14.3.1 (23D60)
* Mac Chip: M1 Pro 

**Crash log**  

It hasn't crashed.

**Debug log**  

The problem occurs when the virtual machine is not running.

**Upload VM**  

N/A

**Comment by chengluyu** [comment] 2024-03-11 12:06
The function which moves VMs should be this one: https://github.com/utmapp/UTM/blob/2e54e955e015d94ee8c3317f27db377e0ae5c4cb/Platform/UTMData.swift#L663-L670

I know less about macOS system programming. How about the performance of `COPYFILE_ALL | COPYFILE_RECURSIVE | COPYFILE_CLONE | COPYFILE_DATA_SPARSE` in general. Is this the bottle neck?

**Comment by adamallo** [comment] 2024-03-12 18:22
I have the same issue, also on a M1 Pro, macOS Version 14.4 (23E214), and UTM Version 4.4.5 (94)

**Comment by chengluyu** [comment] 2024-03-12 18:35
> I have the same issue, also on a M1 Pro, macOS Version 14.4 (23E214), and UTM Version 4.4.5 (94)

How long have you been waiting? I waited for 12 hours and had to manually terminate the UTM.

**Comment by adamallo** [comment] 2024-03-12 22:03
Much less than you so far, but I am planning to leave it for around 24h

**Comment by DrDonk** [comment] 2024-03-17 16:30
Are you moving a macOS VM and what is the format of the external drive? MacOS virtualisation is provided by the Apple HVF system in UTM and that uses sparse files to store the VM. If you copy the files to another drive it must be APFS formatted or it will copy the defined size of the VM file and not the on disk sparse file size.

I’d recommend finding the macOS VM and using Apple Archive to create a compressed archive and copy to the new drive. Then decompress and open in UTM. The same issue can be seen in other uses of sparse files.

https://eclecticlight.co/2021/03/27/how-sparse-files-can-explode-backups/

**Comment by chengluyu** [comment] 2024-03-18 04:59
@DrDonk I have checked my external hard drive, and it is indeed not APFS. Thank you for your reminder!

**Comment by chengluyu** [comment] 2024-03-18 06:01
I formatted another SSD to APFS and then started moving again. Let's see if it works this time.

**Comment by adamallo** [comment] 2024-03-18 13:18
I am using HVF, too, but my external SSD was already APFS. If using Apple Archive to create a compressed archive and copying it to the new drive is faster, that could be what the move option in UTM does by default. Adding an option to create a new macOS VM in a specific location would help, too.

**Comment by chengluyu** [comment] 2024-03-18 17:41
> Adding an option to create a new macOS VM in a specific location would help, too.

I agree. There should be a progress bar as well.

**Comment by osy** [comment] 2024-03-28 21:48
Duplicate of #4006

**Closed by osy** 2024-03-28 21:48 UTC

**Comment by chengluyu** [comment] 2024-03-29 12:37
According to my understanding, this seems to have no relation to #4006. Moving files does not require QEMU. As I mentioned before, it is done by the macOS system API. Moving VMs is related to the function below.

https://github.com/utmapp/UTM/blob/88ef79069fee19b5eb686bd5a26950a4c63cfe90/Platform/UTMData.swift#L492-L512

https://github.com/utmapp/UTM/blob/2e54e955e015d94ee8c3317f27db377e0ae5c4cb/Platform/UTMData.swift#L663-L670
