### ISSUE TITLE
App loses access to ISO files on restart

### ISSUE THREAD

**Issue by wjk** [utmapp/UTM#5654] opened 2023-09-04 20:14 UTC
**Describe the issue**  
I use UTM with a Git repository I work on called [ReactOS](https://github.com/reactos/reactos). I configured UTM to access the `bootcd.iso` file in situ where it is generated by ReactOS’ build process. However, usually immediately after I rebuild that file, UTM starts displaying an “operation not permitted” error naming the ISO file. After this happens, when I go to the VM’s settings, I see that the field naming the ISO file in the IDE Drive settings is blank. Usually what I have to do is click Browse and reselect the ISO file in the Open dialog.

Furthermore, it appears that when try to run the VM (or check its settings) immediately after launching UTM, the field will appear blank. But if I click Cancel and reopen the settings dialog, the file name shows up and the VM boots.

**Configuration**  
* UTM Version: 4.3.5 (87), from the Mac App Store
* macOS Version: 13.5.1
* Mac Chip (Intel, M1, ...): Apple M1

**Upload VM**  
[config.plist](https://github.com/utmapp/UTM/files/12516467/config.plist.zip)

**Comment by osy** [comment] 2023-09-04 20:34
Duplicate of #5615

**Closed by osy** 2023-09-04 20:34 UTC
