### ISSUE TITLE
Network connection no longer passed through in Ubuntu 20.04

### ISSUE THREAD

**Issue by jempiere** [utmapp/UTM#2737] opened 2021-08-11 15:59 UTC
**Describe the issue**
I recently set up a virtual Ubuntu v20.04 using UTM on my Macbook Pro M1. For the first several hours, and both turning on and off the vm entirely, network was passed through and I was still able to access browsers (I even watched a youtube video). However, as of today, with no changes to the Virtual Machine settings, it no longer has a network connection.

**Configuration**
* UTM Version: 2.1.2
* OS Version: Mac OS 11.4, Ubuntu 20.04
* Intel or Apple Silicon? Apple Silicon

**Debug log**
[debug.log](https://github.com/utmapp/UTM/files/6969768/debug.log)

**Upload VM**
[config.plist.txt](https://github.com/utmapp/UTM/files/6969790/config.plist.txt)

I had to upload it as a txt file, but there's my plist.

**Comment by conath** [comment] 2021-08-11 20:02
Did the internet connection of your MacBook Pro change between when internet was working and now? For example, did you go from one WiFi to another, go from work to home or something like that?

In that case I believe that your VM might not recognize the changed network and needs its DNS set to manual to it can continue to work on any network. https://phoenixnap.com/kb/ubuntu-dns-nameservers

**Comment by jempiere** [comment] 2021-08-11 20:30
@conath yes, that has happened, I didn't even think about that. I've read the tutorial, but I can't quite get how to resolve this issue in ubuntu. Is there a way to pass it through UTM itself? or do I set it up through the Network Proxy?

**Comment by conath** [comment] 2021-08-11 20:40
The cause of the problem is likely that one of your internet connections is IPv6 and the other is IPv4. The technical error is within a technology that UTM uses for network emulation, and should go away once UTM 2.2 is released, as that offers bridged networking. The issue is known for some time. So this is a duplicate of #2353 and/or #2429.

To work around it, you must change the DNS to manual within the guest. I always choose 1.1.1.1 as DNS server since that's a fast DNS provider.
Don't change any of the network settings in UTM - only in the guest.

**Closed by conath** 2021-08-11 20:40 UTC
