### ISSUE TITLE
Boot loop when trying to create an emulated Windows Server VM

### ISSUE THREAD

**Issue by indishal** [utmapp/UTM#6708] opened 2024-10-01 00:30 UTC
**BEFORE SUBMITTING YOUR ISSUE, PLEASE LOOK AT THE PINNED ISSUES AND USE THE SEARCH FUNCTION TO MAKE SURE IT IS NOT ALREADY REPORTED. ALWAYS COMMENT ON AN EXISTING ISSUE INSTEAD OF MAKING A NEW ONE.**

**Describe the issue**  
When I attempt to spin up an emulated Windows machine and use the latest Windows Server ISO or VHD (downloaded directly from MS Eval center), the machine successfully starts the boot process to the ISO or the VHD but reboots before the install boot environment loads. It loops in this way infinitely.

I have tried various settings modifications from the UTM UI such as forcing multicore, disabling UEFI boot, disabling TPM, forcing PS/2 controller, but that has not made a difference. Any ideas what the issue might be? 

**Configuration**  
* UTM Version: 4.5.4
* macOS Version: 15
* Mac Chip: M3 pro

**Crash log**  
N/A

**Debug log**  
I've attached it here.

[debug.log](https://github.com/user-attachments/files/17197820/debug.log)

**Upload VM**  
[config.plist.zip](https://github.com/user-attachments/files/17197838/config.plist.zip)

**Comment by indishal** [comment] 2024-10-01 00:35
In case it helps, here is a video of the behavior.

https://github.com/user-attachments/assets/71ad0952-1d23-435c-a6b2-78d8664c6409

**Comment by abhishekbhakat** [comment] 2024-10-02 11:02
Same here

**Comment by mateusgalasso** [comment] 2024-10-25 13:43
same here

**Comment by mikegarciam** [comment] 2024-10-31 17:38
This might be the same issue described on #6772 and was solved by using an earlier iso build

**Comment by Marty56** [comment] 2024-11-11 04:30
same here. Where do I get an earlier build of Windows 11

**Comment by mikegarciam** [comment] 2024-11-11 20:24
> same here. Where do I get an earlier build of Windows 11

Using the CrystalFetch app, there is a "All Builds" button on the lower left which allows you to select a specific Windows build.

**Comment by osy** [comment] 2024-11-26 20:58
Duplicate of #6772

**Closed by osy** 2024-11-26 20:58 UTC
