### ISSUE TITLE
Virtualised Monterey VM with variable disk size on M1

### ISSUE THREAD

**Issue by viking1304** [utmapp/UTM#3559] opened 2022-01-31 17:16 UTC
As far as I can see if I create virtualized macOS Monterey VM, it will be created with a fixed size disk. It would be nice to have ability to use disk without preallocated size.

I guess it should not effect performance too much, since CPU is virtualized and not emulated.

**Comment by osy** [comment] 2022-01-31 18:29
This is an Apple API limitation.

**Comment by adespoton** [comment] 2022-01-31 18:30
This is essentially #3478.  Answer is likely to be the same: can't do anything until Apple adds support.

**Comment by osy** [comment] 2022-01-31 18:31
Duplicate of #3478

**Closed by osy** 2022-01-31 18:31 UTC
Labels: duplicate
