### ISSUE TITLE
Mouse Right Click Middle Click wrong iPad Pro Windows 7

### ISSUE THREAD

**Issue by HenryTheX** [utmapp/UTM#523] opened 2020-11-10 00:06 UTC
cannot right click on iPad Pro, running UTM 2.0 b8
iPadOS 14.2 with altstore 1.4.2 beta
windows 7 ultimate x86 
Citrix X1 Bluetooth mouse

right click is just become single click so uncomfortable
also why middle click on my mouse serves as half baked right click onto windows 7?? on task bar it doest work but works on most other places

super strange!

**Comment by HenryTheX** [comment] 2020-11-10 00:10
Same for Microsoft Surface arc Bluetooth mouse

**Comment by IIWare** [comment] 2020-11-10 08:46
tap with 2 fingers for right click.

**Comment by HenryTheX** [comment] 2020-11-10 08:49
2 finger click (right click) doesnt work at all, already set inside settings still doesnt work, please fix, not sure is it specific to iPadOS 14.2 or iPad Pro 11?

**Comment by osy86** [comment] 2020-11-10 16:04
This should be fixed next release but for now, you need to go into settings and change it to anything else and back for it to take place.

**Comment by HenryTheX** [comment] 2020-11-10 19:20
Hi I updated the latest version  2.0.9 today same behaviour completely buggy wrong and unusable.
My mouse right click doesn't work at all. (Bug bug)
Middle button (scroll wheel) now acts as a half baked right click in most places (another bug?) but it doesn't work on many other places, doesn't work on task bar, doesn't work on start menu right half side, etc.

It seems to be the UTM pointer incompatibility with iPadOS 14.2 please kindly fix this asap otherwise it's unusable for people with iPadOS 14.2

**Comment by HenryTheX** [comment] 2020-11-10 19:22
I can see the update log for UTM version 2.0.9 saying fixed bug that prevent default pointer setting  to be load but it's not like that. The UTM VM doesn't translate iosb14.2 pointer event properly it has nothing to do with user setting in the app setting page.

**Comment by osy86** [comment] 2020-11-10 20:15
I was referring to https://github.com/utmapp/UTM/commit/e74e9e6bdea5a31fbd44ec882433dcc6bbcc0c7b If you have a different issue, then so be it.

**Comment by HenryTheX** [comment] 2020-11-10 20:42
Aappreciate osy86 for making such an amazing app. Windows 7 is fully usable on A14 (a bit slow on A12X due to its weaker single core performance) that is just unbelievable! I trust next version of iPad Pro that has A14X with 8GB ram would make Windows 7 smoothly running locally as having a free low end x86 PC inside iPad! Incredible work thanks for all the bug fixes.

**Comment by HenryTheX** [comment] 2020-11-10 20:44
> I was referring to [e74e9e6](https://github.com/utmapp/UTM/commit/e74e9e6bdea5a31fbd44ec882433dcc6bbcc0c7b) If you have a different issue, then so be it.
> 
> Even if I was mistaken there’s no reason to be an ass about it.

Sorry you took it that way. I think I mistaken your reply as "issued was fixed already in today's new version 3 hours ago" before I found out it's still present

**Comment by HenryTheX** [comment] 2020-11-10 20:47
Didn't expect not many people run mouse GUI VM on iOS 14 with altstore yet, thought it would be literally everyone but obviously I was wrong. This obvious mouse event issue related to iOS 14 has not been found

**Comment by MutatingFunc** [comment] 2020-11-14 16:59
First time user here, just ran into this too. It's great to see a fix is coming!

**Comment by Krummer** [comment] 2020-12-13 15:34
I found this to be an issue with every v2 build to date.  I have not yet been able to update beyond the last v1 build which does recognize the right click gesture of the Magic Keyboard trackpad because of this.   I am running a 2020 12.9 iPad Pro with the Magic Keyboard.  Regardless, a huge thanks you to the developers and contributors for an amazing piece of software!  Happy Holidays 👍

**Comment by osy** [comment] 2020-12-13 17:20
Yes I know that’s why the issue is still open. Right now I’m focused on getting M1 stuff working. Will circle back to ios once that’s more stable.

**Comment by Krummer** [comment] 2020-12-13 19:12
Sounds good, thanks for all of your hard work osy!

**Comment by 0sy-is-ssucch-a-s-st-puid-idio-t-l-l-l** [comment] 2020-12-23 11:44
> I was referring to [e74e9e6](https://github.com/utmapp/UTM/commit/e74e9e6bdea5a31fbd44ec882433dcc6bbcc0c7b) If you have a different issue, then so be it.
> 
> Even if I was mistaken there’s no reason to be an ass about it.

π0 υ!

**Closed** 2020-12-29 06:17 UTC
