### ISSUE TITLE
UTM crashes at a specific width/aspect ratio

### ISSUE THREAD

**Issue by zanderp25** [utmapp/UTM#3732] opened 2022-03-09 05:11 UTC
**Description**
When scaling horizontally from a large window, there’s a point where the content on the right scales as if the vertical scroll bar (on the far right) isn’t there, before the scroll bar itself disappears. (It works the opposite way, too, when scaling from a small window) Stop at that moment and relaunch the app. Now when you click a VM, it crashes a few seconds afterwards.

**Configuration**
* UTM Version: 3.0.4
* OS Version: 12.2.1
* Apple Silicon

**Crash log**
[UTM-2022-03-08-234553.ips](https://cdn.discordapp.com/attachments/732218843610742855/950980121114853436/UTM-2022-03-08-234553.ips)
(GitHub doesn't let me upload the filetype so i used Discord.)

**Additional Files**
<video src="https://user-images.githubusercontent.com/13000207/157377016-3a773004-52d5-4d03-bbc7-ac8101d4e48b.mp4" />

**Comment by osy** [comment] 2022-03-09 16:19
Duplicate of #3612

**Closed by osy** 2022-03-09 16:19 UTC
Labels: duplicate
