### ISSUE TITLE
Keyboard does not work in iPadOS 15.1 TrollStore

### ISSUE THREAD

**Issue by ak4zh** [utmapp/UTM#4419] opened 2022-09-15 23:11 UTC
**Describe the issue**
I have installed Windows 11 build 22000.
Devices connected MX Master3 and Logitech k380.
Mouse works fine inside windows but keyboard does not register the key press. I can still use the keyboard outside of UTM everything works fine with iPadOS. UTM does detect the keyboard because when I click on the on screen keyboard option of UTM it only shows the function bar in screen and not whole keyboard.

**Configuration (required)**
* UTM Version: 4.0.4 TrollStore version
* OS Version: iPadOS 15.1
* Device Model: iPad 12.9 M1
* Is it jailbroken (name jailbreak used)? No
* How did you install UTM? TrollStore

**Comment by ak4zh** [comment] 2022-09-15 23:29
So I have tested with Ubuntu 20.04 as well and confirmed keyboard does not work in that as well.

**Comment by osy** [comment] 2022-09-16 08:38
Duplicate of #4399

**Closed by osy** 2022-09-16 08:38 UTC
