### ISSUE TITLE
Question: AltSigner

### ISSUE THREAD

**Issue by Anwu949** [utmapp/UTM#542] opened 2020-11-19 23:33 UTC
To Mr. Osy,

Will AltSigner Work? It is an IPA signer on Windows(If you don't have AltStore 1.4.2b), which uses your Apple ID to sign certificates. In your description, you said UTM works with developer certificates(Which is this), yet not Enterprise. I will test it, yet I'm asking you for verification.

**Comment by osy86** [comment] 2020-11-20 18:01
Closing since it is not a bug. If you get it working though please post an update so others who are searching will know.

**Closed by osy86** 2020-11-20 18:01 UTC
