### ISSUE TITLE
Doesn't restart after stopping the virtual machine

### ISSUE THREAD

**Issue by KadirArslan** [utmapp/UTM#2461] opened 2021-04-26 00:05 UTC
I got the updated UTM application from the Apple store. Then I launched Ubuntu Focal Desktop as a virtual machine. (https://cdimage.ubuntu.com/focal/daily-live/current/). I am not having any problem starting or using the machine. But I have a problem like the virtual machine restarts after I stop it.

Repro Steps:
Download the iso file I linked
Follow the doc for install. Which is https://mac.getutm.app/gallery/ubuntu-20-04
Stop the machine. (Instead, you can turn off the virtual machine.)
Try to restart. You will see that it does not open again.

Operating System: macOS Big Sur
Architecture: M1
UTM Version: 2.0.25

**Comment by osy** [comment] 2021-04-26 01:38
Can you enable debug logging from the config and attach a debug log?

**Comment by muratdk23** [comment] 2021-04-26 16:07
Same problem with windows 10 arm. After shutting down I can't launch it any more. It trying to repair but shows blue screen.

**Comment by KadirArslan** [comment] 2021-04-26 21:04
here is the debug log

[debug.log](https://github.com/utmapp/UTM/files/6380309/debug.log)

**Comment by muratdk23** [comment] 2021-04-26 23:11
Version 2.0.27 issue still there.

**Comment by KadirArslan** [comment] 2021-05-03 22:23
Is there an any update?

**Comment by osy** [comment] 2021-05-03 22:24
If there is an update, this issue would be updated...

**Comment by KadirArslan** [comment] 2021-05-03 22:25
okey, thanks

**Comment by muratdk23** [comment] 2021-05-13 11:55
Version 2.0.28 issue still there.

**Comment by muratdk23** [comment] 2021-05-24 22:56
Version 2.1.1 same issue.

**Comment by osy** [comment] 2021-05-24 22:57
You don't need to comment after every update. The fact that the issue is open means that it's not fixed.

**Comment by conath** [comment] 2021-07-18 13:02
This is a duplicate of #2503

**Closed by conath** 2021-07-18 13:02 UTC
