### ISSUE TITLE
Can't load ISO

### ISSUE THREAD

**Issue by EscolarProgramming** [utmapp/UTM#2539] opened 2021-05-16 19:46 UTC
**Describe the issue**
We try to start Windows XP on an iPhone with 14.5.1. We already managed to deploy and launch UTM via Tethered Launch. Also, we already imported the .utm file for XP. The problem is, we cannot import the XP iso file - we select CD/DVD and get into the file browser, but when we want to select the iso file, nothing happens. The file is on the iPhone and not in the iCloud. Here's a demonstration video: https://cdn.discordapp.com/attachments/760196134294650932/842517711502180382/RPReplay_Final1620942200.MP4

**Configuration (required)**
* UTM Version: 2.0.27
* OS Version: 14.5.1
* Device Model: iPhone 12 mini 128GB
* Is it jailbroken (name jailbreak used)? No
* How did you install UTM? Tethered Launch

**Comment by conath** [comment] 2021-05-16 19:59
Indeed in your video the file browser appears and you are selecting the iso file, so it seems like everything is correct from your side. 

I can't reproduce this issue on my iPhone, I tried it with VoiceOver as well.

Please try this alternative Windows XP UTM file. It is newer than the one you are using in the video and it works on my iPhone. [XP.zip](https://chrisp.cafe/UTM/XP.zip)

**Comment by osy** [comment] 2021-05-17 01:50
Duplicate of #2386

**Comment by osy** [comment] 2021-05-17 01:51
Not sure of the cause but good to have another data point. Will track the progress in the other issue.

**Closed by osy** 2021-05-17 01:50 UTC
Labels: duplicate
