### ISSUE TITLE
Prebuilt VMs not opening

### ISSUE THREAD

**Issue by Adiy458** [utmapp/UTM#5539] opened 2023-08-07 23:10 UTC
Hi,

When I press open on a prebuilt .utm file, it doesn’t open and nothing happens. (I used an android vm from the official page on GitHub)

* UTM Version: UTM SE 4.3.5 build 87
* OS Version: iOS 17 public beta
* Device Model: iPhone 11
* Is it jailbroken (name jailbreak used)? N/a
* How did you install UTM? Via scarlet 

No debug log as machine won’t upload 

config.plist file: https://drive.google.com/file/d/1e7emCxRvuAEciS_sIqyouDIn3lwRWqKe/view?usp=drivesdk

thanks !

**Comment by osy** [comment] 2023-08-07 23:21
Duplicate of #5538

**Closed by osy** 2023-08-07 23:21 UTC
