### ISSUE TITLE
List of available VMs distorted/squeezed on macOS 11.3 Beta8

### ISSUE THREAD

**Issue by jamesdbailey** [utmapp/UTM#2449] opened 2021-04-17 21:02 UTC
**Describe the issue**
On the latest macOS Big Sur beta (11.3.Beta 8 20E5231a) the display of the list of available VMs is distorted on an M1 MacBook Air. See attached screenshot.

**Configuration**
* UTM Version: Version 2.0.25 (25)
* OS Version: macOS 11.3 Beta 8 (20E5231a)
* Intel or Apple Silicon? Apple Silicon

<img width="1012" alt="Screen Shot 2021-04-17 at 5 01 35 PM" src="https://user-images.githubusercontent.com/2602382/115126657-a5307e80-9f9e-11eb-98c8-7c8dc6ed7e45.png">

**Comment by osy** [comment] 2021-04-17 23:08
Duplicate of #2335

**Closed by osy** 2021-04-17 23:08 UTC
Labels: duplicate
