### ISSUE TITLE
Time synchronization does not work after sleep

### ISSUE THREAD

**Issue by tommytran732** [utmapp/UTM#5413] opened 2023-06-29 23:52 UTC
**Describe the issue**  
Time in the VM gets out of sync after the host goes to sleep

**Configuration**  
* UTM Version: 4.2.5
* macOS Version: 13.5 Beta
* Mac Chip (Intel, M1, ...): M2 Max

**Steps to reproduce**
1. Start a VM in the background
2. Verify that its time matches that of the host with `timedatectl`. 
3. Put the host to sleep for a few minutes
4. Turn the host back on, check the time inside of the guest. Observe that the guest's time does not get updated properly.

**Comment by tommytran732** [comment] 2023-06-30 02:22
Parallels has this problem too, but it will try to correct the VM's time in about a minute or so, regardless of whether you chose "Sync from mac" or not.

**Comment by osy** [comment] 2023-07-02 01:41
Duplicate of #5252

**Closed by osy** 2023-07-02 01:41 UTC
