### ISSUE TITLE
Display going nuts

### ISSUE THREAD

**Issue by yeetusdeletus69** [utmapp/UTM#2537] opened 2021-05-16 09:53 UTC
**Describe the issue**
A clear and concise description of what the issue is. **BEFORE SUBMITTING YOUR ISSUE, PLEASE LOOK AT THE PINNED ISSUES AND USE THE SEARCH FUNCTION TO MAKE SURE IT IS NOT ALREADY REPORTED. ALWAYS COMMENT ON AN EXISTING ISSUE INSTEAD OF MAKING A NEW ONE.**

**Configuration**
* UTM Version: 2.0.28
* OS Version: 11.3.1
* Intel or Apple Silicon?  Sillicon

**Crash log**
If the app crashed, you need a crash log. To get your crash log, open Console.app, go to `Crash Reports`, and find the latest entry for either QEMU, QEMUHelper, or qemu-\*. Right click and choose `Reveal in Finder`. Attach the report here.

**Debug log**
For all issues, _including_ crashes, you should attach a debug log. Open UTM, and open the settings for the VM you wish to launch. Near the top of the `QEMU` page is `Debug Log`. Turn it on and save the VM. After you experience the issue, open the VM settings again and select `Export Log...` and attach it here.    It doesn't crash. it just freezes and never crashes

**Upload VM**
(Optional) If possible, upload the `config.plist` inside the `.utm`. If you do not have this, you can upload the entire `.utm` but note this contains your personal data. Since Github has an attachment size limit, you may want to upload to another service such as Google Drive. Link it here.

**Comment by conath** [comment] 2021-05-16 19:29
Could you please update your issue with a detailed, concise description of the problem? Just a title of "Display going nuts" without any context is not helpful. Thanks!

**Comment by youtu-DOT-be-SLASH-CB2Z4-t1l7c** [comment] 2021-05-29 10:37
ent

**Comment by youtu-DOT-be-SLASH-CB2Z4-t1l7c** [comment] 2021-05-29 10:37
and

**Comment by youtu-DOT-be-SLASH-CB2Z4-t1l7c** [comment] 2021-05-29 10:37
dfk;

**Comment by osy** [comment] 2021-07-10 19:59
Duplicate of #2569

**Closed by osy** 2021-07-10 19:59 UTC
Labels: duplicate
