### ISSUE TITLE
BSOD while installing Windows 7 from UTM gallery, iOS 15 beta 8, iPad Pro M1

### ISSUE THREAD

**Issue by AnatolyPristensky** [utmapp/UTM#3079] opened 2021-09-02 17:40 UTC
**Describe the issue**
BSOD happening while installing Windows 7 at iPad Pro M1, iOS 15 Beta 8. I've used unmodified Windows 7 ISO file. BSOD appears immediately after setup is initialized and cursor appears. Standard Windows 7 template from UTM gallery has been used.

**Configuration**
* UTM Version: 2.2.2 beta
* OS Version: iOS 15 beta 8
* Device Model: iPad Pro M1
* Is it jailbroken (name jailbreak used)? No
* How did you install UTM? AltStore, UTM SE

**Comment by AnatolyPristensky** [comment] 2021-09-02 17:44
![image](https://user-images.githubusercontent.com/84129877/131891849-942f04b3-b577-4a07-b6ca-811300231c4c.jpeg)

**Comment by osy** [comment] 2021-09-04 03:51
Duplicate of #2721

**Closed by osy** 2021-09-04 03:51 UTC
