### ISSUE TITLE
iOS 15.1.1 - VM boot issue on Elementary OS - iOS device crashes

### ISSUE THREAD

**Issue by larryqiann** [utmapp/UTM#3359] opened 2021-12-01 19:31 UTC
When attempting to boot the live CD of the Elementary OS Linux distribution in BIOS mode, the app crashes the entire device after a while of sitting on the blinking cursor. In UEFI mode, the app sits at a blue UTM icon after a while, but doesn't crash.

Thanks!

**Configuration**
* UTM Version: Latest as of today (how can I check?)
* OS Version: iOS 15.1.1
* Device Model: iPhone 12 Pro Max
* Is it jailbroken (name jailbreak used)? No
* How did you install UTM? AltStore Non Beta

**Crash log**
None noted

**Debug log**
[debug.log](https://github.com/utmapp/UTM/files/7636638/debug.log)

**Upload VM**
[config.plist.zip](https://github.com/utmapp/UTM/files/7636659/config.plist.zip)

**Comment by conath** [comment] 2021-12-02 23:45
Your VM is configured with the Emulated Display Card `virtio-vga-gl`. The `-gl` indicates this card enables OpenGL-based graphics acceleration for the VM.

Unfortunately, there is a known issue that causes iOS 15 devices running UTM with this configuration to crash. Duplicate of #2743 

There is an easy workaround; go to VM configuration and change the Emulated Display Card to `virtio-vga`.

**Closed by conath** 2021-12-02 23:45 UTC
Labels: crash, iOS
