### ISSUE TITLE
Apple ID on macOS VM won't work

### ISSUE THREAD

**Issue by fmsjd** [utmapp/UTM#5214] opened 2023-04-20 02:00 UTC
In any situation on my macOS 12.6 VM, trying to sign in with an Apple ID will not work. I enter my email then it asks for my password, and when I click 'Continue', it simply says in red 'The action could not be completed'.

**Configuration**  
* UTM Version: 4.1.6 (75)
* macOS Version: 12.6
* Mac Chip: M1

This is **not** a VM-specific issue. The image below shows the issue at first setup, it happened in System Preferences and the App Store too.
<img width="1080" alt="Screen Shot 2023-04-20 at 11 58 13" src="https://user-images.githubusercontent.com/130889501/233238367-f8c0a0ea-3328-4b69-b7e5-a6ebb1ad63a9.png">

**Comment by osy** [comment] 2023-04-20 02:59
Duplicate of #3617

**Closed by osy** 2023-04-20 02:59 UTC

**Comment by fmsjd** [comment] 2023-04-20 05:25
> Duplicate of #3617

Thank you, couldn't find a duplicate earlier.

**Comment by mattruzzi** [comment] 2023-07-06 20:59
https://kb.parallels.com/128867
https://forum.parallels.com/threads/apple-id-login-in-macos-guest-os.355059/
https://developer.apple.com/forums/thread/707682
