### ISSUE TITLE
VM list items are cropped visually

### ISSUE THREAD

**Issue by gklka** [utmapp/UTM#2543] opened 2021-05-17 08:36 UTC
**Describe the issue**
I have one VM in my UTM app and the item for that VM looks visually cropped in the sidebar.

**Configuration**
* UTM Version: 2.0.28 (28)
* OS Version: 11.3.1 (20E241)
* Intel or Apple Silicon? Intel

<img width="431" alt="Screen Shot 2021-05-17 at 10 33 56" src="https://user-images.githubusercontent.com/866694/118459138-bc789e00-b6fb-11eb-9eaa-37dade7ce694.png">

**Comment by osy** [comment] 2021-05-17 08:40
Duplicate of #2335

**Closed by osy** 2021-05-17 08:40 UTC
