### ISSUE TITLE
Ubuntu 18.04 slow performance

### ISSUE THREAD

**Issue by daniellaera** [utmapp/UTM#711] opened 2020-11-28 12:34 UTC
**Describe the bug**
When I run ubuntu 18.04 after the logo with dots the black screen appears and it doesn’t load the OS.
For simply run the OS I should put the memory at max. But it still really slow, impossible to interact with it.

**Version**
2.0.11.

**To Reproduce**
1. Run the Ubuntu 18.04 utm file
2. It opens the UTM VM
3. Animation loading...
4. Stuck on black screen

**Expected behavior**
It should work normally.

**Additional context**
No ability to hold mouse button and move pointer at same time.

**Comment by IIWare** [comment] 2020-11-28 13:38
Duplicate of #567

**Comment by IIWare** [comment] 2020-11-28 13:48
@daniellaera I see you confused in my previous comment, so are you using utm in macOS or in iPhone/iPad/iPod?

**Comment by daniellaera** [comment] 2020-11-28 13:56
> @daniellaera I see you confused in my previous comment, so are you using utm in macOS or in iPhone/iPad/iPod?

I am running Ubuntu on the Apple M1 and I tried with the 18.04 desktop provided by UTM VMs and the I tried with the 20.04 LTS and it is impossible to interact with, mouse doesn’t select element when in the virtual environment

**Comment by osy86** [comment] 2020-11-29 23:56
There's two separate issues here. The performance issue is due to the fact that UTM currently does not virtualize the CPU (and if it did, you would need to run the aarch64 version). The emulation is slow even on a fast processor like the M1.

The mouse issue is a Ubuntu driver problem that you can get by running it directly with QEMU. You would have to uninstall some driver (can't remember what right now) that is baked into the live cd.

Finally there are still mouse issues with UTM for macOS that are being tracked in another issue so I'll close this as a duplicate of #710

**Comment by osy86** [comment] 2020-11-29 23:56
Duplicate of #710

**Closed by osy86** 2020-11-29 23:56 UTC
Labels: duplicate
