### ISSUE TITLE
No option for touchscreen when making android vm

### ISSUE THREAD

**Issue by cer1234567-bit** [utmapp/UTM#447] opened 2020-09-10 19:47 UTC
Once I create a virtual machine with an android OS there is no option for touchscreen,only gestures and once I load up the VM I click boot and it freezes. At first I got UTM through github since I'm jail broken then once I had issues I deleted it and side loaded with alt store and it still would not work.

**Comment by osy86** [comment] 2020-09-10 21:13
Duplicate of #446

**Closed by osy86** 2020-09-10 21:13 UTC
Labels: duplicate
