### ISSUE TITLE
efibootmgr not persisted

### ISSUE THREAD

**Issue by pcarrier** [utmapp/UTM#2679] opened 2021-07-23 15:35 UTC
Changes made to the EFI configuration through efibootmgr in Arch Linux ARM are persisted after a reboot, but not a shutdown and a restart. I assume the NVRAM is not persisted but know little about qemu.

**Configuration**
* UTM Version: 2.1.2 (31) from Mac App Store
* OS Version: Big Sur 11.4
* Apple Silicon

**Debug log**
[debug.log](https://github.com/utmapp/UTM/files/6869777/debug.log)

**Upload VM**
[config.plist.txt](https://github.com/utmapp/UTM/files/6869782/config.plist.txt)

**Comment by conath** [comment] 2021-08-03 19:40
Duplicate of #2503 

Thank you for including the required files and a thorough description of the issue!

**Closed by conath** 2021-08-03 19:40 UTC
