### ISSUE TITLE
[Feature Request] Run vm from external storage (USB)

### ISSUE THREAD

**Issue by Krummer** [utmapp/UTM#457] opened 2020-09-14 02:40 UTC
I would love the ability to run my VM img from from an external USB drive rather than having to import to the local iPad storage.  This would greatly expand the number of VM’s that can be maintained as well as reduce the overall wear and use of the iPad flash itself.  I assume the VM profile file has to live in the App container, but could the storage pointer access the external storage for the img?

This may be a duplicate of #123 but the way it reads it is not completely clear this would be the same use case.

**Comment by Krummer** [comment] 2020-09-14 02:44
Sorry, I believe the duplicate may be defect/enhancement #132

**Comment by IIWare** [comment] 2020-09-14 17:58
> Sorry, I believe the duplicate may be defect/enhancement #132
* #123

**Comment by osy86** [comment] 2020-09-15 15:42
Duplicate of #410

**Closed by osy86** 2020-09-15 15:42 UTC
Labels: bug, duplicate
