### ISSUE TITLE
Mac OS Virtualized: unable to use USB device

### ISSUE THREAD

**Issue by mgesmundo** [utmapp/UTM#4923] opened 2023-01-08 09:37 UTC
Hi there,
I've create a Mac OS Monterey 12.6.2 VM but the USB button on the toolbar is disabled and I'm not able to connect an external USB device.
There is some workaround?
Thank you.

**Comment by osy** [comment] 2023-01-08 15:47
Duplicate of #3778

**Closed** 2023-01-08 15:47 UTC
