### ISSUE TITLE
Import 3D acceleration support (through virgl)

### ISSUE THREAD

**Issue by woachk** [utmapp/UTM#2379] opened 2021-03-13 21:41 UTC
https://gist.github.com/akihikodaki/87df4149e7ca87f18dc56807ec5a1bc5 includes instruction on how to have virgl acceleration for Linux guests on macOS hosts (including Apple M1),

**Comment by osy** [comment] 2021-03-13 22:23
Duplicate of #161

**Closed by osy** 2021-03-13 22:23 UTC
Labels: duplicate
