### ISSUE TITLE
Pass in Microphone and Camera

### ISSUE THREAD

**Issue by DUOLabs333** [utmapp/UTM#3295] opened 2021-11-08 16:58 UTC
Would it be possible for UTM to have an option to pass in MacOS's built-in camera and microphone?

**Comment by conath** [comment] 2021-11-08 21:24
Thank you for your question. It is already possible to use the microphone in your VMs. This is supported when the VM uses an Emulated Audio Card that starts with "Intel", and the prompt to enable microphone access shows up once a VM requests to use it. 

Camera pass-through is not (yet) supported. (Duplicate of #432)
Please search previous issues before opening a new one.

If the mic is not working in your VM despite the audio device set to AC97 or Intel HD Audio Controller, please create a new issue with the necessary debug info. (see Issue template)

Feel free to join the [UTM Community Discord server](https://discord.gg/UV2RUgD) if you have further questions.

**Closed by conath** 2021-11-08 21:24 UTC
Labels: enhancement

**Comment by DUOLabs333** [comment] 2021-11-08 21:34
Is this specific to UTM's version of qemu, or is this able to be used by base qemu?

**Comment by conath** [comment] 2021-11-08 21:38
UTM uses the SPICE framework to communicate to QEMU, and the SPICE used is compiled to include [GStreamer](https://gstreamer.freedesktop.org/documentation/index.html?gi-language=c). 

After your question I have just tested if the mic sharing actually works (macOS 12 host) and it seems to be broken with all audio cards. 🙅
