### ISSUE TITLE
The network always failing after a while

### ISSUE THREAD

**Issue by taciocabral** [utmapp/UTM#4134] opened 2022-06-15 12:19 UTC
**Describe the issue**
When started the machine, the network works normally. But after a while it fails, then you have to restart the machine.
It doesn't matter if I use 'Shared Network' or 'Bridge', it fails after a while.

**Configuration**
* UTM Version: 3.2.4
* OS Version: MacOS 12.1
* Apple Silicon

**Comment by introns-bungles** [comment] 2022-06-16 10:51
What Guest OS are you running?

Having the same problem since upgrading some packages in an `Arch Linux ARM` VM. Luckily I had a backup from before the upgrades of said VM.

I'am currently investigating where exactly this appeared. At the moment my hypothesis is that the recent `kernel 5.18.1` or `systemd 250.5` upgrade is to blame, but I'am not sure at the moment.

I may add I use this VM as a server in a home network so there are two network interfaces, the Mac Mini's and a USB ethernet dongle (no passthrough, configured in macOS). But the error occurs randomly on those interfaces.

**Configuration**

- UTM Version: 3.2.4
- OS Version: MacOS 12.4
- Apple Silicon: M1 (Mac Mini)

**Comment by conath** [comment] 2022-06-24 21:21
@introns-bungles Do you think we can close this, since it appears to be a guest-OS-specific issue?

**Comment by introns-bungles** [comment] 2022-06-25 07:46
@conath I did't had any chance to troubleshoot the issue any further. Still using the backup VM. But yes I think this is a guest specific issue, which could be confirmed by @taciocabral answering what guest OS he's referring to. You can close the issue and I will report back if anything comes up on my end.

**Closed** 2022-06-25 12:36 UTC
Labels: macOS

**Comment by introns-bungles** [comment] 2022-06-28 14:05
@conath So I tried to nail down the offending package and it seems related to the recent `irqbalance` upgrade `1.8.0 -> 1.9.0`. Rolled it back and had no issues whatsoever in the last 36h. Weird thing is there are no visible errors in `qemu`, `guest kernel` and `irqbalance` logs. But it seem it doesn't like running inside a VM as there are no reported problems with the recent version in non-VM environments.
