### ISSUE TITLE
[Feature Request] Show disk activity for the active disks

### ISSUE THREAD

**Issue by UrkiMimi** [utmapp/UTM#4207] opened 2022-07-11 23:00 UTC
I think it would be helpful if the disk activity was shown in UTM as both VMware and VirtualBox have this feature. It's useful as it lets me know when an OS froze and lets me know it is safe to turn off the machine if theres no disk activity.

**Comment by osy** [comment] 2022-07-14 22:49
Duplicate of #238

**Closed by osy** 2022-07-14 22:49 UTC
Labels: duplicate
