### ISSUE TITLE
[iPad问题]iOS14.4.1，使用牛磺酸越狱，但我无法打开它（UTM）

### ISSUE THREAD

**Issue by kenny000001** [utmapp/UTM#5628] opened 2023-08-29 20:00 UTC
**what problem I been**
I had a iPhone X iOS15.2,it use TrollStore only,iPhone is installed UTM Successful;then 1 day ,I use taurine to jailbreak the iPad 6,Then I try to install UTM.however ,iPad has installed UTM,but it also crash.(I was try deb and ipa)

***UTM version ：4.3.5 and 4.4.0 version(.deb and .hv.ipa)
* system version:iOS 14.4.1
*model:MRJP2ZP/A[iPad(6th generation)]
*taurine jailbreak(ver1.1.7b1)
*installion:I use Sileo install Deb and TrollStore install UTM.HV.ipa   .
* **崩溃日志**
[UTM-2023-08-30-025706.ips.txt](https://github.com/utmapp/UTM/files/12468720/UTM-2023-08-30-025706.ips.txt)

**Comment by osy** [comment] 2023-08-29 20:12
Duplicate of #3628

**Closed by osy** 2023-08-29 20:12 UTC

**Comment by kenny000001** [comment] 2023-08-30 03:46
Thanks
