### ISSUE TITLE
USB Device disconnected (fatal IO error)

### ISSUE THREAD

**Issue by Zhanyuanium** [utmapp/UTM#4777] opened 2022-12-07 13:09 UTC
**BEFORE SUBMITTING YOUR ISSUE, PLEASE LOOK AT THE PINNED ISSUES AND USE THE SEARCH FUNCTION TO MAKE SURE IT IS NOT ALREADY REPORTED. ALWAYS COMMENT ON AN EXISTING ISSUE INSTEAD OF MAKING A NEW ONE.**

**Describe the issue**
Windows 7 x64 emulation, shared USB, USB 3.0 or 2.0. 
When I connect my iPhone 4S through a USB dock, it is recognized as `iPhone (1:3)` in UTM toolbar. But clicking on it immediately causes an error alert: 
> USB Device [05ac:12a0] at 1-6 disconnected (fatal IO error)

Then there is a tick in front of `iPhone (1:3)`, however my iPhone is not really connected with my Windows guest OS. 
<img width="240" alt="截屏2022-12-07 20 47 02" src="https://user-images.githubusercontent.com/92024923/206185060-add5151d-77c2-44f2-aa06-c75fe79bd863.png">
<img width="404" alt="截屏2022-12-07 20 47 19" src="https://user-images.githubusercontent.com/92024923/206184915-991cc439-698f-45b2-a043-51ddaafd3162.png">
<img width="748" alt="截屏2022-12-07 20 48 02" src="https://user-images.githubusercontent.com/92024923/206192744-1c9c1bf1-5214-4426-a9e2-13655937659a.png">

A proper version of iTunes and Spice guest tools are installed, and I’ve tried every combinations of USB settings. 
By the way, iPhone is shown in macOS Finder. Maybe macOS hijacked my connection? 
<img width="1032" alt="截屏2022-12-07 21 35 32" src="https://user-images.githubusercontent.com/92024923/206195386-f3ca94bb-eeb8-45d0-96c3-86e396ad3b93.png">

**Configuration**  
* UTM Version: 4.0.9
* macOS Version: 12.6.1
* Mac Chip: M1

**Crash log**  
N/A

**Debug log**  
Sounds weird but UTM couldn’t output a debug log (the button is grey).
<img width="425" alt="截屏2022-12-07 20 59 00" src="https://user-images.githubusercontent.com/92024923/206185584-239f4de9-e085-4dbd-ad09-e54b87c4463c.png">

**Upload VM**  
May not necessary. 
[config.zip](https://github.com/utmapp/UTM/files/10176539/config.zip)

**Comment by osy** [comment] 2023-01-07 18:57
Duplicate of #3063

**Closed by osy** 2023-01-07 18:57 UTC
