### ISSUE TITLE
"Display Output Not Active" Error + Misleading UTM Documentation on SPICE Tools.

### ISSUE THREAD

**Issue by denischernenko** [utmapp/UTM#6853] opened 2024-11-29 14:17 UTC
Hi, everyone!

I made sure, that there is no exact same issue before posting it. Also, I really think, that fixing that is a major deal.

- Machine: Apple MacBook M1 Pro 16'' 16Gb 2021
- MacOS Sonoma 14.7
- UTM Version 4.6.2 (104)
- Windows 11 (straight from Microsoft website)
- RAM assigned to VM: 12Gb
- HDD assigned to VM: 128Gb
- Ticked 'Installed SPICE Drivers', while creating a new VM too.
- Emulated Display Card: virtio-ramfb-gl (GPU Supported) / default setting

_Issue One:_ After installing Windows 11, it immediately offers you to install UTM Guest Tools. However, after 60-70% of installation complete, suddenly the screen get black and it returns error "Display Output Not Active". Sadly, there is nothing to do with the screen being black and reboot did not help, neither did changing the Emulated Display Card in VM Hardware settings.

I tried the whole procedure again, but got the exact same result. 

On the 3rd attempt I noticed, that the version of UTM Guest tools is different from the knowledge base on UTM website! 

_Issue Two:_ Out of the box it offers you to install the drivers from the file called E:\utm-guest-tools-**0.229**.exe, but the link from the documentation (namely [https://github.com/utmapp/qemu/releases/download/v7.0.0-utm/spice-guest-tools-0.164.4.iso](url) is leading to the file called spice-guest-tools-**0.164.4**.iso all the way from QEMU v7 Assets! 

The problem is still not solved, by the way. I installed Windows 11 for the 3rd time and now I will be finding a way to, at least, install network drivers separately and try to use the VM.

Unfortunately, there are no crash logs available, since the screen of the VM get ALL BLACK and I have no idea how to extract it from dead VM. However, I am ready to provide any additional information on the matter. 

UPDATE: installing drivers from spice-guest-tools-**0.164.4**.iso — leads to the exact same error. 

UPDATE 2: I have managed to boot the VM back by changing Emulated Display Card -> virtio-ramfb-gl (GPU Not Supported).

**Comment by osy** [comment] 2024-11-29 15:20
Duplicate of #6332

**Closed by osy** 2024-11-29 15:20 UTC

**Comment by thewindowsBoy2012** [comment] 2025-05-17 12:06
Hello I am also experiencing the same issue i am on a macbook air m3 13 inch and I boot the windows 11 vhdx and I successfully get past the installer but after trying to install utm guest tools I get the same message and I don't see the option for virtio-ramfb-gl (GPU Not Supported).
