### ISSUE TITLE
Can't turn VHDX into qcow2 with Homebrew

### ISSUE THREAD

**Issue by NitroxTeddy** [utmapp/UTM#3401] opened 2021-12-21 12:47 UTC
So recently I got into vms and wanted to set one up on my M1 mac, since there is no intel card I came here. I figured out a bunch of stuff and realized that I needed to convert the VHDX into a qcow2 via HomeBrew. I tried this but It said "Operation not permitted".
Any ideas?

**Comment by conath** [comment] 2021-12-22 12:12
Welcome to UTM. You are right, you can absolutely emulate Intel/x86-64 based systems with this app. (emulated speed will vary)

However website, UTM issues, is for reporting technical problems or requests related to UTM - not QEMU or Homebrew.

I will close this as duplicate of #2526 since it is a related topic. 

All that being said, I do have an idea about your error. 

> Operation not permitted

It seems like either it can’t read the VHDX file or the destination path you have provided is not writable by your current user. When I use `qemu-img` I always do it in the `~/Downloads` folder to avoid this. And make sure no other app on your Mac is accessing the VHDX when you are doing the conversion.

**Closed by conath** 2021-12-22 12:12 UTC
