### ISSUE TITLE
UTM SE crash when start VM - iPad Pro M1

### ISSUE THREAD

**Issue by jesselafeber** [utmapp/UTM#4523] opened 2022-10-19 19:08 UTC
**Describe the issue**
App crashes when start a VM. It makes no different  if I change the setting or create a linux VM when a .ISO from the gallery.

**Configuration (required)**
* UTM Version: SE (4.0.8)
* OS Version: iPadOS 16.1
* Device Model: Ipad Pro 2021 M1
* Is it jailbroken (name jailbreak used)?  NO
* How did you install UTM? Altstore

<details>
  <summary>**Crash log**</summary>

```log
{"app_name":"UTM SE","timestamp":"2022-10-19 20:58:31.00 +0200","app_version":"4.0.8","slice_uuid":"2c59f93d-8de3-379f-adae-2975a8f813ac","build_version":"67","platform":2,"bundleID":"com.utmapp.UTM-SE.5G9448A888","share_with_app_devs":1,"is_first_party":0,"bug_type":"309","os_version":"iPhone OS 16.1 (20B5056e)","roots_installed":0,"name":"UTM SE","incident_id":"C0858E75-29D4-49E0-B1B9-526685C10D43"}
{
  "uptime" : 22000,
  "procRole" : "Foreground",
  "version" : 2,
  "userID" : 501,
  "deployVersion" : 210,
  "modelCode" : "iPad13,4",
  "coalitionID" : 826,
  "osVersion" : {
    "isEmbedded" : true,
    "train" : "iPhone OS 16.1",
    "releaseType" : "Beta",
    "build" : "20B5056e"
  },
  "captureTime" : "2022-10-19 20:58:30.0252 +0200",
  "incident" : "C0858E75-29D4-49E0-B1B9-526685C10D43",
  "pid" : 976,
  "cpuType" : "ARM-64",
  "roots_installed" : 0,
  "bug_type" : "309",
  "procLaunch" : "2022-10-19 20:51:03.6305 +0200",
  "procStartAbsTime" : 539204319979,
  "procExitAbsTime" : 549918014855,
  "procName" : "UTM SE",
  "procPath" : "\/private\/var\/containers\/Bundle\/Application\/80851BC7-E6D8-4090-B4DD-8C065B6E2469\/App.app\/UTM SE",
  "bundleInfo" : {"CFBundleShortVersionString":"4.0.8","CFBundleVersion":"67","CFBundleIdentifier":"com.utmapp.UTM-SE.5G9448A888"},
  "storeInfo" : {"deviceIdentifierForVendor":"AFC9B81D-8AA0-4799-B438-47E93E08F289","thirdParty":true},
  "parentProc" : "launchd",
  "parentPid" : 1,
  "coalitionName" : "com.utmapp.UTM-SE.5G9448A888",
  "crashReporterKey" : "7fe823b1d571ce9f294de04a21b1482647df597b",
  "exception" : {"codes":"0x0000000000000001, 0x0000000121367b30","rawCodes":[1,4852185904],"type":"EXC_BREAKPOINT","signal":"SIGTRAP"},
  "termination" : {"flags":0,"code":5,"namespace":"SIGNAL","indicator":"Trace\/BPT trap: 5","byProc":"exc handler","byPid":976},
  "os_fault" : {"process":"UTM SE"},
  "faultingThread" : 10,
  "threads" : [{"id":403402,"queue":"com.apple.main-thread","frames":[{"imageOffset":2856,"symbol":"mach_msg2_trap","symbolLocation":8,"imageIndex":0},{"imageOffset":77800,"symbol":"mach_msg2_internal","symbolLocation":80,"imageIndex":0},{"imageOffset":78376,"symbol":"mach_msg_overwrite","symbolLocation":388,"imageIndex":0},{"imageOffset":4204,"symbol":"mach_msg","symbolLocation":24,"imageIndex":0},{"imageOffset":502512,"symbol":"__CFRunLoopServiceMachPort","symbolLocation":160,"imageIndex":1},{"imageOffset":507188,"symbol":"__CFRunLoopRun","symbolLocation":1232,"imageIndex":1},{"imageOffset":528084,"symbol":"CFRunLoopRunSpecific","symbolLocation":612,"imageIndex":1},{"imageOffset":4968,"symbol":"GSEventRunModal","symbolLocation":164,"imageIndex":2},{"imageOffset":3807296,"symbol":"-[UIApplication _run]","symbolLocation":888,"imageIndex":3},{"imageOffset":3806372,"symbol":"UIApplicationMain","symbolLocation":340,"imageIndex":3},{"imageOffset":1910608,"imageIndex":4},{"imageOffset":1257380,"imageIndex":4},{"imageOffset":1163192,"imageIndex":4},{"imageOffset":2156000,"imageIndex":5},{"imageOffset":193808,"imageIndex":5},{"imageOffset":88416,"symbol":"start","symbolLocation":2528,"imageIndex":6}]},{"id":403413,"name":"com.apple.uikit.eventfetch-thread","frames":[{"imageOffset":2856,"symbol":"mach_msg2_trap","symbolLocation":8,"imageIndex":0},{"imageOffset":77800,"symbol":"mach_msg2_internal","symbolLocation":80,"imageIndex":0},{"imageOffset":78376,"symbol":"mach_msg_overwrite","symbolLocation":388,"imageIndex":0},{"imageOffset":4204,"symbol":"mach_msg","symbolLocation":24,"imageIndex":0},{"imageOffset":502512,"symbol":"__CFRunLoopServiceMachPort","symbolLocation":160,"imageIndex":1},{"imageOffset":507188,"symbol":"__CFRunLoopRun","symbolLocation":1232,"imageIndex":1},{"imageOffset":528084,"symbol":"CFRunLoopRunSpecific","symbolLocation":612,"imageIndex":1},{"imageOffset":271156,"symbol":"-[NSRunLoop(NSRunLoop) runMode:beforeDate:]","symbolLocation":212,"imageIndex":7},{"imageOffset":270876,"symbol":"-[NSRunLoop(NSRunLoop) runUntilDate:]","symbolLocation":64,"imageIndex":7},{"imageOffset":5072196,"symbol":"-[UIEventFetcher threadMain]","symbolLocation":436,"imageIndex":3},{"imageOffset":374792,"symbol":"__NSThread__start__","symbolLocation":716,"imageIndex":7},{"imageOffset":5836,"symbol":"_pthread_start","symbolLocation":148,"imageIndex":8},{"imageOffset":2980,"symbol":"thread_start","symbolLocation":8,"imageIndex":8}]},{"id":403415,"queue":"com.apple.root.background-qos","frames":[{"imageOffset":2724,"symbol":"semaphore_wait_trap","symbolLocation":8,"imageIndex":0},{"imageOffset":17784,"symbol":"_dispatch_sema4_wait","symbolLocation":28,"imageIndex":9},{"imageOffset":19500,"symbol":"_dispatch_semaphore_wait_slow","symbolLocation":132,"imageIndex":9},{"imageOffset":46948,"imageIndex":5},{"imageOffset":9396,"symbol":"_dispatch_call_block_and_release","symbolLocation":32,"imageIndex":9},{"imageOffset":16348,"symbol":"_dispatch_client_callout","symbolLocation":20,"imageIndex":9},{"imageOffset":88972,"symbol":"_dispatch_root_queue_drain","symbolLocation":684,"imageIndex":9},{"imageOffset":90756,"symbol":"_dispatch_worker_thread2","symbolLocation":164,"imageIndex":9},{"imageOffset":3516,"symbol":"_pthread_wqthread","symbolLocation":228,"imageIndex":8},{"imageOffset":2968,"symbol":"start_wqthread","symbolLocation":8,"imageIndex":8}]},{"id":409593,"frames":[{"imageOffset":2960,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":8}]},{"id":409623,"frames":[{"imageOffset":2960,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":8}]},{"id":409624,"frames":[{"imageOffset":2960,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":8}]},{"id":409625,"queue":"com.utmapp.UTM.VMOperations","frames":[{"imageOffset":2748,"symbol":"semaphore_timedwait_trap","symbolLocation":8,"imageIndex":0},{"imageOffset":17908,"symbol":"_dispatch_sema4_timedwait","symbolLocation":64,"imageIndex":9},{"imageOffset":19444,"symbol":"_dispatch_semaphore_wait_slow","symbolLocation":76,"imageIndex":9},{"imageOffset":24724,"imageIndex":5},{"imageOffset":27600,"imageIndex":5},{"imageOffset":9396,"symbol":"_dispatch_call_block_and_release","symbolLocation":32,"imageIndex":9},{"imageOffset":16348,"symbol":"_dispatch_client_callout","symbolLocation":20,"imageIndex":9},{"imageOffset":46740,"symbol":"_dispatch_lane_serial_drain","symbolLocation":672,"imageIndex":9},{"imageOffset":49632,"symbol":"_dispatch_lane_invoke","symbolLocation":384,"imageIndex":9},{"imageOffset":93712,"symbol":"_dispatch_workloop_worker_thread","symbolLocation":652,"imageIndex":9},{"imageOffset":3576,"symbol":"_pthread_wqthread","symbolLocation":288,"imageIndex":8},{"imageOffset":2968,"symbol":"start_wqthread","symbolLocation":8,"imageIndex":8}]},{"id":411252,"name":"SPICE Main Loop","frames":[{"imageOffset":16908,"symbol":"poll","symbolLocation":8,"imageIndex":0},{"imageOffset":462456,"symbol":"g_poll","symbolLocation":40,"imageIndex":10},{"imageOffset":382992,"symbol":"g_main_context_poll","symbolLocation":104,"imageIndex":10},{"imageOffset":372232,"symbol":"g_main_context_iterate","symbolLocation":420,"imageIndex":10},{"imageOffset":374080,"symbol":"g_main_loop_run","symbolLocation":868,"imageIndex":10},{"imageOffset":2991276,"imageIndex":5},{"imageOffset":5836,"symbol":"_pthread_start","symbolLocation":148,"imageIndex":8},{"imageOffset":2980,"symbol":"thread_start","symbolLocation":8,"imageIndex":8}]},{"id":411256,"name":"com.apple.SwiftUI.AsyncRenderer","frames":[{"imageOffset":2856,"symbol":"mach_msg2_trap","symbolLocation":8,"imageIndex":0},{"imageOffset":77800,"symbol":"mach_msg2_internal","symbolLocation":80,"imageIndex":0},{"imageOffset":78376,"symbol":"mach_msg_overwrite","symbolLocation":388,"imageIndex":0},{"imageOffset":4204,"symbol":"mach_msg","symbolLocation":24,"imageIndex":0},{"imageOffset":502512,"symbol":"__CFRunLoopServiceMachPort","symbolLocation":160,"imageIndex":1},{"imageOffset":507188,"symbol":"__CFRunLoopRun","symbolLocation":1232,"imageIndex":1},{"imageOffset":528084,"symbol":"CFRunLoopRunSpecific","symbolLocation":612,"imageIndex":1},{"imageOffset":271156,"symbol":"-[NSRunLoop(NSRunLoop) runMode:beforeDate:]","symbolLocation":212,"imageIndex":7},{"imageOffset":270792,"symbol":"-[NSRunLoop(NSRunLoop) run]","symbolLocation":64,"imageIndex":7},{"imageOffset":698800,"imageIndex":4},{"imageOffset":690928,"imageIndex":4},{"imageOffset":374792,"symbol":"__NSThread__start__","symbolLocation":716,"imageIndex":7},{"imageOffset":5836,"symbol":"_pthread_start","symbolLocation":148,"imageIndex":8},{"imageOffset":2980,"symbol":"thread_start","symbolLocation":8,"imageIndex":8}]},{"id":411267,"frames":[{"imageOffset":4072,"symbol":"__semwait_signal","symbolLocation":8,"imageIndex":0},{"imageOffset":22488,"symbol":"nanosleep","symbolLocation":220,"imageIndex":11},{"imageOffset":629736,"symbol":"g_usleep","symbolLocation":80,"imageIndex":10},{"imageOffset":36542620,"symbol":"call_rcu_thread","symbolLocation":116,"imageIndex":12},{"imageOffset":36510232,"symbol":"qemu_thread_start","symbolLocation":128,"imageIndex":12},{"imageOffset":5836,"symbol":"_pthread_start","symbolLocation":148,"imageIndex":8},{"imageOffset":2980,"symbol":"thread_start","symbolLocation":8,"imageIndex":8}]},{"triggered":true,"id":411268,"threadState":{"x":[{"value":5},{"value":2},{"value":2},{"value":4899224280,"symbolLocation":936,"symbol":"tcg_init_ctx"},{"value":4889629576,"symbolLocation":82464,"symbol":"all_helpers"},{"value":0},{"value":0},{"value":0},{"value":4882639110},{"value":2},{"value":4852185988},{"value":76},{"value":4735369216},{"value":4336497608},{"value":0},{"value":0},{"value":9147472896,"symbolLocation":0,"symbol":"_platform_memset"},{"value":9398221296},{"value":0},{"value":4},{"value":10761365632},{"value":10771787888},{"value":10789229632},{"value":0},{"value":4899223248,"symbolLocation":0,"symbol":"current_machine"},{"value":4899360768,"symbolLocation":0,"symbol":"vixl::s30"},{"value":4890333184,"symbolLocation":80,"symbol":".compoundliteral.21"},{"value":0},{"value":4899360768,"symbolLocation":0,"symbol":"vixl::s30"}],"flavor":"ARM_THREAD_STATE64","lr":{"value":4852185116},"cpsr":{"value":2147487744},"fp":{"value":6174190144},"sp":{"value":6174190064},"esr":{"value":4060086273,"description":"(Breakpoint) brk 1"},"pc":{"value":4852185904,"matchesCrashFrame":1},"far":{"value":4852187136}},"frames":[{"imageOffset":6519600,"symbol":"process_op_defs","symbolLocation":924,"imageIndex":12},{"imageOffset":6518812,"symbol":"process_op_defs","symbolLocation":136,"imageIndex":12},{"imageOffset":6488884,"symbol":"tcg_context_init","symbolLocation":472,"imageIndex":12},{"imageOffset":6488384,"symbol":"tcg_init","symbolLocation":32,"imageIndex":12},{"imageOffset":3508164,"symbol":"tcg_init_machine","symbolLocation":116,"imageIndex":12},{"imageOffset":6425448,"symbol":"accel_init_machine","symbolLocation":92,"imageIndex":12},{"imageOffset":4016400,"symbol":"do_configure_accelerator","symbolLocation":204,"imageIndex":12},{"imageOffset":36535724,"symbol":"qemu_opts_foreach","symbolLocation":116,"imageIndex":12},{"imageOffset":4006296,"symbol":"qemu_init","symbolLocation":12068,"imageIndex":12},{"imageOffset":140980,"imageIndex":5},{"imageOffset":5836,"symbol":"_pthread_start","symbolLocation":148,"imageIndex":8},{"imageOffset":2980,"symbol":"thread_start","symbolLocation":8,"imageIndex":8}]},{"id":411269,"name":"pool-spawner","frames":[{"imageOffset":5116,"symbol":"__psynch_cvwait","symbolLocation":8,"imageIndex":0},{"imageOffset":32876,"symbol":"_pthread_cond_wait","symbolLocation":1232,"imageIndex":8},{"imageOffset":869100,"symbol":"g_cond_wait","symbolLocation":52,"imageIndex":10},{"imageOffset":56568,"symbol":"g_async_queue_pop_intern_unlocked","symbolLocation":128,"imageIndex":10},{"imageOffset":56848,"symbol":"g_async_queue_pop_unlocked","symbolLocation":92,"imageIndex":10},{"imageOffset":622248,"symbol":"g_thread_pool_spawn_thread","symbolLocation":128,"imageIndex":10},{"imageOffset":620088,"symbol":"g_thread_proxy","symbolLocation":176,"imageIndex":10},{"imageOffset":5836,"symbol":"_pthread_start","symbolLocation":148,"imageIndex":8},{"imageOffset":2980,"symbol":"thread_start","symbolLocation":8,"imageIndex":8}]},{"id":411270,"name":"gmain","frames":[{"imageOffset":16908,"symbol":"poll","symbolLocation":8,"imageIndex":0},{"imageOffset":462456,"symbol":"g_poll","symbolLocation":40,"imageIndex":10},{"imageOffset":382992,"symbol":"g_main_context_poll","symbolLocation":104,"imageIndex":10},{"imageOffset":372232,"symbol":"g_main_context_iterate","symbolLocation":420,"imageIndex":10},{"imageOffset":372416,"symbol":"g_main_context_iteration","symbolLocation":92,"imageIndex":10},{"imageOffset":380860,"symbol":"glib_worker_main","symbolLocation":36,"imageIndex":10},{"imageOffset":620088,"symbol":"g_thread_proxy","symbolLocation":176,"imageIndex":10},{"imageOffset":5836,"symbol":"_pthread_start","symbolLocation":148,"imageIndex":8},{"imageOffset":2980,"symbol":"thread_start","symbolLocation":8,"imageIndex":8}]},{"id":411271,"frames":[{"imageOffset":64648,"symbol":"__sigwait","symbolLocation":8,"imageIndex":0},{"imageOffset":42324,"symbol":"sigwait","symbolLocation":40,"imageIndex":8},{"imageOffset":36499372,"symbol":"sigwait_compat","symbolLocation":80,"imageIndex":12},{"imageOffset":36510232,"symbol":"qemu_thread_start","symbolLocation":128,"imageIndex":12},{"imageOffset":5836,"symbol":"_pthread_start","symbolLocation":148,"imageIndex":8},{"imageOffset":2980,"symbol":"thread_start","symbolLocation":8,"imageIndex":8}]},{"id":411273,"frames":[{"imageOffset":5116,"symbol":"__psynch_cvwait","symbolLocation":8,"imageIndex":0},{"imageOffset":32876,"symbol":"_pthread_cond_wait","symbolLocation":1232,"imageIndex":8},{"imageOffset":36509132,"symbol":"qemu_sem_timedwait","symbolLocation":204,"imageIndex":12},{"imageOffset":36619392,"symbol":"worker_thread","symbolLocation":324,"imageIndex":12},{"imageOffset":36510232,"symbol":"qemu_thread_start","symbolLocation":128,"imageIndex":12},{"imageOffset":5836,"symbol":"_pthread_start","symbolLocation":148,"imageIndex":8},{"imageOffset":2980,"symbol":"thread_start","symbolLocation":8,"imageIndex":8}]}],
  "usedImages" : [
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 8876236800,
    "size" : 225260,
    "uuid" : "f9830013-bade-3606-bbbb-23fcc37931b7",
    "path" : "\/usr\/lib\/system\/libsystem_kernel.dylib",
    "name" : "libsystem_kernel.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 7867072512,
    "size" : 4087808,
    "uuid" : "624a5ce2-ed62-367d-b415-cba2219953ce",
    "path" : "\/System\/Library\/Frameworks\/CoreFoundation.framework\/CoreFoundation",
    "name" : "CoreFoundation"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 8817278976,
    "size" : 36864,
    "uuid" : "9540de3d-cc9a-3ee0-8453-a58e12807f5d",
    "path" : "\/System\/Library\/PrivateFrameworks\/GraphicsServices.framework\/GraphicsServices",
    "name" : "GraphicsServices"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 7902466048,
    "size" : 24997888,
    "uuid" : "d3c486e4-2aa3-3dcb-b044-63a17764b7dd",
    "path" : "\/System\/Library\/PrivateFrameworks\/UIKitCore.framework\/UIKitCore",
    "name" : "UIKitCore"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 7927463936,
    "size" : 26427392,
    "uuid" : "30d0be87-1576-3bc4-8b0b-458f35577b40",
    "path" : "\/System\/Library\/Frameworks\/SwiftUI.framework\/SwiftUI",
    "name" : "SwiftUI"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4298407936,
    "size" : 5718016,
    "uuid" : "2c59f93d-8de3-379f-adae-2975a8f813ac",
    "path" : "\/private\/var\/containers\/Bundle\/Application\/80851BC7-E6D8-4090-B4DD-8C065B6E2469\/App.app\/UTM SE",
    "name" : "UTM SE"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 8376688640,
    "size" : 536596,
    "uuid" : "f8a1467c-11dd-3630-bb7c-b848a5ffe102",
    "path" : "\/usr\/lib\/dyld",
    "name" : "dyld"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 7771013120,
    "size" : 9740288,
    "uuid" : "e333ecaa-c33b-371d-8aef-5e29f2be8d0d",
    "path" : "\/System\/Library\/Frameworks\/Foundation.framework\/Foundation",
    "name" : "Foundation"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 9148080128,
    "size" : 49152,
    "uuid" : "0cb9ebb4-17eb-386b-b1e0-4cea7f3ca5af",
    "path" : "\/usr\/lib\/system\/libsystem_pthread.dylib",
    "name" : "libsystem_pthread.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 7990534144,
    "size" : 290816,
    "uuid" : "7209f7ce-3e45-3321-8b0b-41f0fcb53847",
    "path" : "\/usr\/lib\/system\/libdispatch.dylib",
    "name" : "libdispatch.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4324147200,
    "size" : 1654784,
    "uuid" : "9e8af8f0-8494-340b-82d0-43b0ab9d08a7",
    "path" : "\/private\/var\/containers\/Bundle\/Application\/80851BC7-E6D8-4090-B4DD-8C065B6E2469\/App.app\/Frameworks\/glib-2.0.0.framework\/glib-2.0.0",
    "name" : "glib-2.0.0"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 7990824960,
    "size" : 524280,
    "uuid" : "9ae6619b-b9eb-3578-9193-29b5bc8e1b5d",
    "path" : "\/usr\/lib\/system\/libsystem_c.dylib",
    "name" : "libsystem_c.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4845666304,
    "size" : 42385408,
    "uuid" : "51d82331-8f81-33eb-8c16-4e524dd1e444",
    "path" : "\/private\/var\/containers\/Bundle\/Application\/80851BC7-E6D8-4090-B4DD-8C065B6E2469\/App.app\/Frameworks\/qemu-aarch64-softmmu.framework\/qemu-aarch64-softmmu",
    "name" : "qemu-aarch64-softmmu"
  }
],
  "sharedCache" : {
  "base" : 7752728576,
  "size" : 2851569664,
  "uuid" : "8bfad288-f6b9-3ee5-94f3-bb52e46eb6b8"
},
  "vmSummary" : "ReadOnly portion of Libraries: Total=1.0G resident=0K(0%) swapped_out_or_unallocated=1.0G(100%)\nWritable regions: Total=651.7M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=651.7M(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nActivity Tracing                   256K        1 \nCG raster data                    1040K       22 \nColorSync                          448K       25 \nCoreAnimation                      944K       25 \nFoundation                          16K        1 \nImage IO                           256K        2 \nKernel Alloc Once                   32K        1 \nMALLOC                           613.3M      215 \nMALLOC guard page                  192K       12 \nSQLite page cache                  256K        2 \nSTACK GUARD                        240K       15 \nStack                             8624K       15 \nVM_ALLOCATE                       6400K       14 \n__AUTH                            3005K      417 \n__AUTH_CONST                      24.0M      599 \n__CTF                               756        1 \n__DATA                            23.7M      635 \n__DATA_CONST                      28.7M      606 \n__DATA_DIRTY                      3013K      493 \n__FONT_DATA                        2352        1 \n__LINKEDIT                       360.8M       45 \n__OBJC_CONST                      5367K      394 \n__OBJC_RO                         78.0M        1 \n__OBJC_RW                         2394K        1 \n__TEXT                           675.4M      658 \ndyld private memory                256K        1 \nlibnetwork                        21.9M      236 \nmapped file                      177.7M       28 \nshared memory                       48K        3 \n===========                     =======  ======= \nTOTAL                              2.0G     4469 \n",
  "legacyInfo" : {
  "threadTriggered" : {

  }
},
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "6081ed9716bb6d61d81d5014",
      "factorPackIds" : {
        "BIFROST_PROD_1" : "634d80a02dd5856aef2ca1b8"
      },
      "deploymentId" : 250001955
    },
    {
      "rolloutId" : "6112d17137f5d11121dcd4e2",
      "factorPackIds" : {
        "SIRI_UNDERSTANDING_ASR_HAMMER" : "632d08d401482c74ed7637a9"
      },
      "deploymentId" : 250000125
    }
  ],
  "experiments" : [
    {
      "treatmentId" : "c1eda467-5c09-4fd6-8d90-7034cc98438f",
      "experimentId" : "62cf21389a1c885618978432",
      "deploymentId" : 500000005
    }
  ]
}
}
```
</details> 

**Debug log**
Running:  -L /private/var/containers/Bundle/Application/80851BC7-E6D8-4090-B4DD-8C065B6E2469/App.app/qemu -S -spice unix=on,addr=/private/var/mobile/Containers/Data/Application/BD20032A-48EA-43F1-815B-883C7341F73A/tmp/2F2C4095-EC5B-49CD-A654-FE17D7EC7CAA.spice,disable-ticketing=on,image-compression=off,playback-compression=off,streaming-video=off,gl=off -chardev spiceport,id=org.qemu.monitor.qmp,name=org.qemu.monitor.qmp.0 -mon chardev=org.qemu.monitor.qmp,mode=control -nodefaults -vga none -device virtio-net-pci,mac=16:7C:DF:F1:FC:DE,netdev=net0 -netdev user,id=net0 -nographic -chardev spiceport,id=term0,name=com.utmapp.terminal.0 -serial chardev:term0 -cpu host -smp cpus=4,sockets=1,cores=4,threads=1 -machine virt -accel tcg,tb-size=512 -drive if=pflash,format=raw,unit=0,file=/private/var/containers/Bundle/Application/80851BC7-E6D8-4090-B4DD-8C065B6E2469/App.app/qemu/edk2-aarch64-code.fd,readonly=on -drive if=pflash,unit=1,file=/private/var/mobile/Containers/Data/Application/BD20032A-48EA-43F1-815B-883C7341F73A/Documents/ArchLinux.utm/Data/efi_vars.fd -m 2048 -device intel-hda -device hda-duplex -device nec-usb-xhci,id=usb-bus -device usb-tablet,bus=usb-bus.0 -device usb-mouse,bus=usb-bus.0 -device usb-kbd,bus=usb-bus.0 -device usb-storage,drive=drive03019F2F-A7F2-4B33-B2CF-1F6A72E60438,removable=true,bootindex=0,bus=usb-bus.0 -drive if=none,media=cdrom,id=drive03019F2F-A7F2-4B33-B2CF-1F6A72E60438 -device virtio-blk-pci,drive=driveBB208CBD-BFB4-4895-9542-48527C9E5473,bootindex=1 -drive if=none,media=disk,id=driveBB208CBD-BFB4-4895-9542-48527C9E5473,file=/private/var/mobile/Containers/Data/Application/BD20032A-48EA-43F1-815B-883C7341F73A/Documents/ArchLinux.utm/Data/BB208CBD-BFB4-4895-9542-48527C9E5473.qcow2,discard=unmap,detect-zeroes=unmap -device virtio-serial -device virtserialport,chardev=vdagent,name=com.redhat.spice.0 -chardev spicevmc,id=vdagent,debug=0,name=vdagent -name ArchLinux -uuid 2F2C4095-EC5B-49CD-A654-FE17D7EC7CAA -device virtio-rng-pci
Loading qemu-aarch64-softmmu.framework/qemu-aarch64-softmmu
2022-10-19 21:05:41.672 UTM SE[1009:418860] Running:  -L /private/var/containers/Bundle/Application/80851BC7-E6D8-4090-B4DD-8C065B6E2469/App.app/qemu -S -spice unix=on,addr=/private/var/mobile/Containers/Data/Application/BD20032A-48EA-43F1-815B-883C7341F73A/tmp/2F2C4095-EC5B-49CD-A654-FE17D7EC7CAA.spice,disable-ticketing=on,image-compression=off,playback-compression=off,streaming-video=off,gl=off -chardev spiceport,id=org.qemu.monitor.qmp,name=org.qemu.monitor.qmp.0 -mon chardev=org.qemu.monitor.qmp,mode=control -nodefaults -vga none -device virtio-net-pci,mac=16:7C:DF:F1:FC:DE,netdev=net0 -netdev user,id=net0 -nographic -chardev spiceport,id=term0,name=com.utmapp.terminal.0 -serial chardev:term0 -cpu host -smp cpus=4,sockets=1,cores=4,threads=1 -machine virt -accel tcg,tb-size=512 -drive if=pflash,format=raw,unit=0,file=/private/var/containers/Bundle/Application/80851BC7-E6D8-4090-B4DD-8C065B6E2469/App.app/qemu/edk2-aarch64-code.fd,readonly=on -drive if=pflash,unit=1,file=/private/var/mobile/Containers/Data/Application/BD20032A-48EA-43F1-815B-883C7341F73A/Documents/ArchLinux.utm/Data/efi_vars.fd -m 2048 -device intel-hda -device hda-duplex -device nec-usb-xhci,id=usb-bus -device usb-tablet,bus=usb-bus.0 -device usb-mouse,bus=usb-bus.0 -device usb-kbd,bus=usb-bus.0 -device usb-storage,drive=drive03019F2F-A7F2-4B33-B2CF-1F6A72E60438,removable=true,bootindex=0,bus=usb-bus.0 -drive if=none,media=cdrom,id=drive03019F2F-A7F2-4B33-B2CF-1F6A72E60438 -device virtio-blk-pci,drive=driveBB208CBD-BFB4-4895-9542-48527C9E5473,bootindex=1 -drive if=none,media=disk,id=driveBB208CBD-BFB4-4895-9542-48527C9E5473,file=/private/var/mobile/Containers/Data/Application/BD20032A-48EA-43F1-815B-883C7341F73A/Documents/ArchLinux.utm/Data/BB208CBD-BFB4-4895-9542-48527C9E5473.qcow2,discard=unmap,detect-zeroes=unmap -device virtio-serial -device virtserialport,chardev=vdagent,name=com.redhat.spice.0 -chardev spicevmc,id=vdagent,debug=0,name=vdagent -name ArchLinux -uuid 2F2C4095-EC5B-49CD-A654-FE17D7EC7CAA -device virtio-rng-pci
2022-10-19 21:05:41.672 UTM SE[1009:418860] Loading qemu-aarch64-softmmu.framework/qemu-aarch64-softmmu

**Upload VM**
Last try: https://mac.getutm.app/gallery/archlinux-arm

**Comment by osy** [comment] 2022-10-20 23:59
Duplicate of #4516

**Closed by osy** 2022-10-20 23:59 UTC
Labels: crash, qemu, iOS
