### ISSUE TITLE
Unable to login in apple account on macOS12 VM

### ISSUE THREAD

**Issue by invokermoon** [utmapp/UTM#3935] opened 2022-04-23 07:55 UTC
I just used UTM to build a new macos12 on my M1max macbook14.
Everything seems to be okay, but i can't login my apple account in setting.
And i can login my apple id in the safari in the virtual macos12.
Does anyone have this problem？

**Comment by osy** [comment] 2022-04-23 09:02
Duplicate of #3617

**Closed by osy** 2022-04-23 09:02 UTC
Labels: duplicate

**Comment by invokermoon** [comment] 2022-04-23 11:09
@osy 
I saw your Duplicate.
So there is no way to workaround this feature?

**Comment by invokermoon** [comment] 2022-04-23 11:09
> Duplicate of #3617
Dear osy,
I saw your Duplicate.
So there is no way to workaround this feature?

**Comment by mattruzzi** [comment] 2023-07-06 21:05
https://kb.parallels.com/128867
https://forum.parallels.com/threads/apple-id-login-in-macos-guest-os.355059/
https://developer.apple.com/forums/thread/707682
