### ISSUE TITLE
Add MacOS Guest VM Support for IOS UTM App for UTM HPV version

### ISSUE THREAD

**Issue by kind-grape** [utmapp/UTM#6083] opened 2024-02-09 19:52 UTC
For IOS users with UTM app (hypervisor version), would love to see added capability for installing macos guest VM similar to UTM MacOS app.

This would unlock the m1/m2 ipads with supported IOS version into something else entirely. 

Not sure if MacOS guest VM requires features from host that are present on MacOS but not present on IOS though

**Comment by osy** [comment] 2024-02-09 20:28
Duplicate of #5776

**Closed by osy** 2024-02-09 20:28 UTC
Labels: enhancement
