### ISSUE TITLE
Error when trying to virtualize Windows 11 for ARM on MacOS

### ISSUE THREAD

**Issue by fm360** [utmapp/UTM#6829] opened 2024-11-22 19:22 UTC
**Describe the issue**  
QEMU error: QEMU exited from an error: qemu-aarch64-softmmu: Property 'host-arm-cpu.sme' not found

**Configuration**  
* UTM Version: 4.6.0
* macOS Version: 15.2 beta 2
* Mac Chip (Intel, M1, ...): M4 Max

**Crash log**  
[QEMULauncher-2024-11-22-111333.ips.txt](https://github.com/user-attachments/files/17875235/QEMULauncher-2024-11-22-111333.ips.txt)

**Debug log**  
[debug.log](https://github.com/user-attachments/files/17875257/debug.log)

**Upload VM**  
[config.plist.txt](https://github.com/user-attachments/files/17875266/config.plist.txt)

Virtualization was working fine before but it seemed to just stop working all of a sudden without me having to do anything

**Comment by osy** [comment] 2024-11-22 19:43
Duplicate of #6790

**Closed by osy** 2024-11-22 19:43 UTC
