### ISSUE TITLE
Guest OS is not capable to switch output audio device while running

### ISSUE THREAD

**Issue by fiore42** [utmapp/UTM#4744] opened 2022-12-01 08:44 UTC
Hello and thank you for UTM! It's amazing! :) 

**Describe the issue**  
The audio of the guest always outputs from the host audio device which is default at boot. I tried to start the guest both with laptop speakers and AirPods as system default. In both cases switching output device only affects host apps, but the guest sticks to the device it is already sending output to. I'm playing audio from Chromium in the guest and Chrome in the host.

I tried all available audio devices (see img below) and the behaviour is always the same (except usb-audio which throws an error and doesn't boot).

I would be happy even with a manual override, but I couldn't find any solution except rebooting the guest.

As a side note, I also can't find a way to get the guest to remember my last audio volume. It always only starts muted.

**Configuration**  
* UTM Version: 4.0.9
* macOS Version: 13.0.1
* Mac Chip (Intel, M1, ...): MacBook Air M2
* Host: Ubuntu 22.04 for ARM (built from daily live desktop iso)

<img width="320" alt="image" src="https://user-images.githubusercontent.com/7117346/205006342-f5c79a37-6efd-41ea-89cb-6053d94495d6.png">

**Comment by osy** [comment] 2022-12-01 22:31
Duplicate of #3488

**Closed by osy** 2022-12-01 22:31 UTC
