### ISSUE TITLE
Microphone access not working

### ISSUE THREAD

**Issue by conath** [utmapp/UTM#3299] opened 2021-11-08 21:49 UTC
VMs can't access my Mac's microphone even though the device "Intel HD Audio Controller" is selected and the `-device hda-duplex` is present in the Debug Log. Tested with two `q35` guests and one `virt` guest.

* UTM Version: 2.4.1
* OS Version: macOS 12.1 beta
* Apple Silicon

**Debug log**
<details>
  <summary>Debug Log running Windows 11 ARM guest</summary>

```log
Running:  -L /Applications/UTM/UTM.app/Contents/Resources/qemu -S -qmp tcp:127.0.0.1:4000,server,nowait -nodefaults -vga none -spice "unix=on,addr=/Users/chris/Library/Group Containers/WDNLXAD4W8.com.utmapp.UTM/305C84D7-49E8-4CDB-8CA4-AE5DBFECB0CA.spice,disable-ticketing=on,image-compression=off,playback-compression=off,streaming-video=off,gl=off" -device virtio-gpu-pci -cpu host -smp cpus=4,sockets=1,cores=4,threads=1 -machine virt,highmem=off,virtualization=on -accel hvf -accel tcg,thread=multi,tb-size=1024 -drive if=pflash,format=raw,unit=0,file=/Applications/UTM/UTM.app/Contents/Resources/qemu/edk2-aarch64-code.fd,readonly=on -drive "if=pflash,format=raw,unit=1,file=/Users/chris/Library/Containers/com.utmapp.UTM/Data/Documents/Windows 11 for ARM.utm/Images/efi_vars.fd" -boot menu=on -m 4096 -device ich9-intel-hda -device hda-duplex -name "Windows 11 for ARM" -device qemu-xhci,id=usb-bus -device usb-tablet,bus=usb-bus.0 -device usb-mouse,bus=usb-bus.0 -device usb-kbd,bus=usb-bus.0 -device qemu-xhci,id=usb-controller-0 -chardev spicevmc,name=usbredir,id=usbredirchardev0 -device usb-redir,chardev=usbredirchardev0,id=usbredirdev0,bus=usb-controller-0.0 -device usb-storage,drive=drive0,removable=true,bootindex=0,bus=usb-bus.0 -drive if=none,media=cdrom,id=drive0 -device virtio-blk-pci,drive=B14E51A9-C646-41F9-A26B-1D73232DDC66,bootindex=1 -drive "if=none,media=disk,id=B14E51A9-C646-41F9-A26B-1D73232DDC66,file=/Users/chris/Library/Containers/com.utmapp.UTM/Data/Documents/Windows 11 for ARM.utm/Images/driveC128GB.qcow2,cache=writethrough" -device virtio-net-pci,mac=8E:43:36:8C:30:B5,netdev=net0 -netdev vmnet-macos,mode=bridged,id=net0 -device virtio-serial -device virtserialport,chardev=vdagent,name=com.redhat.spice.0 -chardev spicevmc,id=vdagent,debug=0,name=vdagent -uuid 305C84D7-49E8-4CDB-8CA4-AE5DBFECB0CA -rtc base=localtime
qemu-aarch64-softmmu: -netdev vmnet-macos,mode=bridged,id=net0: info: Started vmnet interface with configuration:
qemu-aarch64-softmmu: -netdev vmnet-macos,mode=bridged,id=net0: info: MTU:              1500
qemu-aarch64-softmmu: -netdev vmnet-macos,mode=bridged,id=net0: info: Max packet size:  1514
qemu-aarch64-softmmu: -netdev vmnet-macos,mode=bridged,id=net0: info: MAC:              36:c5:9f:c9:58:59
qemu-aarch64-softmmu: -netdev vmnet-macos,mode=bridged,id=net0: info: UUID:             45436D6D-E029-460B-9263-26DA3F2FB18D
qemu-aarch64-softmmu: warning: Spice: playback:0 (0x1388c5920): setsockopt failed, Operation not supported on socket
qemu-aarch64-softmmu: warning: Spice: record:0 (0x1388c59d0): setsockopt failed, Operation not supported on socket
```

</details> 

VM config: [config.plist.zip](https://github.com/utmapp/UTM/files/7500346/config.plist.zip)

**Comment by conath** [comment] 2021-11-08 21:51
Also tested with AC97 device, same result: guest sees a microphone but recordings contain silence, and the macOS microphone access prompt does not appear (even though UTM does not have microphone permission according to System Preferences).

**Comment by spacecadet123** [comment] 2021-12-07 12:28
Hi, I have come across the same issue, is there any way to override it? 
UTM hasn't requested mic access in the host system
The thing is my only reason to deal with virtualization is one voice recognition application for windows...
Big Sur M1 Air 2020 host
Win 11 guest

**Comment by SamHep0803** [comment] 2021-12-24 00:03
It would be gladly appreciated if someone could look into this issue, there seems to be some sort of microphone being detected in my W11 VM (shows up as "Line In") however UTM hasn't actually requested microphone usage or anything like that. Thanks in advance!

**Comment by conath** [comment] 2021-12-25 11:31
I did a brief check: is the only missing code to make Microphone access work on Mac the permissions prompt? To test this, I added these lines to UTMData.swift `save(vm: UTMVirtualMachine)`:

```swift
    func save(vm: UTMVirtualMachine) throws {
        do {
            #if os(macOS)
            if vm.configuration.soundCard?.contains("hda") ?? false {
                /// get mic permisison
                AVCaptureDevice.requestAccess(for: .audio) { access in
                    print(access)
                }
            }
            #endif
```

To run this successfully, in the Info.plist for the Mac target you need to enable "Audio Input" in the "Hardened Runtime" and add a "NSMicrophoneUsageDescription" key with a string value. Then the next time a HDA-soundcard VM is saved, the microphone popup appears, and clicking Allow results in `true` printed. So far, so good.

However there is still no sound recorded in the running VM, I assume that no AVCaptureSession is started. So this is a topic that needs further research and development.

**Comment by conath** [comment] 2021-12-25 11:43
See PR #3408

**Comment by vlad-a-c** [comment] 2022-01-09 23:38
i'm running utm 3.0.1 and i'm still not getting even the prompt to allow access. that's so weird though.

**Comment by conath** [comment] 2022-01-10 20:19
@vlad-a-c My current understanding is that mic access is not a feature of the macOS app yet, and is not working as intended on iOS.

**Comment by marrem** [comment] 2022-05-17 20:00
I experience the same issue. I have also tried with 'bare' qemu but I could get sound out off the vm but not into it. I would like to be able to choose in the vm the inputs that I see on my Mac. I have installed Rogue Amoeba's Loopback. I see the virtual input in my Mac's audio inputs. 

<img width="648" alt="image" src="https://user-images.githubusercontent.com/2941173/168899279-926cc070-8ce9-4c96-ba0c-1c55977dc456.png">

Would be nice if I could see the same selection of inputs in my linux (ubuntu 22.04) guest.
I have SDR software running on host. I would like to send audio to vm audio input so I can use tools like qsstv in linux to receive sstv broadcasts.

**Comment by osy** [comment] 2022-08-01 23:29
Duplicate of #219

**Closed by osy** 2022-08-01 23:29 UTC
Labels: bug, duplicate, spice, macOS

**Comment by GlobeShocked** [comment] 2023-06-08 20:24
> 
Thank you for providing the detailed instructions. I have been facing a similar issue, but I'm having some trouble understanding some aspects of your instructions. Could you provide some clarity on the following points?

1. Where can I locate the `UTMData.swift` file? I'm assuming it is part of the project directory, but I would appreciate if you could give more specific guidance on its location.

2. You mentioned enabling "Audio Input" in the "Hardened Runtime". Where can I find this "Hardened Runtime"? Is it within a specific application, or is it a part of system settings or line of code?

3. I'm not quite clear on how to add a key with a string value. Specifically, you mentioned the "NSMicrophoneUsageDescription" key. How can I go about adding this?

I'm relatively new to this, and any additional explanation or clarification you could provide would be very helpful.

**Comment by allucat1000** [comment] 2024-10-18 19:36
The issue still seems to not have been solved as on my W11 VM I am unable to use the microphone. Certain applications such as Duolingo can detect that I don't have a microphone, which means the issue isn't just with it not showing the popup menu for microphone and video permissions,
