### ISSUE TITLE
Ipad 2020 - black screen - Altstore

### ISSUE THREAD

**Issue by FuocomanSap** [utmapp/UTM#1414] opened 2020-12-20 20:17 UTC
**Describe the bug**
The last 2 realeases get stuck in black screen when starting a VM.( v2.0.14 and v2.0.15)
(v2.0.13 works fine)

**To Reproduce**

- Requirements:
1) iPad 2020
2) IOS: 14.3
3) random VM on the site

- Steps to reproduce the behavior:
1) install UTM with ALTSTORE
2) start a VM

**Crash log**
nd.

**Debug log**
in the next comment

**Upload VM**
nd.

**Comment by FuocomanSap** [comment] 2020-12-20 20:37
[debug_utm.log](https://github.com/utmapp/UTM/files/5721469/debug_utm.log)
at 21.35 i pressed the quit button

**Comment by osy** [comment] 2020-12-22 09:33
Duplicate of #2080

**Closed by osy** 2020-12-22 09:33 UTC
Labels: duplicate
