### ISSUE TITLE
Storing UTM bundles on external drives

### ISSUE THREAD

**Issue by ldmbouge** [utmapp/UTM#3656] opened 2022-02-21 13:18 UTC
I have too many of those. I can't keep this data on the main disk off my MBP. TB3/TB4 is fast enough to store externally and have no performance impact. This would *really* be nice to have.

Thanks!

**Comment by osy** [comment] 2022-02-22 02:52
Duplicate of #132

**Comment by osy** [comment] 2022-02-22 02:52
You can test it out in UTM v3.1.x beta.

**Closed by osy** 2022-02-22 02:52 UTC
Labels: duplicate
