### ISSUE TITLE
Windows shuts down then UTM crashes

### ISSUE THREAD

**Issue by DJZSwag** [utmapp/UTM#4037] opened 2022-05-18 16:02 UTC
**Describe the issue**
Was just normally shutting down Windows, then UTM crashed (Not QEMU or anything)
**Configuration**
* UTM Version: 3.2.5
* OS Version: 12.4 (21F79)
* Intel or Apple Silicon? Apple M1

**Crash log**
[crash.zip](https://github.com/utmapp/UTM/files/8718001/crash.zip)

**Debug log**
[debug.log](https://github.com/utmapp/UTM/files/8718010/debug.log)

**Comment by kyunghoon-KIM** [comment] 2022-05-19 02:25
Same issue
A crash occurred in the previously used virtual environment, so I installed a new one, and both crashed. doesn't boot
[debug_05_19.log](https://github.com/utmapp/UTM/files/8722970/debug_05_19.log)

**Comment by osy** [comment] 2022-05-20 22:07
Duplicate of #4009

**Closed by osy** 2022-05-20 22:07 UTC
