### ISSUE TITLE
UTM instantly crashes trying to launch the official UTM-provided Arch ARM VM

### ISSUE THREAD

**Issue by themaster567** [utmapp/UTM#5329] opened 2023-05-24 00:00 UTC
**Describe the issue**  
I downloaded the latest version of UTM, downloaded the latest version of the premade UTM file for Arch ARM, imported it, and then it crashes as soon I try to start the VM.

**Configuration**  
* UTM Version: 4.2.5
* macOS Version: macOS 13.2
* Mac Chip (Intel, M1, ...): M2

**Crash log**  
https://pastebin.com/VVZza4Tq

**Debug log**  
Followed the steps for getting a debug log but none is created, likely to how fast it crashes.

**Upload VM**  
It's the official UTM file for Arch ARM. No changes.

**Comment by osy** [comment] 2023-05-27 23:18
Duplicate of #4582

**Closed by osy** 2023-05-27 23:19 UTC

**Comment by osy** [comment] 2023-05-27 23:20
@themaster567 This is a known issue but I cannot reproduce it on my machine. Can you provide more details on your macOS configuration? For example, what is your system language? Do you have voiceover enabled? Do you have any third party extensions that may modify mouse/keyboard input?

**Comment by osy** [comment] 2023-05-27 23:20
Other useful information: are you running UTM from /Applications or elsewhere? Have you used an older version of UTM before?

**Comment by themaster567** [comment] 2023-06-03 17:34
Just saw this, apologies for the wait.

> @themaster567 This is a known issue but I cannot reproduce it on my machine. Can you provide more details on your macOS configuration? For example, what is your system language? Do you have voiceover enabled? Do you have any third party extensions that may modify mouse/keyboard input?

My system language is English. I do not have voiceover enabled. I do not use extensions that modify input.



> Other useful information: are you running UTM from /Applications or elsewhere? Have you used an older version of UTM before?

I am running it from the standard place, /Applications. The M2 MBA is my first MacOS device, so I have not used an older version before.
