### ISSUE TITLE
Ability to open main window while running VMs

### ISSUE THREAD

**Issue by JaiganeshKumaran** [utmapp/UTM#4959] opened 2023-01-21 13:53 UTC
I sometimes close the main UTM window after opening a VM and currently, there's no way to open it without closing all VMs and opening the application again. 

Please consider providing an option to switch back to the main window in the menu bar or automatically display it on reactivation (app icon clicked on the dock or launchpad).

**Comment by osy** [comment] 2023-01-21 15:21
Duplicate of #3632

**Closed by osy** 2023-01-21 15:21 UTC
Labels: enhancement
