### ISSUE TITLE
It's not working properly.

### ISSUE THREAD

**Issue by xodus0818** [utmapp/UTM#143] opened 2020-03-15 13:53 UTC
![DEF04432-AF08-47BC-88B0-3D82C73A9162](https://user-images.githubusercontent.com/62111097/76702711-55cead80-670f-11ea-8ffd-750a2317e472.png)

ios 13.3.1 In use and installed through appcake The model is the third generation of iPad air. Is there a problem with my internet environment?

**Comment by Andy245** [comment] 2020-03-15 14:49
我的闪退

**Comment by Andy245** [comment] 2020-03-15 14:50
设置好win7点击运行就闪退，13.3.1通过appcake安装

**Comment by osy86** [comment] 2020-03-15 15:11
Duplicate of #130

**Closed by osy86** 2020-03-15 15:11 UTC
Labels: duplicate
