### ISSUE TITLE
Start Virtual Machine fail, and crash

### ISSUE THREAD

**Issue by barryblueice** [utmapp/UTM#148] opened 2020-03-16 12:05 UTC
I installed the latest version yesterday evening. I found that if I only create one virtual machine, it can start normally. But if you shutdown the first virtual machine, and create another virtual machine, and you want to launch it, the app will crash.

For example, I create the virtual machine A, the VM-A can launch normally, but if you shutdown VM-A, and create the virtual machine B (or directly create virtual machine B), the app will crash. You need to shutdown the app or restart your iPad.But when you open it and start the virtual machine again, it will crash.
Is it the problem of my device, or the problem of app?
P.S:My iPad system is iPadOS 1.13.4. The fifth generation of iPad.

**Comment by barryblueice** [comment] 2020-03-16 12:09
> I installed the latest version yesterday evening. I found that if I only create one virtual machine, it can start normally. But if you shutdown the first virtual machine, and create another virtual machine, and you want to launch it, the app will crash.
> 
> For example, I create the virtual machine A, the VM-A can launch normally, but if you shutdown VM-A, and create the virtual machine B (or directly create virtual machine B), the app will crash. You need to shutdown the app or restart your iPad.But when you open it and start the virtual machine again, it will crash.
> Is it the problem of my device, or the problem of app?
> P.S:My iPad system is iPadOS 1.13.4. The fifth generation of iPad.

If the app version is 0.3 or 0.2, it won’t have this problem; but if the app version is 0.4 or 0.5, it will have this problem.

**Comment by osy86** [comment] 2020-03-16 17:57
Just to be clear, you exited UTM using the X button on the left and restarted the app before attempting to launch the second VM?

**Comment by barryblueice** [comment] 2020-03-16 23:07
> Just to be clear, you exited UTM using the X button on the left and restarted the app before attempting to launch the second VM?

Yes. If you want, I can give the video record to you.

**Comment by ljzxzxl** [comment] 2020-03-17 06:21
This problem has always existed and has never been fixed

**Comment by osy86** [comment] 2020-03-17 08:30
Yup
Duplicate of #95 which is stickied

**Comment by osy86** [comment] 2020-03-17 08:31
To be clear this is a big issue that many people have. I just can’t reproduce it myself so I can’t fix it. If anyone has an idea of why it happens let me know.

**Comment by barryblueice** [comment] 2020-03-17 08:41
> To be clear this is a big issue that many people have. I just can’t reproduce it myself so I can’t fix it. If anyone has an idea of why it happens let me know.

But in the version 0.2 and 0.3, the app won’t have this problem.

**Comment by osy86** [comment] 2020-03-17 08:42
Ugh okay so it seems like there’s different people with different issues commenting on here.

**Comment by barryblueice** [comment] 2020-03-17 08:47
> Ugh okay so it seems like there’s different people with different issues commenting on here.

OK, I will test the latest release of app later.

**Comment by barryblueice** [comment] 2020-03-17 08:52
It may be that when you shut down the virtual machine, some of the processes are still running. When you run another virtual machine, the previous processes are still running, resulting in insufficient memory, and finally the app goes down.

**Comment by barryblueice** [comment] 2020-03-17 09:05
Or when the virtual machine was started, the iPad couldn't process too much data at the same time, causing the app to crash.

**Comment by osy86** [comment] 2020-03-23 21:10
@barryblueice please confirm you are not using AppCake to sign UTM

**Comment by barryblueice** [comment] 2020-03-23 23:06
> @barryblueice please confirm you are not using AppCake to sign UTM

Yes, I’m sure I didn’t use AppCake to sign UTM, I use AltStore.

**Comment by osy86** [comment] 2020-03-24 00:43
Okay that should be fine.

**Comment by adi6409** [comment] 2020-03-25 10:10
I uses AppCake to sign it, and it crashes when I try to start the vm. Is it a problem that I used appcake?

**Comment by barryblueice** [comment] 2020-03-25 10:25
> I uses AppCake to sign it, and it crashes when I try to start the vm. Is it a problem that I used appcake?

Yes. I suggested you don’t use AppCake. You can use AltStore.

**Comment by adi6409** [comment] 2020-03-25 10:26
> > I uses AppCake to sign it, and it crashes when I try to start the vm. Is it a problem that I used appcake?
> 
> Yes. I suggested you don’t use AppCake. You can use AltStore.

Do I need to pay for it?

**Comment by barryblueice** [comment] 2020-03-25 10:40
> > > I uses AppCake to sign it, and it crashes when I try to start the vm. Is it a problem that I used appcake?
> > 
> > 
> > Yes. I suggested you don’t use AppCake. You can use AltStore.
> 
> Do I need to pay for it?

No, AltStore is free.
If you want to use AltStore to install UTM, it will be a little difficult. I can tell you how can use it.

**Comment by Andy245** [comment] 2020-03-25 14:26
> > > > 我使用AppCake对其进行签名，并且在尝试启动vm时崩溃。我使用appcake是否有问题？
> > > 
> > > 
> > > 是。我建议您不要使用AppCake。您可以使用AltStore。
> > 
> > 
> > 我需要为此付费吗？
> 
> 不，AltStore是免费的。
> 如果要使用AltStore安装UTM，将有些困难。我可以告诉你如何使用它。

麻烦问一下怎么使用AltStore安装UTM

**Comment by barryblueice** [comment] 2020-03-25 14:51
> > > > > 我使用AppCake对其进行签名，并且在尝试启动vm时崩溃。我使用appcake是否有问题？
> > > > 
> > > > 
> > > > 是。我建议您不要使用AppCake。您可以使用AltStore。
> > > 
> > > 
> > > 我需要为此付费吗？
> > 
> > 
> > 不，AltStore是免费的。
> > 如果要使用AltStore安装UTM，将有些困难。我可以告诉你如何使用它。
> 
> 麻烦问一下怎么使用AltStore安装UTM

抱歉回复的晚了，刚才在写作业。
下面是用altstore安装utm的方法（来自js-john，适用于Windows系统）：
需要用到的软件：http file server（以下简称hfs），altstorepatcher，altstore，用数据线连接到电脑的ios设备。
具体步骤：
1.安装altstore；
2.打开hfs，将utm安装包拖入文件列表；
3.在浏览器中输入“localhost”，复制里面utm.ipa文件的下载地址；
4.打开altstorepatcher，定位altstore的安装位置（比如我安装在C：/AltStore，那么我要定位到C：/Altstore/Altstore.exe）；
5.在里面的下拉栏里选择“IPA Link”，选择后在下面的文本框里粘贴刚才复制的UTM.ipa下载地址。复制完后点击“patch！”；
6.弹出对话框之后在系统托盘中找到altstore图标，左键图标，选中“install alt store”，在右边栏里选择你的设备；
7.安装过程中可能会提示你“依赖altstore的应用将会停止运行”不用管他，直接yes；
8.出现“installation succeed”就OK了。
提示：在使用altstore安装utm时会有一定的几率安装失败，目前没办法解决这个问题，只能换一个安装包。

**Comment by osy86** [comment] 2020-03-25 15:47
Duplicate of #95

**Closed by osy86** 2020-03-25 15:47 UTC
Labels: crash
