### ISSUE TITLE
Shared folder setting forgotten

### ISSUE THREAD

**Issue by Vartkat** [utmapp/UTM#5562] opened 2023-08-14 22:39 UTC
UTM forgets shared folder if ever this folder is on a removable disk and this disk is not mounted.

**Configuration**  
* UTM Version: 4.2.5(81)
* macOS Version: 12.6.2
* Mac Chip (Intel, M1, ...): M1

**Crash log**  
no crash

**Debug log**  
No log needed. On a Debian11 VM, just try to share a removable disk folder. It works if you use instructions from https://github.com/utmapp/UTM/discussions/3755, but if ever the the VM is launched while the removable disk is not mounted on the Mac side, the shared folder setting is gone.

**Upload VM**  
nope

I expect not to loose this setting without any notice, I'd prefer a error message telling me what's happening. 

The problem is worse if ever any process in the VM is supposed to access this shared folder, i.e. some process create the missing folder (empty) and beleives data is missing or even save data in it. Once theses folder are created and filled user must do some gymnastics of moving file and renaming then merging to get back all data in one place.

**Comment by osy** [comment] 2023-08-19 19:09
Can you try v4.3.5?

**Comment by runwaygoats** [comment] 2023-08-21 00:33
Is this the same or similar to #5569 ?

**Comment by osy** [comment] 2023-08-21 00:34
It may be, in which case it is not fixed in v4.3.5 but in the next beta. Another similar issue was fixed in v4.3.x but for QEMU VMs.

**Comment by osy** [comment] 2023-09-02 04:24
Duplicate of #5569

**Closed by osy** 2023-09-02 04:24 UTC
