### ISSUE TITLE
Audio not working Windows 10 for ARM

### ISSUE THREAD

**Issue by tkreind** [utmapp/UTM#2470] opened 2021-04-26 21:25 UTC
**Describe the issue**
No audio device appears within Windows when using a fresh image. If there's some fix to this I'm not aware of it should be added to the gallery instructions for Windows 10.

**Configuration**
* UTM Version: 2.0.25 
* OS Version: Big Sur 11.2.3
* Apple Silicon

**Upload VM**
Fresh install of Windows 10 for ARM (21354) after following all but the display enhancing directions. Converted VHDX to qcow2 from a fresh image before install and ran the virtual machine solely on the qcow2 image.

Attatched as txt since plist isn't allowed.
[config.txt](https://github.com/utmapp/UTM/files/6380198/config.txt)

**Comment by osy** [comment] 2021-04-26 21:27
Duplicate of #2448

**Comment by osy** [comment] 2021-04-26 21:27
This was fixed in v2.0.26/27 which is out for download should be in the App Store soon.

**Closed** 2021-04-26 21:27 UTC
Labels: duplicate
