### ISSUE TITLE
Double execution of command when cloning or deleting vm

### ISSUE THREAD

**Issue by tiiiecherle** [utmapp/UTM#3352] opened 2021-11-28 11:51 UTC
**Describe the issue**
When I clone or delete a vm the command gets executed twice and the second one always fails. I do a right click on a vm, click clone and a popup asks if I want to really do that. If I say yes a second popup asks me if I want to really do that and if I click yes it fails. Same when deleting a vm.

Command should only try to clone or delete once.

**Configuration**
UTM Version 2.4.1
macOS Version 11.6.1
Intel MacBook Pro 2019, 32 GB RAM, 1 TB SSD

Thanks for looking into this in advance.

**Comment by conath** [comment] 2021-11-28 15:55
This is a macOS 11 bug and has been fixed by Apple in macOS 12. Please update to macOS 12, or just click "Cancel" on the second popup. 

Duplicate of #2337

**Closed by conath** 2021-11-28 15:55 UTC
