### ISSUE TITLE
Add the ability to boot into macOS recovery mode.

### ISSUE THREAD

**Issue by jawshoeadan** [utmapp/UTM#4164] opened 2022-06-26 03:15 UTC
As seen in [VirtualBuddy](https://github.com/insidegui/VirtualBuddy) it is possible to do this now with the private headers, so my proposal is to add this to UTM as well.

**Comment by ideologysec** [comment] 2022-06-27 23:06
It's explicitly supported in macOS 13 as well.

https://developer.apple.com/documentation/virtualization/vzmacosvirtualmachinestartoptions

**Comment by conath** [comment] 2022-07-04 06:38
Duplicate of #3526

**Closed** 2022-07-30 00:42 UTC
Labels: enhancement
