### ISSUE TITLE
Virtual machine crashes at start

### ISSUE THREAD

**Issue by TheGoal10** [utmapp/UTM#419] opened 2020-07-19 22:53 UTC
Excuse me by advance for my bad english, I’m french.

So I took the .ipa here, on the Github. Then I installed it on AltStore. 

So I did like they did on tutorials of Youtube to have Windows 7. It crashed. So I tried to remove some memory, still crashed.

I make that on an iPhone 8 so I thought maybe my phone is not ready for Windows 7. So I tried again with Windows XP. But still crash. I don’t understand.

Thanks by advance.

**Comment by XxAndreSPLxX** [comment] 2020-07-22 00:48
I have the exact same thing, even with a blank VM. It seems to be something to do with iOS/iPadOS 14.

**Comment by osy86** [comment] 2020-07-22 00:58
Duplicate of #397

**Closed by osy86** 2020-07-22 00:58 UTC
Labels: duplicate
