### ISSUE TITLE
Graphical problem with Hexchat app in Ubuntu VM

### ISSUE THREAD

**Issue by stendro** [utmapp/UTM#4979] opened 2023-01-29 20:23 UTC
**Describe the issue**  
While using Ubuntu Server 22.04 (ARM64) the app "hexchat" doesn't work. When the app is launched it displays the window, and it's all black. Other than that it seems to work normally. I can click in the corner, if I guess where the button is, to close it.

Sometimes it crashes with: "hexchat: Fatal IO error 11 (Resource temporarily unavailable) on X server :0."

I've also gotten it to work in a few instances, although after some use it eventually starts to flicker with black areas, and or crashes with the above error.

I've been in contact with the hexchat support channel. They've concluded it's most likely related to the display stack/virgl.

**Configuration**  
* UTM Version: 4.1.5
* macOS Version: 13.1
* Mac Chip (Intel, M1, ...): M1

**Crash log**  

**Debug log**  
[Pastebin](https://pastebin.com/7A5Tnyir)

**Upload VM**  
[config.zip](https://github.com/utmapp/UTM/files/10530745/config.zip)

**Comment by osy** [comment] 2023-02-26 04:34
Duplicate of 	#5043

**Closed by osy** 2023-02-26 04:34 UTC
Labels: duplicate, virgl
