### ISSUE TITLE
Ubuntu 20.04.1/20.04 ARM64 Stuck on black screen iOS 13.6.1

### ISSUE THREAD

**Issue by cuj** [utmapp/UTM#2290] opened 2021-01-28 05:38 UTC
**Describe the issue**
I created an Ubuntu 20.04.1/20.04 ARM64 VM, inserted the Ubuntu ARM64 iso image, and created a hard disk for the VM, I made the VM boot to CD first, but when I start the VM, it is stuck on a black screen.

**Configuration (required)**
* UTM Version: 2.0.19
* OS Version: 13.6.1
* Device Model: iPhone X (iPhone10,6)
* Is it jailbroken: Yes, using checkra1n 0.12.1-beta
* How did you install UTM? Using cydia. (cydia.getutm.app)

**Crash log**
If the app crashed, you need a crash log. To get your crash log, open the Settings app and browse to `Privacy -> Analytics & Improvements -> Analytics Data` and find the latest entry for UTM. You should export the text and attach it here.

**Debug log**
[Here](https://pastebin.com/raw/raMcuqdD)

**Upload VM**
(Optional) If possible, upload the `config.plist` inside the `.utm`. If you do not have this, you can upload the entire `.utm` but note this contains your personal data. Since Github has an attachment size limit, you may want to upload to another service such as Google Drive. Link it here.

**Comment by osy** [comment] 2021-01-28 20:39
Can you try pressing the Zoom button twice?

**Comment by cuj** [comment] 2021-01-29 09:30
> Can you try pressing the Zoom button twice?

That didn't work,

**Comment by elgambitero** [comment] 2021-02-06 22:01
I can confirm that in 2.0.20 with Big Sur 11.2 in an M1 MBP, it's impossible to even boot the iso.

I deleted the VM because I could not activate network, and now I am stuck with no linux VM.

It fails to load "UEFI Disk Device" 1 and 2 with the message "not found", and jumps into EFI shell

**Comment by osy** [comment] 2021-02-19 01:41
Have you tested with 2.0.20?

**Comment by cuj** [comment] 2021-02-19 05:50
> Have you tested with 2.0.20?

I will test it with v2.0.20 and 2.0.21 which is just released

**Comment by osy** [comment] 2021-09-04 03:30
Closing since this issue is old. If issue persists, please open a new issue with updated logs.

**Closed by osy** 2021-09-04 03:30 UTC
