### ISSUE TITLE
Shared Directories List (Apple Virtualization, macOS Guest on M1 Host) is not saved in config.plist

### ISSUE THREAD

**Issue by runwaygoats** [utmapp/UTM#5569] opened 2023-08-17 12:45 UTC
**Describe the issue** 

   Add some folders to Shared Directories List to a VM (on external disk).
   Remove the VM (on external disk) from UTM.
   Re-add the same VM (on external disk) to UTM.
   Shared Directories list is empty.

   It seems that Shared Directories List is not saved in config.plist.
   Is it possible to save it in config.plist?
   So that, you do not need to add it again every time you remove and add the VM.

**Configuration**  
* UTM Version: 4.3.5 (87)
* macOS Version: 14.0 Beta (23A5312d)
* Mac Chip (Intel, M1, ...): M1
* Guest OS: macOS 14.0 Beta (23A5312d)

**Comment by osy** [comment] 2023-08-19 19:04
Shared Directories should be saved in the registry (part of the app container). When you remove the VM, the registry is cleared. Why are you removing the VM?

**Comment by runwaygoats** [comment] 2023-08-19 19:14
I store all of my VMs on a different partition formatted with APFS.

I create a new VM and create my work environment in the VM.
Then I clone the VM by duplicating the VM.utm in Finder.
Thanks to APFS, duplication is done instantly.
After doing my tests, I delete the clone and create a new one again.

**Comment by osy** [comment] 2023-08-19 19:18
I see; so the registry uses the UUID inside config.plist to know what corresponds to what registry entry. If you try to have two VMs with the same UUID, the second one will automatically get assigned a new UUID and hence an empty registry entry. If you want to preserve the registry entry, replace the original .utm with the cloned one using Finder and it should retain the UUID. The reason we don't store bookmarks inside config.plist anymore is because they do not work across multiple machines.

**Comment by runwaygoats** [comment] 2023-08-19 19:38
My plan was like below.
Is it possible to have an option to "Store Shared Directories in config.plist"?

Disk partitions:

macOS_12_6
macOS_13_5
macOS_14_0
data

Share Directory setting on all VMs:
/Volumes/data/UTM/Shared

So that, all VMs could access to the common Shared Directory by all UTM.apps on all host macOSes.
On multiple machine scenario, VMs would be on a common network storage.

**Comment by osy** [comment] 2023-08-19 19:42
I don’t see why you can’t just set up the same shared directory for all the VMs?

**Comment by runwaygoats** [comment] 2023-08-19 19:42
I did a test.
I have removed all the VMs from UTM.
Added a previously created VM to UTM.
Add a Shared Directory.
Save the VM.
Remove and re-add the same VM. (No clone)
Shared Directory list is empty again.

**Comment by runwaygoats** [comment] 2023-08-19 19:50
> I don’t see why you can’t just set up the same shared directory for all the VMs?

I do. I have no problem setting up Shared Directory and using it in VM.
Only problem is Shared Directory List not being portable (saved within the VM.utm ).
When I remove the VM and re-add it to UTM, Shared Directory List comes as empty.
When I set up the Shared Directory again, it works as expected.

VMs are created and destroyed frequently on a test environment.
Also, host macOS operating systems needs to be created and destroyed often.


UTM: 4.3.5
macOS Host : 14.0 Beta (23A5312d)
macOS Guest : 14.0 Beta (23A5312d)

**Comment by osy** [comment] 2023-08-19 19:52
As I’ve asked above, I’m wondering why you have to remove the existing VM. Why not just replace it in Finder?

**Comment by runwaygoats** [comment] 2023-08-19 20:12
I did a test from scratch.

It seems that Shared Directory List goes away when I close UTM.app, even without removing or adding any VM.

I created a video of the screen.

https://we.tl/t-ehz83LJ8gP

**Comment by runwaygoats** [comment] 2023-08-19 20:24
> As I’ve asked above, I’m wondering why you have to remove the existing VM. Why not just replace it in Finder?

I think I have just managed to understand what you said.

Create vmOriginal.utm.
Close UTM.app.
Clone vmOriginal.utm as vmBackup.utm
Do not add or use vmBackup.utm in UTM.app. Just leave it aside.
Do your tests with vmOriginal.utm.
When done, close UTM.app.
Delete vmOriginal.utm.
Clone vmBackup.utm as vmOriginal.utm.
Open UTM.app.

I will test this after the new [problem](https://github.com/utmapp/UTM/issues/5569#issuecomment-1685099647) is solved.
That should work.
Thank you!

**Comment by osy** [comment] 2023-08-21 00:25
Oh I forgot I already fixed this lol

**Comment by osy** [comment] 2023-08-21 00:25
Duplicate of #5531

**Comment by osy** [comment] 2023-08-21 00:25
I didn't understand what you were talking about until I saw the video but that was addressed in #5531

**Closed by osy** 2023-08-21 00:25 UTC
Labels: interface
