### ISSUE TITLE
Ability to add more than one network card

### ISSUE THREAD

**Issue by JuniorJPDJ** [utmapp/UTM#3248] opened 2021-11-04 12:11 UTC
Hello!
I just tried to migrate from VirtualBox and I spotted a problem.
My usecase needs more than one network card attached to VM, but I found no way of doing it.
It's probably possible using qemu arguments, but it's a workaround.

**Comment by conath** [comment] 2021-11-05 16:26
Duplicate of #2722 

As you pointed out correctly, it is already possible to add multiple NICs via the "QEMU" tab - but not in the Network tab UI.

**Closed by conath** 2021-11-05 16:26 UTC
Labels: enhancement
