### ISSUE TITLE
UTM0.8 can't run MacOSX but UTM0.7 can

### ISSUE THREAD

**Issue by none-null-blank** [utmapp/UTM#245] opened 2020-04-10 02:03 UTC
Error message:QEMU encountered an error exit: qemu: Property'.vmport' not frund
UTM0.8 has this bug.But UTM0.7 doesn't have the bug.

**Comment by obbcth** [comment] 2020-04-10 02:58
Duplicate of #229

**Closed** 2020-04-10 03:43 UTC
