### ISSUE TITLE
Cannot Edit VM w/o Force Stop

### ISSUE THREAD

**Issue by stvhay** [utmapp/UTM#4580] opened 2022-10-30 21:47 UTC
**Describe the issue**  
I cannot edit an Apple Virtualized (Debian Linux) VM if I power it down normally. I have to pause the VM then force stop it. After that, I get errors starting it unless I click the "play" button on the VM window.

**Configuration**  
* UTM Version: 4.0.9
* macOS Version: 13.0
* Mac Chip (Intel, M1, ...): M1 Max

**Crash log**  
N/A

**Debug log**  
This is editing the VM.

**Upload VM**  
Uploaded.

[config.plist.zip](https://github.com/utmapp/UTM/files/9896884/config.plist.zip)

**Comment by osy** [comment] 2023-02-27 02:18
I am not able to reproduce this issue. Can you reproduce it on 4.1.5?

**Comment by osy** [comment] 2023-03-17 18:37
Closing due to inability to reproduce. Please re-open it if you can provide steps to re-produce it.

**Closed by osy** 2023-03-17 18:37 UTC
