### ISSUE TITLE
deleted VMs should be moved to the macOS (Finder) trash

### ISSUE THREAD

**Issue by Rastafabisch** [utmapp/UTM#5884] opened 2023-11-11 12:00 UTC
**Describe the issue**  
Deleted VMs are just gone. They should be restorable from Finder. Could be valid to call this a feature request, but as it just feels wrong compared to other VM solutions I explicitly filed an issue.

**Configuration**  
* UTM Version: 4.4.4
* macOS Version: 14.1.1
* Mac Chip (Intel, M1, ...): any

**Comment by gustaf71** [comment] 2023-11-11 16:18
I believe the method Apple provide is broken. The developers of UTM could use Apple event to call Finder to delete the object VM. This way you get put back in trash folder. Or you could also make AppleScript to get the folder content from ~/Library/Containers/UTM/Data/Documents and use Finder to delete your selections.

**Comment by osy** [comment] 2023-11-11 18:40
Duplicate of #4332

**Comment by osy** [comment] 2023-11-11 18:41
> I believe the method Apple provide is broken. The developers of UTM could use Apple event to call Finder to delete the object VM. This way you get put back in trash folder. Or you could also make AppleScript to get the folder content from ~/Library/Containers/UTM/Data/Documents and use Finder to delete your selections.

Using AppleScript requires additional entitlements that Apple likely will not grant in 2023

**Closed by osy** 2023-11-11 18:40 UTC
