### ISSUE TITLE
On Fedora 35 aarch64 guest, ping produces errors and never terminates if Emulated VLAN is used

### ISSUE THREAD

**Issue by michel-slm** [utmapp/UTM#3529] opened 2022-01-24 05:30 UTC
**Describe the issue**
`ping` produces errors on the guest, seems to affect all sites, if Emulated VLAN is used (so I can ssh into the guest). This doesn't happen if Shared Network mode is used. `ping`-ing the same site from the host macOS also works fine.

Other network operations seem to work fine e.g. I can run `dnf upgrade` to upgrade the guest just fine, and SSH works fine.

e.g.
```
[michel@fedora ~]$ ping lwn.net -c 3
PING lwn.net (66.228.47.22) 56(84) bytes of data.
ping: Warning: time of day goes back (-6543460708837932211us), taking countermeasures
ping: Warning: time of day goes back (-6543460708837929032us), taking countermeasures
64 bytes from prod3.lwn.net (66.228.47.22): icmp_seq=0 ttl=255 time=0.000 ms
wrong data byte #16 should be 0x10 but was 0x0
#16     0 5 0 1 4f 38 ee 61 0 0 0 0 e8 76 3 0 0 0 0 0 10 11 12 13 14 15 16 17 18 19 1a 1b 
#48     1c 1d 1e 1f 20 21 22 23 
ping: Warning: time of day goes back (-5616030280704030468us), taking countermeasures
64 bytes from prod3.lwn.net (66.228.47.22): icmp_seq=0 ttl=255 time=0.000 ms (DUP!)
wrong data byte #16 should be 0x10 but was 0x0
#16     0 5 0 2 50 38 ee 61 0 0 0 0 c5 82 3 0 0 0 0 0 10 11 12 13 14 15 16 17 18 19 1a 1b 
#48     1c 1d 1e 1f 20 21 22 23 
ping: Warning: time of day goes back (-3778328447074703846us), taking countermeasures
64 bytes from prod3.lwn.net (66.228.47.22): icmp_seq=0 ttl=255 time=0.000 ms (DUP!)
wrong data byte #16 should be 0x10 but was 0x0
#16     0 5 0 3 51 38 ee 61 0 0 0 0 3f 9b 3 0 0 0 0 0 10 11 12 13 14 15 16 17 18 19 1a 1b 
#48     1c 1d 1e 1f 20 21 22 23 

--- lwn.net ping statistics ---
3 packets transmitted, 1 received, +2 duplicates, 66.6667% packet loss, time 2009ms
rtt min/avg/max/mdev = 0.000/0.000/0.000/0.000 ms, pipe 4
[michel@fedora ~]$ ping google.com -c 3
PING google.com (142.251.46.206) 56(84) bytes of data.
ping: Warning: time of day goes back (-7826133672992043027us), taking countermeasures
ping: Warning: time of day goes back (-7826133672992003776us), taking countermeasures
64 bytes from nuq04s45-in-f14.1e100.net (142.251.46.206): icmp_seq=0 ttl=255 time=0.000 ms
wrong data byte #16 should be 0x10 but was 0x0
#16     0 6 0 1 59 38 ee 61 0 0 0 0 4c 85 5 0 0 0 0 0 10 11 12 13 14 15 16 17 18 19 1a 1b 
#48     1c 1d 1e 1f 20 21 22 23 
ping: Warning: time of day goes back (-6430862213436317034us), taking countermeasures
64 bytes from nuq04s45-in-f14.1e100.net (142.251.46.206): icmp_seq=0 ttl=255 time=0.000 ms (DUP!)
wrong data byte #16 should be 0x10 but was 0x0
#16     0 6 0 2 5a 38 ee 61 0 0 0 0 a7 97 5 0 0 0 0 0 10 11 12 13 14 15 16 17 18 19 1a 1b 
#48     1c 1d 1e 1f 20 21 22 23 
ping: Warning: time of day goes back (-5487921041454612886us), taking countermeasures
64 bytes from nuq04s45-in-f14.1e100.net (142.251.46.206): icmp_seq=0 ttl=255 time=0.000 ms (DUP!)
wrong data byte #16 should be 0x10 but was 0x0
#16     0 6 0 3 5b 38 ee 61 0 0 0 0 bc a3 5 0 0 0 0 0 10 11 12 13 14 15 16 17 18 19 1a 1b 
#48     1c 1d 1e 1f 20 21 22 23 

--- google.com ping statistics ---
3 packets transmitted, 1 received, +2 duplicates, 66.6667% packet loss, time 2008ms
rtt min/avg/max/mdev = 0.000/0.000/0.000/0.000 ms, pipe 4
```

A clear and concise description of what the issue is. **BEFORE SUBMITTING YOUR ISSUE, PLEASE LOOK AT THE PINNED ISSUES AND USE THE SEARCH FUNCTION TO MAKE SURE IT IS NOT ALREADY REPORTED. ALWAYS COMMENT ON AN EXISTING ISSUE INSTEAD OF MAKING A NEW ONE.**

**Configuration**
* UTM Version: 2.4.1 (40)
* OS Version: macOS 12.1 (host), Fedora 35 for aarch64 (guest)
* Intel or Apple Silicon? Apple Silicon

**Crash log**
If the app crashed, you need a crash log. To get your crash log, open Console.app, go to `Crash Reports`, and find the latest entry for either QEMU, QEMUHelper, or qemu-\*. Right click and choose `Reveal in Finder`. Attach the report here.

**Debug log**
For all issues, _including_ crashes, you should attach a debug log. Open UTM, and open the settings for the VM you wish to launch. Near the top of the `QEMU` page is `Debug Log`. Turn it on and save the VM. After you experience the issue, open the VM settings again and select `Export Log...` and attach it here.
[fedora-debug.log](https://github.com/utmapp/UTM/files/7922872/fedora-debug.log)

**Upload VM**
(Optional) If possible, upload the `config.plist` inside the `.utm`. If you do not have this, you can upload the entire `.utm` but note this contains your personal data. Since Github has an attachment size limit, you may want to upload to another service such as Google Drive. Link it here.

**Comment by osy** [comment] 2022-01-24 07:15
Ping does not work with QEMU slirp. It’s a known limitation.

**Comment by osy** [comment] 2022-01-24 07:15
Duplicate of #351

**Closed by osy** 2022-01-24 07:15 UTC
Labels: duplicate

**Comment by michel-slm** [comment] 2022-01-26 18:27
Thanks @osy . Is Firefox not being able to reach https://start.fedoraproject.org/ due to the same limitation?

﻿﻿```
Secure Connection Failed

An error occurred during a connection to start.fedoraproject.org. The OCSP response is not yet valid (contains a date in the future).

Error code: SEC_ERROR_OCSP_FUTURE_RESPONSE

    The page you are trying to view cannot be shown because the authenticity of the received data could not be verified.
    Please contact the website owners to inform them of this problem.
```
