### ISSUE TITLE
UTM Crashes on selecting ubuntu from the sidebar

### ISSUE THREAD

**Issue by jempiere** [utmapp/UTM#3889] opened 2022-04-10 21:04 UTC
**Describe the issue**
For all of my Ubuntu VM's (both the current LTS and 21.10) clicking them in the sidebar will result in an immediate crash of UTM, regardless of whether GL acceleration is on. The crash log is attached, but I was unable to get a debug log because the VM never ran.

**Configuration**
* UTM Version: 3.1.5 (latest)
* OS Version: 12.3.1 (latest)
* Intel or Apple Silicon? Apple Silicon

**Crash log**
[UTM-2022-04-10-145829.ips.txt](https://github.com/utmapp/UTM/files/8459899/UTM-2022-04-10-145829.ips.txt)

**Debug log**
I was unable to get the debug log, because it crashes as soon as the VM is clicked

**Config plist**
[config.plist.txt](https://github.com/utmapp/UTM/files/8459904/config.plist.txt)

**Comment by osy** [comment] 2022-04-23 00:49
Duplicate of #3612

**Closed by osy** 2022-04-23 00:49 UTC
Labels: duplicate
