### ISSUE TITLE
Implement snapshot

### ISSUE THREAD

**Issue by imclint21** [utmapp/UTM#6020] opened 2024-01-12 18:50 UTC
Hi,

I really like UTM, a nice VM software on macOS, I was wondering if you plan to implement snapshots system,

There is a ready to use snapshots system for UTM here: https://github.com/Metamogul/UTM-Snapshot-Manager/issues/7#issuecomment-1889721145

Regards

**Comment by osy** [comment] 2024-02-26 21:03
Duplicate of #5484

**Closed by osy** 2024-02-26 21:03 UTC
Labels: enhancement
