### ISSUE TITLE
Mac OS 9.2.1 fails to start: Error 启动 QEMU 时出错

### ISSUE THREAD

**Issue by ylluminate** [utmapp/UTM#3476] opened 2022-01-13 08:57 UTC
**Describe the issue**
UTM 3.0.2 (43) tried to install Mac OS 9.2.1 from https://mac.getutm.app/gallery/mac-os-9-2-1 and upon installation and trying to start, I get the following error:
![error](https://p153.p0.n0.cdn.getcloudapp.com/items/bLuxRmAo/e4c08f18-bec6-4099-9ac2-6c9b680cf78b.jpg?v=e34ad9d3cfb5d4d2b04166840341a1b8)

This is with the following configuration

**Configuration**
* UTM Version: 3.0.2
* OS Version: macOS 12.1 (21C52)
* Intel or Apple Silicon? M1 Max (Apple Silicon)

**Debug log**
```
Running:  -L /Applications/UTM.app/Contents/Resources/qemu -S -qmp tcp:127.0.0.1:4000,server,nowait -nodefaults -vga none -spice "unix=on,addr=/Users/user/Library/Group Containers/WDNLXAD4W8.com.utmapp.UTM/4D6EFE89-3FF4-4110-8E05-7FE7A930FE6D.spice,disable-ticketing=on,image-compression=off,playback-compression=off,streaming-video=off,gl=off" -device VGA -smp cpus=1,sockets=1,cores=1,threads=1 -machine mac99,via=pmu -accel tcg,tb-size=128 -boot menu=on -m 512 -audiodev coreaudio,id=audio0 -name "Mac OS 9.2.1" -usb -device usb-tablet,bus=usb-bus.0 -device usb-mouse,bus=usb-bus.0 -device usb-kbd,bus=usb-bus.0 -device ich9-usb-ehci1,id=usb-controller-0 -device ich9-usb-uhci1,masterbus=usb-controller-0.0,firstport=0,multifunction=on -device ich9-usb-uhci2,masterbus=usb-controller-0.0,firstport=2,multifunction=on -device ich9-usb-uhci3,masterbus=usb-controller-0.0,firstport=4,multifunction=on -chardev spicevmc,name=usbredir,id=usbredirchardev0 -device usb-redir,chardev=usbredirchardev0,id=usbredirdev0,bus=usb-controller-0.0 -chardev spicevmc,name=usbredir,id=usbredirchardev1 -device usb-redir,chardev=usbredirchardev1,id=usbredirdev1,bus=usb-controller-0.0 -chardev spicevmc,name=usbredir,id=usbredirchardev2 -device usb-redir,chardev=usbredirchardev2,id=usbredirdev2,bus=usb-controller-0.0 -device ide-hd,bus=ide.0,drive=drive1,bootindex=0 -drive "if=none,media=disk,id=drive1,file=/Users/user/Library/Containers/com.utmapp.UTM/Data/Documents/Mac OS 9.2.1.utm/Images/disk-0.qcow2,cache=writethrough" -device ide-cd,bus=ide.1,drive=drive0,bootindex=1 -drive if=none,media=cdrom,id=drive0 -device sungem,mac=C6:F8:CC:03:A4:E2,netdev=net0 -netdev user,id=net0 -uuid 4D6EFE89-3FF4-4110-8E05-7FE7A930FE6D -rtc base=localtime
```

**Comment by conath** [comment] 2022-01-13 19:27
The missing error message here is already tracked as #3369 by the way.

**Comment by ylluminate** [comment] 2022-01-14 09:32
@conath downloaded 3.0.2 manually via releases (https://github.com/utmapp/UTM/releases). Hmmm. Seems like I'm having the same issue then perhaps, but I'm not clear on the status. Have you had any luck there? Quite a lot of static and/or no resolution it seems from that issue.

What can I do to help track this down further?

**Comment by conath** [comment] 2022-01-14 09:45
Checking your debug log, it seems like you have USB 3 sharing enabled in the sharing tab, please disable the USB 3 / XHCI and set the number of ports to 0. 

If the error persists, please record and post your system log as outlined on the [system troubleshooting page](https://github.com/utmapp/UTM/wiki/Troubleshooting-UTM-and-system-errors#system-log). Thank you!

**Comment by ylluminate** [comment] 2022-01-14 16:33
Interesting, I am using whatever it configured by default there, but what is weird is that I don't see any setting options anywhere so far that indicate a way to disable USB 3 / XHCI... The only thing I see indicates that it's disabled (and I have never enabled it):
![image](https://p153.p0.n0.cdn.getcloudapp.com/items/mXuJ66Jn/e571ef7f-20d9-4c83-9891-2e45032d4a9d.jpg?v=21ab00730939aede9d3d03cfadf1c3ac)

**Comment by conath** [comment] 2022-01-14 17:24
My bad, I misread that. Still, change number of ports to 0 please and follow the troubleshooting instructions.

**Comment by ylluminate** [comment] 2022-01-14 17:56
@conath I did as instructed:
![image](https://p153.p0.n0.cdn.getcloudapp.com/items/o0uZm6Jx/93fe2f7a-9c24-407e-bef1-e0b4a8453882.jpg?v=7066ee10940cf7b4183c1b6da69fcc70)

Got the same results, exported the debug log: [2022-01-14 (12-48) - debug.log](https://p153.p0.n0.cdn.getcloudapp.com/items/rRuNoGxq/0318a981-9de5-462b-b0e2-9340cc3d7317.log?v=128a8cdec4ef8cbb50c4c93f0aebaa83)

From the troubleshooting instructions linked to and the subsequent link from that page, I don't really see any additional steps to take that are directly indicated except for extracting and reviewing the debug log. I'm happy to go through this (and gave it a cursory read), but beyond just trying to execute the virtual machine manually with different arguments, I'm not sure what to do. 

Am I missing something?

Also, what's the correct way to use that qemu line in conjunction with UTM from the shell to test this via the shell? For example, executing the line indicated for qemu therein simply returns: `The file '/Applications/UTM.app/Contents/Resources/qemu' is not executable by this user` and sudo gives a different error (`command not found`)...

**Comment by conath** [comment] 2022-01-14 18:00
@ylluminate Please follow the steps in the section ["How to get macOS System Log for UTM troubleshooting?"](https://github.com/utmapp/UTM/wiki/Troubleshooting-UTM-and-system-errors#how-to-get-macos-system-log-for-utm-troubleshooting).

The QEMU is not included in UTM as a binary, so the command will not work. You would need to install QEMU using [Homebrew](https://brew.sh).

**Comment by ylluminate** [comment] 2022-01-14 18:08
Thank you - on the qemu point: is 6.2.0 the right version or should I use the head?  I prefer to use MacPorts since Homebrew is a dumpster fire in my experience.

**Comment by conath** [comment] 2022-01-14 18:14
I would go with 6.2.0, that is also what we base UTM on at the moment.

**Comment by ylluminate** [comment] 2022-01-20 04:54
Sorry it's taken me some days here to get back. Buried up with some work. So I installed qemu via MacPorts, but it didn't have the `ppc` system emulator binary. I went ahead and installed it via Homebrew to get more system binaries quickly vs fighting the situation at the moment.

So when I ran the above command, it was missing Spice support, but I managed to get this to execute, but got only a black screen and the cursor for macOS seemed to stop responding altogether:
```
qemu-system-ppc -S -qmp tcp:127.0.0.1:4000,server,nowait -nodefaults -vga none -device VGA -smp cpus=1,sockets=1,cores=1,threads=1 -machine mac99,via=pmu -accel tcg,tb-size=128 -boot menu=on -m 512 -audiodev coreaudio,id=audio0 -name "Mac OS 9.2.1" -usb -device usb-tablet,bus=usb-bus.0 -device usb-mouse,bus=usb-bus.0 -device usb-kbd,bus=usb-bus.0 -device ide-hd,bus=ide.0,drive=drive1,bootindex=0 -drive "if=none,media=disk,id=drive1,file=/Users/user/Library/Containers/com.utmapp.UTM/Data/Documents/Mac OS 9.2.1.utm/Images/disk-0.qcow2,cache=writethrough" -device ide-cd,bus=ide.1,drive=drive0,bootindex=1 -drive if=none,media=cdrom,id=drive0 -device sungem,mac=C6:F8:CC:03:A4:E2,netdev=net0 -netdev user,id=net0 -uuid 4D6EFE89-3FF4-4110-8E05-7FE7A930FE6D -rtc base=localtime
```
Following this I kinda became flustered and had to kill the process and then restarted UTM with this VM. I then went into the settings and hit [that weird issue](https://github.com/utmapp/UTM/issues/3503) where I couldn't cancel or save the config. I force quit UTM and then reopened and Mac OS 9 fired right up and works now. This is really strange, but hopefully this might make some sense for you.

I couldn't really get a failure within Console.app logging, so I guess this is where this lies at this point... Any thought?

**Comment by conath** [comment] 2022-01-20 08:32
Unfortunately without any technical information like a system log, I can‘t find out why this is happening. The error seems to be only happening for those who downloaded the .dmg from GitHub or the website, as opposed to installing visa the App Store. My best guess is a macOS security system is interfering with UTM here. https://github.com/utmapp/UTM/issues/3369#issuecomment-997446806

Closing as duplicate of #3369

**Closed by conath** 2022-01-20 08:32 UTC
Labels: question
