### ISSUE TITLE
UEFI Interactive Shell v2.2 mapping table

### ISSUE THREAD

**Issue by shareef-dweikat** [utmapp/UTM#3867] opened 2022-04-05 15:40 UTC
I am getting this issue when try boot Debian.

* UTM Version: 3.1.5 (53)
* OS Version:  MACOS 12
* Intel or Apple Silicon?  Apple 

<img width="800" alt="149540297-b1265fc6-d859-424d-b25e-57b0b904cdb4" src="https://user-images.githubusercontent.com/10628302/161792015-566cd558-8fd7-4efc-b9d6-bcc2b2aa885c.png">

**Comment by conath** [comment] 2022-04-05 22:16
Duplicate of the discussion in https://github.com/utmapp/UTM/discussions/3486 and note my answer. https://github.com/utmapp/UTM/discussions/3486#discussioncomment-1971300

**Closed by conath** 2022-04-05 22:16 UTC
