### ISSUE TITLE
Unable to power on virtual machine

### ISSUE THREAD

**Issue by yuanyiming** [utmapp/UTM#4275] opened 2022-08-08 08:52 UTC
Describe the issue
Unable to power on virtual machine

Configuration

UTM Version: V.4
macOS Version: macOS Ventura beta4
Mac Chip (Intel, M1, ...): M1
Crash log
If the app crashed, you need a crash log. To get your crash log, open
Console.app, go to Crash Reports, and find the latest entry for either
UTM, QEMU, QEMUHelper, or qemu-*. Right click and choose Reveal in Finder. Attach the report here.

Debug log
For all issues related to running a VM, including crashes, you should
attach a debug log. (This is unavailable for macOS-on-macOS VMs. Attach an
excerpt of your system log instead.)
To get the Debug log: open UTM, and open the settings for the VM you wish
to launch. Near the top of the QEMU page is Debug Log. Turn it on and
save the VM. After you experience the issue, open the VM settings again and
select Export Log... and attach it here.

Upload VM
If your issue is related to a specific VM, please upload the config.plist
from your VM's .utm directory. To get this, right-click the VM in UTM and
choose "Show in Finder". Then right-click the selected file in Finder and
choose "Show Package Contents". The config.plist file is now visible.
Right-click it and choose "Compress". Attach the resulting config.plist.zip
file here.
You can upload the entire .utm if needed, but note this includes your VM's
drive image and may contain personal data. Since Github has an attachment
size limit, you may want to upload to another service such as Google Drive.
Link it here
![183365017-e0aa2339-5370-4f78-8ce2-5f8d33eb085a](https://user-images.githubusercontent.com/109521734/183379154-54e13a06-917a-4727-8150-e5e755f5a014.jpeg)

**Comment by osy** [comment] 2022-08-08 18:39
Duplicate of #4274

**Closed by osy** 2022-08-08 18:39 UTC
