### ISSUE TITLE
USB Passthrough with Apple Virtualization

### ISSUE THREAD

**Issue by jmstacey** [utmapp/UTM#4699] opened 2022-11-21 03:37 UTC
**Feature Request:** Connect USB devices to a virtual machine that is virtualized using Apple Virtualization. 

**Example use case:** attach USB storage device to the virtual machine.

This is possible in QEMU, but that would lose Rosetta x86 emulation.

**Comment by osy** [comment] 2022-11-22 23:48
Duplicate of #3778

**Closed by osy** 2022-11-22 23:48 UTC
Labels: enhancement
