### ISSUE TITLE
UTM make iPad not responsed when stop VM during installing Debain

### ISSUE THREAD

**Issue by TangMonk** [utmapp/UTM#165] opened 2020-03-23 04:11 UTC
**Describe the bug**
I am  installling the debain 10, during installing , I click the 'X' to stop install, but the UTM stop response, and iPad is no responsed too

**Comment by osy86** [comment] 2020-03-23 04:31
Please upload the .utm and a video showing the issue. I don’t understand.

**Comment by osy86** [comment] 2020-03-24 18:16
Duplicate of #148

**Closed by osy86** 2020-03-24 18:16 UTC
Labels: duplicate
