### ISSUE TITLE
Fix Windows network issue

### ISSUE THREAD

**Issue by Jaiganeshkumaran** [utmapp/UTM#3033] opened 2021-08-20 05:20 UTC
**Describe the issue**
Although networking is available inside the Windows VM, the operating system thinks there's no internet and thus prevents things like installing Windows Updates or downloading Store apps. Is there a way to fix the issue?

**Configuration**
* UTM Version: 2.1.2 (31)
* OS Version: Windows 10 Pro Build 21354.1
* Intel or Apple Silicon? Apple Silicon

**Comment by Jaiganeshkumaran** [comment] 2021-08-20 05:27
Windows keeps trying to load http://msftconnecttest.com/ in the browser which is annoying and I have displayed auto polling however that doesn't really help.

**Comment by muratdk23** [comment] 2021-08-20 05:58
Version 2.2.0 beta fixes this problem. In settings go to network tab and select shared or bridged network.

**Comment by conath** [comment] 2021-08-20 21:41
Duplicate of #2585 - thanks @muratdk23 I will add your remark to the #2585 discussion

**Closed by conath** 2021-08-20 21:41 UTC
