### ISSUE TITLE
Mac Virtual machine has skewed view for any downloaded apps

### ISSUE THREAD

**Issue by siammais10** [utmapp/UTM#3947] opened 2022-04-28 02:07 UTC
I am using a Mac virtual machine in UTM, and native apps are working fine, but if I try to download chrome or visual studio code, the view is skewed (see screenshots). In Chrome, the "x" button in the tap shows up as a square and most of the other icons are also appearing incorrectly. Visual studio code is not even usable because of how skewed it is
Any ideas how to resolve this?
![image](https://user-images.githubusercontent.com/75688941/165661867-fc4fc080-4fa3-487f-8ea2-ddd0f1e90db6.png)

![Screen Shot 2022-04-27 at 10 08 54 PM](https://user-images.githubusercontent.com/75688941/165662245-d4144a08-37bd-4820-94d8-c7db1d174c9b.png)

**Configuration**
* UTM Version: 3.1.5
* OS Version: 12.0.1
* Intel or Apple Silicon? Silicon

**Comment by siammais10** [comment] 2022-04-28 02:08
![image](https://user-images.githubusercontent.com/75688941/165662126-7ce34abd-e896-40c3-a5a9-4ff537a17278.png)

**Comment by anthony-bennett** [comment] 2022-04-28 04:14
See this issue, looks the same: #3692

**Comment by conath** [comment] 2022-04-30 18:46
Duplicate of #3692

**Closed by conath** 2022-04-30 18:46 UTC
