### ISSUE TITLE
UTM HV installed via TrollStore 2 does not run any VMs, displays error saying running VMs is not supported when iOS is unmodified

### ISSUE THREAD

**Issue by NekoMichi** [utmapp/UTM#5927] opened 2023-11-28 20:10 UTC
**Describe the issue**
UTM HV version 4.4.4 installed via TrollStore 2.0.7 displays an error when launched that reads "Your version of iOS does not support running VMs while unmodified. You must either run UTM while jailbroken or with a remote debugger attached." I thought UTM-HV does not require a jailbreak, the iOS compatibility table specifically lists HV as "Non-jailbroken iOS version (TrollStore)", so I'm not sure why this error message is being displayed. I understand that hypervisor requires M1 but I have that disabled in all of my VMs. Attempting to run any VM will result in a black screen whereas the same VM files can boot normally in UTM SE.

**Configuration (required)**
* UTM Version: UTM HV 4.4.4
* OS Version: iPadOS 16.1
* Device Model: iPad Mini 6th generation
* Is it jailbroken (name jailbreak used)?: Non-jailbroken
* How did you install UTM?: TrollStore 2.0.7

**Comment by osy** [comment] 2023-11-28 21:16
Duplicate of #5216

**Closed by osy** 2023-11-28 21:16 UTC
