### ISSUE TITLE
Enable USB Sharing for guest OS running under Apple Virtualization

### ISSUE THREAD

**Issue by stefanoaz** [utmapp/UTM#5685] opened 2023-09-08 19:17 UTC
I am running Debian 12 guest OS with Ventura running on Mac M2 silicon. Because I need Rosetta to run some amd64 apps, I have to use Apple Virtualization. However, presently USB sharing isn't available under Apple Virtualization in UTM. This is something I could immediately use. It would be a valuable enhancement.

If there are any workarounds that still allow me to use Rosetta in the guest OS, I'd be happy to know about them.

**Comment by parasaito** [comment] 2023-09-09 02:08
I think this is duplicate of #3778 

Apple Virtualization uses the Virtualization.framework which currently does not support USB passthrough unfortunately.

QEMU uses Hypervisor framework so it does allow USB sharing. For now that's the only option to get USB devices working with VM.

**Comment by osy** [comment] 2023-09-09 17:46
Duplicate of #3778

**Closed by osy** 2023-09-09 17:46 UTC
Labels: enhancement
