### ISSUE TITLE
iOS 14 All VMs crash the app

### ISSUE THREAD

**Issue by Winterknight1353** [utmapp/UTM#566] opened 2020-11-22 19:47 UTC
I installed UTM recently through AltStore on my iPhone 7+ With iOS 14. When I setup my first VM(Windows 7) it crashed when I tried to launch it for the first time. Thinking I did some thing wrong I installed the prebuilt android 9.0 vm and it crashed too. Is it because I’m using an old device or installed it through alt store or is it something else?
[**Crash log**](https://drive.google.com/file/d/1ShMMb3kiAUrFwAdwGFSvmtAcsHZv7usr/view?usp=drivesdk) 

[**Debug log**](https://drive.google.com/file/d/1Rsut-ZbEZNfO8Kl_iwhhnm0FNjHrHeYq/view?usp=drivesdk)

**Comment by IIWare** [comment] 2020-11-22 20:04
Duplicate of #516

**Closed** 2020-11-23 01:23 UTC
Labels: duplicate
