### ISSUE TITLE
UTM crash on IPad Air M1

### ISSUE THREAD

**Issue by Iamansweringyou** [utmapp/UTM#4530] opened 2022-10-20 19:22 UTC
**Describe the issue**
After UTM SE update non jailbroken IPad crashes, when I start VM

**Configuration (required)**
* UTM Version: SE (4.0.8)
* OS Version: IPad OS 15.7
* Device Model: IPad Air M1 2022
* Is it jailbroken (name jailbreak used)? No
* How did you install UTM? Installed in AltStore 

**Crash log**

{"app_name":"UTM SE","timestamp":"2022-10-20 16:31:46.00 +0300","app_version":"4.0.8","slice_uuid":"2c59f93d-8de3-379f-adae-2975a8f813ac","build_version":"67","platform":2,"bundleID":"com.utmapp.UTM-SE.2SNV3Q9Z47","share_with_app_devs":0,"is_first_party":0,"bug_type":"309","os_version":"iPhone OS 15.7 (19H12)","incident_id":"DBF39C11-BDEE-444B-80A0-1B13BD822AE1","name":"UTM SE"}
{
  "uptime" : 300,
  "procLaunch" : "2022-10-20 16:31:42.6749 +0300",
  "procRole" : "Foreground",
  "version" : 2,
  "userID" : 501,
  "deployVersion" : 210,
  "modelCode" : "iPad13,16",
  "procStartAbsTime" : 7266910955,
  "coalitionID" : 465,
  "osVersion" : {
    "isEmbedded" : true,
    "train" : "iPhone OS 15.7",
    "releaseType" : "User",
    "build" : "19H12"
  },
  "captureTime" : "2022-10-20 16:31:45.6185 +0300",
  "incident" : "DBF39C11-BDEE-444B-80A0-1B13BD822AE1",
  "bug_type" : "309",
  "pid" : 400,
  "procExitAbsTime" : 7337549759,
  "cpuType" : "ARM-64",
  "procName" : "UTM SE",
  "procPath" : "\/private\/var\/containers\/Bundle\/Application\/B53170BE-9577-458B-9B72-0D378113B4C1\/App.app\/UTM SE",
  "bundleInfo" : {"CFBundleShortVersionString":"4.0.8","CFBundleVersion":"67","CFBundleIdentifier":"com.utmapp.UTM-SE.2SNV3Q9Z47"},
  "storeInfo" : {"deviceIdentifierForVendor":"54D139C1-F7DC-4539-93AC-E705AE68F859","thirdParty":true},
  "parentProc" : "launchd",
  "parentPid" : 1,
  "coalitionName" : "com.utmapp.UTM-SE.2SNV3Q9Z47",
  "crashReporterKey" : "690f61c1d3f714e5ca6c8a7928d9a449dfaa1ace",
  "isCorpse" : 1,
  "exception" : {"codes":"0x0000000000000001, 0x0000000119d52208","rawCodes":[1,4728365576],"type":"EXC_BREAKPOINT","signal":"SIGTRAP"},
  "termination" : {"flags":0,"code":5,"namespace":"SIGNAL","indicator":"Trace\/BPT trap: 5","byProc":"exc handler","byPid":400},
  "faultingThread" : 11,
  "threads" : [{"id":7961,"queue":"com.apple.main-thread","frames":[{"imageOffset":5280,"symbol":"mach_msg_trap","symbolLocation":8,"imageIndex":0},{"imageOffset":6884,"symbol":"mach_msg","symbolLocation":76,"imageIndex":0},{"imageOffset":27952,"symbol":"__CFRunLoopServiceMachPort","symbolLocation":372,"imageIndex":1},{"imageOffset":45500,"symbol":"__CFRunLoopRun","symbolLocation":1180,"imageIndex":1},{"imageOffset":125896,"symbol":"CFRunLoopRunSpecific","symbolLocation":600,"imageIndex":1},{"imageOffset":4980,"symbol":"GSEventRunModal","symbolLocation":164,"imageIndex":2},{"imageOffset":5327704,"symbol":"-[UIApplication _run]","symbolLocation":1100,"imageIndex":3},{"imageOffset":2711704,"symbol":"UIApplicationMain","symbolLocation":364,"imageIndex":3},{"imageOffset":2359076,"symbol":"closure #1 in KitRendererCommon(_:)","symbolLocation":164,"imageIndex":4},{"imageOffset":1498632,"symbol":"runApp<A>(_:)","symbolLocation":252,"imageIndex":4},{"imageOffset":1372404,"symbol":"static App.main()","symbolLocation":128,"imageIndex":4},{"imageOffset":2156000,"imageIndex":5},{"imageOffset":193808,"imageIndex":5},{"imageOffset":105892,"symbol":"start","symbolLocation":520,"imageIndex":6}]},{"id":7965,"frames":[{"imageOffset":3668,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":7}]},{"id":7966,"queue":"com.utmapp.UTM.VMOperations","frames":[{"imageOffset":5364,"symbol":"semaphore_timedwait_trap","symbolLocation":8,"imageIndex":0},{"imageOffset":16456,"symbol":"_dispatch_sema4_timedwait","symbolLocation":64,"imageIndex":8},{"imageOffset":17980,"symbol":"_dispatch_semaphore_wait_slow","symbolLocation":76,"imageIndex":8},{"imageOffset":24724,"imageIndex":5},{"imageOffset":27600,"imageIndex":5},{"imageOffset":7788,"symbol":"_dispatch_call_block_and_release","symbolLocation":32,"imageIndex":8},{"imageOffset":14896,"symbol":"_dispatch_client_callout","symbolLocation":20,"imageIndex":8},{"imageOffset":45348,"symbol":"_dispatch_lane_serial_drain","symbolLocation":668,"imageIndex":8},{"imageOffset":48256,"symbol":"_dispatch_lane_invoke","symbolLocation":392,"imageIndex":8},{"imageOffset":91392,"symbol":"_dispatch_workloop_worker_thread","symbolLocation":648,"imageIndex":8},{"imageOffset":4284,"symbol":"_pthread_wqthread","symbolLocation":288,"imageIndex":7},{"imageOffset":3676,"symbol":"start_wqthread","symbolLocation":8,"imageIndex":7}]},{"id":7967,"queue":"com.apple.root.background-qos","frames":[{"imageOffset":5340,"symbol":"semaphore_wait_trap","symbolLocation":8,"imageIndex":0},{"imageOffset":16332,"symbol":"_dispatch_sema4_wait","symbolLocation":28,"imageIndex":8},{"imageOffset":18036,"symbol":"_dispatch_semaphore_wait_slow","symbolLocation":132,"imageIndex":8},{"imageOffset":46948,"imageIndex":5},{"imageOffset":7788,"symbol":"_dispatch_call_block_and_release","symbolLocation":32,"imageIndex":8},{"imageOffset":14896,"symbol":"_dispatch_client_callout","symbolLocation":20,"imageIndex":8},{"imageOffset":86656,"symbol":"_dispatch_root_queue_drain","symbolLocation":680,"imageIndex":8},{"imageOffset":88428,"symbol":"_dispatch_worker_thread2","symbolLocation":164,"imageIndex":8},{"imageOffset":4224,"symbol":"_pthread_wqthread","symbolLocation":228,"imageIndex":7},{"imageOffset":3676,"symbol":"start_wqthread","symbolLocation":8,"imageIndex":7}]},{"id":7968,"frames":[{"imageOffset":3668,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":7}]},{"id":7969,"frames":[{"imageOffset":3668,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":7}]},{"id":7971,"name":"com.apple.uikit.eventfetch-thread","frames":[{"imageOffset":5280,"symbol":"mach_msg_trap","symbolLocation":8,"imageIndex":0},{"imageOffset":6884,"symbol":"mach_msg","symbolLocation":76,"imageIndex":0},{"imageOffset":27952,"symbol":"__CFRunLoopServiceMachPort","symbolLocation":372,"imageIndex":1},{"imageOffset":45500,"symbol":"__CFRunLoopRun","symbolLocation":1180,"imageIndex":1},{"imageOffset":125896,"symbol":"CFRunLoopRunSpecific","symbolLocation":600,"imageIndex":1},{"imageOffset":103492,"symbol":"-[NSRunLoop(NSRunLoop) runMode:beforeDate:]","symbolLocation":236,"imageIndex":9},{"imageOffset":372236,"symbol":"-[NSRunLoop(NSRunLoop) runUntilDate:]","symbolLocation":92,"imageIndex":9},{"imageOffset":4779204,"symbol":"-[UIEventFetcher threadMain]","symbolLocation":524,"imageIndex":3},{"imageOffset":431132,"symbol":"__NSThread__start__","symbolLocation":808,"imageIndex":9},{"imageOffset":6572,"symbol":"_pthread_start","symbolLocation":148,"imageIndex":7},{"imageOffset":3688,"symbol":"thread_start","symbolLocation":8,"imageIndex":7}]},{"id":7989,"name":"AVAudioSession Notify Thread","frames":[{"imageOffset":5280,"symbol":"mach_msg_trap","symbolLocation":8,"imageIndex":0},{"imageOffset":6884,"symbol":"mach_msg","symbolLocation":76,"imageIndex":0},{"imageOffset":27952,"symbol":"__CFRunLoopServiceMachPort","symbolLocation":372,"imageIndex":1},{"imageOffset":45500,"symbol":"__CFRunLoopRun","symbolLocation":1180,"imageIndex":1},{"imageOffset":125896,"symbol":"CFRunLoopRunSpecific","symbolLocation":600,"imageIndex":1},{"imageOffset":28420,"symbol":"CADeprecated::GenericRunLoopThread::Entry(void*)","symbolLocation":164,"imageIndex":10},{"imageOffset":67824,"symbol":"CADeprecated::CAPThread::Entry(CADeprecated::CAPThread*)","symbolLocation":92,"imageIndex":10},{"imageOffset":6572,"symbol":"_pthread_start","symbolLocation":148,"imageIndex":7},{"imageOffset":3688,"symbol":"thread_start","symbolLocation":8,"imageIndex":7}]},{"id":8004,"name":"SPICE Main Loop","frames":[{"imageOffset":19364,"symbol":"poll","symbolLocation":8,"imageIndex":0},{"imageOffset":462456,"symbol":"g_poll","symbolLocation":40,"imageIndex":11},{"imageOffset":382992,"symbol":"g_main_context_poll","symbolLocation":104,"imageIndex":11},{"imageOffset":372232,"symbol":"g_main_context_iterate","symbolLocation":420,"imageIndex":11},{"imageOffset":374080,"symbol":"g_main_loop_run","symbolLocation":868,"imageIndex":11},{"imageOffset":2991276,"imageIndex":5},{"imageOffset":6572,"symbol":"_pthread_start","symbolLocation":148,"imageIndex":7},{"imageOffset":3688,"symbol":"thread_start","symbolLocation":8,"imageIndex":7}]},{"id":8027,"frames":[{"imageOffset":5280,"symbol":"mach_msg_trap","symbolLocation":8,"imageIndex":0},{"imageOffset":6884,"symbol":"mach_msg","symbolLocation":76,"imageIndex":0},{"imageOffset":27952,"symbol":"__CFRunLoopServiceMachPort","symbolLocation":372,"imageIndex":1},{"imageOffset":45500,"symbol":"__CFRunLoopRun","symbolLocation":1180,"imageIndex":1},{"imageOffset":125896,"symbol":"CFRunLoopRunSpecific","symbolLocation":600,"imageIndex":1},{"imageOffset":103492,"symbol":"-[NSRunLoop(NSRunLoop) runMode:beforeDate:]","symbolLocation":236,"imageIndex":9},{"imageOffset":105472,"symbol":"-[NSRunLoop(NSRunLoop) run]","symbolLocation":92,"imageIndex":9},{"imageOffset":784012,"symbol":"static DisplayLink.asyncThread(arg:)","symbolLocation":836,"imageIndex":4},{"imageOffset":774904,"symbol":"@objc static DisplayLink.asyncThread(arg:)","symbolLocation":100,"imageIndex":4},{"imageOffset":431132,"symbol":"__NSThread__start__","symbolLocation":808,"imageIndex":9},{"imageOffset":6572,"symbol":"_pthread_start","symbolLocation":148,"imageIndex":7},{"imageOffset":3688,"symbol":"thread_start","symbolLocation":8,"imageIndex":7}]},{"id":8028,"frames":[{"imageOffset":6700,"symbol":"__semwait_signal","symbolLocation":8,"imageIndex":0},{"imageOffset":20708,"symbol":"nanosleep","symbolLocation":220,"imageIndex":12},{"imageOffset":629736,"symbol":"g_usleep","symbolLocation":80,"imageIndex":11},{"imageOffset":33584492,"symbol":"call_rcu_thread","symbolLocation":116,"imageIndex":13},{"imageOffset":33552104,"symbol":"qemu_thread_start","symbolLocation":128,"imageIndex":13},{"imageOffset":6572,"symbol":"_pthread_start","symbolLocation":148,"imageIndex":7},{"imageOffset":3688,"symbol":"thread_start","symbolLocation":8,"imageIndex":7}]},{"triggered":true,"id":8029,"threadState":{"x":[{"value":5},{"value":2},{"value":2},{"value":4774526272,"symbolLocation":936,"symbol":"tcg_init_ctx"},{"value":4765199280,"symbolLocation":19848,"symbol":"all_helpers"},{"value":0},{"value":0},{"value":0},{"value":4758793665},{"value":2},{"value":4728365660},{"value":76},{"value":3},{"value":2260854796},{"value":2262953984},{"value":62},{"value":8327286144,"symbolLocation":0,"symbol":"_platform_memset"},{"value":7977749880},{"value":0},{"value":1},{"value":10788397120},{"value":10744548400},{"value":10762566560},{"value":0},{"value":4774525240,"symbolLocation":0,"symbol":"current_machine"},{"value":4774662144,"symbolLocation":24,"symbol":"qemu_pause_cond"},{"value":4765908992,"symbolLocation":0,"symbol":"bdo_queue"},{"value":0},{"value":4774662144,"symbolLocation":24,"symbol":"qemu_pause_cond"}],"flavor":"ARM_THREAD_STATE64","lr":{"value":4728364788},"cpsr":{"value":2147487744},"fp":{"value":6167243328},"sp":{"value":6167243248},"esr":{"value":4060086273,"description":"(Breakpoint) brk 1"},"pc":{"value":4728365576,"matchesCrashFrame":1},"far":{"value":4728364504}},"frames":[{"imageOffset":3580424,"symbol":"process_op_defs","symbolLocation":924,"imageIndex":13},{"imageOffset":3579636,"symbol":"process_op_defs","symbolLocation":136,"imageIndex":13},{"imageOffset":3549716,"symbol":"tcg_context_init","symbolLocation":472,"imageIndex":13},{"imageOffset":3549216,"symbol":"tcg_init","symbolLocation":32,"imageIndex":13},{"imageOffset":1192596,"symbol":"tcg_init_machine","symbolLocation":116,"imageIndex":13},{"imageOffset":3452808,"symbol":"accel_init_machine","symbolLocation":92,"imageIndex":13},{"imageOffset":1714376,"symbol":"do_configure_accelerator","symbolLocation":204,"imageIndex":13},{"imageOffset":33577596,"symbol":"qemu_opts_foreach","symbolLocation":116,"imageIndex":13},{"imageOffset":1704272,"symbol":"qemu_init","symbolLocation":12068,"imageIndex":13},{"imageOffset":140980,"imageIndex":5},{"imageOffset":6572,"symbol":"_pthread_start","symbolLocation":148,"imageIndex":7},{"imageOffset":3688,"symbol":"thread_start","symbolLocation":8,"imageIndex":7}]},{"id":8030,"frames":[{"imageOffset":189348,"symbol":"__sigwait","symbolLocation":8,"imageIndex":0},{"imageOffset":42372,"symbol":"sigwait","symbolLocation":40,"imageIndex":7},{"imageOffset":33541244,"symbol":"sigwait_compat","symbolLocation":80,"imageIndex":13},{"imageOffset":33552104,"symbol":"qemu_thread_start","symbolLocation":128,"imageIndex":13},{"imageOffset":6572,"symbol":"_pthread_start","symbolLocation":148,"imageIndex":7},{"imageOffset":3688,"symbol":"thread_start","symbolLocation":8,"imageIndex":7}]},{"id":8031,"name":"pool-spawner","frames":[{"imageOffset":7972,"symbol":"__psynch_cvwait","symbolLocation":8,"imageIndex":0},{"imageOffset":33432,"symbol":"_pthread_cond_wait","symbolLocation":1236,"imageIndex":7},{"imageOffset":869100,"symbol":"g_cond_wait","symbolLocation":52,"imageIndex":11},{"imageOffset":56568,"symbol":"g_async_queue_pop_intern_unlocked","symbolLocation":128,"imageIndex":11},{"imageOffset":56848,"symbol":"g_async_queue_pop_unlocked","symbolLocation":92,"imageIndex":11},{"imageOffset":622248,"symbol":"g_thread_pool_spawn_thread","symbolLocation":128,"imageIndex":11},{"imageOffset":620088,"symbol":"g_thread_proxy","symbolLocation":176,"imageIndex":11},{"imageOffset":6572,"symbol":"_pthread_start","symbolLocation":148,"imageIndex":7},{"imageOffset":3688,"symbol":"thread_start","symbolLocation":8,"imageIndex":7}]},{"id":8032,"name":"gmain","frames":[{"imageOffset":19364,"symbol":"poll","symbolLocation":8,"imageIndex":0},{"imageOffset":462456,"symbol":"g_poll","symbolLocation":40,"imageIndex":11},{"imageOffset":382992,"symbol":"g_main_context_poll","symbolLocation":104,"imageIndex":11},{"imageOffset":372232,"symbol":"g_main_context_iterate","symbolLocation":420,"imageIndex":11},{"imageOffset":372416,"symbol":"g_main_context_iteration","symbolLocation":92,"imageIndex":11},{"imageOffset":380860,"symbol":"glib_worker_main","symbolLocation":36,"imageIndex":11},{"imageOffset":620088,"symbol":"g_thread_proxy","symbolLocation":176,"imageIndex":11},{"imageOffset":6572,"symbol":"_pthread_start","symbolLocation":148,"imageIndex":7},{"imageOffset":3688,"symbol":"thread_start","symbolLocation":8,"imageIndex":7}]},{"id":8033,"frames":[{"imageOffset":7972,"symbol":"__psynch_cvwait","symbolLocation":8,"imageIndex":0},{"imageOffset":33432,"symbol":"_pthread_cond_wait","symbolLocation":1236,"imageIndex":7},{"imageOffset":33551004,"symbol":"qemu_sem_timedwait","symbolLocation":204,"imageIndex":13},{"imageOffset":33662416,"symbol":"worker_thread","symbolLocation":324,"imageIndex":13},{"imageOffset":33552104,"symbol":"qemu_thread_start","symbolLocation":128,"imageIndex":13},{"imageOffset":6572,"symbol":"_pthread_start","symbolLocation":148,"imageIndex":7},{"imageOffset":3688,"symbol":"thread_start","symbolLocation":8,"imageIndex":7}]}],
  "usedImages" : [
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 7369547776,
    "size" : 221184,
    "uuid" : "6a661aa2-f93f-30a3-9649-465ad95b65bc",
    "path" : "\/usr\/lib\/system\/libsystem_kernel.dylib",
    "name" : "libsystem_kernel.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6447828992,
    "size" : 4546560,
    "uuid" : "da3c2e10-0c3d-3fbc-9c3e-e950eba7020f",
    "path" : "\/System\/Library\/Frameworks\/CoreFoundation.framework\/CoreFoundation",
    "name" : "CoreFoundation"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6919217152,
    "size" : 36864,
    "uuid" : "72f2e29c-6aae-3587-adf9-614b48586e5a",
    "path" : "\/System\/Library\/PrivateFrameworks\/GraphicsServices.framework\/GraphicsServices",
    "name" : "GraphicsServices"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6486102016,
    "size" : 25812992,
    "uuid" : "2a0536ac-dc79-368a-be35-3934c48694c1",
    "path" : "\/System\/Library\/PrivateFrameworks\/UIKitCore.framework\/UIKitCore",
    "name" : "UIKitCore"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6578094080,
    "size" : 17399808,
    "uuid" : "a738ef5b-7ed9-382e-acb6-297c797ca1fd",
    "path" : "\/System\/Library\/Frameworks\/SwiftUI.framework\/SwiftUI",
    "name" : "SwiftUI"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4305928192,
    "size" : 5718016,
    "uuid" : "2c59f93d-8de3-379f-adae-2975a8f813ac",
    "path" : "\/private\/var\/containers\/Bundle\/Application\/B53170BE-9577-458B-9B72-0D378113B4C1\/App.app\/UTM SE",
    "name" : "UTM SE"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 4313759744,
    "size" : 360448,
    "uuid" : "74eac11c-b88e-3d1e-acdb-56ec661bb4c0",
    "path" : "\/usr\/lib\/dyld",
    "name" : "dyld"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 8327315456,
    "size" : 49152,
    "uuid" : "38d5598d-7dab-3247-b654-9a0225549fcd",
    "path" : "\/usr\/lib\/system\/libsystem_pthread.dylib",
    "name" : "libsystem_pthread.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6444670976,
    "size" : 286720,
    "uuid" : "2d55ad2f-6aff-303d-8e82-088ada4695b2",
    "path" : "\/usr\/lib\/system\/libdispatch.dylib",
    "name" : "libdispatch.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6472962048,
    "size" : 3190784,
    "uuid" : "5292a0bd-260c-3983-a5be-838997d362f7",
    "path" : "\/System\/Library\/Frameworks\/Foundation.framework\/Foundation",
    "name" : "Foundation"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6605307904,
    "size" : 176128,
    "uuid" : "9c17ea54-d7c9-3c59-8820-62350cd4bb61",
    "path" : "\/System\/Library\/PrivateFrameworks\/AudioSession.framework\/AudioSession",
    "name" : "AudioSession"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4332175360,
    "size" : 1654784,
    "uuid" : "9e8af8f0-8494-340b-82d0-43b0ab9d08a7",
    "path" : "\/private\/var\/containers\/Bundle\/Application\/B53170BE-9577-458B-9B72-0D378113B4C1\/App.app\/Frameworks\/glib-2.0.0.framework\/glib-2.0.0",
    "name" : "glib-2.0.0"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6634004480,
    "size" : 524288,
    "uuid" : "07b35aa1-e884-36b0-9027-55c91bacaa46",
    "path" : "\/usr\/lib\/system\/libsystem_c.dylib",
    "name" : "libsystem_c.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4724785152,
    "size" : 39026688,
    "uuid" : "e81c9795-7bf6-3a7d-ba57-707984bef59d",
    "path" : "\/private\/var\/containers\/Bundle\/Application\/B53170BE-9577-458B-9B72-0D378113B4C1\/App.app\/Frameworks\/qemu-x86_64-softmmu.framework\/qemu-x86_64-softmmu",
    "name" : "qemu-x86_64-softmmu"
  }
],
  "sharedCache" : {
  "base" : 6444351488,
  "size" : 2517696512,
  "uuid" : "aa377fed-1cb2-341a-a1c6-0ca62bd337e2"
},
  "vmSummary" : "ReadOnly portion of Libraries: Total=853.0M resident=0K(0%) swapped_out_or_unallocated=853.0M(100%)\nWritable regions: Total=622.0M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=622.0M(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nActivity Tracing                   256K        1 \nCG raster data                    1184K       24 \nColorSync                          432K       24 \nCoreAnimation                      816K       32 \nFoundation                          16K        1 \nImage IO                           256K        2 \nKernel Alloc Once                   32K        1 \nMALLOC                           606.2M      160 \nMALLOC guard page                  128K        8 \nSQLite page cache                  128K        2 \nSTACK GUARD                        256K       16 \nStack                             9168K       16 \nVM_ALLOCATE                       5344K       11 \n__AUTH                            3694K      384 \n__AUTH_CONST                      20.8M      528 \n__CTF                               756        1 \n__DATA                            25.8M      566 \n__DATA_CONST                      19.4M      536 \n__DATA_DIRTY                      2051K      438 \n__FONT_DATA                          4K        1 \n__LINKEDIT                       247.4M       46 \n__OBJC_CONST                      4604K      345 \n__OBJC_RO                         91.3M        1 \n__OBJC_RW                         3472K        1 \n__TEXT                           605.6M      585 \n__UNICODE                          592K        1 \ndyld private memory               1024K        1 \nmapped file                      161.0M       16 \nshared memory                       48K        3 \n===========                     =======  ======= \nTOTAL                              1.8G     3751 \n",
  "legacyInfo" : {
  "threadTriggered" : {

  }
},
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "6112e14f37f5d11121dcd519",
      "factorPackIds" : {
        "SIRI_TEXT_TO_SPEECH" : "634710168e8be655c1316aaa"
      },
      "deploymentId" : 240000231
    },
    {
      "rolloutId" : "607844aa04477260f58a8077",
      "factorPackIds" : {
        "SIRI_MORPHUN_ASSETS" : "6103050cbfe6dc472e1c982a"
      },
      "deploymentId" : 240000066
    }
  ],
  "experiments" : [
    {
      "treatmentId" : "8cf30c1d-2301-4048-ba76-1b7f560bb69d",
      "experimentId" : "6192fb082171a2330e561df0",
      "deploymentId" : 400000037
    }
  ]
}
}

**Debug log**

setting share directory to /private/var/mobile/Containers/Data/Application/6C3226B3-697F-4DD8-B390-F584C1030D2C/Documents/Public
2022-10-20 21:58:16.605 UTM SE[482:16973] setting share directory to /private/var/mobile/Containers/Data/Application/6C3226B3-697F-4DD8-B390-F584C1030D2C/Documents/Public
Running:  -L /private/var/containers/Bundle/Application/B53170BE-9577-458B-9B72-0D378113B4C1/App.app/qemu -S -spice unix=on,addr=/private/var/mobile/Containers/Data/Application/6C3226B3-697F-4DD8-B390-F584C1030D2C/tmp/06337800-7189-4195-8D97-55844B7E6933.spice,disable-ticketing=on,image-compression=off,playback-compression=off,streaming-video=off,gl=off -chardev spiceport,id=org.qemu.monitor.qmp,name=org.qemu.monitor.qmp.0 -mon chardev=org.qemu.monitor.qmp,mode=control -nodefaults -vga none -device e1000,mac=12:7A:BE:A9:85:35,netdev=net0 -netdev user,id=net0 -device virtio-vga -smp cpus=1,sockets=1,cores=1,threads=1 -machine q35,vmport=off,i8042=off -accel tcg,tb-size=128 -global PIIX4_PM.disable_s3=1 -global ICH9-LPC.disable_s3=1 -m 512 -device intel-hda -device hda-duplex -usb -device usb-tablet,bus=usb-bus.0 -device usb-mouse,bus=usb-bus.0 -device usb-kbd,bus=usb-bus.0 -device ide-cd,bus=ide.0,drive=drive93C9E33D-6004-4220-B7E8-ED202756E116,bootindex=0 -drive "if=none,media=cdrom,id=drive93C9E33D-6004-4220-B7E8-ED202756E116,file=/private/var/mobile/Containers/Shared/AppGroup/B0AEAB29-00B3-4621-829A-D6AD7D9940F2/File Provider Storage/Wins/en_windows_7_professional_x86_dvd.iso" -device ide-hd,bus=ide.1,drive=drive5E58E41A-9AB0-4A07-8B2A-7C257C1BF52E,bootindex=1 -drive "if=none,media=disk,id=drive5E58E41A-9AB0-4A07-8B2A-7C257C1BF52E,file=/private/var/mobile/Containers/Data/Application/6C3226B3-697F-4DD8-B390-F584C1030D2C/Documents/Windows 2.utm/Data/5E58E41A-9AB0-4A07-8B2A-7C257C1BF52E.qcow2,discard=unmap,detect-zeroes=unmap" -device virtio-serial -device virtserialport,chardev=vdagent,name=com.redhat.spice.0 -chardev spicevmc,id=vdagent,debug=0,name=vdagent -device virtserialport,chardev=charchannel1,id=channel1,name=org.spice-space.webdav.0 -chardev spiceport,name=org.spice-space.webdav.0,id=charchannel1 -name "Windows 2" -uuid 06337800-7189-4195-8D97-55844B7E6933 -rtc base=localtime -device virtio-rng-pci
Loading qemu-x86_64-softmmu.framework/qemu-x86_64-softmmu
2022-10-20 21:58:16.621 UTM SE[482:16971] Running:  -L /private/var/containers/Bundle/Application/B53170BE-9577-458B-9B72-0D378113B4C1/App.app/qemu -S -spice unix=on,addr=/private/var/mobile/Containers/Data/Application/6C3226B3-697F-4DD8-B390-F584C1030D2C/tmp/06337800-7189-4195-8D97-55844B7E6933.spice,disable-ticketing=on,image-compression=off,playback-compression=off,streaming-video=off,gl=off -chardev spiceport,id=org.qemu.monitor.qmp,name=org.qemu.monitor.qmp.0 -mon chardev=org.qemu.monitor.qmp,mode=control -nodefaults -vga none -device e1000,mac=12:7A:BE:A9:85:35,netdev=net0 -netdev user,id=net0 -device virtio-vga -smp cpus=1,sockets=1,cores=1,threads=1 -machine q35,vmport=off,i8042=off -accel tcg,tb-size=128 -global PIIX4_PM.disable_s3=1 -global ICH9-LPC.disable_s3=1 -m 512 -device intel-hda -device hda-duplex -usb -device usb-tablet,bus=usb-bus.0 -device usb-mouse,bus=usb-bus.0 -device usb-kbd,bus=usb-bus.0 -device ide-cd,bus=ide.0,drive=drive93C9E33D-6004-4220-B7E8-ED202756E116,bootindex=0 -drive "if=none,media=cdrom,id=drive93C9E33D-6004-4220-B7E8-ED202756E116,file=/private/var/mobile/Containers/Shared/AppGroup/B0AEAB29-00B3-4621-829A-D6AD7D9940F2/File Provider Storage/Wins/en_windows_7_professional_x86_dvd.iso" -device ide-hd,bus=ide.1,drive=drive5E58E41A-9AB0-4A07-8B2A-7C257C1BF52E,bootindex=1 -drive "if=none,media=disk,id=drive5E58E41A-9AB0-4A07-8B2A-7C257C1BF52E,file=/private/var/mobile/Containers/Data/Application/6C3226B3-697F-4DD8-B390-F584C1030D2C/Documents/Windows 2.utm/Data/5E58E41A-9AB0-4A07-8B2A-7C257C1BF52E.qcow2,discard=unmap,detect-zeroes=unmap" -device virtio-serial -device virtserialport,chardev=vdagent,name=com.redhat.spice.0 -chardev spicevmc,id=vdagent,debug=0,name=vdagent -device virtserialport,chardev=charchannel1,id=channel1,name=org.spice-space.webdav.0 -chardev spiceport,name=org.spice-space.webdav.0,id=charchannel1 -name "Windows 2" -uuid 06337800-7189-4195-8D97-55844B7E6933 -rtc base=localtime -device virtio-rng-pci
2022-10-20 21:58:16.621 UTM SE[482:16971] Loading qemu-x86_64-softmmu.framework/qemu-x86_64-softmmu

**Upload VM**
[Windows 2.zip](https://github.com/utmapp/UTM/files/9833293/Windows.2.zip)

**Comment by osy** [comment] 2022-10-20 23:59
Duplicate of #4516

**Closed by osy** 2022-10-20 23:59 UTC
