### ISSUE TITLE
Pause feature not working (Failed to save VM state)

### ISSUE THREAD

**Issue by pawelwiejkut** [utmapp/UTM#3303] opened 2021-11-10 06:52 UTC
**Describe the issue**
When I try to pause the VM I get the following message:

Failed to save VM state. Do you have at
least one read-write drive attached that
supports snapshots?

<img width="310" alt="Screenshot 2021-11-10 at 07 48 35" src="https://user-images.githubusercontent.com/11619019/141064091-e41bbed1-66ee-4bf0-ad8b-435091515dce.png">

Is there any way to enable this support ? I was trying to add a new disk but without success. Thank you very much for your help.

**Configuration**
* UTM Version 2.4.1 (40)
* OS Version: 12.0.1 
* Apple Silicon?

**Crash log**
N/A

**Debug log**
N/A

**Upload VM**
N/A

**Comment by conath** [comment] 2021-11-11 10:43
Please provide debug log.

**Comment by pawelwiejkut** [comment] 2021-11-11 21:37
Hello,
Debug log attached. Thank you for the instructions.
[debug.log](https://github.com/utmapp/UTM/files/7523392/debug.log)

**Comment by conath** [comment] 2021-11-12 15:23
Thank you for the log. As there is no error related to drives in the log I assume we have a UTM bug here.

I can see that you have a VM with EFI boot enabled. I believe this might be causing the problem, and it should be possible to work around it. I would suggest you convert both the .fd files mentioned in the log to QCOW2 and import them into the VM. The edk2 file should be set to BIOS and the vars file set to disk image/pflash. 

I will test this myself later and upload the files here with screenshots (if it works).

Another note: about the log you provided: you are requesting lots of CPU features to be emulated that are not (currently) supported by the backend (QEMU TCG). Maybe it is possible to filter the list of CPU flags by what the emulator supports. I’ve created #3309 to track this idea.

**Comment by pawelwiejkut** [comment] 2021-11-12 15:35
Thank you for the support and quick response. I will check the idea with converting and flags in the upcoming days and let you know.

Just want to mention that I really appreciate what you are doing for this project. Thanks to UTM I'm able to run SAP docker container which uses 32 GB RAM / 7 CPUs and it is working usable - without UTM it will be not possible so easily. I'm very impressed.

**Comment by toblerone567** [comment] 2021-11-13 21:43
Hey @pawelwiejkut is it working for you?

**Comment by pawelwiejkut** [comment] 2021-11-13 21:45
Hi @toblerone567 for now I just removed the unsupported flags and I'm checking the possibility of switch to BIOS.

**Comment by pawelwiejkut** [comment] 2021-11-14 13:12
Hello,
Because I'm using the original machine for my work, I have created a new one - based on BIOS. I have installed the same operating system ( ubuntu-20.04.3-live-server-amd64.iso ), wait until the system fully boots, and try to suspend - unfortunately without success.

New logs:
[debug.log](https://github.com/utmapp/UTM/files/7533695/debug.log)

Desktop record:
https://media.giphy.com/media/FqudsHbUpduiVecEI6/giphy.gif

**Comment by conath** [comment] 2021-11-14 13:35
I've verified this problem with UTM version 2.4.1 (40). Steps to reproduce:

1. Create a new VM from scratch
2. Save
3. Click Play
4. Click Pause

Expected result: VM execution is paused and suspended to disk, so I can close the window and reopen it later to resume my work.

Actual result: Error "Failed to save VM state. Do you have at least one read-write drive attached that supports snapshots?". I can close the error and the VM is paused (UI shows play button, VM does not keep running behind the blurred background). However if I try to close the VM, I get the warning "Closing this window will kill the VM." and it indeed shuts down the VM when I click OK. 

The error does not go away if I add a hard drive to the VM, nor if I disable EFI boot and delete the EFI variables drive.
Example .utm is attached: 
[TestMachine.utm.zip](https://github.com/utmapp/UTM/files/7533821/TestMachine.utm.zip)

**Comment by donaciano** [comment] 2021-11-14 14:27
I've had these issues as well. From the Gallery none have suspended for me with 2.4.0 and with 2.4.1 as well.  Tested: Mac OS 9.2.1, Sun Solaris 9, ReactOS. These seem to be qcow2 images and fit the criteria for suspend to work my assumption is that gallery images work properly and should suspend (if not virtualized).  FYI M1 MacBook Pro macOS Monterey 12.0.1.

**Comment by blahdy** [comment] 2021-11-30 22:43
On a mac x86 I get have the pause button greyed out, on my iPhone I get the message from the initial post. This is the same on xp/7/8.1 on both platforms.

The reason I tried all 3 of them is because xp and 7 don't have a working share folder (the service doesn't start) and have a code 10 error on the virtio serial device. 8.1 was ok, but considering the speed of xs max emulating 8.1 - resuming is a must have.

Would be glad if someone could advise at least a temporary solution.

p.s.
(efi/legacy has no effect)

**Comment by conath** [comment] 2021-12-02 01:47
@blahdy Re: greyed out pause button: sorry, no known workarounds are available. When running a guest with the same architecture as the host, UTM relies on the QEMU for Mac integration with Apple Hypervisor, and the former lacks the pause feature. (@agraf I am not entirely sure, is this correct?)

**Comment by agraf** [comment] 2021-12-02 06:02
Earlier versions of the HVF enablement did not support snapshotting/migration, but hopefully the one that landed in upstream QEMU did. Would you mind to verify if that one works? And if not, what breaks?

**Comment by osy** [comment] 2021-12-03 23:13
FYI the current QEMU uses the "earlier" version. We will be updating to QEMU 6.2.0 soon which should pick up the latest patches.

**Comment by adespoton** [comment] 2022-01-22 03:39
Just so you're all aware: the qemu-system-ppc used in UTM is built against Mark Cave-Ayland's Screamer sources.  These have not been integrated into QEMU main branch because of issues with saving state with the screamer code implemented.  So if you're using a PowerPC guest, snapshotting will not work.  A possible workaround would be to use a different qemu-system-ppc and firmware if the Screamer audio isn't enabled in the prefs -- state saving should work fine on vanilla qemu-system-ppc.

It appears that sometime suring the 3.0.x betas, someone fixed something in the UI so that when you pause it doesn't even attempt to save state on qemu-system-ppc.  This is useful as a short-term fix.

Another thing to note is that state saving only works on UNCOMPRESSED QCow2 files.  It might be worthwhile for UTM to check to see if the compressed flag is set on an image, and even provide feedback during saving after editing a config that if all images aren't uncompressed qcow2, a warning will be presented to the user that state saving is disabled for this guest, and the guest will act like qemu-system-ppc currently does, pausing but not saving state.

**Comment by osy** [comment] 2022-01-22 04:30
> It appears that sometime during the 3.0.x betas, someone fixed something in the UI so that when you pause it doesn't even attempt to save state on qemu-system-ppc. This is useful as a short-term fix.

Actually you caught a bug where the save function was just broken for every VM. https://github.com/utmapp/UTM/commit/e9fabfb09e9c2f8b6b1aedd7c10aeb2fcea538e6

**Comment by adespoton** [comment] 2022-02-18 23:56
I may have caught another bug in 3.1b: clicking pause now appears to disconnect from the QEMU process, but not successfully save state in x86_64 guests.  Process is left running, and the image becomes corrupted so it no longer boots.

For reference, I just spent 3 days installing and upgrading macOS 11, clicked pause, and it would not resume.  Killing it after waiting 3 hours resulted in an unbootable image.

**Comment by osy** [comment] 2022-02-28 01:37
There seems to be a lot of different things in this issue which may or may not be fixed. I will close this and track the more specific error in #3698

**Closed by osy** 2022-02-28 01:37 UTC
Labels: bug, qemu
