### ISSUE TITLE
Black Screen after Installation and Reboot 

### ISSUE THREAD

**Issue by schummd** [utmapp/UTM#4967] opened 2023-01-24 23:40 UTC
**Describe the issue**  
I have installed Kali arm64 and followed installation guide using Serial settings. After installation completed and reboot it returns to the main installation window. After shutting down the VM and clearing CD/DVD option, I tried running Kali again. This time (with Serial) I can access only terminal window. When I remove Serial from the settings, I can only see the black screen. 

<img width="600" alt="Screen Shot 2023-01-25 at 10 30 39 am" src="https://user-images.githubusercontent.com/44360306/214445187-88aaea96-8415-4b97-8b12-b73c76b83f91.png">

<img width="600" alt="Screen Shot 2023-01-25 at 10 31 23 am" src="https://user-images.githubusercontent.com/44360306/214445201-fb5ee962-d5dc-4e63-a3f1-d2cd156545b9.png">

<img width="600" alt="Screen Shot 2023-01-25 at 10 31 40 am" src="https://user-images.githubusercontent.com/44360306/214445229-860c182a-6d40-4108-a58e-c93e435f416f.png">

**Configuration**  
* UTM Version: 4.1.5 (74)
* macOS Version: 11.7
* Mac Chip (Intel, M1, ...): M1

**Upload VM**  
config.plist file is attached to the issue. 
[config.plist.zip](https://github.com/utmapp/UTM/files/10494808/config.plist.zip)

**Comment by wing-cheng** [comment] 2023-02-05 04:44
I have encountered the same issue as u. 

Here is another issue I encountered.
During installation, I also chose to install Gnome and chose gdm3 as the display manager.
Login screen was shown and I was able to get to the desktop screen. But when I launched the terminal from the menu, it won't show. I also tried launch wireshark and quit, the wireshark window won't go.

**Comment by ktprograms** [comment] 2023-02-05 08:03
Seems like the mesa issue: #4983

**Comment by wing-cheng** [comment] 2023-02-06 12:20
> Seems like the mesa issue: #4983

that solves the problem, thank u so much!

**Comment by osy** [comment] 2023-02-26 04:37
Duplicate of #4983

**Closed by osy** 2023-02-26 04:37 UTC
