### ISSUE TITLE
Shared Directory setting is not persistent after restarting the UTM app

### ISSUE THREAD

**Issue by sasaleese** [utmapp/UTM#5583] opened 2023-08-21 07:02 UTC
(app: UTM
host: M1 MacBook Pro, macOS Ventura
guest: ArchLinux ARM)

1. If I configure folder sharing from the host machine to the guest as a VirtFS Shared Directory (under Edit selected VM -> Sharing) then the shared folder gets correctly mounted under /mnt/share after I start up my VM.

2. However if I close the UTM app and reopen it again my shared folder now won't mount at all under my guest OS.

3. If I reconfigure folder sharing by manually selecting the Shared Directory again, my shared folder gets mounted again as expected after starting up the VM.

Seems like UTM "forgets" Shared Directory setting when I close the UTM app.

By using Export QEMU Command... I can verify that behaviour.

If I compare the exported qemu commands, the `-fsdev local,id=virtfs0,path=/Users/jobs/Downloads/SHARED,security_model=mapped-xattr -device virtio-9p-pci,fsdev=virtfs0,mount_tag=share` part is missing from it after restarting UTM.

1. QEMU command after adding the Shared Directory:
```
qemu-system-aarch64 -L /Applications/UTM.app/Contents/Resources/qemu -S -spice unix=on,addr=2F2C4095-EC5B-49CD-A654-FE17D7EC7CAA.spice,disable-ticketing=on,image-compression=off,playback-compression=off,streaming-video=off,gl=off -chardev spiceport,id=org.qemu.monitor.qmp,name=org.qemu.monitor.qmp.0 -mon chardev=org.qemu.monitor.qmp,mode=control -nodefaults -vga none -device virtio-net-pci,mac=16:7C:DF:F1:FC:DE,netdev=net0 -netdev vmnet-bridged,id=net0,ifname=en0 -nographic -cpu host -smp cpus=4,sockets=1,cores=4,threads=1 -machine virt -accel hvf -drive if=pflash,format=raw,unit=0,file=/Applications/UTM.app/Contents/Resources/qemu/edk2-aarch64-code.fd,readonly=on -drive "if=pflash,unit=1,file=/Users/jobs/Library/Containers/com.utmapp.UTM/Data/Documents/ArchLinux ARM.utm/Data/efi_vars.fd" -m 3072 -device nec-usb-xhci,id=usb-bus -device usb-tablet,bus=usb-bus.0 -device usb-mouse,bus=usb-bus.0 -device usb-kbd,bus=usb-bus.0 -device qemu-xhci,id=usb-controller-0 -chardev spicevmc,name=usbredir,id=usbredirchardev0 -device usb-redir,chardev=usbredirchardev0,id=usbredirdev0,bus=usb-controller-0.0 -chardev spicevmc,name=usbredir,id=usbredirchardev1 -device usb-redir,chardev=usbredirchardev1,id=usbredirdev1,bus=usb-controller-0.0 -chardev spicevmc,name=usbredir,id=usbredirchardev2 -device usb-redir,chardev=usbredirchardev2,id=usbredirdev2,bus=usb-controller-0.0 -device virtio-blk-pci,drive=driveBB208CBD-BFB4-4895-9542-48527C9E5473,bootindex=0 -drive "if=none,media=disk,id=driveBB208CBD-BFB4-4895-9542-48527C9E5473,file=/Users/jobs/Library/Containers/com.utmapp.UTM/Data/Documents/ArchLinux ARM.utm/Data/BB208CBD-BFB4-4895-9542-48527C9E5473.qcow2,discard=unmap,detect-zeroes=unmap" -device virtio-serial -device virtserialport,chardev=org.qemu.guest_agent,name=org.qemu.guest_agent.0 -chardev spiceport,id=org.qemu.guest_agent,name=org.qemu.guest_agent.0 -device virtserialport,chardev=vdagent,name=com.redhat.spice.0 -chardev spicevmc,id=vdagent,debug=0,name=vdagent -fsdev local,id=virtfs0,path=/Users/jobs/Downloads/SHARED,security_model=mapped-xattr -device virtio-9p-pci,fsdev=virtfs0,mount_tag=share -name "ArchLinux ARM" -uuid 2F2C4095-EC5B-49CD-A654-FE17D7EC7CAA -device virtio-rng-pci
```

2. QEMU command after restarting UTM app:
```
qemu-system-aarch64 -L /Applications/UTM.app/Contents/Resources/qemu -S -spice unix=on,addr=2F2C4095-EC5B-49CD-A654-FE17D7EC7CAA.spice,disable-ticketing=on,image-compression=off,playback-compression=off,streaming-video=off,gl=off -chardev spiceport,id=org.qemu.monitor.qmp,name=org.qemu.monitor.qmp.0 -mon chardev=org.qemu.monitor.qmp,mode=control -nodefaults -vga none -device virtio-net-pci,mac=16:7C:DF:F1:FC:DE,netdev=net0 -netdev vmnet-bridged,id=net0,ifname=en0 -nographic -cpu host -smp cpus=4,sockets=1,cores=4,threads=1 -machine virt -accel hvf -drive if=pflash,format=raw,unit=0,file=/Applications/UTM.app/Contents/Resources/qemu/edk2-aarch64-code.fd,readonly=on -drive "if=pflash,unit=1,file=/Users/jobs/Library/Containers/com.utmapp.UTM/Data/Documents/ArchLinux ARM.utm/Data/efi_vars.fd" -m 3072 -device nec-usb-xhci,id=usb-bus -device usb-tablet,bus=usb-bus.0 -device usb-mouse,bus=usb-bus.0 -device usb-kbd,bus=usb-bus.0 -device qemu-xhci,id=usb-controller-0 -chardev spicevmc,name=usbredir,id=usbredirchardev0 -device usb-redir,chardev=usbredirchardev0,id=usbredirdev0,bus=usb-controller-0.0 -chardev spicevmc,name=usbredir,id=usbredirchardev1 -device usb-redir,chardev=usbredirchardev1,id=usbredirdev1,bus=usb-controller-0.0 -chardev spicevmc,name=usbredir,id=usbredirchardev2 -device usb-redir,chardev=usbredirchardev2,id=usbredirdev2,bus=usb-controller-0.0 -device virtio-blk-pci,drive=driveBB208CBD-BFB4-4895-9542-48527C9E5473,bootindex=0 -drive "if=none,media=disk,id=driveBB208CBD-BFB4-4895-9542-48527C9E5473,file=/Users/jobs/Library/Containers/com.utmapp.UTM/Data/Documents/ArchLinux ARM.utm/Data/BB208CBD-BFB4-4895-9542-48527C9E5473.qcow2,discard=unmap,detect-zeroes=unmap" -device virtio-serial -device virtserialport,chardev=org.qemu.guest_agent,name=org.qemu.guest_agent.0 -chardev spiceport,id=org.qemu.guest_agent,name=org.qemu.guest_agent.0 -device virtserialport,chardev=vdagent,name=com.redhat.spice.0 -chardev spicevmc,id=vdagent,debug=0,name=vdagent -name "ArchLinux ARM" -uuid 2F2C4095-EC5B-49CD-A654-FE17D7EC7CAA -device virtio-rng-pci
```

**Comment by nabiltntn** [comment] 2023-08-22 21:06
Duplicate of https://github.com/utmapp/UTM/issues/5531 and already fixed here https://github.com/utmapp/UTM/commit/40187dc4f12ea6b162276fee48feff21b340f5d4

**Comment by osy** [comment] 2023-09-02 04:23
Duplicate of #5531

**Closed by osy** 2023-09-02 04:23 UTC
