### ISSUE TITLE
Ubuntu 20.04 Display freezes after 10 minutes

### ISSUE THREAD

**Issue by martinerk0** [utmapp/UTM#6434] opened 2024-06-18 15:04 UTC
**Describe the issue**  
20.04 Freeze Display after some time ~ 5-30min

**Configuration**  
* UTM Version: Version 4.5.3 (99)
* macOS Version: 14.5
* Mac Chip (Intel, M1, ...): M3

**Crash log**  

**Debug log**  
[debug2.log](https://github.com/user-attachments/files/15888542/debug2.log)

The SSH & serial works, just display freezes. I tried multipe QEMU versions and display cards.

**Comment by brad-x** [comment] 2024-07-03 13:58
This could be power management, I suggest testing by setting display sleep and system sleep on idle to 'never' temporarily - this will depend on the desktop environment you're using (if the default GNOME this is under Settings -> Power)

**Comment by osy** [comment] 2024-12-19 18:58
Duplicate of #5205

**Closed as not planned by osy** 2024-12-19 18:58 UTC

**Comment by CrawX** [comment] 2025-01-22 06:56
Not digging up an old thread but I just wanted to mention that the advice by @brad-x helped with a possibly unrelated issue where UTM was freezing after a few minutes in the background while the VM was still available via ssh. Thanks!
