### ISSUE TITLE
Mouse offset incorrectly Windows 10 for ARM after display resolution changes

### ISSUE THREAD

**Issue by tkreind** [utmapp/UTM#2471] opened 2021-04-26 21:41 UTC
**Describe the issue**
When using a fresh Windows 10 for ARM install and following the gallery instructions the instructions to enable the high resolution display break my virtual machine permanently and need to be fixed, or have the instructions changed, ASAP as any use who follows them will brick their VM. After changing to display 2 with the spice tools installed the mouse stays on the other screen like it says, but this issue persists after restarts. The mouse is always offset about an inch or two incorrectly. If one changes the VM window screen dimensions this issue exacerbates. I tried changing the display dimensions in Windows 10 to see if one was better but they're all equally bad. When trying to change back to "Only on display 2" settings crashes and the change doesn't propagate. Since this seems to be irreversible it might as well be bricking the container.

I've tried mitigating it by capturing the mouse before changing the screen to screen 1. This seems to work, but once the mouse un-captures once it starts flickering in and out and being invisible on the screen. Additionally it's possible to move the mouse off screen, presumably to the other monitor. Either way, only supporting the mouse in capture mode is not a long term solution and significantly impacts usability. I'm not entirely sure what the issue is but it, or the gallery documentation, needs to be fixed ASAP or users won't be able to use Windows 10 virtual machines.

**Configuration**
* UTM Version: 2.0.25 
* OS Version: Big Sur 11.2.3
* Apple Silicon

**Upload VM**
Fresh install of Windows 10 for ARM (21354) after following all but the display enhancing directions. Converted VHDX to qcow2 from a fresh image before install and ran the virtual machine solely on the qcow2 image.

The config.plist doesn't change during the display change, it is this same file before and after.

I can prepare a VM with no personal information if required, but it should be pretty easy to reproduce and I don't wanna risk licensing of uploading a Windows 10 VM.

Attatched as txt since plist isn't allowed.
[config.txt](https://github.com/utmapp/UTM/files/6380198/config.txt)

**Comment by tkreind** [comment] 2021-04-26 21:48
Also tried changing display output to virtio-gpu-pci, didn't work as expected.

**Comment by iRonJ** [comment] 2021-05-23 00:24
I noticed this too. It works if you capture mouse but you lose scroll wheel and the tracking is off.

**Comment by conath** [comment] 2021-07-18 12:58
This issue persists with UTM 2.1.2 using Windows 10 x86_64 guest on M1 host, virtio-gpu-pci virtual graphics adapter.

I can work around the issue by capturing the cursor. However, this is inconvenient.

**Comment by gaurav21r** [comment] 2021-07-27 04:27
Do not change the resolution as given in the Instructions, instead use a Custom BIOS to get the default Mac Resolution by following the steps given in #2628 This is, of course, a workaround till the issue gets fixed.

@conath You could probably close this issue and a few others and all of us can carry forward the discussion at #2628 ?

**Comment by conath** [comment] 2021-07-27 07:13
Thanks for the heads up. Duplicate of #2628

**Closed by conath** 2021-07-27 07:13 UTC
Labels: bug, interface
