### ISSUE TITLE
USB not being detected

### ISSUE THREAD

**Issue by SmartBoy84** [utmapp/UTM#3986] opened 2022-05-05 10:24 UTC
`Latest version of UTM (3.2.1) - Unc0ver - Fugu14 - 14.4.1 - iPhone SE 2`
USB devices don't show up in the latest build of UTM despite them (storage devices at least) showing up in the files app. I'm using the official Apple adapter and have tried rebooting.
I haven't tested on 3.1, I updated to this version because I was advised by osy as it may fix the LibUSB errors I was having on that version.

**Comment by SmartBoy84** [comment] 2022-05-05 10:25
Duplicate of #3975 I believe, feel free to close this.

**Comment by osy** [comment] 2022-05-06 01:56
On iOS, anything that you would see in Files will not be supported because the OS hijacks the device as soon as it's detected.

**Comment by SmartBoy84** [comment] 2022-05-06 05:06
> On iOS, anything that you would see in Files will not be supported because the OS hijacks the device as soon as it's detected.

So USB devices aren't supported? They certainly worked in 3.1.5 despite them coming up in the files app/filza. Upon "binding" them to the VM however, they were disconnected @osy

**Comment by osy** [comment] 2022-05-06 05:26
I see then it probably is the same issue as #3975

**Comment by conath** [comment] 2022-05-09 20:28
FWIW I have gotten a USB DVD drive to work in a JB iPhone with UTM. Of course, I had to run it through a powered USB hub to make it work.

**Comment by SmartBoy84** [comment] 2022-05-12 01:30
That makes sense, but I can’t seem to run anything without an external USB dock (even if it’s not externally powered)

**Comment by osy** [comment] 2022-05-20 16:01
Can confirm this is a duplicate of #3975

**Closed by osy** 2022-05-20 16:01 UTC
