### ISSUE TITLE
Raspberry Pi 2/3 (and other systems?) unusable

### ISSUE THREAD

**Issue by XDUser** [utmapp/UTM#281] opened 2020-04-17 15:17 UTC
**Describe the bug**
Trying to start a Raspberry Pi 2/3 VM results in the error “QEMU exited from an error: qemu: -device usb-ehci: No ‘PCI’ bus found for device ‘usb-ehci’”

**To Reproduce**
1. Make a new VM
2. Set to 4 cores
3. Change Architecture to “ARM64 (aarch64)”
4. Change System to “Raspberry Pi 2” or “Raspberry Pi 3”
5. Disable Network
6. Disable Audio
7. Try to start the VM

**Crash log**
N/A

**Debug log**
Enabling this option causes UTM to crash right after clicking the VM to start it.

**Upload VM**
[Test.zip](https://github.com/utmapp/UTM/files/4493723/Test.zip)

**Comment by jankais3r** [comment] 2020-04-17 16:18
This is not a bug in UTM, you have to supply your own kernel image when running aarch64 platform in QEMU. It's quite involved process compared to other architectures, but you can find steps how to do that if you search the Discord channel.

**Comment by TBAALi-ros** [comment] 2020-04-17 16:21
ok TBAALi 邮箱：jiaxx903@tom.com 签名由 网易邮箱大师 定制 On 04/18/2020 00:19, Jan Kaiser wrote: This is not a bug in UTM, you have to supply your own kernel image when running aarch64 platform in QEMU. It's quite involved process compared to other architectures, but you can find steps how to do that if you search the Discord channel. — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by osy86** [comment] 2020-04-17 17:20
For that error you need legacy input mode.

**Comment by zwerdna** [comment] 2020-04-18 22:31
Well, actually you can get by with just UEFI BIOS image of ed2k. (I mean, without kernel image).
That worked for me with Fedora and Alpine images.

**Comment by zwerdna** [comment] 2020-04-18 22:31
With that, “virt” machine works.

**Comment by XDUser** [comment] 2020-04-20 10:04
> Well, actually you can get by with just UEFI BIOS image of ed2k. (I mean, without kernel image).
> That worked for me with Fedora and Alpine images.

I assume you mean EDK II because that’s what comes IP when searching ed2k and it looks like what you are talking about. Do you have a link for this? I can’t find a compiled version.

**Comment by zwerdna** [comment] 2020-04-20 10:13
> > Well, actually you can get by with just UEFI BIOS image of ed2k. (I mean, without kernel image).
> > That worked for me with Fedora and Alpine images.
> 
> I assume you mean EDK II because that’s what comes up when searching ed2k and it looks like what you are talking about. Do you have a link for this? I can’t find a compiled version.

True about EDK II. Actually, can't find the link to that one. I could have extracted it from Linux package. Anyway, try this one: https://releases.linaro.org/components/kernel/uefi-linaro/latest/release/qemu64/QEMU_EFI.fd.

**Comment by zwerdna** [comment] 2020-04-20 10:15
> Anyway, try this one: https://releases.linaro.org/components/kernel/uefi-linaro/latest/release/qemu64/QEMU_EFI.fd.

I thin I had success with that too.

**Comment by brunocastello** [comment] 2020-04-21 02:56
How you can use these downloaded kernel images with UTM? I see no field in cfg screens to reference them.

**Comment by zwerdna** [comment] 2020-04-22 15:39
AH, well, sorry for delay. You can use either image as 'BIOS'.

**Comment by brunocastello** [comment] 2020-04-23 00:06
> Ah, well, sorry for delay. You can use either image as 'BIOS' drive.

I understood that point, but... how?

**Comment by jankais3r** [comment] 2020-04-23 09:39
When importing an image in UTM, you can specify which type of image it is.
![5EC6B736-A6AB-4287-9DD8-D938DDE7DA15](https://user-images.githubusercontent.com/2159464/80084233-e7271000-8556-11ea-9a3e-337e88bfe51d.png)

**Comment by zaptrem** [comment] 2020-04-27 06:01
Do you have an X86_64 version of this UEFI file? I haven't been able to find one yet.

**Comment by osy86** [comment] 2020-05-08 22:16
Closing since this is not a bug

**Closed by osy86** 2020-05-08 22:16 UTC
Labels: question
