### ISSUE TITLE
UTM crashed when showing all CPU flags

### ISSUE THREAD

**Issue by LostInCompilation** [utmapp/UTM#6512] opened 2024-07-24 02:39 UTC
**Describe the issue**  
This is the second sporadic crash I experienced two times now over a few weeks. It happens when I click on "Show All..." under *VM settings->System->Cpu flags*. It's not specific to a single VM.
No USB devices were plugged in or out.

**Configuration**  
* UTM Version: 4.5.3 (99)
* macOS Version: 14.5.1
* Mac Chip: M1 Pro

**Crash log**  
[View crashlog on Pastebin](https://pastebin.com/NWEiwHVq)

**Comment by osy** [comment] 2024-08-22 15:06
Duplicate of #6511

**Closed by osy** 2024-08-22 15:06 UTC
