### ISSUE TITLE
Windows 11 installer can’t connect to the internet

### ISSUE THREAD

**Issue by ghost** [utmapp/UTM#3857] opened 2022-03-31 18:11 UTC
UTM v1.5
i was tried so many time and i struck there only like in network connection part while setup the windows 11 os in mac m1 chip there snapshot will uploaded in nelow please resolve this issue bec i can not go further steps
![WhatsApp Image 2022-03-31 at 6 37 24 PM](https://user-images.githubusercontent.com/102758443/161121953-467dc912-b332-437b-bb61-be33390e652e.jpeg)

**Comment by freebrowser1** [comment] 2022-04-01 09:50
The problem is that a Windows VM in UTM/QEMU does not have network drivers installed as long as Spice tools is not installed.
Download these https://github.com/utmapp/qemu/releases/download/v6.2.0-utm/spice-guest-tools-0.164.3.iso and make a virtual CD ROM (removable drive) from it.

Try these for installing Win11:

https://winaero.com/how-to-install-windows-11-without-an-internet-connection/
https://4sysops.com/archives/how-to-set-up-windows-11-home-with-an-offline-account/

I tried and had success, it installed. 
After installing offline, go to D: and install Spice tools and reboot the VM and then you have Win11 with internet connection and if you specified a shared folder of the host PC, it will be visible in drive Z:\.

**Comment by conath** [comment] 2022-04-05 22:31
Duplicate of #3865

**Closed by conath** 2022-04-05 22:31 UTC
