### ISSUE TITLE
Option to boot from usb

### ISSUE THREAD

**Issue by SarKaa** [utmapp/UTM#400] opened 2020-06-26 09:18 UTC
So I have a bootable hackintosh on a usb, but I want to be able to run it on my phone. Is it possible to use a usb drive instead of a virtual disk, because then it would take up less space and let me run it without having to turn the usb into an img file and have to move it to my phone. I know this is hard, but I have seen some apps do it on windows with qemu.

**Comment by obbcth** [comment] 2020-06-26 12:38
Duplicate of #46

**Closed** 2020-06-26 16:38 UTC
