### ISSUE TITLE
UTM freezes after closing VM and relaunching it

### ISSUE THREAD

**Issue by obbcth** [utmapp/UTM#171] opened 2020-03-24 05:03 UTC
https://vimeo.com/400131944
(Video link)

After closing VM, pressing X button works fine.
But relaunching VM freezes UTM and shows white screen.

iOS 13.3, unc0ver 4.3.1 jailbroken.

**Comment by osy86** [comment] 2020-03-24 18:15
Duplicate of #148

**Closed by osy86** 2020-03-24 18:15 UTC
Labels: duplicate
