### ISSUE TITLE
Can’t Ping (ICMP Echo), but can browse the internet.

### ISSUE THREAD

**Issue by TyrD** [utmapp/UTM#5035] opened 2023-02-17 14:49 UTC
Hello,

I got some problems with the network connection in my VMs, I’m able browse the internet (e.g. www.google.com) but I’m not able to ping e.g. www.google.com. First I thought Linux is blocking ICMP but I can’t find any blocking rules.
I can ping the VM from my MacOS Host. 
Trying this with active and inactive firewall gives the same results.

Configurations:
- UTM Version: 4.1.5
- MacOS: Ventura 13.2
- Chip: M1 Max
- VM: Debian (Qemu, ARM64)
- VM: Kali Linux (AppleVirtualization, ARM64)
- Network: Shared Network

What did I try (in the VM):
- start wireshark
- ping www.google.com -> 100% packet loss
- nslookup -> I got an ip4 address for www.google.com
- traceroute -> I got the route to www.google.com 
- traceroute -I -> Can’t find any hop (-I -> set to ICMP)
- tested everything with sudo -> no changes
- tested everything with ipv4 and ipv6 instead of Name
- sudo iptables -L -> no rules in iptables
- cat /etc/sysctl.conf -> no ICMP blocking rules here
- cat /proc/sys/net/ipv4/icmp_echo_ignore_all -> 0 
- I added rules in iptables (Input, forward, output) and sysctl to enable ICMP (Input, forward, output) -> no changes
- Removed the rules in iptables and sysctl -> no changes
- ping from VM to MacOS Host -> 100% packet loss
- nping www.google.com -> with TCP in nping everything works
- I can see the arp (request and response), ping request and other protocols (UDP, TCP, ...) in Wireshark but no ping response

Seems something blocks the incoming ICMP Ping traffic.

Thanks for helping out.

**Comment by Pesthuf** [comment] 2023-02-19 20:57
This seems to be an expected issue; It's mentioned [here](https://docs.getutm.app/guides/windows/#ping-does-not-work) for the Windows install guide.

**Comment by osy** [comment] 2023-02-26 04:12
Duplicate of #351

**Closed** 2023-02-26 04:12 UTC
