### ISSUE TITLE
is it real to use bridged network?

### ISSUE THREAD

**Issue by progreccor** [utmapp/UTM#2615] opened 2021-06-14 19:29 UTC
I can port forward to guest virtual machine but on VMware I can use bridged network where virtual machine gets its own IP address.
Can I get something similar on UTM?

**Comment by wancom** [comment] 2021-06-16 08:48
It looks similar to #358.

**Comment by conath** [comment] 2021-06-24 10:00
Duplicate of #358

**Closed by conath** 2021-06-24 10:00 UTC
Labels: enhancement
