### ISSUE TITLE
Firefox *always* crashes in emulated x86-64 Ubuntu VM on M1 Mac

### ISSUE THREAD

**Issue by freebrowser1** [utmapp/UTM#6459] opened 2024-07-06 11:03 UTC
**Describe the issue**  
Running Firefox (122 or later, including 127) in Ubuntu results in a crash of Firefox. Sometimes it loads shortly and sometimes it crashes immediately.
Other browsers (Brave or Vivaldi x86-64 version) do run normally.

I had the issue in Ubuntu 22.04LTS and I installed a fresh 24.04LTS, in both it is reproducible.

Strange that *all* apps work normally except Firefox, so it should be a combination of Firefox and QEMU.
Do I use the wrong QEMU parameters ?

**Configuration**  
* UTM Version: 4.4.5
* macOS Version: 14.5
* Mac Chip : M1

**Crash log**  
The VM or UTM did not crash, but Firefox.
[firefox.crash.zip](https://github.com/user-attachments/files/16115757/firefox.crash.zip)
<img width="420" alt="Screenshot 2024-07-06 at 12 57 17" src="https://github.com/utmapp/UTM/assets/26625141/39667526-091e-4a33-a863-d23563637875">

**Debug log**  
[debug.log.zip](https://github.com/user-attachments/files/16115756/debug.log.zip)

**Upload VM**  
[config.plist.zip](https://github.com/user-attachments/files/16115759/config.plist.zip)

**Comment by moipcr** [comment] 2024-08-03 11:15
Do you try with other browser? I see that you are using Snap, try avoid Snap or Flat firstly.

**Comment by freebrowser1** [comment] 2024-08-03 19:25
> Do you try with other browser? I see that you are using Snap, try avoid Snap or Flat firstly.
Yes, I tried Vivaldi, same issue (under Linux Lite, an XCFE4 version of Ubuntu 24.04). But on xubuntu 22.04 not.
None of these Linuxes contain Snap or Flatpak.
I removed them as well from ARM VM and on a Raspberry Pi device, because snap is a resource hog.

**Comment by osy** [comment] 2024-08-21 15:49
Duplicate of #5749

**Closed by osy** 2024-08-21 15:49 UTC
