### ISSUE TITLE
Bus 'ide.0' not found when creating a new virtualized VM (v3.1.3 preview)

### ISSUE THREAD

**Issue by transistor1** [utmapp/UTM#3734] opened 2022-03-09 14:13 UTC
**Describe the issue**
When creating a new "virtualized" Linux VM through UTM using the provided defaults (Virtualize->Linux->Boot ISO Image->4096MB, default CPU cores, no GPU accel->64GB->no shared dir), two things happen:
  1) ARM64 (aarch64) is chosen, but no system is chosen, causing the error "Use -machine help to list supported machines" upon launch.
  2) When you choose "virt" as the system (alias of virt-6.2), an error occurs when launching the VM: 'qemu-aarch64-softmmu: -device ide-cd,bus=ide.0,drive=cdrom0,bootindex=0: Bus 'ide.0' not found'

This worked in earlier revisions of UTM.

**Configuration**
* UTM Version: v3.1.3 (51) preview
* OS Version: 12.2.1
* Intel or Apple Silicon? Apple Silicon

**Crash log**
None provided

**Debug log**
[debug.log](https://github.com/utmapp/UTM/files/8215339/debug.log)

**Upload VM**
[config.plist.zip](https://github.com/utmapp/UTM/files/8215306/config.plist.zip)

<img width="1220" alt="image" src="https://user-images.githubusercontent.com/5625360/157458437-4c244f1a-53aa-4dda-b87d-a592041f4ee2.png">

<img width="912" alt="image" src="https://user-images.githubusercontent.com/5625360/157456001-56b93b38-336d-45ae-b076-164fd98911f8.png">

**Comment by osy** [comment] 2022-03-09 16:13
Duplicate of #3722

**Comment by osy** [comment] 2022-03-09 16:13
Will be fixed next update.

**Closed by osy** 2022-03-09 16:13 UTC
Labels: duplicate
