### ISSUE TITLE
How to enable TPM 2 and Secure boot for upgrade Win 10 VM to Win 11 VM ?

### ISSUE THREAD

**Issue by freebrowser1** [utmapp/UTM#4321] opened 2022-08-19 09:25 UTC
**Describe the issue**  
Using an existing Windows 10 VM works fine, but when trying to upgrade to Windows 11, it issues an error that Secure Boot and TPN 2.0 is not enabled.
I tried bypass hacks in the registry within Windows, but to no avail.

The weird thing is that running an ARM Windows 11 VM on another (M1) Mac runs flawlessly without any hacks.

**Configuration**  
* UTM Version: 3.2.4
* macOS Version: 12.5
* Mac Chip: Intel (MBP 2018 touch bar)

**config.plist**  
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>ConfigurationVersion</key>
	<integer>2</integer>
	<key>Debug</key>
	<dict>
		<key>DebugLog</key>
		<true/>
	</dict>
	<key>Display</key>
	<dict>
		<key>ConsoleBackgroundColor</key>
		<string>#000000</string>
		<key>ConsoleFont</key>
		<string>Menlo-Regular</string>
		<key>ConsoleFontSize</key>
		<integer>12</integer>
		<key>ConsoleOnly</key>
		<false/>
		<key>ConsoleTextColor</key>
		<string>#ffffff</string>
		<key>ConsoleTheme</key>
		<string>Default</string>
		<key>DisplayCard</key>
		<string>virtio-vga</string>
		<key>DisplayDownscaler</key>
		<string>linear</string>
		<key>DisplayUpscaler</key>
		<string>nearest</string>
	</dict>
	<key>Drives</key>
	<array>
		<dict>
			<key>DriveName</key>
			<string>cdrom0</string>
			<key>ImageType</key>
			<string>cd</string>
			<key>InterfaceType</key>
			<string>ide</string>
			<key>Removable</key>
			<true/>
		</dict>
		<dict>
			<key>DriveName</key>
			<string>drive0</string>
			<key>ImagePath</key>
			<string>Windows XP.qcow2</string>
			<key>ImageType</key>
			<string>disk</string>
			<key>InterfaceType</key>
			<string>ide</string>
		</dict>
		<dict>
			<key>DriveName</key>
			<string>driveBA2080B4-0461-4AFA-BFAF-C66E0F5F9B4E</string>
			<key>ImagePath</key>
			<string>efi_vars.fd</string>
			<key>ImageType</key>
			<string>none</string>
			<key>InterfaceType</key>
			<string></string>
		</dict>
		<dict>
			<key>DriveName</key>
			<string>drive1</string>
			<key>ImageType</key>
			<string>cd</string>
			<key>InterfaceType</key>
			<string>ide</string>
			<key>Removable</key>
			<true/>
		</dict>
	</array>
	<key>Info</key>
	<dict>
		<key>Icon</key>
		<string>windows</string>
	</dict>
	<key>Input</key>
	<dict>
		<key>InputInvertScroll</key>
		<true/>
		<key>InputLegacy</key>
		<false/>
	</dict>
	<key>Networking</key>
	<dict>
		<key>NetworkCard</key>
		<string>e1000</string>
		<key>NetworkCardMAC</key>
		<string>16:21:CE:93:FD:38</string>
		<key>NetworkMode</key>
		<string>bridged</string>
	</dict>
	<key>Printing</key>
	<dict/>
	<key>Sharing</key>
	<dict>
		<key>ClipboardSharing</key>
		<true/>
		<key>DirectoryReadOnly</key>
		<false/>
		<key>DirectorySharing</key>
		<true/>
		<key>Usb3Support</key>
		<true/>
		<key>UsbRedirectMax</key>
		<integer>3</integer>
	</dict>
	<key>Sound</key>
	<dict>
		<key>SoundCard</key>
		<string>intel-hda</string>
		<key>SoundEnabled</key>
		<true/>
	</dict>
	<key>System</key>
	<dict>
		<key>Architecture</key>
		<string>x86_64</string>
		<key>BootDevice</key>
		<string></string>
		<key>BootUefi</key>
		<true/>
		<key>CPU</key>
		<string>default</string>
		<key>CPUCount</key>
		<integer>4</integer>
		<key>ForceMulticore</key>
		<true/>
		<key>ForcePS2Controller</key>
		<false/>
		<key>Memory</key>
		<integer>4096</integer>
		<key>RTCUseLocalTime</key>
		<true/>
		<key>RngEnabled</key>
		<true/>
		<key>SystemUUID</key>
		<string>DDC015C5-EAC1-46A0-A1EA-9B3F86EC1921</string>
		<key>Target</key>
		<string>q35</string>
		<key>UseHypervisor</key>
		<true/>
	</dict>
</dict>
</plist>

```

**Comment by conath** [comment] 2022-08-20 12:15
Duplicate of #3082

**Closed by conath** 2022-08-20 12:15 UTC
