### ISSUE TITLE
[Feature suggestion] qemu-system-ppc with audio using qemu-screamer fork?

### ISSUE THREAD

**Issue by brunocastello** [utmapp/UTM#577] opened 2020-11-24 02:56 UTC
I have a QEMU 5.1.0 build I got from homebrew, and a qemu-system-ppc binary I compiled myself from qemu-screamer fork, which enables audio for macOS 9 and works well on my Intel Mac (macOS Big Sur). I managed to replace the homebrews qemu-system-ppc binary with the fork version, so I don't need to mantain a separate version, use a link or a shortcut for that. Can we use the same approach so UTM users who want to run macOS 9 or later (it also enables sound for OS X 10.5 Leopard, for example) can benefit from this? I don't know how it affects other operating systems like PowerPC linux distros (who still does it?) but I suppose it also enables sound for them since vanilla qemu-system-ppc audio never really worked well at all before I found this fork. Why QEMU devs never pushed it to vanilla is beyond my thoughts.

If the UTM dev decide not to do that I would like to hear some info on how to replace the binary by myself or compile my own version for UTM?

**Comment by osy86** [comment] 2020-11-24 05:24
Duplicate of #312

**Closed by osy86** 2020-11-24 05:24 UTC
Labels: duplicate
