### ISSUE TITLE
macOS: UI - Duplicate confirmation dialog

### ISSUE THREAD

**Issue by jankais3r** [utmapp/UTM#2502] opened 2021-05-09 18:42 UTC
**Describe the issue**
There is a duplicate VM deletion confirmation dialog in the macOS UI.

https://user-images.githubusercontent.com/2159464/117583286-ad478e00-b106-11eb-84df-97a6104296e1.mov

**Configuration**
* UTM Version: 2.0.27 (27)
* OS Version: 11.3.1 (20E241)
* Intel or Apple Silicon? Intel

**Comment by conath** [comment] 2021-05-09 19:33
Thanks for reporting this, however there is already an open issue about this. Duplicate of #2337

**Closed by conath** 2021-05-09 19:33 UTC
