### ISSUE TITLE
"+" and "Edit" buttons not working

### ISSUE THREAD

**Issue by barantamur** [utmapp/UTM#2281] opened 2021-01-23 11:53 UTC
**Describe the issue**
After opening the app, I touch the "+" and "Edit" buttons(Only buttons in the main menu) but nothing happens. 

**Configuration (required)**
* UTM Version: 2.0.18
* OS Version: iOS 14.2
* Device Model: iPhone 7 (9,1)
* Checkra1n jailbreaked. Procursus bootstrap.
* Installed via cydia repo 

**Crash log**
It didn't crash.

**Debug log**
Cannot use the menu

**Upload VM**
I cannot create VMS.

**Comment by osy** [comment] 2021-01-24 00:18
I cannot reproduce this. What language is your phone set to? Do you have any tweaks/extensions that could affect how things are displayed?

**Comment by barantamur** [comment] 2021-01-24 09:30
> I cannot reproduce this. What language is your phone set to? Do you have any tweaks/extensions that could affect how things are displayed?

My language is: English

My tweaks(I only listed which affect how things are displayed): Little11(not enabled), Snowboard, XenHTML, Rofi(Not enabled), A-Font(not enabled),MobileGoose(not enabled)

**Comment by Vishram1123** [comment] 2021-02-12 14:23
> > I cannot reproduce this. What language is your phone set to? Do you have any tweaks/extensions that could affect how things are displayed?
> 
> My language is: English
> 
> My tweaks(I only listed which affect how things are displayed): Little11(not enabled), Snowboard, XenHTML, Rofi(Not enabled), A-Font(not enabled),MobileGoose(not enabled)
> 
> Edit: I use FiveDock13 too.

You might want to upgrade to little12 as it causes some issues in iOS 14. For example, the home screen is broken when you use it. That may be part of the problem.

**Comment by osy** [comment] 2021-02-19 01:40
I am closing this as I cannot reproduce but if you run into this error without running any tweaks (non-jailbroken mode), please reopen.

**Closed by osy** 2021-02-19 01:40 UTC
