### ISSUE TITLE
How can i move data dir to an external HDD?

### ISSUE THREAD

**Issue by mehdico** [utmapp/UTM#3377] opened 2021-12-09 14:33 UTC
How can i move data dir to an external HDD?

**Comment by conath** [comment] 2021-12-09 20:22
This is not yet possible with UTM, but may be added in a future update. Duplicate of #132 

You can store removable drives on external HDD, so you could for example create a qcow2 image and move it to the external HDD, then add it to the VM as a removable drive. Then you can store data and applications on it from the VM.

**Closed by conath** 2021-12-09 20:22 UTC
Labels: enhancement
