### ISSUE TITLE
Option to run VMs and UTM itself in the background.

### ISSUE THREAD

**Issue by dan-developer** [utmapp/UTM#3451] opened 2022-01-06 16:43 UTC
Those of us who used docker are looking for a lightweight alternative (at the RAM level) to the Docker Desktop on both Windows and Mac. The option is always to virtualize a small linux and install the docker on it (this is awesome on parallels).

UTM is moving towards native virtualization support on MacOS, and that's great. I managed to run a simple VM and the resources used are according to the VM and not something without explanation. So maybe UTM will become the almost official standard for running docker, minikube on lightweight Linux VMs.

I believe that with the option to run in the background and the machine to be accessible by hostname on the network would be too much.

It's just a suggestion from a user.

Hugs. And congratulations on the beautiful work.

**Comment by conath** [comment] 2022-01-07 10:24
Are you asking for a gui-reduced version of UTM, like a menu bar app?

**Comment by osy** [comment] 2022-01-08 05:25
There are plans to launch VMs in the background. It'll be more work to keep UTM in the background as well. I'm not even sure it's allowed in Sandboxed app.

**Comment by dan-developer** [comment] 2022-01-08 09:47
> Are you asking for a gui-reduced version of UTM, like a menu bar app?

Exactly, in the menu bar, or maybe a cli itself. E.g.: ucli, utmcli to list virtual machines, stop, kill, etc...

**Comment by conath** [comment] 2022-01-08 10:20
> > Are you asking for a gui-reduced version of UTM, like a menu bar app?
> 
> Exactly, in the menu bar, or maybe a cli itself. E.g.: ucli, utmcli to list virtual machines, stop, kill, etc...

I understand. In that case this is a duplicate of #2280. 
As a stop-gap solution you might be able to incorporate the [UTM URL scheme](https://github.com/utmapp/UTM/wiki/URL-Scheme-–-Automation-for-UTM-app-&-VMs#auto-start-vm-on-mac) into your workflow.

**Closed by conath** 2022-01-08 10:20 UTC
Labels: enhancement

**Comment by dan-developer** [comment] 2022-01-08 10:50
> > > Você está pedindo uma versão reduzida em interface gráfica do UTM, como um aplicativo da barra de menus?
> > 
> > 
> > Exatamente, na barra de menu, ou talvez no próprio cli. Ex: ucli, utmcli para listar máquinas virtuais, parar, matar, etc ...
> 
> Compreendo. Nesse caso, é uma duplicata de [# 2280](https://github.com/utmapp/UTM/issues/2280) . Como uma solução temporária, você pode incorporar o [esquema de URL UTM](https://github.com/utmapp/UTM/wiki/URL-Scheme-%E2%80%93-Automation-for-UTM-app-&-VMs#auto-start-vm-on-mac) ao seu fluxo de trabalho.

Thank you for your attention.

**Comment by dan-developer** [comment] 2022-01-08 10:50
> > > Você está pedindo uma versão reduzida em interface gráfica do UTM, como um aplicativo da barra de menus?
> > 
> > 
> > Exatamente, na barra de menu, ou talvez no próprio cli. Ex: ucli, utmcli para listar máquinas virtuais, parar, matar, etc ...
> 
> Compreendo. Nesse caso, é uma duplicata de [# 2280](https://github.com/utmapp/UTM/issues/2280) . Como uma solução temporária, você pode incorporar o [esquema de URL UTM](https://github.com/utmapp/UTM/wiki/URL-Scheme-%E2%80%93-Automation-for-UTM-app-&-VMs#auto-start-vm-on-mac) ao seu fluxo de trabalho.

Thank you for your attention.

**Comment by DrHyde** [comment] 2023-04-01 19:34
> or maybe a cli itself. E.g.: ucli, utmcli to list virtual machines, stop, kill, etc...

You want `/Applications/UTM.app/Contents/MacOS/utmctl`, which already exists :-)
