### ISSUE TITLE
cant add up storage

### ISSUE THREAD

**Issue by Aras1386** [utmapp/UTM#2718] opened 2021-08-09 06:31 UTC
please add the option to add storage to the vm I really nead more storage on my virtual machine

**Comment by conath** [comment] 2021-08-09 07:36
Thanks for your suggestion. It is currently necessary to add more storage by adding more drives to the VM. Other than that there are external tools on macOS that can resize your existing virtual drive, and after using them you would need to extend the guest's partition to use the new free space. Here is a third-party guide on resizing, you will need to `brew install qemu` on your host (macOS). https://maunium.net/blog/resizing-qcow2-images/

Duplicate of #16

**Closed by conath** 2021-08-09 07:36 UTC
Labels: enhancement
