### ISSUE TITLE
UTM program crash automatically once I hit the "play" button to Load Ubuntu #crash  -label:bug -label:crash

### ISSUE THREAD

**Issue by 992379555** [utmapp/UTM#3105] opened 2021-09-12 03:25 UTC
**Describe the issue**
UTM program crash automatically once I hit the "play" button to Load Ubuntu 

Ubuntu version: impish-desktop-arm64.iso

**Configuration** m1 Macbook pro
* UTM Version:   2.2.4 (36)
* OS Version:  MacOS bigsur 11.2.3
Apple Silicon

**Crash log**
[QEMUHelper_2021-09-12-110901_cmcc-mb.txt](https://github.com/utmapp/UTM/files/7148930/QEMUHelper_2021-09-12-110901_cmcc-mb.txt)
[UTM_2021-09-12-110918_cmcc-mb.txt](https://github.com/utmapp/UTM/files/7148931/UTM_2021-09-12-110918_cmcc-mb.txt)

 -label:bug
-label:crash

**Comment by conath** [comment] 2021-09-18 16:52
Please update to macOS 11.3 or later to use UTM. Duplicate of #3098

**Closed by conath** 2021-09-18 16:52 UTC
