### ISSUE TITLE
UTM 4.5.3 Crashes on iOS 14.4.1

### ISSUE THREAD

**Issue by plia7** [utmapp/UTM#6396] opened 2024-05-27 23:56 UTC
**Describe the issue**
The app crashes as soon as I try to open it.
**Configuration (required)**
* UTM Version: 4.5.3
* OS Version: iOS 14.4.1
* Device Model: iPhone 12 Pro Max
* Is it jailbroken (name jailbreak used)? Yes. Taurine jailbreak.
* How did you install UTM? I installed UTM 4.5.3 from Sileo repo https://cydia.getutm.app/

**Crash log**
https://jmp.sh/s/GHlz1tvc1AX0989hXljC

**Debug log**
N/A as I can't open the app.

Thanks.

**Comment by osy** [comment] 2024-05-28 00:11
Duplicate of #3628

**Closed by osy** 2024-05-28 00:11 UTC
