### ISSUE TITLE
Port UTM to Android Devices?

### ISSUE THREAD

**Issue by WMCB-Tech** [utmapp/UTM#434] opened 2020-08-31 02:11 UTC
Now I am a Android/Windows user. and fan of Virtualization and I saw a video about UTM for IOS. and they run VM's at decent speed such as running Windows 7 in iOS Devices.

There is an QEMU port to Android app called Limbo. but the issue is the Emulation speed is slow. even when running stripped version of windows 7. it still slow as hell. especially full version of windows and lacks of features. such as SPICE.

Now I was just wondering if you can port UTM to Android. or tell me how the Emulation speed runs at decent performance.

**Comment by WeiChei7** [comment] 2020-08-31 02:29
How do I unsubscribe from this thread

**Comment by ThatsNiceGuy** [comment] 2020-08-31 03:58
Duplicate of #69 

Also slow emulation speed on android is likely due to crappy Qualcomm chips. Both emulators are based on QEMU anyway

**Comment by chobix77** [comment] 2020-08-31 04:05
Please don't ask such stupid question, unless you're developer, github is not a place to discuss something like request like this

**Closed** 2020-08-31 04:54 UTC
