### ISSUE TITLE
Cannot import iso drive image

### ISSUE THREAD

**Issue by osy** [utmapp/UTM#519] opened 2020-11-07 05:45 UTC
This appears to only be an issue if a **wildcard provisioning profile is used**. It is not an issue if installed with AltStore 1.4.2 (with a free developer account) or with Xcode build + run.

**Comment by saagarjha** [comment] 2020-11-07 06:08
Works for me?

**Comment by osy86** [comment] 2020-11-07 06:14
I’m posting this on behalf of someone who told me in chat. I haven’t verified the issue.

**Comment by FD-** [comment] 2020-11-07 09:42
I have the Same issue on an iPad 2018 (6th gen) running iOS 14.2. I was starting to think I’m dump since I seem to be unable to import any disk images. Is there any info that could help you fix the issue?

**Comment by FD-** [comment] 2020-11-07 09:44
The disk creation dialog doesn’t include a path field as suggested by some (obsolete?) documentation. The import icon in the toolbar shows the system file picker, but tapping an iso or zip file doesn’t do anything at all.

**Comment by FD-** [comment] 2020-11-07 09:51
Rebooting the iPad doesn’t help.

**Comment by FD-** [comment] 2020-11-07 10:13
Installed the app by downloading the newest release ipa, using iOS App Signer to sign it with the Team Provisioning Profile of my paid iOS developer account (I tried Re-Sign Only before but it wouldn’t install) and installed via Xcode.

**Comment by firecrafts** [comment] 2020-11-07 11:06
im having same problem on my ipad pro ( 2018 ) ios14.2

**Comment by cleverer** [comment] 2020-11-07 12:26
Same here. I also have  [Notability ](https://apps.apple.com/ch/app/notability/id360593530)installed and in the files app, the iso shows the notability icon.

**Comment by abn5x** [comment] 2020-11-07 14:30
same issue here.

**Comment by yrjo** [comment] 2020-11-07 18:57
same here, ipad pro 11, 2018. ios 14.2
utm 2.0.8

**Comment by cleverer** [comment] 2020-11-07 21:54
Ah got it working. I tried different approaches, including building the app myself (build + run in Xcode, so it's a develop build). However, I think what made it work is putting the files in to the UTM folder in the Files app (On My iPad/iPhone => UTM). This worked for ISOs.

I also couldn't open `.utm` files (UTM would open, but not import it), but by putting them in the folder and force-quitting and reopening the app, they just appeared.

**Comment by osy86** [comment] 2020-11-07 23:26
I still cannot reproduce this on my iPhone 12 Pro or iPad Pro 2018 (both on iOS 14.2). When trying to import an image, I can select any file. People here are seeing that all the files are grayed out and cannot be selected?

**Comment by cleverer** [comment] 2020-11-07 23:44
To clarify: the ISO wasn't greyed out for me. when tapping it nothing happened… I did play around and found the "Browse" button in the `VMDetailsView`. When trying to select the iso there, a warning popped up stating that the current version could only use ISOs that are in the App directory.

I did just check again however, I now seem to be able to import the ISO. I assume it might be, because I'm now running my own build?

**Comment by yrjo** [comment] 2020-11-07 23:49
for me, i can tap the icon for importing the files, i can see ISO file, but once tapping to the file, nothing happens 
its possible to create the new drive, by tapping to "plus" icon, but if choosing the option "CD/DVD" image, its not possible to chose the existing file.

i am running build from here, IPA, signed by my dev paid cert

**Comment by osy86** [comment] 2020-11-07 23:52
> nothing happened

Does the file selector close?

**Comment by cleverer** [comment] 2020-11-08 00:13
> > nothing happened
> 
> Does the file selector close?

Nope, the file quickly gets highlighted (as is expected) and then looses the highlight immediately. nothing more happened, file  selector stayed open.

**Comment by acfrazier** [comment] 2020-11-08 00:46
I am also having this issue. I am able to add the iso directly from the file picker (box with down arrow), but it disappears once the app is closed. I then have to delete the entire virtual machine because it won't let me pick or re-add the same .iso.

**Comment by osy86** [comment] 2020-11-08 01:29
@acfrazier you mean when you save the VM the iso doesn’t get saved? I think that’s a different issue than described here where people cannot even close the file picker.

**Comment by ZonD80** [comment] 2020-11-08 07:36
My issue #521 was merged & closed. However, according to @acfrazier  I can't import qcow2 even if I copy it to UTM data folder.
@osy86 is your iPad jailbroken?

I suppose this issue happens only for non-jb devices, when app is running without Xcode. Unfortunately I have no device with jailbreak right now.

I have compared release IPA and signed IPA file, the only difference is that signer adds entitlements and UIFileSharingEnabled=true , and signature change ofc.

**Comment by osy86** [comment] 2020-11-08 08:53
I’m on iOS 14.2, there is no jailbreak.

**Comment by ZonD80** [comment] 2020-11-08 10:00
Sorry. This:
`	<key>UISupportsDocumentBrowser</key>
	<true/>`
Not UIFileSharingEnabled.

**Comment by firecrafts** [comment] 2020-11-08 10:17
if you need me to send video or stream of this problem or anything can help let me know

**Comment by kkk669** [comment] 2020-11-08 17:20
I'm using iPadOS 14.2 and it's not jailbroken. I have a paid Apple Developer account.

- Case 1. iOS App Signer
    - Result: importing drive **doesn't work** just like https://github.com/utmapp/UTM/issues/519#issuecomment-723512326
    - Steps:
        1. Download UTM.ipa from https://github.com/utmapp/UTM/releases/tag/v2.0.8
        1. Using [iOS App Signer](https://www.iosappsigner.com/) 1.13.1, change the signing certificate, the provisioning profile, and the application ID
            - I selected the Apple Development certificate and the "iOS Team Provisioning Profile: *", and used `xyz.kebo.UTM` as a new application ID
        1. Save the new ipa file
        1. Install it with Xcode's "Devices and Simulators" window
- Case 2. Build with Xcode
    - Result: importing drive **works** (both Debug and Release)
    - Steps:
        1. `git clone https://github.com/utmapp/UTM.git`
        1. `git checkout v2.0.8`
        1. Download Sysroot-ios-arm64 from https://github.com/utmapp/UTM/actions/runs/348441158 and extract it into the UTM directory
        1. Open UTM.xcodeproj
        1. Change the Team and the Bundle Identifier on the Signing settings
            - My bundle ID is `xyz.kebo.UTM`.
        1. Build and Run

**Comment by ZonD80** [comment] 2020-11-08 17:43
@kkk669 can you please export built IPA file from Xcode and give me link to it?

**Comment by ZonD80** [comment] 2020-11-08 19:53
Looks like issue is related to entitlements. Bundle ID in entitlements must match bundle ID in Info.plist, I will try to test it tomorrow.

**Comment by osy86** [comment] 2020-11-08 23:55
I was able to reproduce this issue but only with iOS App Signer. It worked fine for me on both Xcode and AltStore (beta). I also tried adding `UISupportsDocumentBrowser` to an Xcode run and it worked fine so I don't think that's the issue.

**Comment by ZonD80** [comment] 2020-11-09 09:50
Confirmed. **application-identifier entitlement must match "team_id.bundle_id" in Info.plist**. Otherwise it is not working and making app incompatible with almost all alternative signing software. Btw, tested with [Rickpactor](https://appdb.to/app/standalone/1900000033) and appdb PRO - works fine.

**Comment by ecstaticax** [comment] 2020-11-09 13:40
Same problem for me. 14.2 iPad Pro 2020, self signed no jailbreak, if I click on .iso file to import, nothing happens.

**Comment by osy86** [comment] 2020-11-09 19:10
@ZonD80 can you explain what you mean? iOS App Signer should update Info.plist automatically with the profile you selected and replace CFBundleIdentifier with the application-identifier entitlement.

**Comment by ZonD80** [comment] 2020-11-09 19:27
Never used ios app signer. Maybe it makes entitlements and Info.plist to not match, so maybe that's why it is not working.

**Comment by osy86** [comment] 2020-11-09 19:41
Like I said it specifically makes it match. Can you tell me what you did to say that bundle id is the issue?

**Comment by ZonD80** [comment] 2020-11-09 19:54
Then it should work. I'll check ios app signer as well.

**Comment by osy86** [comment] 2020-11-09 20:11
I tried a couple of different variations and it seems like the problem occurs when you use a wildcard provisioning profile. This is probably an Apple bug and should be reported to them.

**Comment by osy86** [comment] 2020-11-10 02:47
Those who are using iOS App Signer should build this pull request https://github.com/DanTheMan827/ios-app-signer/pull/163 to get a fixed version to sign UTM.

**Comment by ecstaticax** [comment] 2020-11-10 10:47
> Those who are using iOS App Signer should build this pull request [DanTheMan827/ios-app-signer#163](https://github.com/DanTheMan827/ios-app-signer/pull/163) to get a fixed version to sign UTM.

I did it, but it didn’t work. I will try to compile utm.

**Comment by mindesik** [comment] 2020-12-27 08:38
> Those who are using iOS App Signer should build this pull request [DanTheMan827/ios-app-signer#163](https://github.com/DanTheMan827/ios-app-signer/pull/163) to get a fixed version to sign UTM.

Works, I am able to pick .iso file now. But had to uncheck "No get-task-allow".

**Comment by brunocastello** [comment] 2021-01-09 23:11
> Those who are using iOS App Signer should build this pull request [DanTheMan827/ios-app-signer#163](https://github.com/DanTheMan827/ios-app-signer/pull/163) to get a fixed version to sign UTM.

How I build this from a pull request? I have never done it before.

**Comment by brunocastello** [comment] 2021-01-10 01:27
Just ran a patched iOS App Signer with no-get-task-allow unchecked, on the build @osy had to fix my issue with the popups about not being jailbroken (when I am actually jailbroken, yes) and all my issues are gone. No more nagging popups and I can now use a removable drive with my Windows 98SE VM. I’m feeling great 👍🏼 As always, fantastic job, osy!

**Comment by ecstaticax** [comment] 2021-01-10 08:56
Hi, how do I uncheck "no-get-task"?

**Comment by ViRb3** [comment] 2021-01-17 21:38
Thanks a lot for the fix! Until this PR get merged, here is a fork with the fix applied and prebuilt binaries via GitHub CI: https://github.com/ViRb3/ios-app-signer

**Comment by osy** [comment] 2021-09-04 03:40
See https://github.com/osy/Jitterbug/issues/1#issuecomment-861544260 as well

**Comment by Jadon67** [comment] 2022-05-02 09:01
Fine I will install altstore

**Comment by nandahtb** [comment] 2022-10-28 10:27
Does this app is a dead web ? 
No solution from them Lol.
Everyone can't select the iso file, good app.

**Comment by osy** [comment] 2022-10-28 16:19
@nandahtb It’s because you can’t read the instructions.

**Comment by nandahtb** [comment] 2022-10-28 16:20
@osy so what the solution?

**Comment by ViRb3** [comment] 2022-10-28 18:02
> @osy so what the solution?

Sign the app properly. The problem is in you, not the app. If you deviate from the official instructions then you're on your own. This issue can be closed btw, it's been long resolved.

**Closed** 2022-10-28 18:03 UTC
Labels: wontfix

**Comment by CBYTFANZIPAD** [comment] 2023-10-21 22:38
Same Here. iPad 7th Gen. 2019
