### ISSUE TITLE
iPadOS crashed and reboot

### ISSUE THREAD

**Issue by KrisCris** [utmapp/UTM#3341] opened 2021-11-26 05:18 UTC
**Describe the issue**

Installed Ubuntu 20.04 ARM with Desktop (I named the VM 20.10 but I did install 20.04). After a random crash caused by switching UTM to the background and switching back, I can't boot the VM anymore - It causes my iPad to reboot every time.

**Configuration (required)**

* UTM Version: 2.4.1
* OS Version: iPadOS 15.1
* Device Model: 256g M1 iPad Pro 12.9
* Is it jailbroken (name jailbreak used)? NO
* How did you install UTM? Installed directly from AltStore

**Crash log**

NO

<details>
  <summary>Debug Log</summary>

```log

-[CSConnection finishInit]:271
2021-11-25 23:09:21.326 UTM[302:5689] -[CSConnection finishInit]:271
-[CSInput initWithSession:]:293
2021-11-25 23:09:21.326 UTM[302:5689] -[CSInput initWithSession:]:293
-[CSSession initWithSession:]:294
2021-11-25 23:09:21.326 UTM[302:5689] -[CSSession initWithSession:]:294
Running:  -L /private/var/containers/Bundle/Application/47A038F6-028E-4943-9ECD-531E3E860611/App.app/qemu -S -qmp tcp:127.0.0.1:4000,server,nowait -nodefaults -vga none -spice unix=on,addr=/private/var/mobile/Containers/Data/Application/6452E32B-9DA6-41A4-99A6-B050B6F212F4/tmp/0DEF0A70-1F0D-48D0-838B-4D3FF8241C56.spice,disable-ticketing=on,image-compression=off,playback-compression=off,streaming-video=off,gl=on -device virtio-ramfb-gl -cpu cortex-a72 -smp cpus=4,sockets=1,cores=4,threads=1 -machine virt,highmem=off -accel tcg,tb-size=256,split-wx=on -drive if=pflash,format=raw,unit=0,file=/private/var/containers/Bundle/Application/47A038F6-028E-4943-9ECD-531E3E860611/App.app/qemu/edk2-aarch64-code.fd,readonly=on -drive if=pflash,format=raw,unit=1,file=/var/mobile/Containers/Data/Application/6452E32B-9DA6-41A4-99A6-B050B6F212F4/Documents/Ubuntu20.10.utm/Images/efi_vars.fd -boot menu=on -m 1024 -device intel-hda -device hda-duplex -name Ubuntu20.10 -device qemu-xhci,id=usb-bus -device usb-tablet,bus=usb-bus.0 -device usb-mouse,bus=usb-bus.0 -device usb-kbd,bus=usb-bus.0 -device ich9-usb-ehci1,id=usb-controller-0 -device ich9-usb-uhci1,masterbus=usb-controller-0.0,firstport=0,multifunction=on -device ich9-usb-uhci2,masterbus=usb-controller-0.0,firstport=2,multifunction=on -device ich9-usb-uhci3,masterbus=usb-controller-0.0,firstport=4,multifunction=on -chardev spicevmc,name=usbredir,id=usbredirchardev0 -device usb-redir,chardev=usbredirchardev0,id=usbredirdev0,bus=usb-controller-0.0 -chardev spicevmc,name=usbredir,id=usbredirchardev1 -device usb-redir,chardev=usbredirchardev1,id=usbredirdev1,bus=usb-controller-0.0 -chardev spicevmc,name=usbredir,id=usbredirchardev2 -device usb-redir,chardev=usbredirchardev2,id=usbredirdev2,bus=usb-controller-0.0 -device virtio-blk-pci,drive=drive0,bootindex=0 -drive if=none,media=disk,id=drive0,file=/var/mobile/Containers/Data/Application/6452E32B-9DA6-41A4-99A6-B050B6F212F4/Documents/Ubuntu20.10.utm/Images/disk-0.qcow2,cache=writethrough -device usb-storage,drive=drive1,removable=true,bootindex=1,bus=usb-bus.0 -drive if=none,media=cdrom,id=drive1 -device virtio-net-pci,mac=4E:51:78:04:6D:AE,netdev=net0 -netdev user,id=net0 -device virtio-serial -device virtserialport,chardev=vdagent,name=com.redhat.spice.0 -chardev spicevmc,id=vdagent,debug=0,name=vdagent -uuid 0DEF0A70-1F0D-48D0-838B-4D3FF8241C56 -rtc base=localtime
Loading qemu-aarch64-softmmu.framework/qemu-aarch64-softmmu
2021-11-25 23:09:21.501 UTM[302:5689] Running:  -L /private/var/containers/Bundle/Application/47A038F6-028E-4943-9ECD-531E3E860611/App.app/qemu -S -qmp tcp:127.0.0.1:4000,server,nowait -nodefaults -vga none -spice unix=on,addr=/private/var/mobile/Containers/Data/Application/6452E32B-9DA6-41A4-99A6-B050B6F212F4/tmp/0DEF0A70-1F0D-48D0-838B-4D3FF8241C56.spice,disable-ticketing=on,image-compression=off,playback-compression=off,streaming-video=off,gl=on -device virtio-ramfb-gl -cpu cortex-a72 -smp cpus=4,sockets=1,cores=4,threads=1 -machine virt,highmem=off -accel tcg,tb-size=256,split-wx=on -drive if=pflash,format=raw,unit=0,file=/private/var/containers/Bundle/Application/47A038F6-028E-4943-9ECD-531E3E860611/App.app/qemu/edk2-aarch64-code.fd,readonly=on -drive if=pflash,format=raw,unit=1,file=/var/mobile/Containers/Data/Application/6452E32B-9DA6-41A4-99A6-B050B6F212F4/Documents/Ubuntu20.10.utm/Images/efi_vars.fd -boot menu=on -m 1024 -device intel-hda -device hda-duplex -name Ubuntu20.10 -device qemu-xhci,id=usb-bus -device usb-tablet,bus=usb-bus.0 -device usb-mouse,bus=usb-bus.0 -device usb-kbd,bus=usb-bus.0 -device ich9-usb-ehci1,id=usb-controller-0 -device ich9-usb-uhci1,masterbus=usb-controller-0.0,firstport=0,multifunction=on -device ich9-usb-uhci2,masterbus=usb-controller-0.0,firstport=2,multifunction=on -device ich9-usb-uhci3,masterbus=usb-controller-0.0,firstport=4,multifunction=on -chardev spicevmc,name=usbredir,id=usbredirchardev0 -device usb-redir,chardev=usbredirchardev0,id=usbredirdev0,bus=usb-controller-0.0 -chardev spicevmc,name=usbredir,id=usbredirchardev1 -device usb-redir,chardev=usbredirchardev1,id=usbredirdev1,bus=usb-controller-0.0 -chardev spicevmc,name=usbredir,id=usbredirchardev2 -device usb-redir,chardev=usbredirchardev2,id=usbredirdev2,bus=usb-controller-0.0 -device virtio-blk-pci,drive=drive0,bootindex=0 -drive if=none,media=disk,id=drive0,file=/var/mobile/Containers/Data/Application/6452E32B-9DA6-41A4-99A6-B050B6F212F4/Documents/Ubuntu20.10.utm/Images/disk-0.qcow2,cache=writethrough -device usb-storage,drive=drive1,removable=true,bootindex=1,bus=usb-bus.0 -drive if=none,media=cdrom,id=drive1 -device virtio-net-pci,mac=4E:51:78:04:6D:AE,netdev=net0 -netdev user,id=net0 -device virtio-serial -device virtserialport,chardev=vdagent,name=com.redhat.spice.0 -chardev spicevmc,id=vdagent,debug=0,name=vdagent -uuid 0DEF0A70-1F0D-48D0-838B-4D3FF8241C56 -rtc base=localtime
2021-11-25 23:09:21.501 UTM[302:5689] Loading qemu-aarch64-softmmu.framework/qemu-aarch64-softmmu
Discovering servers...
Connecting to service: <NSNetService 0x28100e460> local. _altserver._tcp. Pingchuan’s Mac mini 65517
Stopped discovering servers.
Stream error Error Domain=NSPOSIXErrorDomain Code=61 "Connection refused" UserInfo={_kCFStreamErrorCodeKey=61, _kCFStreamErrorDomainKey=1}
QMP stream error seen: Error Domain=NSPOSIXErrorDomain Code=61 "Connection refused" UserInfo={_kCFStreamErrorCodeKey=61, _kCFStreamErrorDomainKey=1}
2021-11-25 23:09:21.586 UTM[302:10026] Stream error Error Domain=NSPOSIXErrorDomain Code=61 "Connection refused" UserInfo={_kCFStreamErrorCodeKey=61, _kCFStreamErrorDomainKey=1}
QMP connection failed, retries left: 29
2021-11-25 23:09:21.586 UTM[302:10026] QMP stream error seen: Error Domain=NSPOSIXErrorDomain Code=61 "Connection refused" UserInfo={_kCFStreamErrorCodeKey=61, _kCFStreamErrorDomainKey=1}
2021-11-25 23:09:21.586 UTM[302:10026] QMP connection failed, retries left: 29
Connected to stream 0x28228c990
QMP connection successful! (readStream:1)
2021-11-25 23:09:22.590 UTM[302:10024] Connected to stream 0x28228c990
2021-11-25 23:09:22.590 UTM[302:10024] QMP connection successful! (readStream:1)
Connected to stream 0x28228ce10
QMP connection successful! (readStream:0)
2021-11-25 23:09:22.590 UTM[302:10024] Connected to stream 0x28228ce10
2021-11-25 23:09:22.590 UTM[302:10024] QMP connection successful! (readStream:0)
Debug JSON recieved <- {
    QMP =     {
        capabilities =         (
            oob
        );
        version =         {
            package = "";
            qemu =             {
                major = 6;
                micro = 0;
                minor = 1;
            };
        };
    };
}
2021-11-25 23:09:22.590 UTM[302:10024] Debug JSON recieved <- {
    QMP =     {
        capabilities =         (
            oob
        );
        version =         {
            package = "";
            qemu =             {
                major = 6;
                micro = 0;
                minor = 1;
            };
        };
    };
}
Got QMP handshake: {
    QMP =     {
        capabilities =         (
            oob
        );
        version =         {
            package = "";
            qemu =             {
                major = 6;
                micro = 0;
                minor = 1;
            };
        };
    };
}
Debug JSON send -> {
    execute = "qmp_capabilities";
}
2021-11-25 23:09:22.591 UTM[302:10018] Got QMP handshake: {
    QMP =     {
        capabilities =         (
            oob
        );
        version =         {
            package = "";
            qemu =             {
                major = 6;
                micro = 0;
                minor = 1;
            };
        };
    };
}
2021-11-25 23:09:22.591 UTM[302:10018] Debug JSON send -> {
    execute = "qmp_capabilities";
}
Debug JSON recieved <- {
    return =     {
    };
}
2021-11-25 23:09:22.592 UTM[302:10025] Debug JSON recieved <- {
    return =     {
    };
}
qemuQmpDidConnect
2021-11-25 23:09:22.592 UTM[302:10018] qemuQmpDidConnect
cs_channel_new:164
2021-11-25 23:09:22.608 UTM[302:10018] cs_channel_new:164
Debug JSON recieved <- {
    data =     {
        client =         {
            family = unix;
            host = "";
            port = "";
        };
        server =         {
            family = unix;
            host = "";
            port = "";
        };
    };
    event = "SPICE_CONNECTED";
    timestamp =     {
        microseconds = 612559;
        seconds = 1637903362;
    };
}
2021-11-25 23:09:22.613 UTM[302:10018] Debug JSON recieved <- {
    data =     {
        client =         {
            family = unix;
            host = "";
            port = "";
        };
        server =         {
            family = unix;
            host = "";
            port = "";
        };
    };
    event = "SPICE_CONNECTED";
    timestamp =     {
        microseconds = 612559;
        seconds = 1637903362;
    };
}
qemu-system: warning: GSpice: main-1:0: could not set sockopt TCP_NODELAY: Operation not supported on socket
Debug JSON send -> {
    execute = cont;
}
qemu-system: info: main channel: opened
2021-11-25 23:09:22.633 UTM[302:10029] Debug JSON send -> {
    execute = cont;
}
Debug JSON recieved <- {
    data =     {
        client =         {
            "channel-id" = 0;
            "channel-type" = 1;
            "connection-id" = 16807;
            family = unix;
            host = "";
            port = 5;
            tls = 0;
        };
        server =         {
            auth = none;
            family = unix;
            host = "";
            port = 5;
        };
    };
    event = "SPICE_INITIALIZED";
    timestamp =     {
        microseconds = 632906;
        seconds = 1637903362;
    };
}
2021-11-25 23:09:22.633 UTM[302:10025] Debug JSON recieved <- {
    data =     {
        client =         {
            "channel-id" = 0;
            "channel-type" = 1;
            "connection-id" = 16807;
            family = unix;
            host = "";
            port = 5;
            tls = 0;
        };
        server =         {
            auth = none;
            family = unix;
            host = "";
            port = 5;
        };
    };
    event = "SPICE_INITIALIZED";
    timestamp =     {
        microseconds = 632906;
        seconds = 1637903362;
    };
}
Debug JSON recieved <- {
    event = RESUME;
    timestamp =     {
        microseconds = 633559;
        seconds = 1637903362;
    };
}
Debug JSON recieved <- {
    return =     {
    };
}
qemuHasResumed
2021-11-25 23:09:22.633 UTM[302:10024] Debug JSON recieved <- {
    event = RESUME;
    timestamp =     {
        microseconds = 633559;
        seconds = 1637903362;
    };
}
2021-11-25 23:09:22.633 UTM[302:10024] Debug JSON recieved <- {
    return =     {
    };
}
2021-11-25 23:09:22.633 UTM[302:10025] qemuHasResumed
resizing to (1366.000000, 1024.000000)
2021-11-25 23:09:22.634 UTM[302:5689] resizing to (1366.000000, 1024.000000)
cs_channel_new:173
2021-11-25 23:09:22.635 UTM[302:10029] cs_channel_new:173
Debug JSON recieved <- {
    data =     {
        client =         {
            family = unix;
            host = "";
            port = "";
        };
        server =         {
            family = unix;
            host = "";
            port = "";
        };
    };
    event = "SPICE_CONNECTED";
    timestamp =     {
        microseconds = 636906;
        seconds = 1637903362;
    };
}
2021-11-25 23:09:22.637 UTM[302:10024] Debug JSON recieved <- {
    data =     {
        client =         {
            family = unix;
            host = "";
            port = "";
        };
        server =         {
            family = unix;
            host = "";
            port = "";
        };
    };
    event = "SPICE_CONNECTED";
    timestamp =     {
        microseconds = 636906;
        seconds = 1637903362;
    };
}
Debug JSON recieved <- {
    data =     {
        client =         {
            family = unix;
            host = "";
            port = "";
        };
        server =         {
            family = unix;
            host = "";
            port = "";
        };
    };
    event = "SPICE_CONNECTED";
    timestamp =     {
        microseconds = 636998;
        seconds = 1637903362;
    };
}
2021-11-25 23:09:22.637 UTM[302:10024] Debug JSON recieved <- {
    data =     {
        client =         {
            family = unix;
            host = "";
            port = "";
        };
        server =         {
            family = unix;
            host = "";
            port = "";
        };
    };
    event = "SPICE_CONNECTED";
    timestamp =     {
        microseconds = 636998;
        seconds = 1637903362;
    };
}
Debug JSON recieved <- {
    data =     {
        client =         {
            family = unix;
            host = "";
            port = "";
        };
        server =         {
            family = unix;
            host = "";
            port = "";
        };
    };
    event = "SPICE_CONNECTED";
    timestamp =     {
        microseconds = 637058;
        seconds = 1637903362;
    };
}
Debug JSON recieved <- {
    data =     {
        client =         {
            family = unix;
            host = "";
            port = "";
        };
        server =         {
            family = unix;
            host = "";
            port = "";
        };
    };
    event = "SPICE_CONNECTED";
    timestamp =     {
        microseconds = 637119;
        seconds = 1637903362;
    };
}
2021-11-25 23:09:22.637 UTM[302:10024] Debug JSON recieved <- {
    data =     {
        client =         {
            family = unix;
            host = "";
            port = "";
        };
        server =         {
            family = unix;
            host = "";
            port = "";
        };
    };
    event = "SPICE_CONNECTED";
    timestamp =     {
        microseconds = 637058;
        seconds = 1637903362;
    };
}
qemu-system: warning: GSpice: display-2:0: could not set sockopt TCP_NODELAY: Operation not supported on socket
2021-11-25 23:09:22.637 UTM[302:10024] Debug JSON recieved <- {
    data =     {
        client =         {
            family = unix;
            host = "";
            port = "";
        };
        server =         {
            family = unix;
            host = "";
            port = "";
        };
    };
    event = "SPICE_CONNECTED";
    timestamp =     {
        microseconds = 637119;
        seconds = 1637903362;
    };
}
qemu-system: warning: GSpice: usbredir-9:2: could not set sockopt TCP_NODELAY: Operation not supported on socket
Debug JSON recieved <- {
    data =     {
        client =         {
            family = unix;
            host = "";
            port = "";
        };
        server =         {
            family = unix;
            host = "";
            port = "";
        };
    };
    event = "SPICE_CONNECTED";
    timestamp =     {
        microseconds = 637200;
        seconds = 1637903362;
    };
}
qemu-system: warning: GSpice: usbredir-9:1: could not set sockopt TCP_NODELAY: Operation not supported on socket
2021-11-25 23:09:22.637 UTM[302:10024] Debug JSON recieved <- {
    data =     {
        client =         {
            family = unix;
            host = "";
            port = "";
        };
        server =         {
            family = unix;
            host = "";
            port = "";
        };
    };
    event = "SPICE_CONNECTED";
    timestamp =     {
        microseconds = 637200;
        seconds = 1637903362;
    };
}
qemu-system: warning: GSpice: usbredir-9:0: could not set sockopt TCP_NODELAY: Operation not supported on socket
Debug JSON recieved <- {
    data =     {
        client =         {
            family = unix;
            host = "";
            port = "";
        };
        server =         {
            family = unix;
            host = "";
            port = "";
        };
    };
    event = "SPICE_CONNECTED";
    timestamp =     {
        microseconds = 637289;
        seconds = 1637903362;
    };
}
qemu-system: warning: GSpice: playback-5:0: could not set sockopt TCP_NODELAY: Operation not supported on socket
2021-11-25 23:09:22.637 UTM[302:10024] Debug JSON recieved <- {
    data =     {
        client =         {
            family = unix;
            host = "";
            port = "";
        };
        server =         {
            family = unix;
            host = "";
            port = "";
        };
    };
    event = "SPICE_CONNECTED";
    timestamp =     {
        microseconds = 637289;
        seconds = 1637903362;
    };
}
Debug JSON recieved <- {
    data =     {
        client =         {
            family = unix;
            host = "";
            port = "";
        };
        server =         {
            family = unix;
            host = "";
            port = "";
        };
    };
    event = "SPICE_CONNECTED";
    timestamp =     {
        microseconds = 637407;
        seconds = 1637903362;
    };
}
qemu-system: warning: GSpice: record-6:0: could not set sockopt TCP_NODELAY: Operation not supported on socket
qemu-system: warning: GSpice: inputs-3:0: could not set sockopt TCP_NODELAY: Operation not supported on socket
2021-11-25 23:09:22.638 UTM[302:10024] Debug JSON recieved <- {
    data =     {
        client =         {
            family = unix;
            host = "";
            port = "";
        };
        server =         {
            family = unix;
            host = "";
            port = "";
        };
    };
    event = "SPICE_CONNECTED";
    timestamp =     {
        microseconds = 637407;
        seconds = 1637903362;
    };
}
Debug JSON recieved <- {
    data =     {
        client =         {
            "channel-id" = 1;
            "channel-type" = 9;
            "connection-id" = 16807;
            family = unix;
            host = "";
            port = "";
            tls = 0;
        };
        server =         {
            auth = none;
            family = unix;
            host = "";
            port = "";
        };
    };
    event = "SPICE_INITIALIZED";
    timestamp =     {
        microseconds = 716457;
        seconds = 1637903362;
    };
}
2021-11-25 23:09:22.716 UTM[302:10027] Debug JSON recieved <- {
    data =     {
        client =         {
            "channel-id" = 1;
            "channel-type" = 9;
            "connection-id" = 16807;
            family = unix;
            host = "";
            port = "";
            tls = 0;
        };
        server =         {
            auth = none;
            family = unix;
            host = "";
            port = "";
        };
    };
    event = "SPICE_INITIALIZED";
    timestamp =     {
        microseconds = 716457;
        seconds = 1637903362;
    };
}
Debug JSON recieved <- {
    data =     {
        client =         {
            "channel-id" = 0;
            "channel-type" = 9;
            "connection-id" = 16807;
            family = unix;
            host = "";
            port = "";
            tls = 0;
        };
        server =         {
            auth = none;
            family = unix;
            host = "";
            port = "";
        };
    };
    event = "SPICE_INITIALIZED";
    timestamp =     {
        microseconds = 717165;
        seconds = 1637903362;
    };
}
2021-11-25 23:09:22.717 UTM[302:10027] Debug JSON recieved <- {
    data =     {
        client =         {
            "channel-id" = 0;
            "channel-type" = 9;
            "connection-id" = 16807;
            family = unix;
            host = "";
            port = "";
            tls = 0;
        };
        server =         {
            auth = none;
            family = unix;
            host = "";
            port = "";
        };
    };
    event = "SPICE_INITIALIZED";
    timestamp =     {
        microseconds = 717165;
        seconds = 1637903362;
    };
}
qemu-system: warning: Spice: playback:0 (0x107119930): setsockopt failed, Operation not supported on socket
Debug JSON recieved <- {
    data =     {
        client =         {
            "channel-id" = 0;
            "channel-type" = 5;
            "connection-id" = 16807;
            family = unix;
            host = "";
            port = "";
            tls = 0;
        };
        server =         {
            auth = none;
            family = unix;
            host = "";
            port = "";
        };
    };
    event = "SPICE_INITIALIZED";
    timestamp =     {
        microseconds = 717843;
        seconds = 1637903362;
    };
}
2021-11-25 23:09:22.718 UTM[302:10026] Debug JSON recieved <- {
    data =     {
        client =         {
            "channel-id" = 0;
            "channel-type" = 5;
            "connection-id" = 16807;
            family = unix;
            host = "";
            port = "";
            tls = 0;
        };
        server =         {
            auth = none;
            family = unix;
            host = "";
            port = "";
        };
    };
    event = "SPICE_INITIALIZED";
    timestamp =     {
        microseconds = 717843;
        seconds = 1637903362;
    };
}
qemu-system: warning: Spice: record:0 (0x1071199e0): setsockopt failed, Operation not supported on socket
Debug JSON recieved <- {
    data =     {
        client =         {
            "channel-id" = 0;
            "channel-type" = 6;
            "connection-id" = 16807;
            family = unix;
            host = "";
            port = "";
            tls = 0;
        };
        server =         {
            auth = none;
            family = unix;
            host = "";
            port = "";
        };
    };
    event = "SPICE_INITIALIZED";
    timestamp =     {
        microseconds = 718521;
        seconds = 1637903362;
    };
}
2021-11-25 23:09:22.718 UTM[302:10027] Debug JSON recieved <- {
    data =     {
        client =         {
            "channel-id" = 0;
            "channel-type" = 6;
            "connection-id" = 16807;
            family = unix;
            host = "";
            port = "";
            tls = 0;
        };
        server =         {
            auth = none;
            family = unix;
            host = "";
            port = "";
        };
    };
    event = "SPICE_INITIALIZED";
    timestamp =     {
        microseconds = 718521;
        seconds = 1637903362;
    };
}
Debug JSON recieved <- {
    data =     {
        client =         {
            "channel-id" = 0;
            "channel-type" = 3;
            "connection-id" = 16807;
            family = unix;
            host = "";
            port = "";
            tls = 0;
        };
        server =         {
            auth = none;
            family = unix;
            host = "";
            port = "";
        };
    };
    event = "SPICE_INITIALIZED";
    timestamp =     {
        microseconds = 719189;
        seconds = 1637903362;
    };
}
2021-11-25 23:09:22.719 UTM[302:10026] Debug JSON recieved <- {
    data =     {
        client =         {
            "channel-id" = 0;
            "channel-type" = 3;
            "connection-id" = 16807;
            family = unix;
            host = "";
            port = "";
            tls = 0;
        };
        server =         {
            auth = none;
            family = unix;
            host = "";
            port = "";
        };
    };
    event = "SPICE_INITIALIZED";
    timestamp =     {
        microseconds = 719189;
        seconds = 1637903362;
    };
}
Debug JSON recieved <- {
    data =     {
        client =         {
            "channel-id" = 0;
            "channel-type" = 2;
            "connection-id" = 16807;
            family = unix;
            host = "";
            port = "";
            tls = 0;
        };
        server =         {
            auth = none;
            family = unix;
            host = "";
            port = "";
        };
    };
    event = "SPICE_INITIALIZED";
    timestamp =     {
        microseconds = 719836;
        seconds = 1637903362;
    };
}
2021-11-25 23:09:22.719 UTM[302:10027] Debug JSON recieved <- {
    data =     {
        client =         {
            "channel-id" = 0;
            "channel-type" = 2;
            "connection-id" = 16807;
            family = unix;
            host = "";
            port = "";
            tls = 0;
        };
        server =         {
            auth = none;
            family = unix;
            host = "";
            port = "";
        };
    };
    event = "SPICE_INITIALIZED";
    timestamp =     {
        microseconds = 719836;
        seconds = 1637903362;
    };
}
Debug JSON recieved <- {
    data =     {
        client =         {
            "channel-id" = 2;
            "channel-type" = 9;
            "connection-id" = 16807;
            family = unix;
            host = "";
            port = "";
            tls = 0;
        };
        server =         {
            auth = none;
            family = unix;
            host = "";
            port = "";
        };
    };
    event = "SPICE_INITIALIZED";
    timestamp =     {
        microseconds = 720484;
        seconds = 1637903362;
    };
}
2021-11-25 23:09:22.720 UTM[302:10026] Debug JSON recieved <- {
    data =     {
        client =         {
            "channel-id" = 2;
            "channel-type" = 9;
            "connection-id" = 16807;
            family = unix;
            host = "";
            port = "";
            tls = 0;
        };
        server =         {
            auth = none;
            family = unix;
            host = "";
            port = "";
        };
    };
    event = "SPICE_INITIALIZED";
    timestamp =     {
        microseconds = 720484;
        seconds = 1637903362;
    };
}
-[CSDisplayMetal initWithSession:channelID:monitorID:]:483
cs_channel_new:310
2021-11-25 23:09:22.721 UTM[302:10029] -[CSDisplayMetal initWithSession:channelID:monitorID:]:483
2021-11-25 23:09:22.721 UTM[302:10029] cs_channel_new:310
Debug JSON recieved <- {
    data =     {
        client =         {
            family = unix;
            host = "";
            port = "";
        };
        server =         {
            family = unix;
            host = "";
            port = "";
        };
    };
    event = "SPICE_CONNECTED";
    timestamp =     {
        microseconds = 721849;
        seconds = 1637903362;
    };
}
qemu-system: warning: GSpice: cursor-4:0: could not set sockopt TCP_NODELAY: Operation not supported on socket
2021-11-25 23:09:22.721 UTM[302:10026] Debug JSON recieved <- {
    data =     {
        client =         {
            family = unix;
            host = "";
            port = "";
        };
        server =         {
            family = unix;
            host = "";
            port = "";
        };
    };
    event = "SPICE_CONNECTED";
    timestamp =     {
        microseconds = 721849;
        seconds = 1637903362;
    };
}
Debug JSON recieved <- {
    data =     {
        client =         {
            "channel-id" = 0;
            "channel-type" = 4;
            "connection-id" = 16807;
            family = unix;
            host = "";
            port = "";
            tls = 0;
        };
        server =         {
            auth = none;
            family = unix;
            host = "";
            port = "";
        };
    };
    event = "SPICE_INITIALIZED";
    timestamp =     {
        microseconds = 731701;
        seconds = 1637903362;
    };
}
2021-11-25 23:09:22.731 UTM[302:10024] Debug JSON recieved <- {
    data =     {
        client =         {
            "channel-id" = 0;
            "channel-type" = 4;
            "connection-id" = 16807;
            family = unix;
            host = "";
            port = "";
            tls = 0;
        };
        server =         {
            auth = none;
            family = unix;
            host = "";
            port = "";
        };
    };
    event = "SPICE_INITIALIZED";
    timestamp =     {
        microseconds = 731701;
        seconds = 1637903362;
    };
}
gl_version 30 - es profile enabled
WARNING: running without ARB/KHR robustness in place may crash
Debug JSON recieved <- {
    data =     {
        path = "/machine/peripheral-anon/device[11]/virtio-backend";
    };
    event = "NIC_RX_FILTER_CHANGED";
    timestamp =     {
        microseconds = 790264;
        seconds = 1637903422;
    };
}
2021-11-25 23:10:22.790 UTM[302:10026] Debug JSON recieved <- {
    data =     {
        path = "/machine/peripheral-anon/device[11]/virtio-backend";
    };
    event = "NIC_RX_FILTER_CHANGED";
    timestamp =     {
        microseconds = 790264;
        seconds = 1637903422;
    };
}
qemu-system: warning: spice: no gl-draw-done within one second
GLSL feature level 130

```

</details> 

<details>
  <summary>VM config plist</summary>

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>ConfigurationVersion</key>
	<integer>2</integer>
	<key>Debug</key>
	<dict>
		<key>DebugLog</key>
		<true/>
	</dict>
	<key>Display</key>
	<dict>
		<key>ConsoleFont</key>
		<string>Menlo</string>
		<key>ConsoleFontSize</key>
		<integer>12</integer>
		<key>ConsoleOnly</key>
		<false/>
		<key>ConsoleTheme</key>
		<string>Default</string>
		<key>DisplayCard</key>
		<string>virtio-ramfb-gl</string>
		<key>DisplayDownscaler</key>
		<string>linear</string>
		<key>DisplayFitScreen</key>
		<false/>
		<key>DisplayRetina</key>
		<false/>
		<key>DisplayUpscaler</key>
		<string>linear</string>
	</dict>
	<key>Drives</key>
	<array>
		<dict>
			<key>DriveName</key>
			<string>drive0</string>
			<key>ImagePath</key>
			<string>disk-0.qcow2</string>
			<key>ImageType</key>
			<string>disk</string>
			<key>InterfaceType</key>
			<string>virtio</string>
		</dict>
		<dict>
			<key>DriveName</key>
			<string>drive1</string>
			<key>ImageType</key>
			<string>cd</string>
			<key>InterfaceType</key>
			<string>usb</string>
			<key>Removable</key>
			<true/>
		</dict>
		<dict>
			<key>DriveName</key>
			<string>DD1E6D47-27F0-40D2-840C-2474DC593913</string>
			<key>ImagePath</key>
			<string>efi_vars.fd</string>
			<key>ImageType</key>
			<string>none</string>
			<key>InterfaceType</key>
			<string></string>
		</dict>
	</array>
	<key>Info</key>
	<dict>
		<key>Icon</key>
		<string>ubuntu</string>
		<key>IconCustom</key>
		<false/>
	</dict>
	<key>Input</key>
	<dict>
		<key>InputInvertScroll</key>
		<true/>
		<key>InputLegacy</key>
		<false/>
	</dict>
	<key>Networking</key>
	<dict>
		<key>NetworkCard</key>
		<string>virtio-net-pci</string>
		<key>NetworkCardMAC</key>
		<string>4E:51:78:04:6D:AE</string>
		<key>NetworkMode</key>
		<string>emulated</string>
	</dict>
	<key>Printing</key>
	<dict/>
	<key>Sharing</key>
	<dict>
		<key>ClipboardSharing</key>
		<true/>
		<key>Usb3Support</key>
		<false/>
		<key>UsbRedirectMax</key>
		<integer>3</integer>
	</dict>
	<key>Sound</key>
	<dict>
		<key>SoundCard</key>
		<string>intel-hda</string>
		<key>SoundEnabled</key>
		<true/>
	</dict>
	<key>System</key>
	<dict>
		<key>Architecture</key>
		<string>aarch64</string>
		<key>BootDevice</key>
		<string></string>
		<key>BootUefi</key>
		<true/>
		<key>CPU</key>
		<string>cortex-a72</string>
		<key>JITCacheSize</key>
		<integer>0</integer>
		<key>MachineProperties</key>
		<string>highmem=off</string>
		<key>Memory</key>
		<integer>1024</integer>
		<key>SystemUUID</key>
		<string>0DEF0A70-1F0D-48D0-838B-4D3FF8241C56</string>
		<key>Target</key>
		<string>virt</string>
	</dict>
</dict>
</plist>
```
</details>

**Comment by conath** [comment] 2021-11-28 16:02
Thank you for the detailed issue report.

This looks like a possible duplicate of #2743 or related problem. From the Debug Log I can see we have a GL-related crash. The VM session starts and the GL backend kicks in, logs these two lines and then it crashes:

`qemu-system: warning: spice: no gl-draw-done within one second`
`GLSL feature level 130`

To work around the crash, please change the VM config => Display => Emulated Display Card to "virtio-ramfb" (note no `-gl` at the end), then start your VM again. Should no longer crash, but may slow down graphics a bit.

**Comment by Sinemora10** [comment] 2021-11-30 03:26
Workaround is effective, preventing further crashes. Unfortunately, the loss of performance is significant in certain DE using a compositor with 3D acceleration (e.g. compiz). Is there a better solution in the works?

**Comment by conath** [comment] 2021-12-11 17:51
Duplicate of #2743

**Closed by conath** 2021-12-11 17:51 UTC
Labels: crash, iOS
