### ISSUE TITLE
Bridged Networking Status

### ISSUE THREAD

**Issue by tiiiecherle** [utmapp/UTM#2598] opened 2021-06-07 09:20 UTC
Hey,

again thanks for this project and all the effort put into it. Really appreciated.

My most important issue is the missing bridged networking on macOS. I searched the old issued but did not get the current or planed status correctly.

As the tuntap project is deprecated the only tuntap I know is the notarized one from here [https://github.com/Tunnelblick/Tunnelblick/tree/master/third_party](https://github.com/Tunnelblick/Tunnelblick/tree/master/third_party).

I don't know a lot about it but parallels seems to use another way to add bridged networking.

It would be very nice if bridged networking could be added/integrated to utm and made configurable via the GUI.

Thanks in advance

**Comment by osy** [comment] 2021-06-07 16:06
Duplicate of #358

it’s actually implemented but can’t be used until apple fixes a bug in macos

**Closed by osy** 2021-06-07 16:06 UTC
Labels: duplicate
