### ISSUE TITLE
Menu Bar Bug

### ISSUE THREAD

**Issue by shadoez** [utmapp/UTM#3973] opened 2022-05-02 21:34 UTC
**Describe the issue**
A small issue with Monterey's new "Automatically hide and show the menu bar in full screen" option. While in full screen in any VM, the menu bar seems to conflict with the header of UTM's window.
<img width="780" alt="Screen Shot 2022-05-02 at 5 20 18 PM" src="https://user-images.githubusercontent.com/66450433/166330918-7e080379-a7a4-41eb-ba21-e5e35663c8f8.png">

https://user-images.githubusercontent.com/66450433/166331229-5f11adc5-cc8e-4f4e-a9e8-7f2d1ef6ac3d.mp4

**Configuration**
* UTM Version: 3.1.5
* OS Version: 12.3.1
* Intel or Apple Silicon? Apple Silicon

**Comment by osy** [comment] 2022-05-06 02:09
Probably related to #3919

**Comment by HilbertIdeals5** [comment] 2022-05-06 15:06
I don't know if anyone's still looking at this issue, but I wanted to add that on my MacBook Air (M1 2020), the situation has an additional problem where _the bottom part of the emulator's screen is cut._

Here's a link to a screenshot: https://drive.google.com/file/d/1VPFX1a84C__2nZ1EQhq9ixbaGpxZey6Y/view?usp=sharing

Two problems:
1. Fullscreen behavior on the top is _quite_ funky! The window bar is cut off and sticks out, which is distracting and never happens in any other fullscreen situation. In addition, there's the poster's issue with the menu bar not being seen.
2. I can hardly see the taskbar because the content is outside of the display! Funnily enough, it gets fixed when I select a button at the top (like the Power button), then press "Cancel" or the like—then it behaves as expected and shrinks to fit the screen. However, the issue comes back if I swipe out of the space and back in (like with desktop switching, swiping left/right with three fingers).

Interestingly, taking a screenshot of the window shows the full emulator screen and top bar, instead of them being cut off.

I haven't tested this with "Automatically hide and show menu bar" turned on.

**Comment by osy** [comment] 2022-05-13 04:08
Duplicate of #3919

**Closed by osy** 2022-05-13 04:08 UTC
Labels: duplicate
