### ISSUE TITLE
Poor shared directory support

### ISSUE THREAD

**Issue by Jaiganeshkumaran** [utmapp/UTM#3077] opened 2021-09-02 08:33 UTC
**Describe the issue**
Currently the shared directory support is extremely buggy and slow, at least on a Windows guest.

1. File Explorer doesn't automatically refresh when the shared directory changes even if the change is made through the guest.
2. Can't save files within apps sometimes (getting path not valid error).
3. Slow write/copy/move operations.
4. UTM lets you power off the VM while a transfer is happening to/from the shared directory. I would expect UTM to show a warning or at least attempt to cancel the transfer operation before powering off to prevent data loss.

**Configuration**
* UTM Version: 2.2.0 (32)
* OS Version: 10.0.21354.1
* Intel or Apple Silicon? Apple Silicon

**Comment by osy** [comment] 2021-09-04 03:54
Unfortunate effect of using SPICE. 9pfs would be better but is not currently supported. #2551 keeps track of that. I will close this issue because it's the "intended behavior" as bad as it is...

**Closed by osy** 2021-09-04 03:54 UTC
