### ISSUE TITLE
ARM machines do not work

### ISSUE THREAD

**Issue by Andrupka** [utmapp/UTM#700] opened 2020-11-26 11:19 UTC
**Describe the bug**
Every ARM machine does not boot

**Version**
2.0.10
**To Reproduce**
1. Create ARM VM
2. Boot it
3. See error

**Expected behavior**
Machine should boot to raspbian

**Screenshots**
<img width="912" alt="Снимок экрана 2020-11-23 в 17 47 00" src="https://user-images.githubusercontent.com/74910987/100344711-4ddf4100-2ff2-11eb-9eb1-946999fa373e.png">

**Comment by osy86** [comment] 2020-11-26 13:33
Duplicate of #567

**Closed by osy86** 2020-11-26 13:33 UTC
Labels: duplicate
