### ISSUE TITLE
Unable to create a VM using default settings on macOS Ventura

### ISSUE THREAD

**Issue by built2order** [utmapp/UTM#4663] opened 2022-11-13 09:42 UTC
**Describe the issue**  
On a clean installation of macOS Ventura, installing UTM and creating a VM using default options results in the error "This virtual machine cannot be run on this machine"

**Configuration**  
* UTM Version: 4.0.9
* macOS Version: 13.0.1
* Mac Chip (Intel, M1, ...): M1

**Crash log**  
N/A

**Debug log**  
N/A

**Upload VM**  
[config.plist.txt](https://github.com/utmapp/UTM/files/9996878/config.plist.txt)
<img width="1012" alt="Screenshot 2022-11-13 at 8 32 22 pm" src="https://user-images.githubusercontent.com/6132811/201515446-157d38b7-1de6-4f75-b102-150f29550541.png">

**Comment by DJZSwag** [comment] 2022-11-13 09:47
This is a dup, as there is already an issue about this, so consider closing this.

**Comment by DJZSwag** [comment] 2022-11-13 09:47
The issue: https://github.com/utmapp/UTM/discussions/4653

**Comment by osy** [comment] 2022-11-23 00:45
Duplicate of #4595

**Closed by osy** 2022-11-23 00:45 UTC
Labels: macOS
