### ISSUE TITLE
UTM crash pls read!

### ISSUE THREAD

**Issue by Matoo69** [utmapp/UTM#173] opened 2020-03-24 13:16 UTC
Hey,i have iPhone 11 pro max 256gb ios 13.4GM

I download and install utm last build over appcake i open utm,configure win 7/xp + ofc disk and tap on play button the window popup like its going to start but secend after that utm crash so its not instant crash when tapping on ply button like before... 

Any help?

**Comment by osy86** [comment] 2020-03-24 18:11
Duplicate of #95 

Speaking of reading, have you ever considered reading the readme? Or the install page? Or the sticky post when you went to the issues page? Or when you clicked the button to create a new issue and typed in the header and it gave you a list of similar issues? Or the part where you missed the button for reporting a crash that tells you to read the sticky post?

**Closed by osy86** 2020-03-24 18:11 UTC
