### ISSUE TITLE
Can't boot vm on macOS(arm64)

### ISSUE THREAD

**Issue by jingdianjd** [utmapp/UTM#524] opened 2020-11-10 03:06 UTC
**Describe the bug**
Once I Start the vm, it shows up "An internal error has occurred"

**Version**
v2.0.8
OS: macOS Big Sur 11.0.1 beta(20B5022A)

**To Reproduce**
1. Create an VM
2. Click start icon.
3. "An internal error has occurred"

**Screenshots**
![Screen Shot 2020-11-10 at 11.05.45 AM.png](https://i.loli.net/2020/11/10/YTlrESjLusVF8fw.png)

**Additional context**
XCODE OUTPUT:
```
2020-11-10 11:02:43.959401+0800 UTM[4803:91416] Metal API Validation Enabled
2020-11-10 11:02:44.022629+0800 UTM[4803:91416] -[CSConnection init]:251
2020-11-10 11:02:44.026492+0800 UTM[4803:91801] SPICE port not in use yet, retries left: 29
2020-11-10T11:02:38+0800 info com.utmapp.UTM : JIT: debugger attached
2020-11-10 11:02:43.959133+0800 UTM[4803:91416] Metal GPU Frame Capture Enabled
2020-11-10 11:02:43.959401+0800 UTM[4803:91416] Metal API Validation Enabled
2020-11-10 11:02:44.022629+0800 UTM[4803:91416] -[CSConnection init]:251
2020-11-10 11:02:44.026492+0800 UTM[4803:91801] SPICE port not in use yet, retries left: 29
2020-11-10 11:02:44.073084+0800 UTM[4803:91801] [connection] nw_socket_handle_socket_event [C1:1] Socket SO_ERROR [61: Connection refused]
2020-11-10 11:02:44.073376+0800 UTM[4803:91807] [connection] nw_connection_get_connected_socket [C1] Client called nw_connection_get_connected_socket on unconnected nw_connection
2020-11-10 11:02:44.073431+0800 UTM[4803:91807] TCP Conn 0x600003cc1810 Failed : error 0:61 [61]
2020-11-10 11:02:44.073841+0800 UTM[4803:91807] Stream error Error Domain=NSPOSIXErrorDomain Code=61 "Connection refused" UserInfo={_kCFStreamErrorCodeKey=61, _kCFStreamErrorDomainKey=1}
2020-11-10 11:02:44.074022+0800 UTM[4803:91807] QMP stream error seen: Error Domain=NSPOSIXErrorDomain Code=61 "Connection refused" UserInfo={_kCFStreamErrorCodeKey=61, _kCFStreamErrorDomainKey=1}
2020-11-10 11:02:44.074527+0800 UTM[4803:91807] QMP connection failed, retries left: 29
2020-11-10 11:02:45.122159+0800 UTM[4803:91807] SPICE port not in use yet, retries left: 28
2020-11-10 11:02:45.122718+0800 UTM[4803:91803] [connection] nw_socket_handle_socket_event [C2:1] Socket SO_ERROR [61: Connection refused]
2020-11-10 11:02:45.123353+0800 UTM[4803:91801] [connection] nw_connection_get_connected_socket [C2] Client called nw_connection_get_connected_socket on unconnected nw_connection
2020-11-10 11:02:45.123654+0800 UTM[4803:91801] TCP Conn 0x600003cc4bb0 Failed : error 0:61 [61]
2020-11-10 11:02:45.123906+0800 UTM[4803:91801] Stream error Error Domain=NSPOSIXErrorDomain Code=61 "Connection refused" UserInfo={_kCFStreamErrorCodeKey=61, _kCFStreamErrorDomainKey=1}
2020-11-10 11:02:45.123979+0800 UTM[4803:91801] QMP stream error seen: Error Domain=NSPOSIXErrorDomain Code=61 "Connection refused" UserInfo={_kCFStreamErrorCodeKey=61, _kCFStreamErrorDomainKey=1}
2020-11-10 11:02:45.124279+0800 UTM[4803:91801] QMP connection failed, retries left: 28
2020-11-10 11:02:46.224173+0800 UTM[4803:91807] SPICE port not in use yet, retries left: 27
2020-11-10 11:02:46.225148+0800 UTM[4803:91803] [connection] nw_socket_handle_socket_event [C3:1] Socket SO_ERROR [61: Connection refused]
2020-11-10 11:02:46.226193+0800 UTM[4803:91801] [connection] nw_connection_get_connected_socket [C3] Client called nw_connection_get_connected_socket on unconnected nw_connection
2020-11-10 11:02:46.226531+0800 UTM[4803:91801] TCP Conn 0x600003cdc000 Failed : error 0:61 [61]
2020-11-10 11:02:46.226947+0800 UTM[4803:91801] Stream error Error Domain=NSPOSIXErrorDomain Code=61 "Connection refused" UserInfo={_kCFStreamErrorCodeKey=61, _kCFStreamErrorDomainKey=1}
2020-11-10 11:02:46.227120+0800 UTM[4803:91801] QMP stream error seen: Error Domain=NSPOSIXErrorDomain Code=61 "Connection refused" UserInfo={_kCFStreamErrorCodeKey=61, _kCFStreamErrorDomainKey=1}
2020-11-10 11:02:46.227478+0800 UTM[4803:91801] QMP connection failed, retries left: 27
2020-11-10 11:02:47.323626+0800 UTM[4803:91807] SPICE port not in use yet, retries left: 26
2020-11-10 11:02:47.326534+0800 UTM[4803:91807] [connection] nw_socket_handle_socket_event [C4:1] Socket SO_ERROR [61: Connection refused]
2020-11-10 11:02:47.327002+0800 UTM[4803:91803] [connection] nw_connection_get_connected_socket [C4] Client called nw_connection_get_connected_socket on unconnected nw_connection
2020-11-10 11:02:47.327106+0800 UTM[4803:91803] TCP Conn 0x600003cd82c0 Failed : error 0:61 [61]
2020-11-10 11:02:47.327357+0800 UTM[4803:91803] Stream error Error Domain=NSPOSIXErrorDomain Code=61 "Connection refused" UserInfo={_kCFStreamErrorCodeKey=61, _kCFStreamErrorDomainKey=1}
2020-11-10 11:02:47.327485+0800 UTM[4803:91803] QMP stream error seen: Error Domain=NSPOSIXErrorDomain Code=61 "Connection refused" UserInfo={_kCFStreamErrorCodeKey=61, _kCFStreamErrorDomainKey=1}
2020-11-10 11:02:47.327671+0800 UTM[4803:91803] QMP connection failed, retries left: 26
qemu-system-x86_64: -accel hvf: invalid accelerator hvf
qemu-system-x86_64: -accel tcg,mirror-rwx=on: Property '.mirror-rwx' not found
2020-11-10 11:02:48.421338+0800 UTM[4803:91803] SPICE port not in use yet, retries left: 25
2020-11-10 11:02:48.712551+0800 UTM[4803:91807] [connection] nw_socket_handle_socket_event [C5:1] Socket SO_ERROR [61: Connection refused]
2020-11-10 11:02:48.713338+0800 UTM[4803:91817] [connection] nw_connection_get_connected_socket [C5] Client called nw_connection_get_connected_socket on unconnected nw_connection
2020-11-10 11:02:48.713704+0800 UTM[4803:91817] TCP Conn 0x600003cd11e0 Failed : error 0:61 [61]
2020-11-10 11:02:48.713992+0800 UTM[4803:91817] Stream error Error Domain=NSPOSIXErrorDomain Code=61 "Connection refused" UserInfo={_kCFStreamErrorCodeKey=61, _kCFStreamErrorDomainKey=1}
2020-11-10 11:02:48.714060+0800 UTM[4803:91817] QMP stream error seen: Error Domain=NSPOSIXErrorDomain Code=61 "Connection refused" UserInfo={_kCFStreamErrorCodeKey=61, _kCFStreamErrorDomainKey=1}
2020-11-10 11:02:48.714326+0800 UTM[4803:91817] QMP connection failed, retries left: 25
2020-11-10 11:02:49.523544+0800 UTM[4803:91807] SPICE port not in use yet, retries left: 24
2020-11-10 11:02:49.816929+0800 UTM[4803:91807] [connection] nw_socket_connect [C6:1] connectx(17, [srcif=0, srcaddr=<NULL>, dstaddr=127.0.0.1:4000], SAE_ASSOCID_ANY, 0, NULL, 0, NULL, SAE_CONNID_ANY) failed: [61: Connection refused]
2020-11-10 11:02:49.817227+0800 UTM[4803:91807] [connection] nw_socket_connect [C6:1] connectx failed (fd 17) [61: Connection refused]
2020-11-10 11:02:49.817341+0800 UTM[4803:91807] [] nw_socket_connect connectx failed [61: Connection refused]
2020-11-10 11:02:49.818534+0800 UTM[4803:91801] [connection] nw_connection_get_connected_socket [C6] Client called nw_connection_get_connected_socket on unconnected nw_connection
2020-11-10 11:02:49.818901+0800 UTM[4803:91801] TCP Conn 0x600003cdc000 Failed : error 0:61 [61]
2020-11-10 11:02:49.819296+0800 UTM[4803:91801] Stream error Error Domain=NSPOSIXErrorDomain Code=61 "Connection refused" UserInfo={_kCFStreamErrorCodeKey=61, _kCFStreamErrorDomainKey=1}
2020-11-10 11:02:49.819659+0800 UTM[4803:91801] QMP stream error seen: Error Domain=NSPOSIXErrorDomain Code=61 "Connection refused" UserInfo={_kCFStreamErrorCodeKey=61, _kCFStreamErrorDomainKey=1}
2020-11-10 11:02:49.819901+0800 UTM[4803:91801] QMP connection failed, retries left: 24
2020-11-10 11:02:50.574035+0800 UTM[4803:91801] SPICE port not in use yet, retries left: 23
2020-11-10 11:02:50.919036+0800 UTM[4803:91801] [connection] nw_socket_handle_socket_event [C7:1] Socket SO_ERROR [61: Connection refused]
2020-11-10 11:02:50.919867+0800 UTM[4803:91807] [connection] nw_connection_get_connected_socket [C7] Client called nw_connection_get_connected_socket on unconnected nw_connection
2020-11-10 11:02:50.920248+0800 UTM[4803:91807] TCP Conn 0x600003cd4000 Failed : error 0:61 [61]
2020-11-10 11:02:50.920647+0800 UTM[4803:91807] Stream error Error Domain=NSPOSIXErrorDomain Code=61 "Connection refused" UserInfo={_kCFStreamErrorCodeKey=61, _kCFStreamErrorDomainKey=1}
2020-11-10 11:02:50.920918+0800 UTM[4803:91807] QMP stream error seen: Error Domain=NSPOSIXErrorDomain Code=61 "Connection refused" UserInfo={_kCFStreamErrorCodeKey=61, _kCFStreamErrorDomainKey=1}
2020-11-10 11:02:50.921415+0800 UTM[4803:91807] QMP connection failed, retries left: 23
2020-11-10 11:02:51.673833+0800 UTM[4803:91807] SPICE port not in use yet, retries left: 22
2020-11-10 11:02:52.024956+0800 UTM[4803:91807] [connection] nw_socket_handle_socket_event [C8:1] Socket SO_ERROR [61: Connection refused]
2020-11-10 11:02:52.025717+0800 UTM[4803:91801] [connection] nw_connection_get_connected_socket [C8] Client called nw_connection_get_connected_socket on unconnected nw_connection
2020-11-10 11:02:52.026043+0800 UTM[4803:91801] TCP Conn 0x600003cd4000 Failed : error 0:61 [61]
2020-11-10 11:02:52.026600+0800 UTM[4803:91801] Stream error Error Domain=NSPOSIXErrorDomain Code=61 "Connection refused" UserInfo={_kCFStreamErrorCodeKey=61, _kCFStreamErrorDomainKey=1}
2020-11-10 11:02:52.027104+0800 UTM[4803:91801] QMP stream error seen: Error Domain=NSPOSIXErrorDomain Code=61 "Connection refused" UserInfo={_kCFStreamErrorCodeKey=61, _kCFStreamErrorDomainKey=1}
2020-11-10 11:02:52.027625+0800 UTM[4803:91801] QMP connection failed, retries left: 22
2020-11-10 11:02:52.774190+0800 UTM[4803:91817] SPICE port not in use yet, retries left: 21
2020-11-10 11:02:53.125422+0800 UTM[4803:91817] [connection] nw_socket_handle_socket_event [C9:1] Socket SO_ERROR [61: Connection refused]
2020-11-10 11:02:53.125929+0800 UTM[4803:91807] [connection] nw_connection_get_connected_socket [C9] Client called nw_connection_get_connected_socket on unconnected nw_connection
2020-11-10 11:02:53.126238+0800 UTM[4803:91807] TCP Conn 0x600003cdc000 Failed : error 0:61 [61]
2020-11-10 11:02:53.126593+0800 UTM[4803:91807] Stream error Error Domain=NSPOSIXErrorDomain Code=61 "Connection refused" UserInfo={_kCFStreamErrorCodeKey=61, _kCFStreamErrorDomainKey=1}
2020-11-10 11:02:53.126934+0800 UTM[4803:91807] QMP stream error seen: Error Domain=NSPOSIXErrorDomain Code=61 "Connection refused" UserInfo={_kCFStreamErrorCodeKey=61, _kCFStreamErrorDomainKey=1}
2020-11-10 11:02:53.127357+0800 UTM[4803:91807] QMP connection failed, retries left: 21
2020-11-10 11:02:53.873248+0800 UTM[4803:91817] SPICE port not in use yet, retries left: 20
2020-11-10 11:02:54.225038+0800 UTM[4803:91817] [connection] nw_socket_handle_socket_event [C10:1] Socket SO_ERROR [61: Connection refused]
2020-11-10 11:02:54.225588+0800 UTM[4803:91801] [connection] nw_connection_get_connected_socket [C10] Client called nw_connection_get_connected_socket on unconnected nw_connection
2020-11-10 11:02:54.225885+0800 UTM[4803:91801] TCP Conn 0x600003cd42c0 Failed : error 0:61 [61]
2020-11-10 11:02:54.226497+0800 UTM[4803:91801] Stream error Error Domain=NSPOSIXErrorDomain Code=61 "Connection refused" UserInfo={_kCFStreamErrorCodeKey=61, _kCFStreamErrorDomainKey=1}
2020-11-10 11:02:54.226737+0800 UTM[4803:91801] QMP stream error seen: Error Domain=NSPOSIXErrorDomain Code=61 "Connection refused" UserInfo={_kCFStreamErrorCodeKey=61, _kCFStreamErrorDomainKey=1}
2020-11-10 11:02:54.227043+0800 UTM[4803:91801] QMP connection failed, retries left: 20
2020-11-10 11:02:54.973209+0800 UTM[4803:91803] SPICE port not in use yet, retries left: 19
2020-11-10 11:02:55.324574+0800 UTM[4803:91803] [connection] nw_socket_handle_socket_event [C11:1] Socket SO_ERROR [61: Connection refused]
2020-11-10 11:02:55.325860+0800 UTM[4803:91817] [connection] nw_connection_get_connected_socket [C11] Client called nw_connection_get_connected_socket on unconnected nw_connection
2020-11-10 11:02:55.326403+0800 UTM[4803:91817] TCP Conn 0x600003cdc000 Failed : error 0:61 [61]
2020-11-10 11:02:55.326769+0800 UTM[4803:91817] Stream error Error Domain=NSPOSIXErrorDomain Code=61 "Connection refused" UserInfo={_kCFStreamErrorCodeKey=61, _kCFStreamErrorDomainKey=1}
2020-11-10 11:02:55.327112+0800 UTM[4803:91817] QMP stream error seen: Error Domain=NSPOSIXErrorDomain Code=61 "Connection refused" UserInfo={_kCFStreamErrorCodeKey=61, _kCFStreamErrorDomainKey=1}
2020-11-10 11:02:55.327324+0800 UTM[4803:91817] QMP connection failed, retries left: 19
2020-11-10 11:02:56.073525+0800 UTM[4803:91808] SPICE port not in use yet, retries left: 18
2020-11-10 11:02:56.425015+0800 UTM[4803:91808] [connection] nw_socket_handle_socket_event [C12:1] Socket SO_ERROR [61: Connection refused]
2020-11-10 11:02:56.425533+0800 UTM[4803:91801] [connection] nw_connection_get_connected_socket [C12] Client called nw_connection_get_connected_socket on unconnected nw_connection
2020-11-10 11:02:56.425813+0800 UTM[4803:91801] TCP Conn 0x600003cd8000 Failed : error 0:61 [61]
2020-11-10 11:02:56.426171+0800 UTM[4803:91801] Stream error Error Domain=NSPOSIXErrorDomain Code=61 "Connection refused" UserInfo={_kCFStreamErrorCodeKey=61, _kCFStreamErrorDomainKey=1}
2020-11-10 11:02:56.426341+0800 UTM[4803:91801] QMP stream error seen: Error Domain=NSPOSIXErrorDomain Code=61 "Connection refused" UserInfo={_kCFStreamErrorCodeKey=61, _kCFStreamErrorDomainKey=1}
2020-11-10 11:02:56.426887+0800 UTM[4803:91801] QMP connection failed, retries left: 18
```

**Comment by osy86** [comment] 2020-11-10 16:05
This should be fixed next release or you can try one of the more recent github actions build.

**Comment by jingdianjd** [comment] 2020-11-11 10:57
> This should be fixed next release or you can try one of the more recent github actions build.

There is still an internal error problem. I will try to restore my DTK and try again.

**Comment by osy86** [comment] 2020-11-15 19:24
I was able to reproduce this error on the DTK. It looks like an Apple error.

**Comment by brunocastello** [comment] 2020-11-16 13:30
I have a similar issue. UTM 2.0.9, macOS Big Sur. I get a message saying that the app is damaged and wants to delete it.

**Comment by kjwamlex** [comment] 2020-11-19 05:12
Has anyone tried latest macOS Big Sur Beta? Maybe that one fixes it?

**Comment by osy86** [comment] 2020-11-19 15:33
Unfortunately still broken on 11.1 beta 1, DTK.

**Comment by osy86** [comment] 2020-11-22 04:43
Should be fixed on latest build as long as you’re not running from Xcode debugger.

**Closed by osy86** 2020-11-22 04:43 UTC
Labels: crash, macOS
