### ISSUE TITLE
I can’t open macOS 9

### ISSUE THREAD

**Issue by Ffwtc** [utmapp/UTM#6523] opened 2024-07-28 22:59 UTC
**Describe the issue**
A clear and concise description of what the issue is. **BEFORE SUBMITTING YOUR ISSUE, PLEASE LOOK AT THE PINNED ISSUES AND USE THE SEARCH FUNCTION TO MAKE SURE IT IS NOT ALREADY REPORTED. ALWAYS COMMENT ON AN EXISTING ISSUE INSTEAD OF MAKING A NEW ONE.** when I open Mac OS it takes me to the Home Screen even tho I applied the correct settings to the vm

**Configuration (required)**
* UTM Version: 4.5.3
* OS Version: ipadOS 18
* Device Model: iPad 7th generation (10.2 2019)
* Is it jailbroken (name jailbreak used)? No
* How did you install UTM? AppStore

**Crash log**
If the app crashed, you need a crash log. To get your crash log, open the Settings app and browse to `Privacy -> Analytics & Improvements -> Analytics Data` and find the latest entry for UTM. You should export the text and attach it here.

https://github.com/user-attachments/assets/45b37260-8931-4d71-9896-01f5bab6ff2e

**Debug log**
For all issues, _including_ crashes, you should attach a debug log. Open UTM, and open the settings for the VM you wish to launch. Near the bottom of the configuration options (or at the top of the `QEMU` page) is `Debug Log`. Turn it on and save the VM. After you experience the issue, quit the VM and re-launch UTM. Open the VM settings again and select `Export Log...` and attach it here.

**Upload VM**
(Optional) If possible, upload the `config.plist` inside the `.utm`. If you do not have this, you can upload the entire `.utm` but note this contains your personal data. Since GitHub has an attachment size limit, you may want to upload to another service such as Google Drive. Link it here.

**Comment by lgrachov** [comment] 2024-08-21 16:29
Same! I am on iOS 17.5.1 and I am having this issue.

**Comment by osy** [comment] 2024-08-22 15:11
Please provide the debug log and crash log as specified in the template.

**Comment by Timopotomus** [comment] 2024-09-05 00:34
I’ve got the same issue as well.  My configuration is slightly different, but here’s the debug & crash logs + config.plist. 
Apologies for the ZIP, seems to be the only way to upload anything other than the LOG file.
[utm_crash_logs.zip](https://github.com/user-attachments/files/16882352/utm_crash_logs.zip)


UTM Version: 4.5.4, build 101
OS Version: ipadOS 17.6.1
Device Model: iPad Air 5th generation (A2588)
Is it jailbroken (name jailbreak used)? No
How did you install UTM? App Store

**Comment by VShrubowich** [comment] 2024-09-19 08:20
Same issue here:
- UTM Version: UTM SE 4.5.4
- OS Version: iOS 17.6.1
- Device Model: iPhone 15 Pro Max
- Is it jailbroken (name jailbreak used)? No
- How did you install UTM? Apple App Store

It appears that the issue is with 32-bit CPUs (PowerPC, i386 - see issue [#5925](https://github.com/utmapp/UTM/issues/5925), and possibly RISC-V32).


## Workaround ##

To work around this issue, I switched the VM's **Architecture** to `PowerPC64`. (I then had to go into **QEMU** settings and re-enable `Use local time for base clock` and re-add `via=pmu` under **QEMU MACHINE PROPERTIES**.) After that, the pre-built macOS VM powered up without UTM SE crashing.

However, now the VM was getting stuck on the OpenBIOS boot screen with `No valid state has been set by load or init-program`. To resolve that, I added `-cpu G3` to the end of the **QEMU ARGUMENTS** in **QEMU** settings. I split it up into two lines like the other arguments:

![image](https://github.com/user-attachments/assets/59c02a81-4f72-4280-8bbc-6be34caff971)

Now, about half a minute after powering up the VM, I'm greeted with the **Mac OS 9.2** splash screen and eventually the Mac OS desktop!

> [!NOTE]
> The OpenBIOS screen will show a `get-key-map` exception and an `unable to find a usable NVRAM partition` message. Both can be safely ignored.

**Comment by osy** [comment] 2024-10-04 16:27
Please this on v4.6.0 https://github.com/utmapp/UTM/releases

**Comment by osy** [comment] 2024-11-27 21:26
Fixed in v4.6

**Closed by osy** 2024-11-27 21:26 UTC
