### ISSUE TITLE
QEMU exited with error: qemu-system: -device piix4-ide,id=ide0: "piix4-ide" is not a valid device model name

### ISSUE THREAD

**Issue by CodeRuner5235** [utmapp/UTM#4391] opened 2022-09-08 22:36 UTC
Boots with only the cd/rom ide drive. If I add a ide HD, it fails with this error. 

**PPC64 mac99 g4 512mb**
* UTM Version: 4.0.3
* OS Version: iOS 15.1
* Device Model: iPhone 11
* Jailbroken: no
* Installed with altstore 
* 
[debug.log](https://github.com/utmapp/UTM/files/9531005/debug.log)

These are the qemu arguments: 
qemu-system-ppc64 -L /private/var/containers/Bundle/Application/62AFF743-2113-463B-B2F2-FD548F03A4E6/App.app/qemu -S -spice unix=on,addr=/private/var/mobile/Containers/Data/Application/5E604520-C4CE-41EF-9C92-DA56551F4DDB/tmp/C2DA1440-DE32-485F-87E8-7E4A03AB0311.spice,disable-ticketing=on,image-compression=off,playback-compression=off,streaming-video=off,gl=off -chardev spiceport,id=org.qemu.monitor.qmp,name=org.qemu.monitor.qmp.0 -mon chardev=org.qemu.monitor.qmp,mode=control -nodefaults -vga none -device VGA -cpu g4 -smp cpus=1,sockets=1,cores=1,threads=1 -machine mac99,via=pmu -accel tcg,tb-size=192,split-wx=on -m 768 -usb -device usb-tablet,bus=usb-bus.0 -device usb-mouse,bus=usb-bus.0 -device usb-kbd,bus=usb-bus.0 -device ich9-usb-ehci1,id=usb-controller-0 -device ich9-usb-uhci1,masterbus=usb-controller-0.0,firstport=0,multifunction=on -device ich9-usb-uhci2,masterbus=usb-controller-0.0,firstport=2,multifunction=on -device ich9-usb-uhci3,masterbus=usb-controller-0.0,firstport=4,multifunction=on -chardev spicevmc,name=usbredir,id=usbredirchardev0 -device usb-redir,chardev=usbredirchardev0,id=usbredirdev0,bus=usb-controller-0.0 -chardev spicevmc,name=usbredir,id=usbredirchardev1 -device usb-redir,chardev=usbredirchardev1,id=usbredirdev1,bus=usb-controller-0.0 -chardev spicevmc,name=usbredir,id=usbredirchardev2 -device usb-redir,chardev=usbredirchardev2,id=usbredirdev2,bus=usb-controller-0.0 -device piix4-ide,id=ide0 -device ide-cd,bus=ide0.0,drive=drive4D7BA451-D80F-4278-B84F-10DED65933A7,bootindex=0 -drive "if=none,media=cdrom,id=drive4D7BA451-D80F-4278-B84F-10DED65933A7,file=/private/var/mobile/Containers/Data/Application/5E604520-C4CE-41EF-9C92-DA56551F4DDB/Documents/Apple Mac OS X 10.3.0 - Disk 1.iso" -device ide-hd,bus=ide0.1,drive=driveD12FFB31-3251-459A-A19F-63AC8158F03D,bootindex=1 -drive "if=none,media=disk,id=driveD12FFB31-3251-459A-A19F-63AC8158F03D,file=/private/var/mobile/Containers/Data/Application/5E604520-C4CE-41EF-9C92-DA56551F4DDB/Documents/Virtual Machine.utm/Data/D12FFB31-3251-459A-A19F-63AC8158F03D.qcow2,discard=unmap,detect-zeroes=unmap" -device e1000e,mac=94:FB:DF:F1:33:E2,netdev=net0 -netdev user,id=net0 -name "Virtual Machine" -uuid C2DA1440-DE32-485F-87E8-7E4A03AB0311 -rtc base=localtime

**Comment by osy** [comment] 2022-09-10 16:03
Duplicate of #4384

**Closed by osy** 2022-09-10 16:03 UTC
