### ISSUE TITLE
No internet connection under Ubuntu 20.04

### ISSUE THREAD

**Issue by F3000** [utmapp/UTM#2523] opened 2021-05-14 15:51 UTC
**Describe the issue**

Network connection for a Ubuntu 20.04 guest doesn't work . 
All network adapters didn't work 

**Configuration**
* UTM Version: 
* OS Version: 11.2
* Intel or Apple Silicon? Silicon 

**Crash log**
If the app crashed, you need a crash log. To get your crash log, open Console.app, go to `Crash Reports`, and find the latest entry for either QEMU, QEMUHelper, or qemu-\*. Right click and choose `Reveal in Finder`. Attach the report here.

**Debug log**
For all issues, _including_ crashes, you should attach a debug log. Open UTM, and open the settings for the VM you wish to launch. Near the top of the `QEMU` page is `Debug Log`. Turn it on and save the VM. After you experience the issue, open the VM settings again and select `Export Log...` and attach it here.

**Upload VM**
(Optional) If possible, upload the `config.plist` inside the `.utm`. If you do not have this, you can upload the entire `.utm` but note this contains your personal data. Since Github has an attachment size limit, you may want to upload to another service such as Google Drive. Link it here.

All networks adapters which UTM offer doesent work in the VM

**Comment by osy** [comment] 2021-05-16 00:47
Duplicate of #2353

**Closed by osy** 2021-05-16 00:47 UTC
Labels: duplicate
