### ISSUE TITLE
UI: Ability to organize VM into folders

### ISSUE THREAD

**Issue by telefax** [utmapp/UTM#5028] opened 2023-02-15 17:46 UTC
Having folders to organize my ever growing list of VM:s with different functions and arch would be awesome 👍

**Comment by osy** [comment] 2023-02-26 04:14
Duplicate of #3960

**Closed by osy** 2023-02-26 04:14 UTC

**Comment by allamiro** [comment] 2023-03-05 15:09
this is a very important feature available in virtual box VMware workstation etc .. I wasn't sure why it hasn't been updated yet in UTM
