### ISSUE TITLE
UTM and VMs display issue

### ISSUE THREAD

**Issue by rimvydukas** [utmapp/UTM#2547] opened 2021-05-18 08:34 UTC
**Describe the issue**

I have UTM VSs display issue. Attached the picture. Is it possible to fix this somehow?

**Configuration**
* UTM Version: 2.0.28
* OS Version: 11.3.1
* Intel or Apple Silicon?  M1

![utm bug 1](https://user-images.githubusercontent.com/25026063/118776095-48233380-b890-11eb-9906-94b17e00d112.jpg)
![utm bug 2](https://user-images.githubusercontent.com/25026063/118776694-edd6a280-b890-11eb-86f9-82cd5a0b74ca.jpg)

**Comment by conath** [comment] 2021-05-19 07:19
There is no picture attached. Please upload your screenshot and include the details on your VM configuration as well.

**Comment by rimvydukas** [comment] 2021-05-19 07:55
Sorry, forgot to attach picture, my bad :( Fixed this. As for VM configuration - how will this help to solve UTM VM display issue? Some more notes regarding this issue. When I initially created VM - it seems that this entry was displayed correctly. But later, when I closed and reopened UTM - I've such VM display issue :(

**Comment by conath** [comment] 2021-05-19 10:17
Oh I get it now. You’re talking about the layout problem with the sidebar. That’s a known macOS issue: #2335 

Duplicate of #2335

**Closed by conath** 2021-05-19 10:17 UTC
