### ISSUE TITLE
Wrong display on sidebar

### ISSUE THREAD

**Issue by sylvoie** [utmapp/UTM#2489] opened 2021-05-06 01:07 UTC
I created some VM and I really like UTM.

The display of VM in sidebar is wrong : 

<img width="303" alt="image" src="https://user-images.githubusercontent.com/3700343/117227623-38621480-ade5-11eb-83b5-4ffab033e20b.png">

**Configuration**
* iMac 27-inch
* UTM Version: 2.0.27
* OS Version: macOS Big Sur
* Intel or Apple Silicon? Intel i7

Thank's

**Comment by osy** [comment] 2021-05-06 02:02
Duplicate of #2335

**Closed by osy** 2021-05-06 02:02 UTC
