### ISSUE TITLE
Creating snapshots/save states

### ISSUE THREAD

**Issue by BluDood** [utmapp/UTM#2695] opened 2021-08-02 21:09 UTC
Being able to create save states for VMs would be cool! QEMU's .qcow2 format already has this feature, so it could probably be easily used in UTM too. A GUI would also be nice to rename, edit, and delete them.

**Comment by juanandresgs** [comment] 2021-08-03 04:42
This would be amazing. It's essential for doing malware analysis with UTM.

**Comment by conath** [comment] 2021-08-03 19:37
Duplicate of #2688

**Closed by conath** 2021-08-03 19:37 UTC
Labels: enhancement

**Comment by osy** [comment] 2022-12-06 07:13
This is a closed issue. Please comment on the designated thread linked above. There is no support for custom save states yet but there is disposable mode and you can also duplicate the vm.

**Comment by juanandresgs** [comment] 2022-12-06 11:17
You have all the elements in place for rudimentary snapshots. Please consider adding the feature explicitly. It's important for malware analysis.

**Comment by osy** [comment] 2022-12-06 15:01
Not really as making the UI is 100% of the work in UTM as we use QEMU which of course has all these features already.

**Comment by Fischmuetze** [comment] 2024-11-21 08:54
Two years later ... question again: 
By any chance is there a timely update expecting for support qemu snapshots?

**Comment by osy** [comment] 2024-11-21 08:55
@Fischmuetze feel free to work on it and submit a PR

**Comment by Fischmuetze** [comment] 2024-11-21 09:03
> @Fischmuetze feel free to work on it and submit a PR

My simple question was actually clearly formulated as to whether it will be available in the near future, and not whether I can work on it. If you ask politely whether a train is running soon, you don't expect a flippant reply that you can get a train driver's licence to speed up the train frequency.

**Comment by osy** [comment] 2024-11-21 09:05
Just as you politely asked about when it will be available, I had politely suggested the best way to get such a feature implemented as an open source project that depends on the generosity of people who donate their time working on it.

**Comment by Fischmuetze** [comment] 2024-11-21 09:25
A clear question should be able to be answered just as clearly. It should be possible to have a question for a feature.  ... It is common knowledge that it is possible to collaborate on an open source project. Anyway thank you for the invitation. However, you cannot contribute to every project whose functions you use. Everyone has different skills and also you don't have the skills to work on all open source projects that you personally use. But sadly it is a trend of the time answer with Know-it-all instead of simply answering a simple questions.

**Comment by osy** [comment] 2024-11-21 09:32
You chose to comment on an issue closed 3 years ago and ignore the first comment leading to another issue (and from there it led to another issue) where active conversation was made about the feature. Please respect other people's time by doing some research before anointing yourself as a project manager. If you wish to contribute the project, there is also the option of the Sponsor link above which allows you to make a $100 contribution to prioritize a single issue in our backlog of > 800 issues. If you do not want to contribute financially or with code, please follow the relevant issues and wait patiently like everyone else.

**Comment by Fischmuetze** [comment] 2024-11-21 09:46
You philosophise pointlessly about wasting time, but never tire of leaving rude and useless long comments here for a itty bitty mistake. That is simply ridiculous! Proof once again that some people, like you, can no longer or no longer want to communicate politely. Back to my question: a simple yes or no would have sufficed (short enough, right?) instead of your kind of tirade ... but spouting rude know-it-alls and the urge to have the last rude word are clearly more important for you.
Is this all your kind of advertising to work on your project? That's really Wow! 

Never mind! Have a nice life!
