### ISSUE TITLE
cannot create vmnet interface: general failure (possibly not enough privileges)

### ISSUE THREAD

**Issue by 33Fraise33** [utmapp/UTM#6221] opened 2024-03-27 12:11 UTC
**Describe the issue**  
When changing shared guest network an error pops up. :
```
QEMU error: QEMU exited from an error: qemu-aarch64-softmmu: -netdev vmnet-shared,id=net0,start-address=169.254.113.10,end-address=169.254.113.100,subnet-mask=255.255.255.0: cannot create vmnet interface: general failure (possibly not enough privileges)
```

**Configuration**  
* UTM Version: 4.4.5
* macOS Version: Sonoma 14.4.1
* Mac Chip (Intel, M1, ...): M2 Pro

**Crash log**  
No crash log

**Debug log**  
Export Debug Log is greyed out, I think it never reaches this point, it crashes immediately after pressing start. 

**Upload VM**  
[config.plist.zip](https://github.com/utmapp/UTM/files/14773041/config.plist.zip)

**Comment by osy** [comment] 2024-03-28 21:25
Duplicate of #4324

**Comment by osy** [comment] 2024-03-28 21:25
I think this is a macos bug and you have to just reboot.

**Closed by osy** 2024-03-28 21:25 UTC

**Comment by 33Fraise33** [comment] 2024-03-29 08:38
> I think this is a macos bug and you have to just reboot.

I can confirm rebooting does NOT fix the issue.

**Comment by osy** [comment] 2024-03-29 08:48
`start-address=169.254.113.10,end-address=169.254.113.100,subnet-mask=255.255.255.0`

Oh this is probably not a valid subnet. Remove those settings.

**Comment by 33Fraise33** [comment] 2024-03-29 09:29
> `start-address=169.254.113.10,end-address=169.254.113.100,subnet-mask=255.255.255.0`
> 
> Oh this is probably not a valid subnet. Remove those settings.

this is a perfectly valid subnet: 169.254.113.0/24, start address the .10, end address the .100 (dhcp range) and subnetmask is the /24 from the network address.
