### ISSUE TITLE
Running UTM via External Drive

### ISSUE THREAD

**Issue by mertsaner** [utmapp/UTM#3307] opened 2021-11-10 18:41 UTC
**Describe the issue**
Hi,
I try to run UTM via an external hard drive, when I try allies on the hard drive and try to import it to UTM, it copies the original .utm file to document, however, I would like it to run on an External drive, not in the Macbook. How can I do that?
Is there a manual that describes how to run UTM on an External drive?
Thanks for any help,

**Configuration**
* UTM Version: 2.4.1
* OS Version: 12.0.1
Apple Silicon

**Comment by conath** [comment] 2021-11-11 10:35
It is currently not possible to run UTM VMs from another drive. Duplicate of #1205 

A similar feature, storing the virtual hard disk on another drive, is in development. #3227 There is no known release date yet. The feature could arrive with or after version 3.0.0. 

Please note https://github.com/utmapp/UTM/discussions/3142#discussioncomment-1391832

**Closed by conath** 2021-11-11 10:35 UTC

**Comment by indicator0** [comment] 2021-12-02 08:02
> **Describe the issue** Hi, I try to run UTM via an external hard drive, when I try allies on the hard drive and try to import it to UTM, it copies the original .utm file to document, however, I would like it to run on an External drive, not in the Macbook. How can I do that? Is there a manual that describes how to run UTM on an External drive? Thanks for any help,
> 
> **Configuration**
> 
> * UTM Version: 2.4.1
> * OS Version: 12.0.1
>   Apple Silicon

You may try this #3355 in discussion, it work for me with almost identical system configurations like yours.
