### ISSUE TITLE
Is there a way to ssh into the VM?

### ISSUE THREAD

**Issue by threefcata** [utmapp/UTM#2463] opened 2021-04-26 09:00 UTC
**Describe the issue**
I don't wanna fiddle with the GUI inside the VM as i usually ssh into the VM. With QEMU, it usually requires some kind of network bridge on the host, then the VM is launched using that bridge as the underlying network device. Could you please advise how to do that on an M1 macbook? Thanks.

**Configuration**
* UTM Version: 2.0.26
* OS Version: 11.2.3
* Intel or Apple Silicon? Apple

**Comment by osy** [comment] 2021-04-26 09:01
Duplicate of #2280

**Comment by osy** [comment] 2021-04-26 09:02
You can use port forwarding but it still requires using the GUI.

**Closed by osy** 2021-04-26 09:01 UTC
Labels: duplicate

**Comment by agreatfool** [comment] 2021-04-26 15:58
@osy How to do this? Is there any guide? I think this should be a common question, since now there are MAC users using UTM vm.
