### ISSUE TITLE
No option for enabling nested virtualization (VT-x/AMD-v)

### ISSUE THREAD

**Issue by almeyras** [utmapp/UTM#4098] opened 2022-06-06 21:16 UTC
**Describe the issue**
Hello, I can't find any option for enabling nested virtualization (VT-x/AMD-v). Does this feature exist in UTM? Or in bare QEMU? Thank you.

**Configuration**
* UTM Version: 3.2.4 (58)
* OS Version: 12.4
* Intel

**Comment by osy** [comment] 2022-06-08 00:23
Duplicate of #4056

**Closed by osy** 2022-06-08 00:23 UTC

**Comment by ohioohio** [comment] 2023-11-01 21:42
did you find the fix?
