### ISSUE TITLE
Can not shows correct characters when installing  Tiny 11

### ISSUE THREAD

**Issue by ewamtw** [utmapp/UTM#6521] opened 2024-07-28 16:26 UTC
**Describe the issue**
Can not shows correct characters when installing Tiny 11 ARM 64.

**Configuration(Required)**
UTM Version: UTM SE 4.5.3
OS Version: Tiny 11 Arm 64
Device Model: ARM64(aarch64) QEMU 7.2 ARM Virtual Machine (alias of virt-7.2) (virt)
My device: iPad Pro 11-inch 4th gen (iPadOS 17.5.1)
Is it jailbroken (name jailbreak used)? No 
How did you install UTM? Via App Store
![image](https://github.com/user-attachments/assets/6a628340-1997-4380-9681-ea1bcea7b68b)

**Comment by endrmen9487** [comment] 2024-08-03 06:43
I have same problem on iPad Air M2

**Comment by osy** [comment] 2024-08-22 15:10
Duplicate of #6483

**Closed by osy** 2024-08-22 15:10 UTC
