### ISSUE TITLE
UTM Crash at first starting of vm after creation

### ISSUE THREAD

**Issue by ipad2user** [utmapp/UTM#115] opened 2020-03-08 12:02 UTC
App Crash at first starting of vm after creation
on iPAD 11 Pro with iPAD OS 13.4 ?

I tried UTM 0.3 & 0.2 ... same problem
Trying many RAM config ... same problem
Trying different OS ... same problem

FYI, Using ipadstore paid version to sign UTM.

Any advise ?

**Comment by ipad2user** [comment] 2020-03-08 12:06
[Crash Logs.zip](https://github.com/utmapp/UTM/files/4303158/Crash.Logs.zip)

**Comment by WindowsBetaTest** [comment] 2020-03-09 03:13
+Try v0.4?

**Comment by ipad2user** [comment] 2020-03-09 12:07
I have tried all versions , resigned with ipastore paid & appcake

Same message in crash log:

Exception Type: EXC_BAD_ACCESS (SIGKILL - CODESIGNING)
Termination Reason: Namespace CODESIGNING, Code 0x2

Any support please ?

**Comment by miuirussia** [comment] 2020-03-09 12:12
Sign errors

**Comment by osy86** [comment] 2020-03-10 02:21
Please try this special build https://mega.nz/#!Zh5mFAhA!k8krwJjhSOfh_y0MyAlfz301g82R1G23o9QiwWM9q6Q
Tell me if you see a message on startup.

**Comment by osy86** [comment] 2020-03-10 02:23
Duplicate of #95

**Closed by osy86** 2020-03-10 02:23 UTC
Labels: duplicate

**Comment by ipad2user** [comment] 2020-03-10 07:23
Still Same problem,
Do you think ipastore or appcake has problem in signing ?

**Comment by miuirussia** [comment] 2020-03-10 07:43
Yes
