### ISSUE TITLE
Unable to import qcow2 disk image

### ISSUE THREAD

**Issue by ZonD80** [utmapp/UTM#521] opened 2020-11-07 13:42 UTC
**Environment**

iOS 14.2 release
iPhone 12
UTM 2.0.8

**Describe the bug**
Unable to import qcow2 image during VM creation from Files picker. No ability to "open in app" as well.

**To Reproduce**
0. Transfer qcow2 image to iOS device via airdrop, save to local storage
1. Press plus to create new UTM machine.
2. Navigate to disk drives
3. Click on import icon
4. Tap on qcow2 image - nothing happens

**Expected behaviour**

Tap on image copies/moves qcow2 file to UTM app folder and links this image as a disk to VM.

OR

Opening image in Files.app and "exporting" it to UTM app.

**Comment by yrjo** [comment] 2020-11-07 19:03
same here, ipad pro 11, 2018. ios 14.2
utm 2.0.8

**Comment by osy86** [comment] 2020-11-07 23:20
Duplicate of #519

**Closed by osy86** 2020-11-07 23:20 UTC
Labels: duplicate
