### ISSUE TITLE
QEMU exited with an error:Could not allocate dynamic translator buffer

### ISSUE THREAD

**Issue by none-null-blank** [utmapp/UTM#459] opened 2020-09-18 11:51 UTC
QEMU exited with an error:Could not allocate dynamic translator buffer
utm version:2.0b2

**Comment by yqs-github** [comment] 2020-09-18 14:05
Maybe this is a bug of UTM2.0 in the systems less than iOS14

**Comment by IIWare** [comment] 2020-09-20 08:37
Duplicate of #451

**Comment by osy86** [comment] 2020-09-20 08:52
True but I’ve confirmed the root cause is different and only seen on jailbroken devices. Next release should address this.

**Comment by IIWare** [comment] 2020-09-20 14:46
ok now I know it isn't a duplicate

**Closed** 2020-09-20 22:21 UTC
Labels: bug
