### ISSUE TITLE
GPU acceleration improvements (maybe)

### ISSUE THREAD

**Issue by lurenJBD** [utmapp/UTM#5321] opened 2023-05-21 08:40 UTC
I opened this issue to let everyone know that there is a project that may help UTM achieve improvements in GPU acceleration. 

I am just a layman and not clear about the principles, so I cannot provide any relevant explanations or help.

[kjliew/qemu-3dfx: MESA GL/3Dfx Glide pass-through for QEMU (github.com)](https://github.com/kjliew/qemu-3dfx)

This project provides a pass-through for MESA GL/3Dfx Glide for QEMU. It includes Glide wrappers for supported guest OS/environment (DOS/Windows/DJGPP/Linux) and MESA GL wrapper for supported guest OS/environment (Windows).

Some screenshots of demonstration videos recorded by the original author below.

![image](https://github.com/utmapp/UTM/assets/31967654/b1760ae6-095b-4385-bdab-0a1a858ba52c)

>https://youtu.be/t2AHiBNhEtI?t=134

![image](https://github.com/utmapp/UTM/assets/31967654/0f4ca474-8608-4d05-b57f-d3f30f831320)

>https://youtu.be/MJBTvcgBKSE?t=19

There is another project, Virgl Windows Driver, which has been able to provide OpenGL acceleration for Windows as early as 2017.

[3D OpenGL Acceleration For Windows Guests On QEMU Using VirGL/VirtIO - Phoronix](https://www.phoronix.com/news/QEMU-3D-Windows-Guests)

[GSoC 2017 | Virgl Windows Driver (github.com)](https://gist.github.com/Keenuts/199184f9a6d7a68d9a62cf0011147c0b)

Thank you very much to all the developers for their hard work, allowing me to use such excellent software as UTM so conveniently. Salute and thank you.

**Comment by osy** [comment] 2023-05-21 15:08
Duplicate of #5115

**Closed by osy** 2023-05-21 15:08 UTC
Labels: enhancement
