### ISSUE TITLE
When you put a slash in the name of a VM it dissapears.

### ISSUE THREAD

**Issue by SmanS723** [utmapp/UTM#421] opened 2020-07-26 16:32 UTC
**Describe the bug**
When you put a slash in the name of a VM it dissapears.

**To Reproduce**
1. Go to Create VM
2. Click on Name
3. Add a name with a slash for example cars/tesla/wakjdhawkdhawkjd
4. Hit save
5. The VM wont save.

**Comment by obbcth** [comment] 2020-07-26 16:34
Duplicate of #210

**Closed** 2020-07-26 16:35 UTC
Labels: bug
