### ISSUE TITLE
Importing large disk has no progress bar and appears frozen

### ISSUE THREAD

**Issue by huntercr42** [utmapp/UTM#5712] opened 2023-09-16 18:10 UTC
Please browse the existing issues and filter by 'enhancement' to make sure this has not already been suggested!
When importing an existing 30GB virtue disk, UTM 4.3.5 ( and probably earlier versions ) 
gives no indicator that it is still processing the drive. I would have thought the app was frozen but I had a hunch it was copying the disk.
Please ad a simple progress bar or similar status so users aren't confused.

**Comment by osy** [comment] 2023-09-27 18:37
Duplicate of #4006

**Closed by osy** 2023-09-27 18:37 UTC
Labels: enhancement
