### ISSUE TITLE
SSH connection to guest drops out

### ISSUE THREAD

**Issue by QuentinGuyot-epitech** [utmapp/UTM#3788] opened 2022-03-18 06:16 UTC
I use UTM to remote develop from vscode to linux 20.04 on a macbook pro m1. Randomly during the day i loose the ssh connexion beyween vscode and the VM. Even trying to connect from the mac directly to the VM throught ssh does'nt work. I need to restart the VM to get the connexion working again.
Each time the VM is not crash i can connect on it directly throught UTM it's only ssh connexion.
Does someone else get this kind of pb ? It is less often between 3.1.5 but get the same pb since 2.x

**Configuration**
* UTM Version: 3.1.5
* OS Version: 12.2
* apple silicon

**Comment by ismailyenigul** [comment] 2022-03-18 13:22
same here!

    UTM Version: 3.1.5
    Macbook M1 Pro CPU

I lost ssh connection to Ubuntu 20.04(Linux 5.4.0-104-generic kernel) VM and sometimes I can still access to VM console to reboot.
But in general can't access from UTM console too to be able to restart.
 I have only one option! stop/kill the instance. After that  my vm crashes and never boots.

<img width="724" alt="image" src="https://user-images.githubusercontent.com/2566232/159010083-2213a276-0b4d-4635-b312-0507ff9ae76d.png">

**Comment by conath** [comment] 2022-03-23 21:26
@ismailyenigul see https://github.com/utmapp/UTM/issues/2682#issuecomment-1064827650 about the "never boots" issue.

**Comment by conath** [comment] 2022-03-23 21:29
@QuentinGuyot-epitech Please add the information that was requested in the New Issue template. Your report lacks all VM configuration information (VM config plist, debug log).

**Comment by QuentinGuyot-epitech** [comment] 2022-03-28 13:48
[debug_UTM.log](https://github.com/utmapp/UTM/files/8363304/debug_UTM.log)
[config.plist.txt](https://github.com/utmapp/UTM/files/8363321/config.plist.txt)
@conath Here are the requested files. Thanks !

**Comment by conath** [comment] 2022-03-29 08:06
Duplicate of #3143 - solution for macOS users is to switch the VM’s network mode to Shared or Bridged Mode. Then you don‘t connect via port forwarding but instead just use the VM‘s IP.

**Closed by conath** 2022-03-29 08:06 UTC

**Comment by WilyWildWilly** [comment] 2023-08-25 08:17
Switching from/to Shared/Bridged mode does NOT solve the issue.
