### ISSUE TITLE
[iOS] Crash when quitting a VM

### ISSUE THREAD

**Issue by conath** [utmapp/UTM#2327] opened 2021-02-22 15:12 UTC
I pressed the Quit button (leftmost in the toolbar) while a Windows 10 x64 VM was running and then confirmed the alert with Yes.

**Crash in [UTMJSONStream.m:193](https://github.com/utmapp/UTM/blob/ce1458940cc22a09533816654c30e55f07a712d7/Managers/UTMJSONStream.m#L193) "terminating with uncaught exception of type NSException"**
`'NSInternalInconsistencyException', reason: 'Invalid stream'`

**Configuration (required)**
* UTM Version: latest
* OS Version: latest
* Device Model: iPad Pro 11" A12X
* Is it jailbroken (name jailbreak used)? No
* How did you install UTM? Xcode

**Crash log**
```log
UTM[4989:1236229] qemuWillQuit, reason = host-qmp-quit
UTM[4989:1237486] *** Assertion failure in -[UTMJSONStream stream:handleEvent:], UTMJSONStream.m:193
UTM[4989:1237486] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Invalid stream'
*** First throw call stack:
(0x18293e8b4 0x1978917a8 0x182840708 0x183c07a74 0x1000e5360 0x1828d5b14 0x1828d5c2c 0x102d70114 0x102d71e40 0x102d79f50 0x102d7ad74 0x102d87ab0 0x1cdbee7a4 0x1cdbf574c)
libc++abi: terminating with uncaught exception of type NSException
```

**Xcode screenshot:**
<img width="1149" alt="invalid stream" src="https://user-images.githubusercontent.com/12073163/108726507-cbe6b180-7527-11eb-9496-4859cc7a7fe0.png">

**VM Config:**
<details>
  <summary>Export QEMU Command</summary>

```
qemu-system-x86_64 -L /…/UTM.app/qemu -S -qmp tcp:127.0.0.1:4444,server,nowait -spice port=5930,addr=127.0.0.1,disable-ticketing,image-compression=off,playback-compression=off,streaming-video=off  
-cpu max -smp cpus=4,sockets=1,cores=4,threads=1   
-machine q35, -accel tcg,thread=multi,tb-size=384,split-wx=on   
-vga qxl -global PIIX4_PM.disable_s3=1 -global ICH9-LPC.disable_s3=1   
-m 1536 -soundhw hda -name "Windows 10 x64"   
-device usb-ehci -device usb-tablet -device usb-mouse -device usb-kbd   
-bios "/…/Windows 10 x64.utm/Images/OVMF_CODE-pure-efi.fd"   
-drive "if=virtio,media=disk,id=drive1,file=/…/Windows 10 x64.utm/Images/disk-0.qcow2,cache=writethrough"   
-device virtio-net-pci,netdev=net0 -netdev user,id=net0   
-device virtio-serial -device virtserialport,chardev=vdagent,name=com.redhat.spice.0 -chardev spicevmc,id=vdagent,debug=0,name=vdagent -uuid A46187B2-1935-48EE-AB00-DF117FDC1BC5 -rtc base=localtime   
-vga none -device qxl-vga,vgamem_mb=128
```

</details>

**Comment by Vishram1123** [comment] 2021-02-22 15:22
This is how UTM quits normally on iOS; it is not pretty, but I guess it is the only way to make the app quit itself.

**Comment by conath** [comment] 2021-02-22 15:31
> This is how UTM quits normally on iOS; it is not pretty, but I guess it is the only way to make the app quit itself.

This is not true anymore. It is supposed to animate to the Home Screen and quit in the background (since last two releases).

**Comment by Vishram1123** [comment] 2021-02-23 16:40
Good point; similarly, if it is reopened too quickly, it freezes then quits.

**Comment by osy** [comment] 2024-08-24 14:04
Duplicate of #139

**Closed by osy** 2024-08-24 14:04 UTC
