### ISSUE TITLE
Adding DirectX support

### ISSUE THREAD

**Issue by ExenalEurope** [utmapp/UTM#409] opened 2020-07-09 21:44 UTC
For now, UTM does not support accelerated graphics.
Adding DirectX support to UTM would allow people to play games in Virtual Machines.

Sadly, whenever DirectX is Installed, it still does nothing at the moment. 
Let's change this!

EDIT: (How did Snazzy Labs manage to run Half Life 2, does it not need DirectX or anything?
https://www.youtube.com/watch?v=LrLDKYFyLMM)

QEMU is able to take advantage of Intel HAXM to run x86 and x86_64 VMs with hardware acceleration.
Can this be implemented?

**Comment by osy86** [comment] 2020-07-09 23:23
Duplicate of #161

**Closed by osy86** 2020-07-09 23:23 UTC
Labels: duplicate
