### ISSUE TITLE
Non-US (IT) keyboard issues with MacOS guest

### ISSUE THREAD

**Issue by dam0vm3nt** [utmapp/UTM#5564] opened 2023-08-16 07:57 UTC
**Describe the issue**  

Some keys aren't mapped in MacOS guests (using Mac virtualization). Everything's good in Linux (using qemu virtualization).

For my italian keyboard the keys that aren't working are those corresponding to "\" and "|" (same key + shift). 

**Configuration**  
* UTM Version: 4.5.5
* macOS Version: ventura
* Mac Chip: M1

**Comment by adeadman** [comment] 2023-08-17 11:17
Duplicate of #4041 
It's a known issue with Apple Virtualization not supporting non-ANSI keyboards.
https://eclecticlight.co/2023/06/27/keyboard-layouts-in-lightweight-virtualisation/

**Comment by osy** [comment] 2023-08-19 19:08
Duplicate of #4041

**Closed by osy** 2023-08-19 19:08 UTC
