### ISSUE TITLE
Allow the QEMU command, which is displayed, to be customized.

### ISSUE THREAD

**Issue by rcfa** [utmapp/UTM#6530] opened 2024-07-31 15:58 UTC
Please browse the existing issues and filter by 'enhancement' to make sure this has not already been suggested!
While UTM displays, and allows to export the QEMU command line it implicitly invokes, it doesn’t allow this to be edited, as it seems this is a display of a dynamically derived command based on the very limited settings allowed by the *.utm/config.plist format.

While this works for standard setups, it’s insufficient for a variety of legacy operating systems. Either the config.plist format must be upgraded to allow for all the configuration options QEMU offers, or there should be a mode in UTM where  it can switch from dynamic configuration to a manual configuration mode, where simply the QEMU command is stored, and it’s up to the user to enter it manually.

Ideally, one could set up a system with the provided tools (drives, etc.) and then when one’s 90% done, convert from the automatically created QEMU command, to a manually maintained command.

The config.plist could then simply contain a single property: qemu-command, which a single string, which would be the complete configuration as sent to QEMU.

**Comment by osy** [comment] 2024-08-22 15:15
Duplicate of #5713

**Closed by osy** 2024-08-22 15:15 UTC
Labels: enhancement

**Comment by osy** [comment] 2024-08-22 15:16
If there is a specific set of arguments that you need, please file a ticket for that so it can be integrated into the GUI.

**Comment by rcfa** [comment] 2024-10-02 17:56
Well, very specifically this is holding me up:

https://github.com/utmapp/UTM/issues/6529
