### ISSUE TITLE
Windows 11 No TPM 2.0 is not supported

### ISSUE THREAD

**Issue by ZhengGuoJie** [utmapp/UTM#3852] opened 2022-03-31 09:37 UTC
**Describe the issue**
Installation steps tips:
This computer cannot run WIndows 11
This computer does not meet the minimum system requirements required to install this version of Windows.

**Configuration**
* UTM Version: 3.0.4
* OS Version: Monterey 12.3
* Apple Silicon

**Comment by freebrowser1** [comment] 2022-03-31 19:34
Get a .vhdx image from Microsoft when you have a Windows Insider account (or register yourself). I did that and run Win 11 (ARM) successfully on UTM, but I have UTM version 3.1.5, the latest.

**Comment by conath** [comment] 2022-04-05 22:31
Duplicate of #3082

**Closed by conath** 2022-04-05 22:31 UTC

**Comment by biapar** [comment] 2022-07-22 21:22
So. How to?

**Comment by cansozbir** [comment] 2022-08-28 11:39
@biapar  have you found a solution?

**Comment by biapar** [comment] 2022-08-29 09:42
Sorry, but I can reply this because I've Macs with Intel CPU, but my Win11 run without TPM object on VmWare Fusion and I tried also on Parallels and it works.
