### ISSUE TITLE
After deleting the virtual machine, the prompt to confirm the deletion still appears.

### ISSUE THREAD

**Issue by fenginsc** [utmapp/UTM#3533] opened 2022-01-24 15:55 UTC
**Describe the issue**
After deleting the virtual machine, the prompt to confirm the deletion still appears.
When deleting a virtual machine, expand the menu to delete, and a confirmation box will pop up. Click the delete button. After a few seconds, the virtual machine has been deleted, but the confirmation box will not disappear. Clicking the delete button again will prompt that the virtual machine does not exist.

**Configuration**
* UTM Version: 3.0.4
* OS Version:  11.6
* Intel or Apple Silicon?  intel

**Comment by conath** [comment] 2022-01-27 08:19
This is a macOS system-level bug that affects UTM on all macOS versions below 12.0.1; please update to macOS 12 or, if you don't want to upgrade, just click "cancel" in the second popup. Sorry! 

Duplicate of #2337

**Closed by conath** 2022-01-27 08:19 UTC
