### ISSUE TITLE
Using host's VPN

### ISSUE THREAD

**Issue by stevehjohn** [utmapp/UTM#4973] opened 2023-01-28 22:54 UTC
Hi,

I have an issue accessing the VPN the host is connected to. I have set the network to be "Emulated VLAN" and for the most part it seems to work.

However, if I try and access websites on a non-default port (e.g. 8080), it does not connect even though the host does successfully.

Any tips greatly appreciated.

UTM: 4.1.5
Host: 2020 M1 MacBook, macOS Ventura 13.1
Guest: Windows 11 arm64, build 25276

Thanks,

Steve.

**Comment by osy** [comment] 2023-02-26 04:36
Duplicate of #3634

**Closed by osy** 2023-02-26 04:36 UTC
