### ISSUE TITLE
Regression: no GPU acceleration working in iPadOS 15.1

### ISSUE THREAD

**Issue by Sinemora10** [utmapp/UTM#3353] opened 2021-11-29 08:20 UTC
Setting up the display of my ubuntu VM with any of the Virtio GPU supported cards causes the VM to crash and the iPad to reboot after a purple screen flash. On iPadOS 14.8 it was possible to set virtio-gpu-gl-pci successfully with a significant gain in performance.  

* UTM Version: 2.4.1
* OS Version: iPadOS 15.1
* Device Model: iPad pro 11' M1 
* Is it jailbroken (name jailbreak used)? No jailbreak, UTM launched with JIT support using Jitterbug 
* How did you install UTM? Sideloaded using AltStore

**Crash log**
If the app crashed, you need a crash log. To get your crash log, open the Settings app and browse to `Privacy -> Analytics & Improvements -> Analytics Data` and find the latest entry for UTM. You should export the text and attach it here.

Apologies, I cannot see the option in the iPad version of UTM 

**Debug log**
For all issues, _including_ crashes, you should attach a debug log. Open UTM, and open the settings for the VM you wish to launch. Near the bottom of the configuration options (or at the top of the `QEMU` page) is `Debug Log`. Turn it on and save the VM. After you experience the issue, quit the VM and re-launch UTM. Open the VM settings again and select `Export Log...` and attach it here.

Please find attached the log (in this attempt I selected the virtio-gpu-gl-pci (GPU Supported) option, as it used to work on iPadOS 14.8)
[debug.log](https://github.com/utmapp/UTM/files/7616613/debug.log)
 

**Upload VM**
(Optional) If possible, upload the `config.plist` inside the `.utm`. If you do not have this, you can upload the entire `.utm` but note this contains your personal data. Since GitHub has an attachment size limit, you may want to upload to another service such as Google Drive. Link it here.

**Comment by conath** [comment] 2021-11-30 01:20
Duplicate of #2743 

Thank you for the log. It shows no QEMU error before your iPad crashes and reboots. As far as I can tell, this a bug in iPadOS / iOS 15.

**Closed by conath** 2021-11-30 01:20 UTC

**Comment by Sinemora10** [comment] 2021-11-30 03:16
Thanks Conath. Will continue the discussion in #2743
