### ISSUE TITLE
Starting VM via utm:// URL scheme doesn't work

### ISSUE THREAD

**Issue by pajp** [utmapp/UTM#6421] opened 2024-06-12 12:05 UTC
To reproduce:
* Create a new VM, named e.g. "xyz"
* From Terminal, try to start the VM using UTM URL scheme: `open 'utm://start?name=xyz'`
* Expected result: VM "xyz" starts
* Observed result: UTM is brought to front but does not start the VM

**Configuration**  
* UTM Version: 4.5.3 (Mac App Store version)
* macOS Version: 14.5
* Mac Chip: M1 Max

**Debug log**  
Logs from "UTM" process:
[utm.log](https://github.com/user-attachments/files/15804366/utm.log)

**Comment by osy** [comment] 2024-06-12 12:07
Duplicate of #6346

**Closed by osy** 2024-06-12 12:07 UTC
