### ISSUE TITLE
bluetooth mouse triggers annoying ios notification gesture

### ISSUE THREAD

**Issue by mio-19** [utmapp/UTM#5016] opened 2023-02-13 03:26 UTC
**Describe the issue**

bluetooth mouse triggers annoying ios notification gesture when moving up

**Configuration (required)**
* UTM Version: 4.1.5
* OS Version: 15.1
* VM: Windows 10 arm
* Device Model: ipad Pro m1
* Is it jailbroken (name jailbreak used)? 
* How did you install UTM? TrollStore

**Crash log**
If the app crashed, you need a crash log. To get your crash log, open the Settings app and browse to `Privacy -> Analytics & Improvements -> Analytics Data` and find the latest entry for UTM. You should export the text and attach it here.

**Debug log**
For all issues, _including_ crashes, you should attach a debug log. Open UTM, and open the settings for the VM you wish to launch. Near the bottom of the configuration options (or at the top of the `QEMU` page) is `Debug Log`. Turn it on and save the VM. After you experience the issue, quit the VM and re-launch UTM. Open the VM settings again and select `Export Log...` and attach it here.

**Upload VM**
(Optional) If possible, upload the `config.plist` inside the `.utm`. If you do not have this, you can upload the entire `.utm` but note this contains your personal data. Since GitHub has an attachment size limit, you may want to upload to another service such as Google Drive. Link it here.

**Comment by mio-19** [comment] 2023-02-13 03:27
This happens randomly. Sometimes the gesture is triggered

**Comment by osy** [comment] 2023-02-26 04:21
I believe this is a duplicate of #4843. What's happening is that your mouse cursor "freezes" in the last location before the VM starts up. If that happens to be in a place where a gesture is recognized (over a button for example, or near the top), it will cause this to happen. A workaround before this is fixed is to make sure you quickly move the mouse cursor to the middle of the screen when starting a VM.

**Closed** 2023-02-26 04:21 UTC
