### ISSUE TITLE
Blank screen after booting Windows 11 in UTM

### ISSUE THREAD

**Issue by joyous-freak** [utmapp/UTM#6817] opened 2024-11-19 04:54 UTC
I have logged into this particular VM many times in the past but on starting it today I experienced a blank boot screen after the UTM logo.Although I am able to hear the Windows 11 boot sound so the issue is only display not showing in VM.

And sometimes the VM goes into recovery and asks to restart the system.

UTM 4.5.3
MacOS 15
M3 Air 

<img width="1470" alt="Screenshot 2024-11-19 at 10 17 04 AM" src="https://github.com/user-attachments/assets/d13bfcd8-92ae-49c5-ac70-ee2cafdc188c">

<img width="1470" alt="Screenshot 2024-11-19 at 10 17 31 AM" src="https://github.com/user-attachments/assets/46220231-716d-4311-b2ab-d3ef8c1429ad">

**VM Config attached below**

[config.plist.zip](https://github.com/user-attachments/files/17809557/config.plist.zip)

**Comment by dmascord** [comment] 2024-11-27 06:56
I have this same issue, and have tried version beta 4.6.1, with no joy.  I think it relates to Windows 11 24H2

**Comment by gtimchenko** [comment] 2024-12-04 17:02
Looks similar to #6872

**Comment by aliofye** [comment] 2024-12-10 07:05
Getting the same black screen after installing a fresh ISO from CrystalFetch and following the UTM Windows 11 Guide

**Comment by osy** [comment] 2024-12-10 09:41
Duplicate of #6332

**Closed by osy** 2024-12-10 09:41 UTC
