### ISSUE TITLE
UTM Vagrant plugin support

### ISSUE THREAD

**Issue by ajaykurani** [utmapp/UTM#4463] opened 2022-09-29 09:14 UTC
Hello UTM Developers,
   With the transition to M1 max architecture (macOS Monterey), one of the issues I have faced is getting an Ubuntu x86_64 working.  UTM was perfect as the emulation mode solved this issue perfectly.  I was interested in using vagrant with UTM and wanted to find out if there was a plugin available, or if this was on the roadmap?   Additionally it would be helpful on the gallery page to include the Ubuntu 20.04 x86_64 version (currently only arm64) if possible.

Thanks,
Ajay

**Comment by osy** [comment] 2022-09-29 13:59
Duplicate of #3718

**Closed by osy** 2022-09-29 13:59 UTC
