### ISSUE TITLE
Unable to ping outside addresses when using "Emulated VLAN" adapter (using v4.6.0 beta, unknown if regression)

### ISSUE THREAD

**Issue by joseph-long** [utmapp/UTM#6749] opened 2024-10-16 02:52 UTC
**Describe the issue**  

I am running Rocky Linux 9.4 on ARM with an "Emulated VLAN" network adapter. My understanding was that this was that this would have all the traffic to the outside appear to come from the qemu process, with things like dhcp and dns provided by qemu to the guest. (I'm trying to diagnose a user's issue with a "Shared Network" that worked until I was no longer helping them, thinking maybe this will rule out some possible sources of errors like changing host OS network config.)

In the pre-installation environment for Rocky 9.4 I get a network configuration from dhcp. I am able to ping the default route host, 10.0.2.2, but not an outside address like 1.1.1.1:

<img width="647" alt="image" src="https://github.com/user-attachments/assets/95a6dd11-cec3-4b2a-9907-42334da2bb48">

I have the firewall disabled, and I was prompted to allow UTM to access devices on the local network-- I am pretty sure I clicked 'allow', but I don't know where that permission lives in System Settings now.

**Configuration**  
* UTM Version: 4.6.0 (beta)
* macOS Version: 15.0.1
* Mac Chip (Intel, M1, ...): M1 Max

**Crash log**  
If the app crashed, you need a crash log. To get your crash log, open Console.app, go to `Crash Reports`, and find the latest entry for either UTM, QEMU, QEMUHelper, or qemu-\*. Right click and choose `Reveal in Finder`. Attach the report here.

**Debug log**  
[debug.log](https://github.com/user-attachments/files/17388581/debug.log2.log)

(I did not see anything network related.)

**Upload VM**  

The config is here; the VM is empty except for a Rocky-9.4-aarch64-minimal.iso install disk.

[config.plist.zip](https://github.com/user-attachments/files/17388550/config.plist.zip)

**Comment by osy** [comment] 2024-11-11 18:03
Duplicate of #351

Ping doesn't work with SLIRP

**Closed by osy** 2024-11-11 18:03 UTC
