### ISSUE TITLE
macOS X 10.4 Tiger on PowerPC in UTM SE didn't work

### ISSUE THREAD

**Issue by LHC0521** [utmapp/UTM#6567] opened 2024-08-18 10:10 UTC
PowerPC Error![image](https://github.com/user-attachments/assets/f3ee7453-ddd9-4b90-bf68-1d8d20db0907)![image](https://github.com/user-attachments/assets/ab5991c0-9537-460c-90b0-b02026797055)![image](https://github.com/user-attachments/assets/9446f327-e123-4cf1-a0dc-14e42906eaf7)![image](https://github.com/user-attachments/assets/7ce2201a-b317-4893-9d4e-1e0ce4d26bc8)![image](https://github.com/user-attachments/assets/1f931068-4d2e-4a77-bf2f-6bc9b5b323fb)![image](https://github.com/user-attachments/assets/fbb74366-fdc6-4f3e-9e5f-4203135c7434)![image](https://github.com/user-attachments/assets/27494ce1-6104-4bf5-af3c-d40fc16101fe)![image](https://github.com/user-attachments/assets/0743ab7b-31d1-489a-9fea-0d8c46976ca8)
M2 iPad Pro 
IOS 18.1 Beta
APP store's UTM SE 
PowerPC
Mac OS X10.4 Tiger 
Thanks for your help :-)

**Comment by osy** [comment] 2024-08-22 23:51
Duplicate of #6539

**Closed by osy** 2024-08-22 23:51 UTC
