### ISSUE TITLE
[UTM] App freezes/white screen on launch

### ISSUE THREAD

**Issue by unorderedpizza** [utmapp/UTM#32] opened 2020-02-20 09:59 UTC
iOS 13.3 on iPhone XS.

While not jailbroken, the app itself can be opened as long as it is signed, however, the app will crash right after clicking on any of the VMs. Configuration menu works without issues.

Additionally, the app will crash when a fairly large VM is attempting to be launched even in jailbroken mode (in my case, a Windows XP install with a 2 GB hard drive, it was set up on the device itself and was fully functional until I shut down the VM and attempted to re-launch the virtual machine later on); when reopened, the app will stay on the white splash screen after the initial crash and stop functioning, even after removing the app in the switcher/respringing/su && ldrestart (possibly due to lack of cleanup?). This is also reproducible by shutting down the virtual machine with the power button on the top menu UI; the machine shuts down and the app freezes. Only fixable by rebooting and re-jailbreaking.
![IMG_0660](https://user-images.githubusercontent.com/43310440/74922700-f41e6a80-5412-11ea-8c83-c74f3eadd8d3.PNG)

**Comment by Tizioincognit0** [comment] 2020-02-20 10:36
I have the same issue on iOS 12.2 on iPhone X.

**Comment by tylerdak** [comment] 2020-02-20 15:26
Similar issue here, iOS 13.3, iPhone XS

**Comment by obbcth** [comment] 2020-02-20 16:19
Same issue on iOS 13.3, iPad Air 3, Jailbroken.

**Comment by JohnnnnyKlayy** [comment] 2020-02-20 16:51
Same issue, iOS 13.3 iPhone XR, jailbroken.

**Comment by osy86** [comment] 2020-02-20 17:55
This is a known issue and is due to an iOS bug. If an app dies (exception, killed, etc) with `ptrace` active, then it will lock up the kernel (I think).

**Comment by obbcth** [comment] 2020-02-20 18:14
> This is a known issue and is due to an iOS bug. If an app dies (exception, killed, etc) with `ptrace` active, then it will lock up the kernel (I think).

Same as ppsspp jit debug ver?
Then there should be a app close button to halt ptrace, I think.

**Comment by seriousm4x** [comment] 2020-02-21 11:01
Same issue on iPad Pro 3 12,9" on iOS 13.3 jailbroken

**Comment by realmayus** [comment] 2020-02-21 15:15
Same issue on iPad Pro 12.9“ 2018 on iOS 13.3.1 non-jailbroken

**Comment by The-SamminAter** [comment] 2020-02-21 21:10
Same issue, iOS 13.2.3 on an iPhone XS

**Comment by saagarjha** [comment] 2020-02-22 00:54
I believe there are ways around this. I’ll make a PR if I can figure this out.

**Comment by Wthebinder** [comment] 2020-02-22 06:46
Same with iPad Pro 11” on iPadOS 13.3

**Comment by saagarjha** [comment] 2020-02-22 07:46
Stuck it in #38, if anyone wants to try it out.

**Comment by osy86** [comment] 2020-02-22 07:48
Thanks, I will test soon!

**Comment by a3lharbi** [comment] 2020-02-22 16:04
It will work again if u installing it on custom bundles, I don’t know why this bug happend

**Comment by Tizioincognit0** [comment] 2020-02-22 16:12
> It will work again if u installing it on custom bundles, I don’t know why this bug happend

Thank you, I’ve found a fix. You must go with Filza on /var/containers/Application/UTM/UTM.app and open the file “Info.plist”. Then you have to expand “Root” and change the value on “BuildMachineOSBuild” from “19D76” to “19D75”.

**Comment by The-SamminAter** [comment] 2020-02-23 03:39
> It will work again if u installing it on custom bundles, I don’t know why this bug happend

Would you care to clarify?

**Comment by a3lharbi** [comment] 2020-02-23 05:10
> > It will work again if u installing it on custom bundles, I don’t know why this bug happend
> 
> Would you care to clarify what this means?

I meant If you installed the app or sign it at different bundle identifier, it will work normal, But the only problem it crashes If you turn any machines

**Comment by The-SamminAter** [comment] 2020-02-23 05:12
> > > It will work again if u installing it on custom bundles, I don’t know why this bug happend
> > 
> > 
> > Would you care to clarify what this means?
> 
> I meant If you installed the app or sign it at different bundle identifier, it will work normal, But the only problem it crashes If you turn any machines

I see, thank you for the clarification. 
How interesting, I’ll check it out. Do you think the new crash is related to the original one? I do not have any knowledge about this.

**Comment by pourhadi** [comment] 2020-02-23 05:20
I'm on iOS 13.2, iPhone 11 -- the hardware restart (volume + power button) isn't even working. Not sure how to get this white screen to go away.

**Comment by The-SamminAter** [comment] 2020-02-23 05:23
> I'm on iOS 13.2, iPhone 11 -- the hardware restart (volume + power button) isn't even working. Not sure how to get this white screen to go away.

Your problem may be that the hardware restart for the iPhone 11 is actually (click and then release) volume up, then (click and release) volume down, and then (hold down) power button.

**Comment by pourhadi** [comment] 2020-02-23 05:28
Oh well sure, that may be my problem.

That is my problem.

Definitely my problem.

[This page is deceiving.](https://support.apple.com/en-us/HT201559)

Thank you. 😅

**Comment by saagarjha** [comment] 2020-02-23 05:30
That’s how you normally restart your device. I’m not sure if Apple has a support article detailing how to forcefully power off your device, as it’s presumably not something users normally need to do.

**Comment by The-SamminAter** [comment] 2020-02-23 05:31
No worries. That’s the apple page for restarting, not force-restarting. The page that you were looking for is here: https://support.apple.com/en-ca/guide/iphone/iph8903c3ee6/ios

**Comment by a3lharbi** [comment] 2020-02-23 05:32
> > > > It will work again if u installing it on custom bundles, I don’t know why this bug happend
> > > 
> > > 
> > > Would you care to clarify what this means?
> > 
> > 
> > I meant If you installed the app or sign it at different bundle identifier, it will work normal, But the only problem it crashes If you turn any machines
> 
> I see, thank you for the clarification.
> How interesting, I’ll check it out. Do you think the new crash is related to the original one? I do not have any knowledge about this.

It might be 

> > > > It will work again if u installing it on custom bundles, I don’t know why this bug happend
> > > 
> > > 
> > > Would you care to clarify what this means?
> > 
> > 
> > I meant If you installed the app or sign it at different bundle identifier, it will work normal, But the only problem it crashes If you turn any machines
> 
> I see, thank you for the clarification.
> How interesting, I’ll check it out. Do you think the new crash is related to the original one? I do not have any knowledge about this.
> 
> Edit: I just checked, the app still crashes immediately when it has a different bundle identifier.

Yes as I mentioned before if you installed without changing The bundle it will be white Screen , after installed At different Bundle the it work but crashes If you try to run any virtual machine

**Comment by The-SamminAter** [comment] 2020-02-23 05:33
> Yes as I mentioned before if you installed without changing The bundle it will be white Screen , after installed At different Bundle the it work but crashes If you try to run any virtual machine

I see, I’ll try doing that and get back to you.

**Comment by saagarjha** [comment] 2020-02-23 05:35
It’s probably crashing at that point because that’s when the dylibs get loaded, and they’re probably not signed correctly.

**Comment by The-SamminAter** [comment] 2020-02-23 05:36
> > Yes as I mentioned before if you installed without changing The bundle it will be white Screen , after installed At different Bundle the it work but crashes If you try to run any virtual machine
> 
> I see, I’ll try doing that and get back to you.

I seem to be unable to do that right now on my phone, would you mind uploading your custom .ipa to somewhere and linking it?

**Comment by The-SamminAter** [comment] 2020-02-23 05:36
> It’s probably crashing at that point because that’s when the dylibs get loaded, and they’re probably not signed correctly.

So could the whole problem be signing?

**Comment by a3lharbi** [comment] 2020-02-23 05:36
> > > Yes as I mentioned before if you installed without changing The bundle it will be white Screen , after installed At different Bundle the it work but crashes If you try to run any virtual machine
> > 
> > 
> > I see, I’ll try doing that and get back to you.
> 
> I seem to be unable to do that right now on my phone, would you mind uploading your custom .ipa to somewhere and linking it?

Just signed By appcake as custom installation

**Comment by The-SamminAter** [comment] 2020-02-23 05:39
> > > > Yes as I mentioned before if you installed without changing The bundle it will be white Screen , after installed At different Bundle the it work but crashes If you try to run any virtual machine
> > > 
> > > 
> > > I see, I’ll try doing that and get back to you.
> > 
> > 
> > I seem to be unable to do that right now on my phone, would you mind uploading your custom .ipa to somewhere and linking it?
> 
> Just signed By appcake as custom installation

How do you export apps to AppCake 7?

**Comment by saagarjha** [comment] 2020-02-23 05:40
> So could the whole problem be signing?

That would be my guess it was working before and @a3lharbi fiddled with the app. There are other things that could be going wrong but I think this is the most likely one.

**Comment by a3lharbi** [comment] 2020-02-23 05:42
> > > I seem to be unable to do that right now on my phone, would you mind uploading your custom .ipa to somewhere and linking it?
> > 
> > 
> > Just signed By appcake as custom installation
> 
> How do you export apps to AppCake 7? Or, how do you do a custom install in AppCake 6?

Exported by sharing S

> > > I seem to be unable to do that right now on my phone, would you mind uploading your custom .ipa to somewhere and linking it?
> > 
> > 
> > Just signed By appcake as custom installation
> 
> How do you export apps to AppCake 7? Or, how do you do a custom install in AppCake 6?

The features only on appcake 7 , imported via sharing sheet then do a custom Installation with different Bundle ID

**Comment by The-SamminAter** [comment] 2020-02-23 05:44
> The features only on appcake 7 , imported via sharing sheet then do a custom Installation with different Bundle ID

Ah, my sharing sheet seems to lack that option as I have both versions of AppCake installed.

**Comment by a3lharbi** [comment] 2020-02-23 05:48
> > The features only on appcake 7 , imported via sharing sheet then do a custom Installation with different Bundle ID
> 
> Ah, my sharing sheet seems to lack that option as I have both versions of AppCake installed.

You don’t have a copy to appcake option !

**Comment by The-SamminAter** [comment] 2020-02-23 05:50
> > > The features only on appcake 7 , imported via sharing sheet then do a custom Installation with different Bundle ID
> > 
> > 
> > Ah, my sharing sheet seems to lack that option as I have both versions of AppCake installed.
> 
> You don’t have a copy to appcake option !

I do, but only for AppCake 6, not 7

**Comment by a3lharbi** [comment] 2020-02-23 05:52
> > > > The features only on appcake 7 , imported via sharing sheet then do a custom Installation with different Bundle ID
> > > 
> > > 
> > > Ah, my sharing sheet seems to lack that option as I have both versions of AppCake installed.
> > 
> > 
> > You don’t have a copy to appcake option !
> 
> I do, but only for AppCake 6, not 7

maybe u can find it at more option when you share it

**Comment by The-SamminAter** [comment] 2020-02-23 05:53
> maybe u can find it at more option when you share it

There is no such option. Would it just be possible for you to share your custom ipa?

**Comment by rogerus** [comment] 2020-02-23 14:59
have the same issue on an iPad Pro 12.9''(iOS 13.3)

**Comment by osy86** [comment] 2020-02-24 07:06
Merged #38

**Comment by The-SamminAter** [comment] 2020-02-24 11:44
@osy86 I'm still having this issue on the new version

**Comment by saagarjha** [comment] 2020-02-24 12:48
Have you done anything that might cause iOS to `SIGKILL` your app, like remove it from the app switcher?

**Comment by The-SamminAter** [comment] 2020-02-24 15:56
> 
> 
> Have you done anything that might cause iOS to `SIGKILL` your app, like remove it from the app switcher?

I have removed it from the app switcher.

**Comment by Tizioincognit0** [comment] 2020-02-24 16:07
> > Have you done anything that might cause iOS to `SIGKILL` your app, like remove it from the app switcher?
> 
> I have removed it from the app switcher.

Me too but I do it with all applications that I have installed and UTM is the only with this problem.

**Comment by saagarjha** [comment] 2020-02-24 17:21
You really shouldn't be doing this in general; it's inefficient and waste resources. But in this particular case you *really* should not do this: UTM cannot handle iOS killing the app correctly and this will cause your system to hang and make it impossible to use the app until you reboot. The new version prevents this from happening in the background and when the app crashes.

**Comment by Tizioincognit0** [comment] 2020-02-24 17:22
> You really shouldn't be doing this in general; it's inefficient and waste resources. But in this particular case you _really_ should not do this: UTM cannot handle iOS killing the app correctly and this will cause your system to hang and make it impossible to use the app until you reboot. The new version prevents this from happening in the background and when the app crashes.

But I use KillX which closes all apps.

**Comment by osy86** [comment] 2020-02-24 17:24
Is there anything we can do to prevent this when user manually kills the app? Or should it show a message on first launch alerting the user to this issue?

**Comment by The-SamminAter** [comment] 2020-02-24 17:24
> You really shouldn't be doing this in general; it's inefficient and waste resources. But in this particular case you _really_ should not do this: UTM cannot handle iOS killing the app correctly and this will cause your system to hang and make it impossible to use the app until you reboot. The new version prevents this from happening in the background and when the app crashes.

It didn’t work right after installing, before I had ever quit it though

**Comment by The-SamminAter** [comment] 2020-02-24 17:26
> Is there anything we can do to prevent this when user manually kills the app? Or should it show a message on first launch alerting the user to this issue?

I suggest showing a message on first-start and also (if possible) after an incorrect close

**Comment by saagarjha** [comment] 2020-02-24 17:29
@Tizioincognit0 I can't tell you to not do that, but I'm compelled to tell you that using that tool is counterproductive. If you really must use it, try to see if there is an exception list where you can UTM.

@osy86 Not that I know of; iOS sends an immediate `SIGKILL` and there's nothing we can do to prepare for this AFAIK. An alert on first launch to inform people about what they should not do might be wise.

@The-SamminAter Installing a new version of the app will kill the one running the background; try restarting your device to see if that fixes the issue. Showing a message after the app has been killed is not possible, as by that point the system can no longer launch the app correctly.

**Comment by The-SamminAter** [comment] 2020-02-24 17:34
> @Tizioincognit0 I can't tell you to not do that, but I'm compelled to tell you that using that tool is counterproductive. If you really must use it, try to see if there is an exception list where you can UTM.
> 
> @osy86 Not that I know of; iOS sends an immediate `SIGKILL` and there's nothing we can do to prepare for this AFAIK. An alert on first launch to inform people about what they should not do might be wise.
> 
> @The-SamminAter Installing a new version of the app will kill the one running the background; try restarting your device to see if that fixes the issue. Showing a message after the app has been killed is not possible, as by that point the system can no longer launch the app correctly.

I have restarted, could the problem be that I extracted the .app, and then used mv as root to move it to /Applications/?

I meant that next time it does open. If that can’t be done, how about show a message every first-use after startup?

**Comment by saagarjha** [comment] 2020-02-24 18:16
> I have restarted, could the problem be that I extracted the .app, and then used mv as root to move it to /Applications/?

I'm not sure. Can you not just install it normally?

> I meant that next time it does open. If that can’t be done, how about show a message every first-use after startup?

I was thinking of a message on first launch.

**Comment by The-SamminAter** [comment] 2020-02-24 20:38
> > I have restarted, could the problem be that I extracted the .app, and then used mv as root to move it to /Applications/?
> 
> I'm not sure. Can you not just install it normally?
> 
> > I meant that next time it does open. If that can’t be done, how about show a message every first-use after startup?
> 
> I was thinking of a message on first launch.

I’m going to try installing it with ReProvision now.

Also, I agree with the message on first launch, but I’m suggesting additional messages, should the person forget.

**Comment by a3lharbi** [comment] 2020-02-24 20:47
still facing the issue in iPad pro 11 inch jailbroken after killing the app, the only solution is to restart and re-jailbreak it's really annoying.BTW, in iPhone x jailbroken by chekra1n never faced any issue even if i kill the app 10 hundred times and it's on beta 0.1 ! and if the ipad on non-jail mode it work fine !

**Comment by a3lharbi** [comment] 2020-02-24 20:54
could anyone explain that

**Comment by a3lharbi** [comment] 2020-02-24 21:05
even LDrestart won't do anything the only solution restart and work without any re installation, is the kernel ex affect the app !

**Comment by a3lharbi** [comment] 2020-02-24 21:21
@saagarjha 


See >  https://imgur.com/sHZhbZV

**Comment by a3lharbi** [comment] 2020-02-24 21:25
@osy86 

the bug related with unc0ver definitely

**Comment by The-SamminAter** [comment] 2020-02-24 21:32
> 
> 
> @osy86
> 
> the bug related with unc0ver definitely

Quite possible, though I don't really see why it would be. 

Also, how did you manage to sign the app? I can't seem to be able to import the ipa into ReProvision or AppCake, and don't have access to a mac with Xcode and iOS App Signer currently.

**Comment by a3lharbi** [comment] 2020-02-24 21:35
> > @osy86
> > the bug related with unc0ver definitely
> 
> Quite possible, though I don't really see why it would be.
> 
> Also, how did you manage to sign the app? I can't seem to be able to import the ipa into ReProvision or AppCake, and don't have access to a mac with Xcode and iOS App Signer currently.



I signed the app in both app cake, ReProvision and altstore. All of them worked 
Try alt store definitely will work.

**Comment by The-SamminAter** [comment] 2020-02-24 21:37
I don't have access to AltStore right now, damn

**Comment by a3lharbi** [comment] 2020-02-24 21:38
> I don't have access to AltStore right now, damn

re install appcake from the site with the new profile and try to sign it again

**Comment by a3lharbi** [comment] 2020-02-24 21:40
you also might have an issue with ur apple id since reprovision its work like a charm just try another apple id if u have

**Comment by The-SamminAter** [comment] 2020-02-24 21:42
My ReProvision works, the share menu extension is just not working. Same as with AppCake.

I'll try again in safemode.

**Comment by a3lharbi** [comment] 2020-02-24 21:46
> My ReProvision works, the share menu extension is just not working. Same as with AppCake.
> 
> I'll try again in safemode.

Why the share ext not working !  really strange which version of ios ! and check any realeted tweak might affect ur share ext menu

**Comment by The-SamminAter** [comment] 2020-02-24 21:46
iOS 13.2.3, and I don't have any tweaks which should affect it.

**Comment by saagarjha** [comment] 2020-02-24 21:55
I can’t actually tell much from your GIF because I can’t tell where it starts or ends. Are you seeing the issue or not?

**Comment by a3lharbi** [comment] 2020-02-24 21:56
> iOS 13.2.3, and I don't have any tweaks which should affect it.

Could u illustrate more, what’s the exact issue with share ext menu ,

Isn’t Show app or u can’t find the specified app

If it was the second Just enable Siri in the setting by going to the app and enable Siri suggestions

**Comment by The-SamminAter** [comment] 2020-02-24 21:57
> 
> 
> > iOS 13.2.3, and I don't have any tweaks which should affect it.
> 
> Could u illustrate more, what’s the exact issue with share ext menu ,
> 
> Isn’t Show app or u can’t find the specified app
> 
> If it was the second Just enable Siri in the setting by going to the app and enable Siri suggestions

I can find and use the apps, they just don't show up in the share menu.

**Comment by a3lharbi** [comment] 2020-02-24 21:58
> I can’t actually tell much from your GIF because I can’t tell where it starts or ends. Are you seeing the issue or not? What are the steps from start to finish?

The gif just an explanation That killing The app seems not affected the app and it works again sorry for the bad recording

**Comment by a3lharbi** [comment] 2020-02-24 21:59
> > > iOS 13.2.3, and I don't have any tweaks which should affect it.
> > 
> > 
> > Could u illustrate more, what’s the exact issue with share ext menu ,
> > Isn’t Show app or u can’t find the specified app
> > If it was the second Just enable Siri in the setting by going to the app and enable Siri suggestions
> 
> I can find and use the apps, they just don't show up in the share menu.
> 
> Safemode didn't work.

Go to setting then appcake > enable Siri and search and enable all

**Comment by The-SamminAter** [comment] 2020-02-24 22:06
> Go to setting then appcake > enable Siri and search and enable all

Ok, thanks. I'll try that with ReProvision too.

**Comment by The-SamminAter** [comment] 2020-02-24 22:09
> > Go to setting then appcake > enable Siri and search and enable all
> 
> Ok, thanks. I'll try that with ReProvision too.

Nope, no luck

**Comment by saagarjha** [comment] 2020-02-24 22:15
> The gif just an explanation That killing The app seems not affected the app and it works again sorry for the bad recording

So the issue is fixed?

**Comment by osy86** [comment] 2020-02-24 22:18
I will reopen this ticket until we address the sigkill case.

**Comment by a3lharbi** [comment] 2020-02-24 22:23
> > The gif just an explanation That killing The app seems not affected the app and it works again sorry for the bad recording
> 
> So the issue is fixed?

No killing the app is not an issue , as u see from the gif i killed the app and it work without the problem , this was an iPhone X checkra1n jailbroken . The issue only occurs on a jailbroken device by unc0ver

**Comment by a3lharbi** [comment] 2020-02-24 22:33
@saagarjha    
@osy86 

Please take into consideration. That resigning the app at different bundle will make the app work and git rid of the white screen without RESTARTING THE DEVICE  , but it’s not functional it will crash if u tried to start any VM.


Thanks again .

**Comment by saagarjha** [comment] 2020-02-24 22:34
It works because that makes it essentially a different app. The issue is that the old app doesn't get killed.

**Comment by a3lharbi** [comment] 2020-02-24 22:41
> It works because that makes it essentially a different app. The issue is that the old app doesn't get killed.

Exactly , but why CocoaTop Not responding to kill the app

**Comment by saagarjha** [comment] 2020-02-24 22:56
Because the app dies with ptrace.

**Comment by The-SamminAter** [comment] 2020-02-24 23:03
Ok, so do we know why UTM crashes immediately and doesn't work on unc0ver jailbreaks?

**Comment by saagarjha** [comment] 2020-02-25 02:24
UTM works correctly on unc0ver.

**Comment by The-SamminAter** [comment] 2020-02-25 02:25
@osy86 this issue still occurs on v0.2 fakesigned, even after restarting and ldrestart.

**Comment by The-SamminAter** [comment] 2020-02-25 02:26
> UTM works correctly on unc0ver.

Ok, so it’s just a general issue then.

**Comment by Slapshot300** [comment] 2020-02-25 21:43
I've never commented on a GitHub issue before so please excuse any informalities, but i'm having this problem too. im running the fakesigned v0.2 build on unc0ver for iOS 13.3. the log suggests that it's a problem loading an outdated dylib but this is just me skimming through it, i could be wrong. i'll attach the crash log that i found.

[UTM-2020-02-25-163337.txt](https://github.com/utmapp/UTM/files/4252332/UTM-2020-02-25-163337.txt)

i hope that this is somewhat helpful

**Comment by osy86** [comment] 2020-02-25 21:48
Do you have `libgpg-error` installed by some jailbreak package?

**Comment by Slapshot300** [comment] 2020-02-25 22:01
By what i see no i don't, and I don't know if this is of any relevant help but crash reporter says that no tweaks were loaded when it crashed (i'll include a screenshot of what crash reporter says) i also don't know the reliability of crash reporter on ios 13.3 so take it with a grain of salt.

![20200225_215904000_iOS](https://user-images.githubusercontent.com/21014540/75291501-56e77b80-57f0-11ea-9ec0-b15545d3ef03.png)

**Comment by osy86** [comment] 2020-02-25 22:13
I don't know much about jailbroken systems, but you definitely have libgpg installed. But I can't tell you how to find out what installed it. Don't worry though, I think I have a fix, come back in an hour and I'll give you an ipa to test.

**Comment by The-SamminAter** [comment] 2020-02-25 22:34
@osy86 libgpg (aka GnuPG Errors) is installed by unc0ver, and seems to be a requirement for all apt packages. It comes from apt.bingner.com, which I think (but am not sure) is unc0ver's included repo.

**Comment by osy86** [comment] 2020-02-25 23:00
@Slapshot300 and any others who are getting crash ON APP OPEN (not launching VM)

1. Download https://github.com/utmapp/UTM/suites/481649046/artifacts/2233950
2. Make sure [MacBrew](https://brew.sh) is installed and `brew install ldid`
3. Clone UTM and run `./scripts/resign.sh UTM.xcarchive` with the .xcarchive downloaded in step 1. This should generate a fakesigned IPA.

**Comment by The-SamminAter** [comment] 2020-02-25 23:03
@osy86 will a release with this done to it be available? Also, just a note, Homebrew is referred to as either Homebrew or Brew.

**Comment by osy86** [comment] 2020-02-25 23:19
There won't be a release until next week. It will have this fix.

**Comment by The-SamminAter** [comment] 2020-02-25 23:19
> There won't be a release until next week. It will have this fix.

Ok, thanks.

**Comment by a3lharbi** [comment] 2020-02-26 06:51
@osy86 
@saagarjha 

I have mentioned Before that the app on my iPhone X checkra1n has never facing any issue it will killed properly . 


> @saagarjha
> 
> See > https://imgur.com/sHZhbZV


So I installed Unc0ver On the same device and since the new version of Unc0ver support old devices 

Tried to kill the app to see if it will have the bug . And yess it was white screen for the first time   


So the problem releated only with unc0ver ! so what u may think which prevent to kill the app properly ?

**Comment by Slapshot300** [comment] 2020-02-26 17:21
@osy86 sorry for the late reply, but your fix works perfectly by what i've tested. The app is able to startup and load into a virtual machine without any crashes!

**Comment by a3lharbi** [comment] 2020-02-26 17:27
> @osy86 sorry for the late reply, but your fix works perfectly by what i've tested. The app is able to startup and load into a virtual machine without any crashes!

Please could confirm by this two will u facing any problem:

(1) to power off the vm 
(2) kill the app while u are in vm

**Closed** 2020-03-02 19:18 UTC
