### ISSUE TITLE
Buggy Cursor

### ISSUE THREAD

**Issue by yim0000** [utmapp/UTM#4683] opened 2022-11-16 04:38 UTC
**Describe the issue**  
1. The cursor having original cursor on top of other cursors like original on top of text cursor, including using any custom cursor. 
2. When using captured mouse mode, cursor stops working (freezes or disappears), can be solve exiting full screen and capture mode, using in non-capture mode, then capturing again. 
3. Having duplicated of cursor left on screen after customising cursor, after applying change
4. 3. issue occurs when moving app windows, however disappears when letting go (Not as important)
5. Cursor appearing on start up screen sometimes and always somehow on shutting down screen

**Configuration**  
* UTM Version: 4.0.9
* macOS Version: Ventura 13.0.1
* Mac Chip (Intel, M1, ...): M1

**Comment by bzuruce** [comment] 2022-11-17 01:49
Your VM may just be slow

**Comment by yim0000** [comment] 2022-11-22 13:08
the same not happening when running vmware

**Comment by osy** [comment] 2022-12-29 19:48
Is this on Windows?

**Comment by Andy312432** [comment] 2023-01-05 15:05
> Is this on Windows?

@osy I can confirm this is on windows, and i made a temporary fix(https://github.com/Andy312432/virtio-gpu-wddm-dod/tree/fix-cursor) here. 
Note that this just teleports the cursor to the invisible area as I haven't figure out how to send hide command.

**Comment by yim0000** [comment] 2023-01-10 04:18
thank you for helping

**Comment by osy** [comment] 2023-03-21 05:29
Duplicate of #4896

**Closed by osy** 2023-03-21 05:29 UTC
