### ISSUE TITLE
Shutting down a VM on iOS 14.2 quits out of UTM

### ISSUE THREAD

**Issue by jawshoeadan** [utmapp/UTM#513] opened 2020-11-05 06:06 UTC
On iOS 14.2, JIT is stable enough to the point that UTM no longer has to quit itself in the case that a VM shuts down. On iOS 14.2, the app should stay open after shutting down a VM.

**Comment by IIWare** [comment] 2020-11-05 07:11
Duplicate of #6

**Comment by jawshoeadan** [comment] 2020-11-05 07:18
This time it's different because that JIT was a lot more unstable due to the workaround used.

**Comment by osy86** [comment] 2020-11-05 08:09
Quitting after shutting down is by design.

**Closed by osy86** 2020-11-05 08:09 UTC
