### ISSUE TITLE
Fedora 36/37 "Install to Hard Disk" app does not open

### ISSUE THREAD

**Issue by mijorus** [utmapp/UTM#4982] opened 2023-01-31 00:06 UTC
**Configuration**  
* UTM Version: 4.1.5
* macOS Version: 13.1
* Mac Chip (Intel, M1, ...): M1

ISO downloaded from fedora's website

**Comment by mijorus** [comment] 2023-01-31 00:08
Disabling GPU acceleration was enough to make it work!

Display > Display Card > Virtio RamFb

**Comment by tvolin** [comment] 2023-02-05 21:01
Are there some details we can/should ask to have put in the docs? The docs imply it'll "just work" but clearly you can't accept all defaults and get very far.

**Comment by mijorus** [comment] 2023-02-05 21:47
well, GPU acceleration is hit or miss in my experience.
On Ubuntu for example, some apps just won't launch when GPU acceleration is enabled.

About fedora, UTM should either default to `virtio ramrb` or add a paragraph about this workaround. Out of the box is  just unusable

**Comment by osy** [comment] 2023-02-26 04:31
Duplicate of #4983

**Closed** 2023-02-26 04:31 UTC

**Comment by imnotsoumyajit** [comment] 2023-05-26 16:13
> Disabling GPU acceleration was enough to make it work!
> 
> Display > Display Card > Virtio RamFb 

Where do I get the Display Card option...it is not in Display menu in Fedora 38...
Can you explain?

**Comment by pdomineaux** [comment] 2024-03-20 16:36
> > Disabling GPU acceleration was enough to make it work!
> > Display > Display Card > Virtio RamFb
> 
> Where do I get the Display Card option...it is not in Display menu in Fedora 38... Can you explain?

The change has to be made in UTM not in Fedora.
