### ISSUE TITLE
Crash when clicking on a VM in the list 

### ISSUE THREAD

**Issue by trisall7** [utmapp/UTM#3920] opened 2022-04-21 16:56 UTC
UTM App version 3.1.5 keeps crashing as of today. possibly due to a recent Upgrade on my Macbook Air 12.3.1?  It seems to crash anytime I just click on a Virtual Machine without even launching or clicking the play Icon.

**Comment by conath** [comment] 2022-04-21 20:24
Can you please try this: before clicking any VM, resize the window to its minimum width. Then click the VM, and finally resize it larger again. Does it work?

**Comment by trisall7** [comment] 2022-04-21 20:41
Yeah that seemed to work, I appreciate the help. I apologize if this is a common issue that has been addressed before.

**Comment by conath** [comment] 2022-04-21 21:34
No worries. Duplicate of #3612

**Closed by conath** 2022-04-21 21:34 UTC
