### ISSUE TITLE
UTM invisible windows Macos Ventura

### ISSUE THREAD

**Issue by Hadesepi** [utmapp/UTM#5153] opened 2023-03-28 12:56 UTC
**Describe the issue**  
I have an issue in my Ubuntu VM, everything starts normally and goes well until i try to open anything, it opens however nothing is displayed, the window is opened but it's invisible. I cannot access any applications nor the terminal, literally every window is invisible. However all the rest seems working fine. I have someone else who encounters problems with his UTM too, I have tried the following : Changing UTM Version, re installing another VM, changing the version of the VM, changing the display mode, updating my mac, rebooting the VM, rebooting the mac and many others. None of this worked. I've tried to look for someone with a similar problem and found none. Is there a solution or should i go back to an old version of mac ?

**Configuration**  
* UTM Version: 4.1.6 (75)
* macOS Version: Ventura 13.2.1 (22D68)
* Mac Chip (Intel, M1, ...): Apple M1 Pro

**Debug log**  
[debug.log](https://github.com/utmapp/UTM/files/11089551/debug.log)

**Upload VM**  
[config.plist.zip](https://github.com/utmapp/UTM/files/11089562/config.plist.zip)

**Comment by palbergstrom** [comment] 2023-04-08 18:20
+1

**Comment by osy** [comment] 2023-04-15 00:45
Duplicate of #4983

**Closed by osy** 2023-04-15 00:45 UTC
