### ISSUE TITLE
App won’t let me select files on iPadOS 18.1 when side loading with a dev certificate

### ISSUE THREAD

**Issue by ActTrue** [utmapp/UTM#6650] opened 2024-09-03 23:52 UTC
The app side loads but when i go to make a VM and they ask for an ISO file it won’t let me pick one. they aren’t greyed out but the open button just won’t go to the next menu? UTM prebuilt files wont open either. What does seem to work is loading prebuilt directly from the gallery.

**Configuration (required)**
* UTM Version: 4.5.1
* OS Version: iPadOS18.1 beta 3
* Device Model: M1 iPad Pro 11” 
* Is it jailbroken (name jailbreak used)? No
* How did you install UTM? I side loaded with an apple Dev Certificate from MapleSigner (now kravasigner)

**Comment by osy** [comment] 2024-09-04 01:00
Duplicate of #5491

Use a supported resigning method like AltStore or Xcode

**Closed by osy** 2024-09-04 01:00 UTC
