### ISSUE TITLE
Keep getting redirected to msn.com

### ISSUE THREAD

**Issue by TudorOnMac** [utmapp/UTM#2666] opened 2021-07-13 06:54 UTC
**Describe the issue**
Once the VM is started and I am logged in Microsoft Edge starts opening a page that redirects to MSN about every minute. No way to stop it.

**Configuration**
* UTM Version: Version 2.1.1 (30)
* OS Version: macOS 12 Dev Beta 2
* Intel or Apple Silicon? Apple Silicon
* 
**Debug log**
[debug.log](https://github.com/utmapp/UTM/files/6806520/debug.log)

**Upload VM**
https://drive.google.com/file/d/12YynY_fus4kkZDCLy57d31rhViNvt7En/view?usp=sharing
GitHub doesn't support .plist files :(

**Video**
https://drive.google.com/file/d/19jw20mQCXHAgyoEy71FbCPPappaBgoKz/view
Video is too big to attach.

**Comment by conath** [comment] 2021-07-13 07:40
Duplicate of #2585 – see https://github.com/utmapp/UTM/discussions/2590#discussioncomment-825681 for a workaround.

**Closed by conath** 2021-07-13 07:40 UTC
