### ISSUE TITLE
Removable USB Drives are always CDROM

### ISSUE THREAD

**Issue by pmsjt** [utmapp/UTM#5171] opened 2023-04-04 10:50 UTC
**Describe the issue**  

When adding a removable, USB **Disk** image, UTM still passes a CDROM parameter to QEMU.

In other words:
```
		<dict>
			<key>Identifier</key>
			<string>2E751467-FB9D-4548-9242-0C2DEE3DC342</string>
			<key>ImageType</key>
			<string>Disk</string>
			<key>Interface</key>
			<string>USB</string>
		</dict>
```
Results in
```
-device usb-storage,drive=drive2E751467-FB9D-4548-9242-0C2DEE3DC342,removable=true,bootindex=1,bus=usb-bus.0 -drive if=none,media=cdrom,id=drive2E751467-FB9D-4548-9242-0C2DEE3DC342
```
Note the `media=cdrom` parameter.

**Configuration**  
* UTM Version:  Version 4.1.6 (75)
* macOS Version: 13.3
* Mac Chip (Intel, M1, ...): M1

**Comment by osy** [comment] 2023-04-15 00:37
That is intended (USB = USB removable CD drive). What purpose is there for a removable USB drive that cannot be achieved as a USB removable CD drive?

**Comment by pmsjt** [comment] 2023-04-15 01:51
Erm... an USB thumbdrive for example? Something I can inject, write to and eject without having to reboot the VM. I am achieving this by adding custom QEMU parameters and using the QEMU console, but that defeats the purpose of using UTM.

**Comment by osy** [comment] 2023-04-15 01:58
Duplicate of #5079

**Comment by pmsjt** [comment] 2023-04-15 04:46
I don't understand why you are closing this. This is clearly a UI bug. The UI has the option to create am external USB CD or disk but the setting has bo effect. Despite of what the user selects, the result is always CD. Some wires are crossed or cut here.

**Closed** 2023-04-17 02:55 UTC

**Comment by pmsjt** [comment] 2023-04-17 02:57
This is great @osy ! Can't wait to give it a try :-)
