### ISSUE TITLE
UTM release with Qemu 8.2.1

### ISSUE THREAD

**Issue by stuaxo** [utmapp/UTM#6082] opened 2024-02-09 17:24 UTC
Qemu 8.2.1 came out on Jan 29th, will there be a UTM release ?

(I realise there are quite a lot of patches in the UTM qemu, have many of these been upstreamed in the meantime?)

**Comment by osy** [comment] 2024-02-09 18:44
Duplicate of #5516

**Closed by osy** 2024-02-09 18:44 UTC
Labels: enhancement
