### ISSUE TITLE
Kernel panic when choosing -gl option for display

### ISSUE THREAD

**Issue by DownGnu** [utmapp/UTM#3646] opened 2022-02-20 02:35 UTC
**Describe the issue**
So, whenever i run “startx” (to startup dwm) it gives me the pink screen/kernel panic. After the reboot, I went to Privacy -> Analytics & Improvements -> Analytics Data -> panic-full-[date].ips it gives me this code on the **Crash Log**. (there are more but it’s just the top part of the code)

**Configuration (required)**
* UTM Version: 3.1.0
* OS Version: 15.3.1
* Device Model: ipad pro 13,4(m1)
* Is it jailbroken (name jailbreak used)? Nope.
* How did you install UTM? Altstore

**Crash log**

{"bug_type":"210","timestamp":"2022-02-19 18:08:45.00 -0800","os_version":"iPhone OS 15.3.1 (19D52)","incident_id":"D56CD42F-3E96-4BC4-9D59-F2D61306C204"}
{
  "build" : "iPhone OS 15.3.1 (19D52)",
  "product" : "iPad13,4",
  "kernel" : "Darwin Kernel Version 21.3.0: Wed Jan  5 21:44:48 PST 2022; root:xnu-8019.80.24~23\/RELEASE_ARM64_T8101",
  "incident" : "D56CD42F-3E96-4BC4-9D59-F2D61306C204",
  "crashReporterKey" : "758d2509f0f823c91381ae7bbc6446fb22901aa5",
  "date" : "2022-02-19 18:08:45.18 -0800",
  "panicString" : "panic(cpu 4 caller 0xfffffff015745e2c): \"IOSurfaceRootUserClient::set_surface_handle asked to set handle 0000013a that was not free: 0xffffffe4ccc65b80\" @IOSurfaceRootUserClient.cpp:2169\nDebugger message: panic\nMemory ID: 0xff\nOS release type: User\nOS version: 19D52\nKernel version: Darwin Kernel Version 21.3.0: Wed Jan  5 21:44:48 PST 2022; root:xnu-8019.80.24~23\/RELEASE_ARM64_T8101\nKernel UUID: AF46758E-09BF-3AB4-8606-5BEFA320A380\niBoot version: iBoot-7429.82.1\nsecure boot?: YES\nPaniclog version: 13\nKernel slide:      0x000000000d160000\nKernel text base:  0xfffffff014164000\nmach_absolute_time: 0x7b18ba315f\nEpoch Time:        sec       usec\n  Boot    : 0x62114b14 0x00053733\n  Sleep   : 0x62115ad4 0x000b64d6\n  Wake    : 0x62115ae6 0x00079af8\n  Calendar: 0x6211a299 0x0002f745\n\nZone info:\nForeign   : 0xfffffff20f3fc000 - 0xfffffff20f40c000\nNative    : 0xffffffe000180000 - 0xffffffe600180000\nReadonly  : 0xffffffe0e67e4000 - 0xffffffe1334a8000\nMetadata  : 0xffffffeb05c30000 - 0xffffffeb0a470000\nBitmaps   : 0xffffffeb07430000 - 0xffffffeb09f78000\nCORE 0 recently retired instr at 0xfffffff014ff4d88\nCORE 1 recently retired instr at 0xfffffff014ff4d88\nCORE 2 recently retired instr at 0xfffffff014ff4d88\nCORE 3 recently retired instr at 0xfffffff014ff4d88\nCORE 4 recently retired instr at 0xfffffff014ff38e8\nCORE 5 recently retired instr at 0xfffffff014ff4d8c\nCORE 6 recently retired instr at 0xfffffff014ff4d8c\nCORE 7 recently retired instr at 0xfffffff014ff4d8c\nCORE 0: PC=0xfffffff0164df0ec, LR=0xfffffff0164df0c8, FP=0xffffffeb1b87bc50\nCORE 1: PC=0xfffffff014f1ba34, LR=0xfffffff014f1ba18, FP=0xffffffeb11edb520\nCORE 2: PC=0xfffffff014edf0a0, LR=0xfffffff014edf0a0, FP=0xffffffeb25963ef0\nCORE 3: PC=0x00000001aec847a0, LR=0x00000001aec84768, FP=0x000000016d5d2a10\nCORE 4 is the one that panicked. Check the full backtrace for details.\nCORE 5: PC=0xfffffff014edf0a4, LR=0xfffffff014edf0a0, FP=0xffffffeb0bc8bef0\nCORE 6: PC=0xfffffff014edf0a0, LR=0xfffffff014edf0a0, FP=0xffffffeb11f4bef0\nCORE 7: PC=0xfffffff014edf0a4, LR=0xfffffff014edf0a0, FP=0xffffffeb218abef0\nPanicked task 0xffffffe2189833e0: 68277 pages, 30 threads: pid 2629: UTM SE\nPanicked thread: 0xffffffe3ea3d4000, backtrace: 0xffffffeb1c6e3130, tid: 158163\n\t\t  lr: 0xfffffff014ea9044  fp: 0xffffffeb1c6e3170\n\t\t  lr: 0xfffffff014ea8d64  fp: 0xffffffeb1c6e31e0\n\t\t  lr: 0xfffffff014ffb46c  fp: 0xffffffeb1c6e3200\n\t\t  lr: 0xfffffff014fec82c  fp: 0xffffffeb1c6e3280\n\t\t  lr: 0xfffffff014feb51c  fp: 0xffffffeb1c6e3340\n\t\t  lr: 0xfffffff0155fc728  fp: 0xffffffeb1c6e3350\n\t\t  lr: 0xfffffff014ea8a30  fp: 0xffffffeb1c6e36e0\n\t\t  lr: 0xfffffff014ea8a30  fp: 0xffffffeb1c6e3740\n\t\t  lr: 0xfffffff0173f13e8  fp: 0xffffffeb1c6e3760\n\t\t  lr: 0xfffffff015745e2c  fp: 0xffffffeb1c6e3790\n\t\t  lr: 0xfffffff015743ec8  fp: 0xffffffeb1c6e37c0\n\t\t  lr: 0xfffffff01573862c  fp: 0xffffffeb1c6e3800\n\t\t  lr: 0xfffffff01573852c  fp: 0xffffffeb1c6e3830\n\t\t  lr: 0xfffffff015740910  fp: 0xffffffeb1c6e3890\n\t\t  lr: 0xfffffff01573f228  fp: 0xffffffeb1c6e38d0\n\t\t  lr: 0xfffffff01555d3b0  fp: 0xffffffeb1c6e3930\n\t\t  lr: 0xfffffff01556a934  fp: 0xffffffeb1c6e3ac0\n\t\t  lr: 0xfffffff014fb8808  fp: 0xffffffeb1c6e3be0\n\t\t  lr: 0xfffffff014eb00c4  fp: 0xffffffeb1c6e3c80\n\t\t  lr: 0xfffffff014e80e10  fp: 0xffffffeb1c6e3cf0\n\t\t  lr: 0xfffffff014e9b138  fp: 0xffffffeb1c6e3d80\n\t\t  lr: 0xfffffff014fdff00  fp: 0xffffffeb1c6e3e50\n\t\t  lr: 0xfffffff014feb954  fp: 0xffffffeb1c6e3f10\n\t\t  lr: 0xfffffff0155fc728  fp: 0xffffffeb1c6e3f20\n\n",
  "panicFlags" : "0x802",
  "otherString" : "\n** Stackshot Succeeded ** Bytes Traced 270833 (Uncompressed 687440) **\n",
  "memoryStatus" : {"compressorSize":19598,"compressions":193451,"decompressions":73749,"busyBufferCount":0,"pageSize":16384,"memoryPressure":false,"memoryPages":{"active":186757,"throttled":0,"fileBacked":136003,"wired":59116,"purgeable":11744,"inactive":185103,"free":22085,"speculative":1461}},

**Comment by osy** [comment] 2022-02-21 08:17
Duplicate of #2743

**Closed by osy** 2022-02-21 08:17 UTC
Labels: duplicate
