### ISSUE TITLE
Mouse pointer gets stuck on wrong animation

### ISSUE THREAD

**Issue by LordBongio** [utmapp/UTM#3115] opened 2021-09-14 14:45 UTC
**ISSUE**
about 6 out of 10 times the mouse pointer gets stack on the "write mode" and i have to bring the cursor all the way up to let it reset and viceversa, sometimes when i have to write the cursor doesn't change and so it doesn't recognize i'm on a writable space and it doesn't let me.

**Configuration**
* UTM Version: 2.2.4
* OS Version: 11.5.2
* Intel or Apple Silicon? apple

**Comment by conath** [comment] 2021-09-18 16:48
Does this happen in the UTM UI or in a VM guest? Which guest OS are you using?

**Comment by LordBongio** [comment] 2021-09-18 18:13
> Does this happen in the UTM UI or in a VM guest? Which guest OS are you using?

It happens on Kali linux, and it happens quite often

**Comment by osy** [comment] 2021-10-11 08:13
@LordBongio can you check if the issue persists in v2.3.0?

**Comment by osy** [comment] 2021-11-01 19:12
Duplicate of #3188

**Closed by osy** 2021-11-01 19:12 UTC
Labels: duplicate
