### ISSUE TITLE
Windows 11 on m1 Mac through UTM stuck on boot loop

### ISSUE THREAD

**Issue by Coding-beginner** [utmapp/UTM#3387] opened 2021-12-14 12:56 UTC
I followed all the steps on UTM website but the Windows setup location screen comes and then the message "why did my PC restart" screen comes.
Then, it restarts again and lands up on the same place after half an hour. I am stuck in this boot loop

* UTM Version: 2.4.2
* OS Version: Monterey 12.0.1
*M1 Apple Silicon
[debug.log](https://github.com/utmapp/UTM/files/7719099/debug.log)

I am not doin the other stuff as I don't know how to... I am a beginner😅

**Comment by Daniyal-Warraich** [comment] 2021-12-17 17:17
Look at the other [issue](https://github.com/utmapp/UTM/issues/3130).

**Comment by conath** [comment] 2021-12-19 13:23
Duplicate of #3130

**Closed by conath** 2021-12-19 13:23 UTC
