### ISSUE TITLE
crash during powering up of VM -> ipad pro 2018, NJB, ios14.2

### ISSUE THREAD

**Issue by yrjo** [utmapp/UTM#522] opened 2020-11-07 23:38 UTC
**Describe the bug**

as mentioned in https://github.com/utmapp/UTM/issues/516
and asked by @osy86 for creation of new issue:
 
--> crash of UTM version 2.0.8
checked with ipad pro11 2018 version, (A12/x device)
NJB, ios14.2. public release,
sideloaded signed with paid dev cert with https://github.com/DanTheMan827/ios-app-signer/releases/tag/1.13.1

UTM started normally, crashed after start of VM (timeout).

**To Reproduce**
1. run the UTM app
2. try to power on the VM
3.  waiting; timeout
4. UTM crashed

**Crash log**
[UTM-2020-11-07-195051.log](https://github.com/utmapp/UTM/files/5505652/UTM-2020-11-07-195051.log)

**Debug log**
[debug.log](https://github.com/utmapp/UTM/files/5505653/debug.log)

**Upload VM**
--> its untouched version of https://github.com/utmapp/vm-downloads/releases/tag/archlinux-arm64

**Comment by osy86** [comment] 2020-11-07 23:43
`qemu-system: -append only allowed with -kernel option`

Seems like QEMU 5.1.0 doesn’t like the arguments out of order.

**Comment by osy86** [comment] 2020-11-07 23:46
Duplicate of #515 

Let’s track the issue there.

**Closed by osy86** 2020-11-07 23:46 UTC
Labels: duplicate

**Comment by vandergw** [comment] 2020-11-16 16:37
@osy86 Hello, having the same issue here, I see you are working on a fix, in the mean time is there a workaround to avoid this error to occur?

**Comment by osy86** [comment] 2020-11-16 16:39
The issue here has been fixed in v2.0.9. If you’re experiencing a similar issue file a new ticket and *fill in all the requested information*.
