### ISSUE TITLE
Unable to install Windows 11

### ISSUE THREAD

**Issue by lukewis** [utmapp/UTM#6809] opened 2024-11-14 23:57 UTC
**Describe the issue** 
Unable to install Windows 11.  UTM seems to get stuck in some kind a boot loop.  It comes up with "Press any key to boot from CD...", I do and it immediately seems to reboot and ask me the same question.  I never reach past this step.  I've tried this BOTH on an M1 Macbook Air and an i9 Macbook Pro and see the same behavior.  I've double-checked that the ios architecture matches the quemu settings (I tried to "Virtualize" x64 on the i9 and "Emulate" x64 on the M1)

**Configuration**  
* UTM Version: 4.5.4 (100)
* macOS Version:  15.1 (Sequoia)
* Mac Chip: Tried with BOTH M1 and i9 

**Crash log**  
N/A

**Debug log**
NOTE: This is from the M1 (not the i9)
[2024-11-14-BootLoopWindows11.log](https://github.com/user-attachments/files/17759325/2024-11-14-BootLoopWindows11.log)

**Upload VM**  
NOTE: This is from the M1 (not the i9)
[config.plist.zip](https://github.com/user-attachments/files/17759400/config.plist.zip)

**Comment by TsangHingTat** [comment] 2024-11-15 17:01
I’m experiencing the same issue on a MacBook Pro 2024.

- UTM Version 4.6.0 (102)
- macOS Version: 15.2 (Sequoia)
- Mac Chip: M4 Pro

**Comment by lukewis** [comment] 2024-11-15 21:21
Possibly.... although that ticket claims it wasn't reproducible on apple silicon

**Comment by mikegarciam** [comment] 2024-11-20 15:43
the workaround in #6772 was to use an earlier win11 build (win11-23H2 instead of win11-24H2). Maybe try and see if that works for you?

**Comment by TsangHingTat** [comment] 2024-11-21 14:22
Windows 11 23H2 installation was successfully tested on the M1 Pro and M4 Pro MacBook Pros. 😊

**Comment by osy** [comment] 2024-11-26 20:58
Duplicate of #6772

**Closed by osy** 2024-11-26 20:58 UTC

**Comment by Bug-Reaper** [comment] 2025-01-21 04:48
#### Update From Jan 20th 2025

- MacOS 15.x
- Arm M1 Mac Pro

Targeting an x86_64 windows 11 VM.  Both versions of win11-24h2 iso (from microsoft and from crystal-fetch) boot loop on "CD/DVD Entered Press any Key to Continue..." screen.

Found [this](https://os.click/en/Windows:Windows_11:23H2:22631.4169:Multi-Edition:en-us:x64) ISO site to grab the 23h2 version. IMHO better place to grab the ISO, untested whether this would have worked.

Finally noticed this was a duplicate issue and saw it was fixed. Manually upgraded to the latest UTM and this has fixed my win11 install bootloop issue.
