### ISSUE TITLE
BdsDxe: Failed to load Boot0001 "UEFI Misc Device"

### ISSUE THREAD

**Issue by ChangheeOh** [utmapp/UTM#2355] opened 2021-03-02 23:49 UTC
**Describe the issue**
A clear and concise description of what the issue is. **BEFORE SUBMITTING YOUR ISSUE, PLEASE LOOK AT THE PINNED ISSUES AND USE THE SEARCH FUNCTION TO MAKE SURE IT IS NOT ALREADY REPORTED. ALWAYS COMMENT ON AN EXISTING ISSUE INSTEAD OF MAKING A NEW ONE.**

I have tried to create Ubuntu 20.04 arm64 VM by UTM almost with default configuration and there is an error occurring now as bellow at console.

1) First screen
```
BdsDxe: failed to load Boot0001 "UEFI Misc Device" from VenHw(93E34C7E-B50E-11DF-9223-244DFD72085,00): Not Found
BdsDxe: failed to lad Boot0002 "UEFI Misc Device 2" from RciRoot(0x0)/Pci(0x3,0x0): Not Found

>>Start PXE over IPv4.
```

2) Last screen
```
UEFI Interactive Shell v2.2
EDK II
UEFI v2.70 (EDK II, 0x00010000)
Mapping table
    FS0: Alias(s):CD0h0a0a:;BLK1:
    ... (omitted)
Press ESC in 1 seconds to skip startup.nsh or any other key to continue.
```

**Configuration**
* UTM Version: 2.0.22(22)
* OS Version: Big Sur 11.2.2
* Intel or Apple Silicon? Apple Silicon
* QEMU Version: 
    qemu: stable 5.2.0 (bottled), HEAD
    Emulator for x86 and PowerPC
    https://www.qemu.org/
    /opt/homebrew/Cellar/qemu/5.2.0 (161 files, 560MB) *
      Poured from bottle on 2021-02-26 at 09:41:33
    From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/qemu.rb
    License: GPL-2.0-only
    ==> Dependencies
    Build: libtool ✔, meson ✔, ninja ✔, pkg-config ✔
    Required: glib ✔, gnutls ✔, jpeg ✔, libpng ✔, libssh ✔, libusb ✔, lzo ✔, ncurses ✔, nettle ✔, pixman ✔, snappy ✔, vde ✔
    ==> Options
    --HEAD
	    Install HEAD version
    ==> Analytics
    install: 12,020 (30 days), 29,110 (90 days), 106,888 (365 days)
    install-on-request: 11,955 (30 days), 28,968 (90 days), 104,695 (365 days)
    build-error: 0 (30 days)

**Crash log**
If the app crashed, you need a crash log. To get your crash log, open Console.app, go to `Crash Reports`, and find the latest entry for either QEMU, QEMUHelper, or qemu-\*. Right click and choose `Reveal in Finder`. Attach the report here.

There is no crash report found in the following directories. If I missed to find somewhere other, please let me know.

/Users/<user>/Library/Logs/DiagnosticReports
/Library/Logs/DiagnosticReports

**Debug log**
For all issues, _including_ crashes, you should attach a debug log. Open UTM, and open the settings for the VM you wish to launch. Near the top of the `QEMU` page is `Debug Log`. Turn it on and save the VM. After you experience the issue, open the VM settings again and select `Export Log...` and attach it here.

1) Debug log exported
Running:  -L /Applications/UTM.app/Contents/Resources/qemu -S -qmp tcp:127.0.0.1:4000,server,nowait -vga none -nographic -chardev pipe,id=term0,path=/var/folders/b_/wc72yt5s56dbjqb0nn7mklqh0000gn/T/com.utmapp.UTM/ubt.terminal -serial chardev:term0 -cpu cortex-a72 -smp cpus=8,sockets=1,cores=8,threads=1 -machine virt,highmem=off -accel hvf -accel tcg,tb-size=512 -bios /Applications/UTM.app/Contents/Resources/qemu/edk2-aarch64-code.fd -boot order=d -m 2048 -name ubt -device qemu-xhci -device usb-tablet -device usb-mouse -device usb-kbd -drive if=virtio,media=disk,id=drive0,file=/Users/och/Library/Containers/com.utmapp.UTM/Data/Documents/ubt.utm/Images/disk-0.qcow2,cache=writethrough -device usb-storage,drive=drive1,removable=true -drive if=none,media=cdrom,id=drive1 -device virtio-net-pci,netdev=net0 -netdev user,id=net0 -uuid C7C37447-A558-42DE-B0FE-BE92B89D5DC6 -rtc base=localtime

2) QEMU command exported 
qemu-system-aarch64 -L /Applications/UTM.app/Contents/Resources/qemu -S -qmp tcp:127.0.0.1:4444,server,nowait -vga none -nographic -chardev pipe,id=term0,path=/var/folders/b_/wc72yt5s56dbjqb0nn7mklqh0000gn/T/com.utmapp.UTM/ubt.terminal -serial chardev:term0 -cpu cortex-a72 -smp cpus=8,sockets=1,cores=8,threads=1 -machine virt,highmem=off -accel hvf -accel tcg,tb-size=512 -bios /Applications/UTM.app/Contents/Resources/qemu/edk2-aarch64-code.fd -boot order=d -m 2048 -name ubt -device qemu-xhci -device usb-tablet -device usb-mouse -device usb-kbd -drive if=virtio,media=disk,id=drive0,file=/Users/och/Library/Containers/com.utmapp.UTM/Data/Documents/ubt.utm/Images/disk-0.qcow2,cache=writethrough -device usb-storage,drive=drive1,removable=true -drive if=none,media=cdrom,id=drive1 -device virtio-net-pci,netdev=net0 -netdev user,id=net0 -uuid C7C37447-A558-42DE-B0FE-BE92B89D5DC6 -rtc base=localtime

**Upload VM**
(Optional) If possible, upload the `config.plist` inside the `.utm`. If you do not have this, you can upload the entire `.utm` but note this contains your personal data. Since Github has an attachment size limit, you may want to upload to another service such as Google Drive. Link it here.

**Comment by osy** [comment] 2021-03-03 02:17
Duplicate of #2333

**Closed by osy** 2021-03-03 02:17 UTC
Labels: duplicate

**Comment by abraamgtr** [comment] 2023-05-03 07:49
You can add boot from the virtual cd drive that is your mac iso file and save and reset it.
It will detect the file and boot from that.

**Comment by Starmynd** [comment] 2024-06-19 12:43
did you fix it? i have the same issue

**Comment by ChangheeOh** [comment] 2024-06-19 22:07
I have not retry it yet.

**Comment by Aaryanb45** [comment] 2024-09-19 20:23
hiii
I am facing this error
BdsDxe: failed to load Boot0001 "UEFI QEMU QEMU USB HARDDRIVE 1-0000:00:04.0-4.1 from PciRoot (0x0)/Pci (0x4,0x0)/USB (0x7,0x0)/USB (0x0,0x0): Not Found BdsDxe: loading Boot0005 "ubuntu" from HD (1,GPT,5E282052-9FD8-4AD5-BO8D-3A91DF45 DDD5,0x800,0x219800)/\EFI\ubuntu\shimaa64.efi BdsDxe: starting Boot0005 "ubuntu" from HD (1,GPT,5E282C52-9FD8-4AD5-BOOD-3A91DF4 5DDD5,0x800,0x219800)/\EFI\ubuntu\shimaa64.efi EFI stub: Booting Linux Kernel... EFI stub: Using DTB from configuration table EFI stub: Exiting boot services...

**Comment by P-A-R-U-S** [comment] 2024-10-05 19:20
Looks like same issue with different ubuntu distro

![Screenshot 2024-10-05 at 12 20 16 PM](https://github.com/user-attachments/assets/4752805f-5076-4450-9015-5667a772f6f2)

**Comment by cbdula** [comment] 2025-01-29 01:37
> Did anyone find a fix to this?
> 
> **Linux VM UTM Error:** "BdsDxe: failed to load Boot0001 "UEFI QEMU QEMU USB HARDDRIVE 1-0000:00:04.0-4.1" from PciRoot(0x0)/Pci(0x4,0x0)/USB(0x7,0x0)/USB(0x0,0x0): Not Found"

When I started my VM, I selected "Emulate" instead of "Virtualize". Then it worked.
