### ISSUE TITLE
Duplicate popup dialogs shown when deleting VMs

### ISSUE THREAD

**Issue by mariobrostech** [utmapp/UTM#3903] opened 2022-04-14 16:41 UTC
**Describe the issue**
This is a pretty minor issue, but as a frequent user of UTM, it can become quite annoying. When I try to delete a VM, I will almost always see multiple popup dialogs confirming the deletion. No matter which option I select (delete or cancel), the same exact dialog will appear afterwards. If I chose to delete the VM in the prior dialog and delete it again, I will receive an error about being unable to remove the machine since UTM had already deleted it. I know this is a minor annoyance, but if it could be fixed, I'd really appreciate it!

I've attached a screen recording showing the behavior below:
https://user-images.githubusercontent.com/17557442/163434873-aa5200db-7c26-4be3-93a5-17a89b393645.mov

**Configuration**
* UTM Version: 3.1.5
* OS Version: macOS Big Sur (11.6.5)
* Intel or Apple Silicon? Intel

**Comment by osy** [comment] 2022-04-23 00:31
Duplicate of #2337

Unfortunately this is a SwiftUI framework bug on Apple's side and they only fixed it on macOS 12. As addressing this on the application side is too messy, we just have to live with the bug.

**Closed by osy** 2022-04-23 00:31 UTC
Labels: duplicate
