### ISSUE TITLE
Unable to select anything but ISO files for a removable drive

### ISSUE THREAD

**Issue by conath** [utmapp/UTM#2386] opened 2021-03-16 14:12 UTC
This issue was reported on Discord, when selecting a file from iCloud.
~~Part of the installed tweaks are Filza and iCleaner.~~
The issue persists in Safe Mode. Unc0ver v6.1.1.

**Configuration**
* UTM Version: 2.0.24
* OS Version: 14.3
* Device Model: iPhone 12 Pro Max
* Is it jailbroken (name jailbreak used)? Yes (unknown)
* How did you install UTM?  Tried AltStore and Cydia

**Upload VM**
[MS-DOS_Windows1.0 [Clone].utm.zip](https://github.com/utmapp/UTM/files/6149627/MS-DOS_Windows1.0.Clone.utm.zip)

**Comment by conath** [comment] 2021-03-16 14:13
This screenshot shows the issue. IMG files can't be selected. 
![image1](https://user-images.githubusercontent.com/12073163/111323407-21ffce00-866a-11eb-8dea-4a9e0043e1ab.png)

**Comment by ahTy** [comment] 2021-03-22 01:59
I have the same problem, not only in 2.0.24, but also in 2.0.22

**Comment by conath** [comment] 2021-03-23 07:48
@ahTy A workaround that has been discovered is to copy the files to the “On My iPhone” part of Files. Then you will be able to select them in UTM.

**Comment by ahTy** [comment] 2021-03-24 08:38
> @ahTy A workaround that has been discovered is to copy the files to the “On My iPhone” part of Files. Then you will be able to select them in UTM.

Thank you. I've uninstalled this junk UTM and don't want to install it any more

**Comment by EscolarProgramming** [comment] 2021-06-13 19:36
After my original issue was closed, I'm now responding to it here, even if a bit late: Unfortunately, the alternative UTM file didn't help either, the same problems still exist.

**Comment by osy** [comment] 2021-09-04 03:39
Duplicate of #519

The issue appears to be how AltStore/others re-sign without changing the provisioning profile's team id.

**Closed by osy** 2021-09-04 03:39 UTC
