### ISSUE TITLE
Cursor disappears while running windows 10 on m1 macs

### ISSUE THREAD

**Issue by Jyuvv** [utmapp/UTM#2684] opened 2021-07-26 04:01 UTC
**Describe the issue**
Cursor disappearing while in use, this issue has been constantly occuring, sometimes the cursor comes back if i move it rapidly around, but then a couple seconds later, the cursor disappears again,  and again, and again 
**Configuration**
* UTM Version: 2.1.2
* OS Version: macOS 11.4
* Intel or Apple Silicon? Apple silicon

**Comment by TudorOnMac** [comment] 2021-07-27 05:06
This might be a duplicate of my issue, #2628. Go check that out and let me know if you are still experiencing problems.

**Comment by brainstorm** [comment] 2021-07-28 00:45
Great forensics and troubleshooting on issue #2628! I'm having this same issue as well but I'm hesitant to go through the workaround since [it seems to involve reinstalling windows?](https://github.com/utmapp/UTM/issues/2628#issuecomment-886149516) ... I hope the final fix does not require that? :-S

**Comment by TudorOnMac** [comment] 2021-07-28 04:57
> Great forensics and troubleshooting on issue #2628! I'm having this same issue as well but I'm hesitant to go through the workaround since [it seems to involve reinstalling windows?](https://github.com/utmapp/UTM/issues/2628#issuecomment-886149516) ... I hope the final fix does not require that? :-S

There will probably be a fix for this in the next version of UTM, but I can’t really tell because I am just an user.

**Comment by conath** [comment] 2021-08-03 19:41
Closing as it's a duplicate of #2628

**Closed by conath** 2021-08-03 19:41 UTC
