### ISSUE TITLE
Remove able device wont let me select the ios

### ISSUE THREAD

**Issue by Earthys** [utmapp/UTM#4591] opened 2022-11-01 16:18 UTC
IOS12.5.5 iphone6 Jailbroken Microsoft xp

When bios starts and i go through my files to select my iso xp its shown as grey and unselectable

**Comment by osy** [comment] 2022-11-01 17:22
Duplicate of #519

**Comment by osy** [comment] 2022-11-01 17:22
You’ve signed it improperly. Follow the guide for correct resigning instructions. https://docs.getutm.app/installation/ios/

**Closed by osy** 2022-11-01 17:22 UTC
