### ISSUE TITLE
network only on localhost

### ISSUE THREAD

**Issue by arnjan** [utmapp/UTM#2423] opened 2021-04-05 11:11 UTC
Please browse the existing issues and filter by 'enhancement' to make sure this has not already been suggested!
there is no machine running with internet connection,I ve tried several prebuild machines, none of them works

**Comment by conath** [comment] 2021-04-05 23:28
Hi, this is likely a duplicate of #2353. Please read the info in the first comment in that issue.

**Comment by osy** [comment] 2021-04-24 22:30
Duplicate of #2353

**Closed by osy** 2021-04-24 22:30 UTC
