### ISSUE TITLE
Windows 7 and 10 crash consistently: mprotect failed: Permission denied

### ISSUE THREAD

**Issue by jonofmac** [utmapp/UTM#2630] opened 2021-06-22 05:37 UTC
**Describe the issue**
Hello, I'm running x86 windows 7 or windows 10 on M1. I'm having an issue where it seems that QEMU is crashing every time I try to launch this VCM Editor or VCM Scanner.

To replicate, I'd suggest the following:
1) Install windows 10 (Version doesn't matter, I have 10 pro). It does it in windows 7 just the same, but 10 has all the pre-reqs.
2) Download and install VCM Suite from hptuners dot com. It's tuning software for cars, but for some reason the emulator crashes 100% of the time with this software.
3) Launch VCM Editor or VCM Scanner. Doesn't matter. The emulator seems to crash and gives me a warning about a random unused parameter. I've tried changing the parameter but it doesn't help anything. Looking at the crash report seems to suggest it may be something there.

End of the log seems to be most telling: 
```log
Please use disable-ticketing=on instead
qemu-x86_64-softmmu: -accel tcg,thread=multi,tb-size=1024: warning: Guest expects a stronger memory ordering than the host provides
This may cause strange/hard to debug errors
qemu-x86_64-softmmu: -accel tcg,thread=multi,tb-size=1024: qemu_mprotect__osdep: mprotect failed: Permission denied
```

**Configuration**
* UTM Version: 2.1.1 (30)
* OS Version: 11.4 (Big Sur)
* Intel or Apple Silicon? Apple M1, 2020, 8 GB, Macbook Air

**Crash log**
[QEMULauncher_2021-06-22-002120_Jonathans-MacBook-Air.crash.zip](https://github.com/utmapp/UTM/files/6691256/QEMULauncher_2021-06-22-002120_Jonathans-MacBook-Air.crash.zip)

**Debug log**
[debug.log](https://github.com/utmapp/UTM/files/6691277/debug.log)

**Comment by jonofmac** [comment] 2021-06-26 05:19
Found a reference that suggested this might have been fixed in the Dev branch. I switched branches and attempted to compile, but was unsuccessful compiling.

```
error: unknown type name 'mbstate_t'; did you mean '__mbstate_t'?
int     mbsinit(const mbstate_t *);
```



And got lots of:
In file included from ```
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk/usr/include/c++/v1/cstddef:37:
../version:1:1: error: expected unqualified-id
6.0.0
```

**Comment by kwhr0** [comment] 2021-06-27 16:19
From the crash log:

```
Exception Type:        EXC_BAD_INSTRUCTION (SIGILL)
Exception Codes:       0x0000000000000001, 0x0000000013948294
Exception Note:        EXC_CORPSE_NOTIFY
```

This bug in QEMU 6.0.0 has been fixed in a patch I submitted.

https://github.com/qemu/qemu/commit/26b1248f66

**Closed** 2021-07-09 20:40 UTC
Labels: crash, qemu

**Comment by martykan** [comment] 2021-07-26 09:33
Unfortunately I got this on 2.1.2 (31) as well. M1 Macbook Air, macOS 11.5

```
qemu-x86_64-softmmu: -accel tcg,tb-size=256: qemu_mprotect__osdep: mprotect failed: Permission denied
```

**Comment by kwhr0** [comment] 2021-07-26 11:59
My patch fixes a crash caused by SIGILL and is not about `mprotect`, which was modified in macOS 11.2.
