### ISSUE TITLE
+ button wont work unless you turn off app and phone multiple times

### ISSUE THREAD

**Issue by jjboi321** [utmapp/UTM#2403] opened 2021-03-25 18:15 UTC
When you click either the edit or plus button none work anything you do wont work i went into the discord and asked for help but didwnt get a reply 

**Configuration (required)**
* UTM Version:newest 
* OS Version: 14.3
* Device Model: 11pro
* Is it jailbroken (name jailbreak used)? Unc0ver
* How did you install UTM? By using the ipa in altstore i also tryed the cydia one miether work

**Comment by conath** [comment] 2021-03-26 00:21
Thanks for reporting this issue. The issue is already known and has the number #2393. Please add your Configuration and the list of installed tweaks to the comments on that issue so we can find which one might be causing this.

In the title you wrote “won’t work unless you turn off the app and phone multiple times”. Are you restarting your phone completely and that makes it work? For how long? Please add your experience to #2393.

**Comment by osy** [comment] 2021-04-24 22:27
Duplicate of #2393

**Closed by osy** 2021-04-24 22:27 UTC
Labels: duplicate
