### ISSUE TITLE
UTM 2.2.4 crash while Windows 10 x86_64 reboots (not reproducible)

### ISSUE THREAD

**Issue by conath** [utmapp/UTM#3100] opened 2021-09-10 11:22 UTC
While testing 2.2.4 UTM crashed with a `possible pointer authentication failure` while a x86_64 guest was rebooting.

**Configuration**
* UTM Version: 2.2.4 (from GitHub releases)
* OS Version: 11.5.2
* Intel or Apple Silicon? Apple Silicon

<details>
  <summary>Crash log</summary>
```log
  Process:               UTM [40454]
Path:                  /Applications/UTM/UTM-2.2.4.app/Contents/MacOS/UTM
Identifier:            com.utmapp.UTM
Version:               2.2.4 (36)
Code Type:             ARM-64 (Native)
Parent Process:        ??? [1]
Responsible:           UTM [40454]
User ID:               501

Date/Time:             2021-09-10 12:47:47.771 +0200
OS Version:            macOS 11.5.2 (20G95)
Report Version:        12
Anonymous UUID:        D6B9F623-1979-6EFA-24EA-D38035B5CD7C

Sleep/Wake UUID:       0E5E1AF4-DE46-4EF6-AEC3-3392B044FB93

Time Awake Since Boot: 210000 seconds
Time Since Wake:       1100 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0xa54c800195d9ca64 -> 0x0000000195d9ca64 (possible pointer authentication failure)
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Segmentation fault: 11
Termination Reason:    Namespace SIGNAL, Code 0xb
Terminating Process:   exc handler [40454]

VM Regions Near 0x195d9ca64:
    __TEXT                      195d12000-195d3e000    [  176K] r-x/r-x SM=COW  /usr/lib/system/libsystem_info.dylib
--> __TEXT                      195d3e000-1961ed000    [ 4796K] r-x/r-x SM=COW  /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
    __TEXT                      1961ed000-196426000    [ 2276K] r-x/r-x SM=COW  /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/LaunchServices.framework/Versions/A/LaunchServices

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   com.apple.CoreFoundation      	0x0000000195d9ca64 -[__NSArrayI_Transfer dealloc] + 136
1   libobjc.A.dylib               	0x0000000195b7e80c AutoreleasePoolPage::releaseUntil(objc_object**) + 204
2   libobjc.A.dylib               	0x0000000195b5ce0c objc_autoreleasePoolPop + 212
3   com.apple.CoreFoundation      	0x0000000195d7fec4 _CFAutoreleasePoolPop + 32
4   com.apple.CoreFoundation      	0x0000000195e98658 __CFRunLoopPerCalloutARPEnd + 48
5   com.apple.CoreFoundation      	0x0000000195dc1730 __CFRunLoopRun + 2592
6   com.apple.CoreFoundation      	0x0000000195dc0598 CFRunLoopRunSpecific + 600
7   com.apple.HIToolbox           	0x000000019dce5280 RunCurrentEventLoopInMode + 292
8   com.apple.HIToolbox           	0x000000019dce4ff4 ReceiveNextEventCommon + 552
9   com.apple.HIToolbox           	0x000000019dce4db4 _BlockUntilNextEventMatchingListInModeWithFilter + 72
10  com.apple.AppKit              	0x00000001985b1660 _DPSNextEvent + 836
11  com.apple.AppKit              	0x00000001985b0000 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1292
12  com.apple.AppKit              	0x00000001985a1e4c -[NSApplication run] + 596
13  com.apple.AppKit              	0x0000000198573878 NSApplicationMain + 1064
14  com.apple.SwiftUI             	0x00000001b65abf58 specialized runApp(_:) + 96
15  com.apple.SwiftUI             	0x00000001b6def964 runApp<A>(_:) + 220
16  com.apple.SwiftUI             	0x00000001b6999600 static App.main() + 128
17  com.utmapp.UTM                	0x0000000100373c40 0x1002d8000 + 638016
18  com.utmapp.UTM                	0x0000000100371010 0x1002d8000 + 626704
19  libdyld.dylib                 	0x0000000195ce1430 start + 4

…
```
</details> 

**Debug log**
Unavailable, sorry.

**Upload VM**
[config.plist.txt](https://github.com/utmapp/UTM/files/7143317/config.plist.txt)

**Comment by osy** [comment] 2022-03-03 21:09
Duplicate of #3515

**Closed by osy** 2022-03-03 21:09 UTC
Labels: crash, macOS, not reproducible
